import test from 'node:test';import assert from 'node:assert/strict';import {register,createRequire} from 'node:module';import {fileURLToPath} from 'node:url'
globalThis.require=createRequire(import.meta.url);globalThis.__dirname=fileURLToPath(new URL('.',import.meta.url));register('./native-car-loader.mjs',import.meta.url);await import('../src/worker/cad.worker.ts');await globalThis.__wheelWorker.ready()
const {useApp}=await import('../src/store.ts'),{ellipseArcWithSweep,ellipseArcPoint,ellipseArcSample}=await import('../src/sketch/ellipseArcGeometry.ts'),{refPts}=await import('../src/sketch/freesolve.ts')
const e=ellipseArcWithSweep({cx:200,cy:200,rx:100,ry:50,rot:0},20,120),arc=()=>({type:'poly',earc:e,pts:ellipseArcSample(e),open:true}),near=(a,b)=>assert.ok(Math.abs(a-b)<1e-6,`${a} != ${b}`)
function seed(auto=true){useApp.setState({...useApp.getInitialState(),mode:'sketch',sketchTool:'polyline',sketchProfiles:[arc()],autoConstrain:auto},true);useApp.getState().setSnapSize(0);useApp.getState().setGeoSnap(true)}
test('snap candidates use real arc ends and center, never arbitrary tessellation vertices',()=>{seed();const p=ellipseArcPoint(e,140);useApp.getState().onSketchMove([p[0]+.1,p[1]+.1]);assert.deepEqual(useApp.getState().sketchSnap,p);useApp.getState().onSketchMove([200.1,200.1]);assert.deepEqual(useApp.getState().sketchSnap,[200,200]);const q=arc().pts[7];useApp.getState().onSketchMove(q);assert.equal(useApp.getState().sketchSnap,null)})
test('actual snapped open line completion creates true Coincident and survives dimension edits/history',async()=>{seed();const p=ellipseArcPoint(e,140),source=structuredClone(useApp.getState().sketchProfiles[0]);await useApp.getState().onSketchClick([p[0]+.1,p[1]+.1]);await useApp.getState().onSketchClick([400,400]);await useApp.getState().finishOpenPolyline();const s=useApp.getState(),co=s.skCons.find(c=>c.type==='coincident');assert.ok(co,'Finish open line must persist its snapped endpoint relation');assert.equal(co.b.kind,'ellipse-arc-end');assert.deepEqual(s.sketchProfiles[0],source);const saved=structuredClone({profiles:s.sketchProfiles,cons:s.skCons});await s.undo();assert.equal(useApp.getState().sketchProfiles.length,1);await useApp.getState().redo();assert.deepEqual({profiles:useApp.getState().sketchProfiles,cons:useApp.getState().skCons},saved);useApp.setState({skCons:[...useApp.getState().skCons,{id:'major',kind:'dim',type:'len',a:{kind:'ellipse-axis',shape:0,idx:0},value:120}]});await useApp.getState().resolveSk();assert.equal(useApp.getState().skConflict,false);const shapes=useApp.getState().sketchProfiles,a=refPts(shapes,co.a)[0],b=refPts(shapes,co.b)[0];near(a[0],b[0]);near(a[1],b[1]);near(shapes[0].earc.rx,120)})
test('auto-constraint opt-out keeps completed line independent',async()=>{seed(false);const p=ellipseArcPoint(e,140);await useApp.getState().onSketchClick(p);await useApp.getState().onSketchClick([400,400]);await useApp.getState().finishOpenPolyline();assert.equal(useApp.getState().skCons.length,0)})
test('pending endpoint inference cannot overwrite a tool change or insert late geometry',async()=>{seed();const p=ellipseArcPoint(e,140);await useApp.getState().onSketchClick(p);await useApp.getState().onSketchClick([400,400]);const history=useApp.getState().sketchUndo.length,pending=useApp.getState().finishOpenPolyline();useApp.getState().setSketchTool('select');await pending;assert.equal(useApp.getState().sketchProfiles.length,1);assert.equal(useApp.getState().sketchTool,'select');assert.equal(useApp.getState().sketchUndo.length,history);assert.equal(useApp.getState().skCons.length,0)})
test('conflicting endpoint inference preserves draft, source, constraints and history',async()=>{seed();const p=ellipseArcPoint(e,140);await useApp.getState().onSketchClick(p);await useApp.getState().onSketchClick([400,400]);useApp.setState({skCons:[{id:'a',kind:'dim',type:'len',a:{kind:'ellipse-axis',shape:0,idx:0},value:100},{id:'b',kind:'dim',type:'len',a:{kind:'ellipse-axis',shape:0,idx:0},value:120}]});const snap=()=>structuredClone({profiles:useApp.getState().sketchProfiles,cons:useApp.getState().skCons,poly:useApp.getState().polyPts,undo:useApp.getState().sketchUndo}),before=snap();await useApp.getState().finishOpenPolyline();assert.deepEqual(snap(),before)})
