import test from 'node:test';import assert from 'node:assert/strict';import {register,createRequire} from 'node:module';import {fileURLToPath} from 'node:url';
globalThis.require=createRequire(import.meta.url);globalThis.__dirname=fileURLToPath(new URL('.',import.meta.url));register('./native-car-loader.mjs',import.meta.url);
await import('../src/worker/cad.worker.ts');const w=globalThis.__wheelWorker;await w.ready();const {detectAnalyticRegions}=await import('../src/sketch/analyticRegions.ts');const {importSTEP,measureVolume,getOC}=await import('replicad');
const line=(a,b)=>({type:'poly',open:true,pts:[a,b]});
async function volume(loop){await w.rebuild([{id:'region',type:'extrude',profile:loop,height:7,operation:'new'}]);const sh=await importSTEP(new Blob([await w.exportSTEP()]));const oc=getOC(),check=new oc.BRepCheck_Analyzer(sh.wrapped,true,false);assert.ok(check.IsValid_2());check.delete();assert.ok(sh.faces.some(f=>f.geomType==='CYLINDRE'),'exact cylindrical side face');return measureVolume(sh)}
for(const angle of [Math.PI/2,Math.PI*1.3])test(`analytic arc plus radial lines preserves sector volume ${angle}`,async()=>{const r=20,a=[r,0],b=[r*Math.cos(angle),r*Math.sin(angle)],m=[r*Math.cos(angle/2),r*Math.sin(angle/2)];const reg=detectAnalyticRegions([{type:'poly',open:true,arc:{a,b,m}},line(b,[0,0]),line([0,0],a)]);assert.ok(reg);assert.equal(reg.pfaces.length,1);const loop=reg.pfaces[0].outer;assert.ok(loop.bulges.some(b=>b!==0));const actual=await volume(loop);assert.ok(Math.abs(actual-7*r*r*angle/2)<1e-6,`${actual}`)})
test('line-circle intersection uses exact analytic split coordinates and both cap volumes',async()=>{const r=20,x=7,reg=detectAnalyticRegions([{type:'circle',c:[0,0],r},line([x,-30],[x,30])]);assert.ok(reg);assert.equal(reg.pfaces.length,2);const cap=r*r*Math.acos(x/r)-x*Math.sqrt(r*r-x*x);const expected=[cap*7,(Math.PI*r*r-cap)*7].sort((a,b)=>a-b);const actual=[];for(const f of reg.pfaces){actual.push(await volume(f.outer));for(const p of f.outer.verts.filter(p=>Math.abs(p[0]-x)<1e-7))assert.ok(Math.abs(Math.abs(p[1])-Math.sqrt(r*r-x*x))<1e-7)}actual.sort((a,b)=>a-b);actual.forEach((v,i)=>assert.ok(Math.abs(v-expected[i])<1e-6,`${v} != ${expected[i]}`))})
test('unsupported smooth curve is explicitly unavailable rather than called exact',()=>assert.equal(detectAnalyticRegions([{type:'poly',smooth:true,pts:[[0,0],[10,0],[0,10]]}]),null))

test('circle-circle intersections preserve exact lens volume',async()=>{const r=20,d=15,reg=detectAnalyticRegions([{type:'circle',c:[0,0],r},{type:'circle',c:[d,0],r}]);assert.ok(reg);assert.equal(reg.pfaces.length,3);const lens=2*r*r*Math.acos(d/(2*r))-d*Math.sqrt(4*r*r-d*d)/2;const expect=[lens,Math.PI*r*r-lens,Math.PI*r*r-lens].map(v=>v*7).sort((a,b)=>a-b);const actual=[];for(const f of reg.pfaces)actual.push(await volume(f.outer));actual.sort((a,b)=>a-b);actual.forEach((v,i)=>assert.ok(Math.abs(v-expect[i])<1e-6,`${v} != ${expect[i]}`))})
test('existing mixed line/arc verts+bulges retains source segment parameters',async()=>{const r=20,reg=detectAnalyticRegions([{type:'poly',verts:[[r,0],[0,r],[0,0]],bulges:[-Math.tan(Math.PI/8),0,0],pts:[[r,0],[0,r],[0,0]]}]);assert.ok(reg);const loop=reg.pfaces[0].outer;assert.ok(loop.sources.some(s=>s.segment===0));assert.ok(Math.abs(await volume(loop)-Math.PI*r*r*7/4)<1e-6)})
test('nested circles expose exact outer and inner loops for annular selection',async()=>{const reg=detectAnalyticRegions([{type:'circle',c:[0,0],r:20},{type:'circle',c:[0,0],r:7}]);assert.ok(reg);const annulus=reg.pfaces.find(f=>f.holes.length===1);assert.ok(annulus);assert.ok(Math.abs(await volume({...annulus.outer,holes:annulus.holes})-Math.PI*(400-49)*7)<1e-6)})
