import {register} from 'node:module';import test from 'node:test';import assert from 'node:assert/strict'
register('data:text/javascript,'+encodeURIComponent(`export async function resolve(s,c,n){if(s.includes('?url'))return {url:'data:text/javascript,export default %22%22',shortCircuit:true};return n(s,c)}`))
const {solveFree,refPts,refValid,conApplicable,hitTest,measureDim,arcResample}=await import('../src/sketch/freesolve.ts')
const {pathPts,bulgeRadius}=await import('../src/sketch/sketchOps.ts')
const arc=()=>{const verts=[[15,20],[10,25]],bulges=[-Math.tan(Math.PI/8),0];return{type:'poly',open:true,verts,bulges,pts:pathPts(verts,bulges)}}
const center=(shape=0,idx=0)=>({kind:'center',shape,idx}),edge=(shape=0,idx=0)=>({kind:'edge',shape,idx}),pt=(shape,idx=0)=>({kind:'pt',shape,idx}),con=(id,type,a,b)=>({id,kind:'con',type,a,b}),dim=(id,type,a,value,b)=>({id,kind:'dim',type,a,value,b})
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-5,`${a} != ${b}`),nearPt=(a,b)=>a.forEach((v,i)=>near(v,b[i]))
async function solve(shapes,cons,drag){const before=JSON.stringify(shapes),r=await solveFree(shapes,cons,drag);assert.ok(r);assert.equal(r.conflict,false,JSON.stringify(r.conflictIds));assert.equal(JSON.stringify(shapes),before);return r.shapes}
test('center reference is a real per-segment point, validates bounds and preserves circle pt0 semantics',()=>{const a=arc();assert.ok(refValid([a],center()));nearPt(refPts([a],center())[0],[10,20]);assert.deepEqual(hitTest([a],[10,20],.5),center());assert.equal(refValid([a],center(0,1)),false);assert.equal(refValid([{...a,bulges:[0,0]}],center()),false);assert.deepEqual(refPts([{type:'circle',c:[2,3],r:4}],pt(0)),[[2,3]]);assert.equal(conApplicable('coincident',[center(),pt(1)]),true);assert.equal(conApplicable('fix',[center()]),true)})
test('fixed true arc center stays fixed while radius dimension edits endpoints',async()=>{let shapes=[arc()];for(const radius of [7,9]){shapes=await solve(shapes,[con('fix','fix',center()),dim('r','rad',edge(),radius)]);nearPt(refPts(shapes,center())[0],[10,20]);near(bulgeRadius(shapes[0].verts[0],shapes[0].verts[1],shapes[0].bulges[0]),radius)}})
test('center horizontal/vertical distances drive arc and coincident dependent circle',async()=>{const cons=[dim('x','hdist',center(),30,{kind:'origin'}),dim('y','vdist',center(),40,{kind:'origin'}),dim('r','rad',edge(),5),con('co','coincident',center(),pt(1)),dim('cr','rad',{kind:'circle',shape:1},2)];const shapes=await solve([arc(),{type:'circle',c:[10,20],r:2}],cons);nearPt(refPts(shapes,center())[0],[30,40]);nearPt(shapes[1].c,[30,40]);near(measureDim(shapes,cons[0]),30);near(measureDim(shapes,cons[1]),40)})
test('multiple surviving arcs share center while radius changes',async()=>{const a=arc(),b={...arc(),verts:[[10,25],[5,20]]};b.pts=pathPts(b.verts,b.bulges);let shapes=[a,b];const cs=[con('fix','fix',center()),con('co','coincident',center(),center(1)),con('eq','equal',edge(),edge(1)),dim('r','rad',edge(),8)];shapes=await solve(shapes,cs);for(let i=0;i<2;i++){nearPt(refPts(shapes,center(i))[0],[10,20]);near(bulgeRadius(shapes[i].verts[0],shapes[i].verts[1],shapes[i].bulges[0]),8)}})
test('center drag translates free arc retaining radius and sweep; fixed center rejects drag',async()=>{const shapes=await solve([arc()],[],{ref:center(),to:[13,24]});nearPt(refPts(shapes,center())[0],[13,24]);nearPt(shapes[0].verts[0],[18,24]);nearPt(shapes[0].verts[1],[13,29]);near(shapes[0].bulges[0],arc().bulges[0]);const blocked=await solveFree([arc()],[con('fix','fix',center())],{ref:center(),to:[13,24]});assert.ok(blocked.conflict)})
test('standalone three-point arc center alias interoperates with legacy pt2 references and JSON',async()=>{const a={a:[15,20],b:[10,25],m:[10+Math.sqrt(12.5),20+Math.sqrt(12.5)]};let shapes=[{type:'poly',open:true,arc:a,pts:arcResample(a.a,a.b,a.m)}];nearPt(refPts(shapes,center())[0],refPts(shapes,pt(0,2))[0]);const cs=JSON.parse(JSON.stringify([con('fix','fix',center()),dim('r','rad',{kind:'circle',shape:0},7)]));shapes=await solve(shapes,cs);nearPt(refPts(shapes,pt(0,2))[0],[10,20])})

test('invalid serialized center references cannot be silently ignored',async()=>{for(const [shape,r] of [[arc(),center(0,1)],[{...arc(),bulges:[0,0]},center()],[arc(),center(3)]]){const original=JSON.stringify([shape]);const result=await solveFree([shape],[con('bad','fix',r)]);assert.equal(result.conflict,true);assert.deepEqual(result.conflictIds,['bad']);assert.equal(JSON.stringify(result.shapes),original)}})
test('fixed center plus radius allows endpoint movement on its support but rejects movement off the circle',async()=>{const cs=[con('fix','fix',center()),dim('r','rad',edge(),5)];const shapes=await solve([arc()],cs,{ref:pt(0,0),to:[13,16]});nearPt(shapes[0].verts[0],[13,16]);nearPt(refPts(shapes,center())[0],[10,20]);near(bulgeRadius(shapes[0].verts[0],shapes[0].verts[1],shapes[0].bulges[0]),5);const bad=await solveFree([arc()],cs,{ref:pt(0,0),to:[16,20]});assert.equal(bad.conflict,true)})
