import test from 'node:test';import assert from 'node:assert/strict';import{register,createRequire}from'node:module';import{fileURLToPath}from'node:url'
globalThis.require=createRequire(import.meta.url);globalThis.__dirname=fileURLToPath(new URL('.',import.meta.url));register('./native-car-loader.mjs',import.meta.url)
await import('../src/worker/cad.worker.ts');await globalThis.__wheelWorker.ready();const{useApp}=await import('../src/store.ts'),{ellipseSample}=await import('../src/sketch/ellipseGeometry.ts')
const setup=(fixed=false)=>{const e={cx:5,cy:7,rx:10,ry:5,rot:30};useApp.setState({...useApp.getInitialState(),mode:'sketch',sketchTool:'move',sketchProfiles:[],sketchShape:{type:'poly',ell:e,pts:ellipseSample(e),construction:true},skCons:fixed?[{id:'fix',kind:'con',type:'fix',a:{kind:'ellipse',shape:0}}]:[],skMove:{cx:5,cy:7,dx:20,dy:10,ang:0,copy:false,targets:[0],drag:null},appPrompt:async()=> '20,10,0,0'},true)}
const snapshot=()=>structuredClone({profiles:useApp.getState().sketchProfiles,shape:useApp.getState().sketchShape,cons:useApp.getState().skCons,undo:useApp.getState().sketchUndo,redo:useApp.getState().sketchRedo})
for(const route of['commitSkMove','skMovePrompt']){
 test(`${route} preserves analytical active shape and exact UndoRedo`,async()=>{setup();const before=snapshot();await useApp.getState()[route]();const after=snapshot();assert.deepEqual(after.shape.ell,{cx:25,cy:17,rx:10,ry:5,rot:30});assert.equal(after.shape.construction,true);assert.equal(after.profiles.length,0);assert.equal(after.undo.length,1);await useApp.getState().undo();assert.deepEqual(useApp.getState().sketchShape,before.shape);await useApp.getState().redo();assert.deepEqual(useApp.getState().sketchShape,after.shape)})
 test(`${route} cannot redefine original Fix`,async()=>{setup(true);const before=snapshot();await useApp.getState()[route]();assert.deepEqual(snapshot(),before);assert.ok(useApp.getState().skMove)})
}
for(const field of['sketchShape','skCons','sketchUndo','sketchRedo','skRefGeo','sketchPlane','skMove'])test(`pending Move discards stale ${field}`,async()=>{setup();const pending=useApp.getState().commitSkMove(),s=useApp.getState();useApp.setState({[field]:field==='sketchPlane'?'XZ':field==='skMove'?null:field==='skRefGeo'?{pts:[[1,2]],segs:[]}:structuredClone(s[field])});const before=snapshot();await pending;assert.deepEqual(snapshot(),before)})
test('zero numeric Move does not consume Undo',async()=>{setup();useApp.setState({appPrompt:async()=> '0,0,0,0'});const before=snapshot();await useApp.getState().skMovePrompt();assert.deepEqual(snapshot(),before)})
for(const route of['commitSkMove','skMovePrompt'])test(`${route} symmetric circle rotation is a geometric no-op`,async()=>{setup();useApp.setState({sketchShape:{type:'circle',c:[5,7],r:10},skMove:{cx:5,cy:7,dx:0,dy:0,ang:30,copy:false,targets:[0],drag:null},appPrompt:async()=> '0,0,30,0'});const before=snapshot();await useApp.getState()[route]();assert.deepEqual(snapshot(),before);assert.equal(useApp.getState().skMove,null)})
