import test from 'node:test';import assert from 'node:assert/strict';import{register,createRequire}from'node:module';import{fileURLToPath}from'node:url'
globalThis.require=createRequire(import.meta.url);globalThis.__dirname=fileURLToPath(new URL('.',import.meta.url));register('./native-car-loader.mjs',import.meta.url)
await import('../src/worker/cad.worker.ts');await globalThis.__wheelWorker.ready();const{useApp}=await import('../src/store.ts'),{ellipseSample}=await import('../src/sketch/ellipseGeometry.ts')
function seed(value='2'){const ell={cx:10,cy:20,rx:5,ry:3,rot:30};useApp.setState({...useApp.getInitialState(),mode:'sketch',sketchTool:'scale',sketchShape:{type:'poly',ell,pts:ellipseSample(ell),construction:true},appPrompt:async()=>value},true)}
const snap=()=>structuredClone({profiles:useApp.getState().sketchProfiles,shape:useApp.getState().sketchShape,cons:useApp.getState().skCons,undo:useApp.getState().sketchUndo,redo:useApp.getState().sketchRedo})
test('scale keeps analytic default center and exact active shape history',async()=>{seed();const before=snap();await useApp.getState().skScalePrompt();const after=snap();assert.deepEqual(after.shape.ell,{cx:10,cy:20,rx:10,ry:6,rot:30});assert.equal(after.shape.construction,true);assert.equal(after.profiles.length,0);assert.equal(after.undo.length,1);await useApp.getState().undo();assert.deepEqual(useApp.getState().sketchShape,before.shape);await useApp.getState().redo();assert.deepEqual(useApp.getState().sketchShape,after.shape)})
test('explicit pivot controls center independently of tessellation',async()=>{seed('0.5,0,0');await useApp.getState().skScalePrompt();assert.deepEqual(useApp.getState().sketchShape.ell,{cx:5,cy:10,rx:2.5,ry:1.5,rot:30})})
for(const input of[null,'1','0','-1','NaN','2,0,','2,0','2,0,0,3'])test(`invalid/cancel/no-op scale ${input} preserves history`,async()=>{seed(input);const before=snap();await useApp.getState().skScalePrompt();assert.deepEqual(snap(),before)})
for(const field of['sketchShape','skCons','sketchUndo','sketchRedo','skRefGeo','sketchPlane','skSel'])test(`pending scale discards stale ${field}`,async()=>{seed();const pending=useApp.getState().skScalePrompt();await Promise.resolve();const s=useApp.getState();useApp.setState({[field]:field==='sketchPlane'?'XZ':field==='skRefGeo'?{pts:[[1,2]],segs:[]}:structuredClone(s[field])});const before=snap();await pending;assert.deepEqual(snap(),before)})
