import {register} from 'node:module';import test from 'node:test';import assert from 'node:assert/strict'
register('data:text/javascript,'+encodeURIComponent(`export async function resolve(s,c,n){if(s.includes('?url'))return {url:'data:text/javascript,export default %22%22',shortCircuit:true};return n(s,c)}`))
const {solveConstrainedPointDrag:drag}=await import('../src/sketch/constrainedDrag.ts');const {pathPts}=await import('../src/sketch/sketchOps.ts');const {arcResample}=await import('../src/sketch/freesolve.ts')
const p=(idx)=>({kind:'pt',shape:0,idx}),e={kind:'edge',shape:0,idx:0},c={kind:'center',shape:0,idx:0},fix=(a)=>({id:'fix'+JSON.stringify(a),kind:'con',type:'fix',a}),dim=(type,a,value)=>({id:type,kind:'dim',type,a,value}),near=(a,b)=>a.forEach((v,i)=>assert.ok(Math.abs(v-b[i])<1e-5,`${a} != ${b}`))
const arc=()=>{const verts=[[60,40],[20,40]],bulges=[1];return{type:'poly',open:true,verts,bulges,pts:pathPts(verts,bulges)}}
const line=()=>({type:'poly',open:true,pts:[[20,20],[60,20]]})
async function checked(shapes,cons,ref,target){const before=JSON.stringify([shapes,cons]),r=await drag(shapes,cons,ref,target);assert.equal(JSON.stringify([shapes,cons]),before);assert.ok(r.ok,r.reason);return r}
test('pointer projects radially onto fixed-center driving-radius arc and keeps metadata',async()=>{const cs=[fix(c),{...dim('rad',e,20),name:'R',expr:'radius',refs:{radius:'pR'}}];const r=await checked([arc()],cs,p(0),[70,30]);near(r.target,[40+20*3/Math.sqrt(10),40-20/Math.sqrt(10)]);near(r.result.shapes[0].verts[0],r.target);assert.equal(r.projection,'circle')})
test('cursor at center keeps previous arc point instead of choosing arbitrary radial direction',async()=>{const r=await checked([arc()],[fix(c),dim('rad',e,20)],p(0),[40,40]);near(r.target,[60,40])})
test('fixed-point drag is a no-op',async()=>{const r=await checked([line()],[fix(p(0))],p(0),[70,80]);near(r.target,[20,20]);near(r.result.shapes[0].pts[0],[20,20]);assert.equal(r.projection,'fixed')})
for(const type of ['h','v'])test(`anchored ${type} line projects cursor onto its axis`,async()=>{const sh=type==='h'?line():{type:'poly',open:true,pts:[[20,20],[20,60]]},r=await checked([sh],[fix(p(0)),{id:type,kind:'con',type,a:e}],p(1),[75,35]);near(r.target,type==='h'?[75,20]:[20,35])})
test('anchored driving length uses nearest circle point; length plus H keeps feasible intersection',async()=>{const cs=[fix(p(0)),dim('len',e,40)];let r=await checked([line()],cs,p(1),[50,60]);near(r.target,[44,52]);r=await checked([line()],[...cs,{id:'h',kind:'con',type:'h',a:e}],p(1),[75,35]);near(r.target,[60,20]);assert.equal(r.projection,'intersection')})
test('conflicting driving lengths reject without dropping either dimension',async()=>{const result=await drag([line()],[fix(p(0)),dim('len',e,40),{...dim('len',e,50),id:'other'}],p(1),[75,35]);assert.equal(result.ok,false)})
test('driven reference length does not restrict horizontal cursor intent',async()=>{const r=await checked([line()],[fix(p(0)),{id:'h',kind:'con',type:'h',a:e},{...dim('len',e,40),driven:true}],p(1),[75,35]);near(r.target,[75,20])})
test('three-point arc with fixed center alias follows radial cursor intent',async()=>{const a={a:[60,40],b:[20,40],m:[40,60]},sh={type:'poly',open:true,arc:a,pts:arcResample(a.a,a.b,a.m)},r=await checked([sh],[fix(c),dim('rad',{kind:'circle',shape:0},20)],p(0),[70,30]);near(r.target,[40+60/Math.sqrt(10),40-20/Math.sqrt(10)]);near(r.result.shapes[0].arc.a,r.target)})
test('fixed opposite arc endpoint and coincident closing chord remain connected during projected drag',async()=>{const verts=[[10,0],[-10,0]],bulges=[-1],a={type:'poly',open:true,verts,bulges,pts:pathPts(verts,bulges)},b={type:'poly',open:true,pts:[[-10,0],[10,0]]};const cs=[fix(c),fix(p(1)),dim('rad',e,10),{id:'joinA',kind:'con',type:'coincident',a:p(0),b:{kind:'pt',shape:1,idx:1}},{id:'joinB',kind:'con',type:'coincident',a:p(1),b:{kind:'pt',shape:1,idx:0}}];const r=await checked([a,b],cs,p(0),[9,12]);near(r.target,[6,8]);near(r.result.shapes[0].verts[1],[-10,0]);near(r.result.shapes[1].pts[1],[6,8]);near(r.result.shapes[1].pts[0],[-10,0])})
test('fixed entire edge keeps endpoint anchor and structural refs do not depend on JSON key order',async()=>{const r=await checked([line()],[fix({idx:0,shape:0,kind:'edge'}),{id:'h',kind:'con',type:'h',a:e}],p(1),[75,35]);near(r.target,[60,20]);near(r.result.shapes[0].pts[0],[20,20]);near(r.result.shapes[0].pts[1],[60,20])})
test('point-to-fixed-point distance uses dimension radius rather than old drawn length',async()=>{const cs=[fix(p(0)),{id:'distance',kind:'dim',type:'dist',a:p(1),b:p(0),value:30}];const r=await checked([line()],cs,p(1),[50,60]);near(r.target,[38,44]);near(r.result.shapes[0].pts[1],[38,44])})

test('discrete H plus driving length does not jump to mirrored branch when cursor crosses anchor',async()=>{const r=await checked([line()],[fix(p(0)),dim('len',e,40),{id:'h',kind:'con',type:'h',a:e}],p(1),[-50,35]);near(r.target,[60,20])})
