import test from 'node:test'
import assert from 'node:assert/strict'
import {register,createRequire} from 'node:module'
import {fileURLToPath} from 'node:url'
globalThis.require=createRequire(import.meta.url);globalThis.__dirname=fileURLToPath(new URL('.',import.meta.url));register('./native-car-loader.mjs',import.meta.url)
await import('../src/worker/cad.worker.ts');const w=globalThis.__wheelWorker;await w.ready()
const {useApp,buildProjectPayload}=await import('../src/store.ts'),{pathPts}=await import('../src/sketch/sketchOps.ts'),{importSTEP,measureVolume,getOC}=await import('replicad')
const approx=(p,q)=>assert.ok(Math.hypot(p[0]-q[0],p[1]-q[1])<1e-5,`${p} != ${q}`)
function setup(){const verts=[[50,40],[30,40]],bulges=[-1],arc={type:'poly',open:true,verts,bulges,pts:pathPts(verts,bulges)},line={type:'poly',open:true,pts:[[30,40],[50,40]]};useApp.setState({...useApp.getInitialState(),mode:'sketch',sketchTool:'select',sketchProfiles:[arc,line],skCons:[{id:'center',kind:'con',type:'fix',a:{kind:'center',shape:0,idx:0}},{id:'radius',name:'dRadius',kind:'dim',type:'rad',a:{kind:'edge',shape:0,idx:0},value:10},{id:'opposite',kind:'con',type:'fix',a:{kind:'pt',shape:0,idx:1}},{id:'joinA',kind:'con',type:'coincident',a:{kind:'pt',shape:1,idx:1},b:{kind:'pt',shape:0,idx:0}},{id:'joinB',kind:'con',type:'coincident',a:{kind:'pt',shape:1,idx:0},b:{kind:'pt',shape:0,idx:1}}],extrudeHeight:5,sketchOp:'new'},true)}
async function volume(expected){const sh=await importSTEP(new Blob([await w.exportSTEP()])),check=new(getOC().BRepCheck_Analyzer)(sh.wrapped,true,false);try{assert.ok(check.IsValid_2())}finally{check.delete()}assert.ok(Math.abs(measureVolume(sh)-expected)<1e-5,`${measureVolume(sh)} != ${expected}`)}
test('off-circle pointer moves constrained endpoint and attached chord then native extrusion/height edit/history/JSON STEP',async()=>{
 setup();const cons=structuredClone(useApp.getState().skCons);assert.equal(useApp.getState().skDragStart([50,40]),true);await useApp.getState().skDragEnd([49,52]);const s=useApp.getState();approx(s.sketchProfiles[0].verts[0],[46,48]);approx(s.sketchProfiles[0].verts[1],[30,40]);approx(s.sketchProfiles[1].pts[1],[46,48]);assert.deepEqual(s.skCons,cons);assert.equal(s.sketchUndo.length,1)
 await s.undo();approx(useApp.getState().sketchProfiles[0].verts[0],[50,40]);await useApp.getState().redo();approx(useApp.getState().sketchProfiles[0].verts[0],[46,48]);await useApp.getState().extrudeSketch();assert.equal(useApp.getState().mode,'model',useApp.getState().status)
 const theta=Math.PI-Math.atan2(8,6),area=50*(theta-Math.sin(theta));await volume(area*5)
 assert.equal(await useApp.getState().applyFeatures(useApp.getState().features.map(f=>({...f,height:8})),'height8'),true);await volume(area*8);await useApp.getState().undo();await volume(area*5);await useApp.getState().redo();await volume(area*8)
 const payload=JSON.parse(JSON.stringify(buildProjectPayload(useApp.getState())));useApp.setState({...useApp.getInitialState()},true);await useApp.getState().applyProjectData(payload);await volume(area*8);const feat=useApp.getState().features.at(-1);await useApp.getState().editSketchOf(feat.id);assert.deepEqual(useApp.getState().skCons,cons);await useApp.getState().applySketchEdit(feat.sketchId);await volume(area*8)
})
test('constrained drag Esc discards pending final projection with no history',async()=>{setup();const before=structuredClone(useApp.getState().sketchProfiles);useApp.getState().skDragStart([50,40]);const pending=useApp.getState().skDragEnd([49,52]);useApp.getState().escSketch();await pending;assert.deepEqual(useApp.getState().sketchProfiles,before);assert.equal(useApp.getState().sketchUndo.length,0)})
test('adding fixed opposite endpoint and horizontal chord locks the arc instead of dropping constraints',async()=>{setup();useApp.setState({skCons:[...useApp.getState().skCons,{id:'horizontal',kind:'con',type:'h',a:{kind:'edge',shape:1,idx:0}}]});const s=useApp.getState(),before=structuredClone(s.sketchProfiles),cons=structuredClone(s.skCons);s.skDragStart([50,40]);await useApp.getState().skDragEnd([49,52]);assert.deepEqual(useApp.getState().sketchProfiles,before);assert.deepEqual(useApp.getState().skCons,cons);assert.equal(useApp.getState().sketchUndo.length,0)})
