import test from 'node:test';import assert from 'node:assert/strict';import {register,createRequire} from 'node:module';import {fileURLToPath} from 'node:url'
globalThis.require=createRequire(import.meta.url);globalThis.__dirname=fileURLToPath(new URL('.',import.meta.url));register('./native-car-loader.mjs',import.meta.url)
await import('../src/worker/cad.worker.ts');await globalThis.__wheelWorker.ready();const {useApp}=await import('../src/store.ts')
const radius=(id,name,shape,value,extra={})=>({id,name,kind:'dim',type:'rad',a:{kind:'circle',shape},value,...extra})
function setup(){useApp.setState({...useApp.getInitialState(),mode:'sketch',sketchTool:'move',sketchProfiles:[{type:'circle',c:[0,0],r:10},{type:'circle',c:[40,0],r:20}],sketchShape:null,skCons:[radius('r1','d1',0,10),radius('r2','d2',1,20,{expr:'d1*2',refs:{d1:'dimension:r1'}})],skMove:{cx:0,cy:0,dx:100,dy:0,ang:0,copy:true,targets:[0,1],drag:null},skDimLabelOff:{r1:[4,5]}},true)}
const snap=()=>structuredClone({shapes:useApp.getState().sketchProfiles,cons:useApp.getState().skCons,undo:useApp.getState().sketchUndo,redo:useApp.getState().sketchRedo,offsets:useApp.getState().skDimLabelOff})
test('actual copy keeps internal formula independent, unique IDs and labels with exact history',async()=>{setup();const before=snap();await useApp.getState().commitSkMove();const s=useApp.getState(),copy=s.skCons.filter(c=>c.a.shape>=2);assert.equal(copy.length,2);assert.deepEqual(s.skCons.slice(0,2),before.cons);assert.deepEqual(copy[1].refs,{[copy[0].name]:`dimension:${copy[0].id}`});assert.equal(copy[1].expr,`${copy[0].name}*2`);assert.deepEqual(s.skDimLabelOff[copy[0].id],[4,5]);await useApp.getState().commitSkDim(copy[0].id,{value:12},'copy12');assert.deepEqual(useApp.getState().sketchProfiles.map(s=>Math.round(s.r)),[10,20,12,24]);await useApp.getState().commitSkDim('r1',{value:8},'source8');assert.deepEqual(useApp.getState().sketchProfiles.map(s=>Math.round(s.r)),[8,16,12,24]);await useApp.getState().undo();await useApp.getState().undo();await useApp.getState().undo();assert.deepEqual(useApp.getState().sketchProfiles,before.shapes);assert.deepEqual(useApp.getState().skCons,before.cons);assert.deepEqual(useApp.getState().skDimLabelOff,before.offsets);await useApp.getState().redo();assert.equal(useApp.getState().skCons.length,4)})
test('numeric multi copy remaps formula independently in every instance',async()=>{setup();useApp.setState({appPrompt:async()=> '100,0,0,2'});await useApp.getState().skMovePrompt();const s=useApp.getState();assert.equal(s.sketchProfiles.length,6);assert.equal(new Set(s.skCons.map(c=>c.id)).size,6);for(const shape of[2,4]){const a=s.skCons.find(c=>c.a.shape===shape),b=s.skCons.find(c=>c.a.shape===shape+1);assert.deepEqual(b.refs,{[a.name]:`dimension:${a.id}`})}assert.equal(s.sketchUndo.length,1)})
test('uncopied external formula dependency rejects the transaction without freezing its value',async()=>{setup();useApp.setState({skMove:{...useApp.getState().skMove,targets:[1]}});const before=snap();await useApp.getState().commitSkMove();assert.deepEqual(snap(),before);assert.match(useApp.getState().status,/uncopied dimension/)})
test('conflicting source dimensions reject copy without consuming history',async()=>{setup();useApp.setState({skCons:[...useApp.getState().skCons,radius('bad','bad',0,15)]});const before=snap();await useApp.getState().commitSkMove();assert.deepEqual(snap(),before);assert.ok(useApp.getState().skMove)})
for(const field of ['sketchProfiles','skCons','sketchUndo','sketchRedo','skRefGeo','sketchPlane','skMove'])test(`pending copy discards stale ${field}`,async()=>{setup();const pending=useApp.getState().commitSkMove(),s=useApp.getState();useApp.setState({[field]:field==='sketchPlane'?'XZ':field==='skMove'?null:field==='skRefGeo'?{pts:[[1,2]],segs:[]}:structuredClone(s[field])});const before=snap();await pending;assert.deepEqual(snap(),before)})
