import{register}from'node:module';import test from'node:test';import assert from'node:assert/strict'
register('data:text/javascript,'+encodeURIComponent(`export async function resolve(s,c,n){if(s.includes('?url'))return {url:'data:text/javascript,export default %22%22',shortCircuit:true};return n(s,c)}`))
const{buildCopyRelations,solveCopyCandidate}=await import('../src/sketch/copyRelations.ts'),{solveFree}=await import('../src/sketch/freesolve.ts'),{ellipseSample}=await import('../src/sketch/ellipseGeometry.ts'),{ellipseArcWithSweep,ellipseArcSample,ellipseArcSweep}=await import('../src/sketch/ellipseArcGeometry.ts')
const tr=(angleDeg=0)=>({dx:30,dy:20,cx:0,cy:0,angleDeg}),circle=(x=0)=>({type:'circle',c:[x,0],r:10}),rad=(shape,id='r',name='d1')=>({id,name,kind:'dim',type:'rad',a:{kind:'circle',shape},value:10}),fix=(shape)=>({id:'fix'+shape,kind:'con',type:'fix',a:{kind:'pt',shape,idx:0}})
test('independent internal dimensions and copied Fix anchors, source identity preserved',async()=>{const shapes=[circle()],cons=[fix(0),rad(0)],p=buildCopyRelations(shapes,cons,[0],[tr()],'copy');assert.equal(p.ok,true);assert.equal(p.shapes[0],shapes[0]);assert.equal(p.cons[0],cons[0]);const r=await solveCopyCandidate(shapes,p);assert.equal(r.ok,true,r.reason);assert.equal(r.shapes[0],shapes[0]);assert.deepEqual(r.shapes[1].c,[30,20]);const edited=await solveFree(r.shapes,r.cons.map(c=>c.kind==='dim'&&c.a.shape===1?{...c,value:8}:c));assert.equal(edited.conflict,false);assert.equal(edited.shapes[0].r,10);assert.equal(edited.shapes[1].r,8)})
test('multiple copies allocate unique IDs and internal formula names/refs while sharing user params',()=>{const shapes=[circle(),circle(25)],cons=[rad(0),{...rad(1,'r2','d2'),expr:'d1 * 2 + Width',refs:{d1:'r',Width:'userWidth'},paramId:'userWidth'}],p=buildCopyRelations(shapes,cons,[0,1],[tr(),{...tr(),dx:60}],'copy');assert.equal(p.ok,true);assert.equal(new Set(p.cons.map(c=>c.id)).size,6);for(const k of[0,1]){const a=p.cons[2+k*2],b=p.cons[3+k*2];assert.equal(b.expr,`${a.name} * 2 + Width`);assert.equal(b.refs[a.name],a.id);assert.equal(b.refs.Width,'userWidth');assert.equal(b.paramId,'userWidth')}})
test('external geometry relation is reported and not silently attached to originals',()=>{const p=buildCopyRelations([circle(),circle(25)],[{id:'external',kind:'con',type:'equal',a:{kind:'circle',shape:0},b:{kind:'circle',shape:1}}],[0],[tr()],'copy');assert.equal(p.ok,true);assert.equal(p.cons.length,1);assert.deepEqual(p.omitted.map(x=>x.id),['external'])})
test('uncopied dimension formula dependency explicitly rejects',()=>{const cs=[rad(0),{...rad(1,'r2','d2'),expr:'d1*2',refs:{d1:'r'}}],p=buildCopyRelations([circle(),circle(25)],cs,[1],[tr()],'copy');assert.equal(p.ok,false)})
for(const angle of[90,-90])test(`local axis constraints rotate at ${angle} with real solver`,async()=>{const s=[{type:'poly',open:true,construction:true,pts:[[0,0],[10,0]]}],cs=[{id:'h',kind:'con',type:'h',a:{kind:'edge',shape:0,idx:0}},{id:'w',kind:'dim',type:'hdist',a:{kind:'pt',shape:0,idx:0},b:{kind:'pt',shape:0,idx:1},value:10}],p=buildCopyRelations(s,cs,[0],[tr(angle)],'copy');assert.equal(p.ok,true);assert.equal(p.cons[2].type,'h');assert.equal(p.cons[3].type,'hdist');assert.equal(p.cons[3].frameAngleDeg,angle);assert.equal(p.cons[3].projectionSign,1);const r=await solveCopyCandidate(s,p);assert.equal(r.ok,true,r.reason);assert.ok(Math.abs(r.shapes[1].pts[0][0]-r.shapes[1].pts[1][0])<1e-7)})
test('arbitrary rotation preserves local axis constraints',()=>{const s=[{type:'poly',open:true,pts:[[0,0],[10,0]]}],cs=[{id:'h',kind:'con',type:'h',a:{kind:'edge',shape:0,idx:0}}];const p=buildCopyRelations(s,cs,[0],[tr(30)],'copy');assert.equal(p.ok,true);assert.equal(p.cons[1].frameAngleDeg,30)})
test('analytical ellipse and signed arc metadata survive arbitrary rotation construction and controls',async()=>{const e={cx:0,cy:0,rx:10,ry:5,rot:30},earc=ellipseArcWithSweep(e,330,-270),s=[{type:'poly',construction:true,ell:e,pts:ellipseSample(e)},{type:'poly',open:true,construction:true,earc,pts:ellipseArcSample(earc)}],p=buildCopyRelations(s,[],[0,1],[tr(25)],'copy');assert.equal(p.ok,true);assert.ok(p.shapes[2].ell);assert.equal(p.shapes[2].ell.rot,55);assert.equal(p.shapes[2].construction,true);assert.equal(ellipseArcSweep(p.shapes[3].earc),-270);assert.equal(p.shapes[3].open,true);const r=await solveCopyCandidate(s,p);assert.equal(r.ok,true,r.reason)})
test('contradictory original dimension never mutates source during copy validation',async()=>{const s=[circle()],cs=[{id:'fix',kind:'con',type:'fix',a:{kind:'circle',shape:0}},{...rad(0),value:12}],snapshot=JSON.stringify({s,cs}),p=buildCopyRelations(s,cs,[0],[tr()],'copy'),r=await solveCopyCandidate(s,p);assert.equal(r.ok,false);assert.equal(JSON.stringify({s,cs}),snapshot)})
test('rotated rectangle retains implicit rectangular constraints and construction',async()=>{const s=[{type:'rect',a:[0,0],b:[10,5],construction:true}],p=buildCopyRelations(s,[],[0],[tr(90)],'copy');assert.equal(p.ok,true);assert.equal(p.shapes[1].construction,true);assert.equal(p.cons.length,4);const r=await solveCopyCandidate(s,p);assert.equal(r.ok,true,r.reason);const q=buildCopyRelations(s,[],[0],[tr(30)],'copy');assert.equal(q.ok,true);assert.equal((await solveCopyCandidate(s,q)).ok,true)})
test('reserved global dimension names cannot collide',()=>{const p=buildCopyRelations([circle()],[rad(0)],[0],[tr()],'copy',['d1_copy1']);assert.equal(p.ok,true);assert.notEqual(p.cons[1].name,'d1_copy1')})
test('general tangent contact metadata and indexed line-end metadata remap intact',async()=>{const e={cx:0,cy:0,rx:10,ry:5,rot:0},s=[{type:'poly',ell:e,pts:ellipseSample(e)},{type:'poly',open:true,construction:true,pts:[[-4,5],[4,5]]}],cs=[{id:'T',kind:'con',type:'tangent',a:{kind:'ellipse',shape:0},b:{kind:'edge',shape:1,idx:0},ellipseContact:{version:1,angleDeg:90}}],p=buildCopyRelations(s,cs,[0,1],[tr(30)],'copy');assert.equal(p.ok,true);assert.deepEqual(p.cons[1].ellipseContact,cs[0].ellipseContact);assert.equal(p.cons[1].a.shape,2);const r=await solveCopyCandidate(s,p);assert.equal(r.ok,true,r.reason)})
test('actual dimension:ID bindings remap and parameter-shadowed tokens stay shared',()=>{const s=[circle(),circle(25)],cs=[rad(0),{...rad(1,'r2','d2'),expr:'d1*2',refs:{d1:'dimension:r'}}],p=buildCopyRelations(s,cs,[0,1],[tr()],'copy');assert.equal(p.ok,true);assert.equal(p.cons[3].refs[p.cons[2].name],'dimension:'+p.cons[2].id);assert.equal(buildCopyRelations(s,cs,[1],[tr()],'copy').ok,false);const shadow=buildCopyRelations(s,[cs[0],{...cs[1],refs:{d1:'user-param'}}],[0,1],[tr()],'copy');assert.equal(shadow.ok,true);assert.equal(shadow.cons[3].expr,'d1*2');assert.equal(shadow.cons[3].refs.d1,'user-param')})
test('world tag positions transform and stale projection metadata cannot leak into independent copy',()=>{const s=[{type:'poly',pts:[[0,0],[10,0]],open:true,projectLink:'all',projectLinkSource:{version:1,points:[[0,0],[10,0]],open:true}}],cs=[{id:'L',kind:'dim',type:'len',a:{kind:'edge',shape:0,idx:0},value:10,tagPos:[3,4]}],p=buildCopyRelations(s,cs,[0],[tr(90)],'copy');assert.equal(p.ok,true);assert.deepEqual(p.cons[1].tagPos,[26,23]);assert.equal(p.shapes[1].projectLink,undefined);assert.equal(p.shapes[1].projectLinkSource,undefined)})

for(const angle of[30,-30,125])for(const sign of[-1,1])test(`oriented copy ${angle} sign ${sign} composes and edits independently`,async()=>{
 const s=[{type:'poly',open:true,pts:[[0,0],[sign*10,0]]}],cs=[{id:'h',kind:'con',type:'h',a:{kind:'edge',shape:0,idx:0}},{id:'w',name:'Width',kind:'dim',type:'hdist',a:{kind:'pt',shape:0,idx:0},b:{kind:'pt',shape:0,idx:1},value:10}]
 const p=buildCopyRelations(s,cs,[0],[tr(angle)],'first');assert.equal(p.ok,true);assert.equal(p.cons[3].projectionSign,sign)
 const r=await solveCopyCandidate(s,p);assert.equal(r.ok,true,r.reason)
 const q=buildCopyRelations(r.shapes,r.cons,[1],[tr(-angle)],'second');assert.equal(q.ok,true);assert.equal(q.cons.at(-1).frameAngleDeg,0);assert.equal(q.cons.at(-1).projectionSign,sign)
 const z=await solveCopyCandidate(r.shapes,q);assert.equal(z.ok,true,z.reason)
 const edited=await solveFree(z.shapes,z.cons.map(c=>c.kind==='dim'&&c.a.shape===2?{...c,value:17}:c));assert.equal(edited.conflict,false)
 for(const [i,length]of[[0,10],[1,10],[2,17]]){const [A,B]=edited.shapes[i].pts;assert.ok(Math.abs(Math.hypot(B[0]-A[0],B[1]-A[1])-length)<1e-7);const a=(i===1?angle:0)*Math.PI/180;assert.ok(Math.abs((B[0]-A[0])*Math.cos(a)+(B[1]-A[1])*Math.sin(a)-sign*length)<1e-7)}
})
for(const angle of[30,-30,125])test(`fixed corner rotated rectangle width and height edit ${angle}`,async()=>{
 const s=[{type:'rect',a:[20,30],b:[40,40]}],cs=[{id:'fix',kind:'con',type:'fix',a:{kind:'pt',shape:0,idx:0}},{id:'w',kind:'dim',type:'hdist',a:{kind:'pt',shape:0,idx:0},b:{kind:'pt',shape:0,idx:1},value:20},{id:'h',kind:'dim',type:'vdist',a:{kind:'pt',shape:0,idx:1},b:{kind:'pt',shape:0,idx:2},value:10}]
 const p=buildCopyRelations(s,cs,[0],[tr(angle)],'fixed');assert.equal(p.ok,true);const r=await solveCopyCandidate(s,p);assert.equal(r.ok,true,r.reason)
 const constraints=r.cons.map(c=>c.kind==='dim'&&c.a.shape===1?{...c,value:c.type==='hdist'?28:14}:c)
 const result=await solveFree(r.shapes,constraints);assert.equal(result.conflict,false,JSON.stringify(result.conflicting));const pts=result.shapes[1].pts,a=angle*Math.PI/180
 assert.deepEqual(result.shapes[0],s[0]);for(let i=0;i<2;i++)assert.ok(Math.abs(pts[0][i]-r.shapes[1].pts[0][i])<1e-7)
 assert.ok(Math.abs((pts[1][0]-pts[0][0])*Math.cos(a)+(pts[1][1]-pts[0][1])*Math.sin(a)-28)<1e-7)
 assert.ok(Math.abs(-(pts[2][0]-pts[1][0])*Math.sin(a)+(pts[2][1]-pts[1][1])*Math.cos(a)-14)<1e-7)
})
