import {register}from'node:module';import test from'node:test';import assert from'node:assert/strict'
register('data:text/javascript,'+encodeURIComponent(`export async function resolve(s,c,n){if(s.includes('?url'))return {url:'data:text/javascript,export default %22%22',shortCircuit:true};return n(s,c)}`))
const{buildMirrorRelations,solveMirrorCandidate}=await import('../src/sketch/mirrorRelations.ts'),{ellipseArcSample,ellipseArcWithSweep,ellipseArcSweep}=await import('../src/sketch/ellipseArcGeometry.ts'),{solveFree,refPts}=await import('../src/sketch/freesolve.ts')
const pt=(shape,idx=0)=>({kind:'ellipse-point',shape,idx}),end=(shape,idx=0)=>({kind:'ellipse-arc-end',shape,idx}),axis=(shape,idx=0)=>({kind:'ellipse-axis',shape,idx}),edge={kind:'edge',shape:1,idx:0},fix=(id,a)=>({id,kind:'con',type:'fix',a}),near=(a,b)=>assert.ok(Math.abs(a-b)<1e-6,`${a}!=${b}`),make=(sweep=80,rx=10,ry=5)=>{const earc=ellipseArcWithSweep({cx:20,cy:30,rx,ry,rot:30},330,sweep);return{type:'poly',earc,pts:ellipseArcSample(earc),open:true,construction:true}}
const ax={type:'poly',open:true,construction:true,pts:[[70,0],[70,70]]};async function prepare(sh,cons=[fix('axis',edge)]){const shapes=[sh,ax],r=buildMirrorRelations(shapes,cons,[0],edge,'M');assert.equal(r.ok,true,r.reason);const checked=await solveMirrorCandidate(shapes,r);assert.equal(checked.ok,true,checked.reason);return{...r,shapes:checked.shapes}}
function symmetric(shapes,x=70){const a=shapes[0],b=shapes[2];near(ellipseArcSweep(b.earc),-ellipseArcSweep(a.earc));for(const j of [0,1]){const p=refPts(shapes,end(0,j))[0],q=refPts(shapes,end(2,j))[0];near(q[0],2*x-p[0]);near(q[1],p[1])}assert.equal(b.pts.length,a.pts.length);for(let i=0;i<a.pts.length;i++){near(b.pts[i][0],2*x-a.pts[i][0]);near(b.pts[i][1],a.pts[i][1])}}
for(const sweep of [80,-80,270,-270,360,-360])for(const rx of [10,5])test(`signedearc mirror ${sweep}deg rx${rx} persists actual curve`,async()=>{const sh=make(sweep,rx),r=await prepare(sh);assert.equal(r.shapes[0],sh);assert.equal(r.shapes[2].open,true);assert.equal(r.shapes[2].construction,true);assert.equal(r.relationIds.length,5);symmetric(r.shapes)})
test('source semiaxis dimension, endpoint edit and axis move keep relation after JSON',async()=>{let r=await prepare(make(),[fix('axis',edge),fix('center',pt(0)),fix('minor',pt(0,2)),{id:'major',kind:'dim',type:'len',a:axis(0),value:10}]);let cs=r.cons.map(c=>c.id==='major'?{...c,value:12}:c),res=await solveFree(r.shapes,cs);assert.equal(res.conflict,false,JSON.stringify(res.conflictIds));symmetric(res.shapes);const p=refPts(res.shapes,end(0,1))[0];res=await solveFree(res.shapes,cs,{ref:end(0,1),to:[p[0]-2,p[1]+4]});assert.equal(res.conflict,false,JSON.stringify(res.conflictIds));symmetric(res.shapes);let shapes=JSON.parse(JSON.stringify(res.shapes));shapes[1]={...ax,pts:[[80,0],[80,70]]};res=await solveFree(shapes,JSON.parse(JSON.stringify(cs)));assert.equal(res.conflict,false,JSON.stringify(res.conflictIds));symmetric(res.shapes,80)})
test('incompatible old endpoint Fix candidate is rejected atomically',async()=>{const sh=make(),shapes=[sh,ax],cs=[fix('bad',{kind:'pt',shape:0,idx:0})],r=buildMirrorRelations(shapes,cs,[0],edge,'M'),snapshot=JSON.stringify({shapes,cs,r});assert.equal(r.ok,true);const solved=await solveMirrorCandidate(shapes,r);assert.equal(solved.ok,false);assert.equal(JSON.stringify({shapes,cs,r}),snapshot)})
test('diagonal off-origin reflection preserves closed contour, centerline and exact original constraint IDs',async()=>{const sh={...make(-270),open:false,centerline:true},diagonal={...ax,pts:[[70,0],[100,30]]},cs=[fix('axis-original-id',edge)],r=buildMirrorRelations([sh,diagonal],cs,[0],edge,'M'),snapshot=JSON.stringify({sh,cs});assert.equal(r.ok,true,r.reason);const result=await solveMirrorCandidate([sh,diagonal],r);assert.equal(result.ok,true,result.reason);assert.equal(result.shapes[2].open,false);assert.equal(result.shapes[2].centerline,true);assert.equal(r.cons[0],cs[0]);assert.equal(JSON.stringify({sh,cs}),snapshot);for(let i=0;i<sh.pts.length;i++){near(result.shapes[2].pts[i][0],sh.pts[i][1]+70);near(result.shapes[2].pts[i][1],sh.pts[i][0]-70)}})
