import {register} from 'node:module';import test from 'node:test';import assert from 'node:assert/strict'
register('data:text/javascript,'+encodeURIComponent(`export async function resolve(s,c,n){if(s.includes('?url'))return {url:'data:text/javascript,export default %22%22',shortCircuit:true};return n(s,c)}`))
const {solveFree,refPts,refValid,hitTest}=await import('../src/sketch/freesolve.ts');const {ellipseSample}=await import('../src/sketch/ellipseGeometry.ts')
const point=(idx=0)=>({kind:'ellipse-point',shape:0,idx}),axis=(idx=0)=>({kind:'ellipse-axis',shape:0,idx}),fix=a=>({id:'fix',kind:'con',type:'fix',a}),shape=()=>{const ell={cx:20,cy:30,rx:10,ry:5,rot:0};return{type:'poly',ell,pts:ellipseSample(ell)}}
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-6,`${a} != ${b}`)
async function solve(shapes,cons=[],drag){const r=await solveFree(shapes,cons,drag);assert.equal(r.conflict,false,JSON.stringify(r.conflictIds));return r}
test('ellipse has five real DOFs, genuine handles, and no sampled refs',async()=>{const sh=shape(),r=await solve([sh]);assert.equal(r.dof,5);assert.deepEqual(hitTest([sh],[30,30],1),point(1));assert.equal(refValid([sh],{kind:'pt',shape:0,idx:0}),false);assert.deepEqual(refPts([sh],axis()),[[20,30],[30,30]])})
test('major drag updates analytic radius; center drag rigidly translates full frame',async()=>{let r=await solve([shape()],[],{ref:point(1),to:[35,30]});near(r.shapes[0].ell.rx,15);near(r.shapes[0].ell.ry,5);near(r.shapes[0].pts[0][0],35);r=await solve(r.shapes,[],{ref:point(),to:[25,40]});near(r.shapes[0].ell.cx,25);near(r.shapes[0].ell.cy,40);near(r.shapes[0].ell.rx,15);near(r.shapes[0].ell.ry,5)})
test('axis len dimensions update ellipse, including equal radii without losing orientation',async()=>{for(const value of [12,5]){const sh=shape();sh.ell.rot=30;sh.pts=ellipseSample(sh.ell);const r=await solve([sh],[fix(point()),{id:'len',kind:'dim',type:'len',a:axis(),value}]);near(r.shapes[0].ell.rx,value);near(r.shapes[0].ell.cx,20);near(r.shapes[0].ell.cy,30)}})
test('whole ellipse Fix and incompatible old sampled refs reject without mutation',async()=>{for(const cons of [[fix({kind:'ellipse',shape:0})],[fix({kind:'pt',shape:0,idx:0})]]){const shapes=[shape()],snapshot=JSON.stringify(shapes),r=await solveFree(shapes,cons,{ref:point(1),to:[35,30]});assert.equal(r.conflict,true);assert.equal(JSON.stringify(shapes),snapshot)}})
test('minor off-axis pointer projects to existing perpendicular ray; crossing center rejects',async()=>{let r=await solve([shape()],[],{ref:point(2),to:[25,38]});near(r.shapes[0].ell.ry,8);near(r.shapes[0].ell.rx,10);near(r.shapes[0].ell.rot,0);const bad=await solveFree([shape()],[],{ref:point(2),to:[20,25]});assert.equal(bad.conflict,true)})
test('rotated major endpoint preserves minor radius and strict constraints still reject incompatible size',async()=>{let sh=shape();sh.ell.rot=30;sh.pts=ellipseSample(sh.ell);const r=await solve([sh],[],{ref:point(1),to:[20,45]});near(r.shapes[0].ell.rot,90);near(r.shapes[0].ell.rx,15);near(r.shapes[0].ell.ry,5);const bad=await solveFree([sh],[{id:'length',kind:'dim',type:'len',a:axis(),value:10}],{ref:point(1),to:[20,45]});assert.equal(bad.conflict,true)})
test('ellipse center coincidence and named semiaxis lengths preserve analytic metadata through JSON',async()=>{const sh=shape();const cs=[fix(point()),{id:'major',kind:'dim',type:'len',a:axis(),value:12,name:'d1'},{id:'minor',kind:'dim',type:'len',a:axis(1),value:7},{id:'co',kind:'con',type:'coincident',a:point(),b:{kind:'pt',shape:1,idx:0}}];const r=await solve(JSON.parse(JSON.stringify([sh,{type:'circle',c:[20,30],r:2}])),JSON.parse(JSON.stringify(cs)));near(r.shapes[0].ell.rx,12);near(r.shapes[0].ell.ry,7);near(r.shapes[1].c[0],20);near(r.shapes[1].c[1],30);assert.equal(r.shapes[0].pts.length,64)})
test('axis center crossing and invalid ellipse refs cannot produce successful stale geometry',async()=>{for(const drag of [{ref:point(1),to:[20,30]},{ref:{kind:'ellipse-point',shape:0,idx:8},to:[1,2]},{ref:{kind:'edge',shape:0,idx:0},to:[1,2]}]){const r=await solveFree([shape()],[],drag);assert.equal(r.conflict,true)}})
const {dimGfx,measureDim,refMid}=await import('../src/sketch/freesolve.ts')
test('legacy sampled ellipse dimensions render safely without inventing measurements or losing persisted constraints',async()=>{const sh=shape();for(const type of ['dist','hdist','vdist','len','angle','p2l','rad','dia','arclen']){const c={id:`legacy-${type}`,kind:'dim',type,a:{kind:type==='len'||type==='angle'||type==='rad'||type==='dia'||type==='arclen'?'edge':'pt',shape:0,idx:0},b:{kind:'edge',shape:0,idx:1},value:10,name:'legacyDimension',expr:'10',refs:{}};assert.equal(measureDim([sh],c),null);assert.equal(dimGfx([sh],c),null);assert.ok(refMid([sh],c.a).every(Number.isFinite));const snapshot=JSON.stringify({sh,c});for(const driven of [false,true]){const r=await solveFree([sh],[{...c,driven}]);assert.equal(r.conflict,true);assert.deepEqual(r.conflictIds,[c.id]);assert.deepEqual(r.shapes,[sh])}assert.equal(JSON.stringify({sh,c}),snapshot)}})
test('ellipse axes and rim are selectable with center and true endpoints taking point priority',()=>{for(const rot of [0,30,125]){const sh=shape();sh.ell.rot=rot;sh.pts=ellipseSample(sh.ell);const c=refPts([sh],point())[0],u=refPts([sh],point(1))[0],v=refPts([sh],point(2))[0];for(const [idx,q] of [[0,u],[1,v]])assert.deepEqual(hitTest([sh],[(c[0]+q[0])/2,(c[1]+q[1])/2],.3),axis(idx));for(let i=0;i<3;i++)assert.deepEqual(hitTest([sh],refPts([sh],point(i))[0],.3),point(i));assert.deepEqual(hitTest([sh],sh.pts[24],.3),{kind:'ellipse',shape:0})}})
const {conApplicable}=await import('../src/sketch/freesolve.ts')
test('whole ellipse and real semiaxis Fix are exposed and preserve their intended anchors',async()=>{const sh=shape();for(const r of [{kind:'ellipse',shape:0},axis(),point()])assert.equal(conApplicable('fix',[r],[sh]),true);const locked=await solve([sh],[fix({kind:'ellipse',shape:0})]);assert.equal(locked.dof,0);const blocked=await solveFree([sh],[fix(axis())],{ref:point(1),to:[35,30]});assert.equal(blocked.conflict,true)})
