import test from 'node:test';import assert from 'node:assert/strict';import {register,createRequire} from 'node:module';import {fileURLToPath} from 'node:url'
globalThis.require=createRequire(import.meta.url);globalThis.__dirname=fileURLToPath(new URL('.',import.meta.url));register('./native-car-loader.mjs',import.meta.url);await import('../src/worker/cad.worker.ts');await globalThis.__wheelWorker.ready()
const {useApp}=await import('../src/store.ts')
function seed(dir){useApp.setState({...useApp.getInitialState(),mode:'sketch',sketchTool:'earc',autoConstrain:false},true);useApp.getState().setSnapSize(0);useApp.getState().setGeoSnap(false);useApp.getState().setEllipseArcDirection(dir)}
const click=async p=>useApp.getState().onSketchClick(p),near=(a,b)=>assert.ok(Math.abs(a-b)<1e-6,`${a} != ${b}`)
for(const dir of['ccw','cw'])test(`actual five-click ${dir} arc agrees with analytic samples and exact history`,async()=>{seed(dir);for(const p of[[40,40],[70,40],[40,60],[70,40],[40,60]])await click(p);const sh=structuredClone(useApp.getState().sketchShape),e=sh.earc;assert.equal(e.version,2);near(e.signedSweepDeg,dir==='cw'?-270:90);for(const [x,y]of sh.pts)near(((x-40)/30)**2+((y-40)/20)**2,1);if(dir==='cw')assert.ok(sh.pts.some(p=>p[1]<20.1));else assert.ok(sh.pts.every(p=>p[1]>=40-1e-8));await useApp.getState().undo();assert.equal(useApp.getState().sketchShape,null);await useApp.getState().redo();assert.deepEqual(useApp.getState().sketchShape,sh)})
test('invalid axes and coincident endpoints cannot silently substitute geometry or consume history',async()=>{seed('cw');await click([40,40]);let before=useApp.getState().sketchUndo.length;await click([40,40]);assert.equal(useApp.getState().polyPts.length,1);assert.equal(useApp.getState().sketchUndo.length,before);await click([70,40]);before=useApp.getState().sketchUndo.length;await click([50,40]);assert.equal(useApp.getState().polyPts.length,2);assert.equal(useApp.getState().sketchUndo.length,before);await click([40,60]);await click([70,40]);before=useApp.getState().sketchUndo.length;await click([70,40]);assert.equal(useApp.getState().sketchShape,null);assert.equal(useApp.getState().sketchUndo.length,before)})
test('typed arc stage Esc removes provisional history and restores original geometry',async()=>{seed('ccw');const original={type:'circle',c:[100,100],r:5};useApp.setState({sketchProfiles:[original]});for(const key of['4','0','Tab','4','0','Enter'])useApp.getState().sketchTypeKey(key);useApp.getState().onSketchMove([70,40]);for(const key of['3','0','Enter'])useApp.getState().sketchTypeKey(key);assert.equal(useApp.getState().polyPts.length,2);assert.equal(useApp.getState().sketchUndo.length,2);useApp.getState().escSketch();useApp.getState().escSketch();assert.equal(useApp.getState().sketchStart,null);assert.equal(useApp.getState().sketchUndo.length,0);assert.deepEqual(useApp.getState().sketchProfiles,[original]);assert.equal(useApp.getState().mode,'sketch')})

test('creation guides are points, not phantom straight edges, and completion clears snap overlays',async()=>{seed('cw');useApp.getState().setGeoSnap(true);for(const p of[[40,40],[70,40],[40,60],[70,40]])await click(p);useApp.getState().onSketchMove([40,60]);assert.ok(!useApp.getState().snapSrc?.seg,'creation support points must not form a synthetic chord');await click([40,60]);assert.equal(useApp.getState().sketchShape.open,true);assert.equal(useApp.getState().snapSrc,null);assert.equal(useApp.getState().sketchSnap,null);useApp.getState().escSketch();assert.equal(useApp.getState().snapSrc,null)})
