import test from 'node:test'
import assert from 'node:assert/strict'
import {register,createRequire} from 'node:module'
import {fileURLToPath} from 'node:url'
globalThis.require=createRequire(import.meta.url);globalThis.__dirname=fileURLToPath(new URL('.',import.meta.url));register('./native-car-loader.mjs',import.meta.url)
await import('../src/worker/cad.worker.ts');await globalThis.__wheelWorker.ready()
const {useApp}=await import('../src/store.ts'),{ellipseSample}=await import('../src/sketch/ellipseGeometry.ts')
const ellipse={kind:'ellipse',shape:0},edge={kind:'edge',shape:1,idx:0},fix=(id,a)=>({id,kind:'con',type:'fix',a})
function setup(conflict=false){const ell={cx:20,cy:30,rx:10,ry:5,rot:30},top=30+Math.sqrt(100*.25+25*.75);useApp.setState({...useApp.getInitialState(),mode:'sketch',sketchTool:'select',sketchProfiles:[{type:'poly',ell,pts:ellipseSample(ell)},{type:'poly',pts:[[0,conflict?50:top],[40,conflict?50:top]],open:true,construction:true}],sketchShape:null,skSel:[ellipse,edge],skCons:conflict?[fix('ellipse',ellipse),fix('line',edge)]:[fix('C',{kind:'ellipse-point',shape:0,idx:0}),fix('V',{kind:'ellipse-point',shape:0,idx:2}),{id:'major',kind:'dim',type:'len',a:{kind:'ellipse-axis',shape:0,idx:0},value:10},{id:'horizontal',kind:'con',type:'h',a:edge}]},true)}
const snap=()=>structuredClone({shapes:useApp.getState().sketchProfiles,cons:useApp.getState().skCons,undo:useApp.getState().sketchUndo,redo:useApp.getState().sketchRedo})
const near=(x,y)=>assert.ok(Math.abs(x-y)<1e-6,`${x} != ${y}`)
function check(){const s=useApp.getState(),e=s.sketchProfiles[0].ell,c=s.skCons.find(c=>c.type==='tangent');assert.ok(c?.ellipseContact,s.status);assert.equal(c.tangentLineEnd,undefined);const expected=Math.atan2(e.ry*Math.cos(Math.PI/6),e.rx*Math.sin(Math.PI/6))*180/Math.PI;near(c.ellipseContact.angleDeg,expected);const y=30+Math.sqrt(e.rx**2*.25+e.ry**2*.75);s.sketchProfiles[1].pts.forEach(p=>near(p[1],y));return structuredClone(c)}
test('general tangent contact state updates atomically with oblique ellipse dimension and survives exact history',async()=>{setup();await useApp.getState().addSkCon('tangent');const before=check();assert.equal(useApp.getState().sketchUndo.length,1);await useApp.getState().commitSkDim('major',{value:12},'major12');const after=check();assert.ok(Math.abs(before.ellipseContact.angleDeg-after.ellipseContact.angleDeg)>1);const solved=snap();await useApp.getState().undo();await useApp.getState().resolveSk();assert.deepEqual(check(),before);await useApp.getState().redo();await useApp.getState().resolveSk();assert.deepEqual(check(),after);assert.deepEqual(useApp.getState().sketchProfiles,solved.shapes)})
test('general tangent fixed conflict preserves shapes constraints and both histories',async()=>{setup(true);const before=snap();await useApp.getState().addSkCon('tangent');assert.deepEqual(snap(),before);assert.match(useApp.getState().status,/衝突/)})
for(const field of ['sketchProfiles','skSel','sketchUndo','sketchRedo','skRefGeo','sketchPlane'])test(`general tangent discards stale ${field}`,async()=>{setup();const pending=useApp.getState().addSkCon('tangent'),s=useApp.getState();useApp.setState({[field]:field==='sketchPlane'?'XZ':field==='skRefGeo'?{pts:[[1,2]],segs:[]}:field==='skSel'?[]:[...s[field]]});const before=snap();await pending;assert.deepEqual(snap(),before)})
test('actual semiaxis drag updates contact state and Esc restores the same geometry and constraints',async()=>{setup();useApp.setState({skCons:useApp.getState().skCons.filter(c=>c.id!=='major')});await useApp.getState().addSkCon('tangent');const initial=check(),before=snap();const u=()=>{const e=useApp.getState().sketchProfiles[0].ell,r=e.rot*Math.PI/180;return[e.cx+e.rx*Math.cos(r),e.cy+e.rx*Math.sin(r)]};const target=[20+12*Math.cos(Math.PI/6),36];assert.equal(useApp.getState().skDragStart(u()),true);await useApp.getState().skDragMove(target,true);near(useApp.getState().sketchProfiles[0].ell.rx,12);const after=check();assert.ok(Math.abs(after.ellipseContact.angleDeg-initial.ellipseContact.angleDeg)>1);useApp.getState().skDragCancel();assert.deepEqual(snap(),before);assert.equal(useApp.getState().skDragStart(u()),true);await useApp.getState().skDragEnd(target);near(useApp.getState().sketchProfiles[0].ell.rx,12);check();await useApp.getState().undo();assert.deepEqual(check(),initial)})
