import test from 'node:test'
import assert from 'node:assert/strict'
import {register} from 'node:module'
register('data:text/javascript,'+encodeURIComponent(`export async function resolve(s,c,n){if(s.includes('?url'))return {url:'data:text/javascript,export default %22%22',shortCircuit:true};return n(s,c)}`))
const {solveFree,refValid,refPts,measureDim,dimGfx}=await import('../src/sketch/freesolve.ts')
function earc(){const e={cx:20,cy:30,rx:10,ry:5,rot:30,a0:0,a1:120},angle=e.rot*Math.PI/180;return{type:'poly',open:true,earc:e,pts:Array.from({length:17},(_,i)=>{const t=i/16*e.a1*Math.PI/180;return[e.cx+e.rx*Math.cos(t)*Math.cos(angle)-e.ry*Math.sin(t)*Math.sin(angle),e.cy+e.rx*Math.cos(t)*Math.sin(angle)+e.ry*Math.sin(t)*Math.cos(angle)]})}}
const point={kind:'pt',shape:0,idx:0},edge={kind:'edge',shape:0,idx:0}
test('unsupported sampled elliptical-arc point and edge drag reject atomically instead of stale analytic metadata',async()=>{
 for(const which of ['point','edge']){const sh=earc(),shapes=[sh],before=structuredClone(shapes),delta=[3,4],drag=which==='point'?{ref:point,to:[sh.pts[0][0]+delta[0],sh.pts[0][1]+delta[1]]}:{ref:edge,ends:[sh.pts[0],sh.pts[1]].map(p=>[p[0]+delta[0],p[1]+delta[1]])};const result=await solveFree(shapes,[],drag);console.log('EARC DRAG',JSON.stringify({which,conflict:result?.conflict,original:before[0].pts[0],actual:result?.shapes[0].pts[0],metadata:result?.shapes[0].earc}));assert.equal(result?.conflict,true);assert.deepEqual(result.shapes,before);assert.deepEqual(shapes,before)}
})
test('unsupported elliptical-arc legacy dimensions including driven preserve IDs and return no invented measurement',async()=>{
 for(const type of ['dist','hdist','vdist','len','angle','p2l','rad','dia','arclen'])for(const driven of [false,true]){const sh=earc(),c={id:`old-${type}`,kind:'dim',type,a:type==='len'||type==='angle'||type==='rad'||type==='dia'||type==='arclen'?edge:point,b:{kind:'edge',shape:0,idx:1},value:10,driven,name:'legacy',expr:'10',refs:{}};const before=structuredClone({sh,c}),result=await solveFree([sh],[c]);assert.equal(result?.conflict,true,`${type} driven=${driven}`);assert.deepEqual(result.conflictIds,[c.id]);assert.deepEqual(result.shapes,[sh]);assert.equal(measureDim([sh],c),null);assert.equal(dimGfx([sh],c),null);assert.deepEqual({sh,c},before)}
})
test('elliptical-arc sample references are unavailable and Fix is rejected rather than discarded',async()=>{
 const sh=earc();for(const ref of [point,edge]){assert.equal(refValid([sh],ref),false);assert.deepEqual(refPts([sh],ref),[]);const c={id:'legacy-fix',kind:'con',type:'fix',a:ref},r=await solveFree([sh],[c]);assert.equal(r?.conflict,true);assert.deepEqual(r.conflictIds,[c.id]);assert.deepEqual(r.shapes,[sh])}
})
test('ordinary geometry solves independently while untouched elliptical arc remains byte-identical',async()=>{
 const sh=earc(),before=structuredClone(sh),shapes=[sh,{type:'circle',c:[80,40],r:4}],c={id:'ordinary-radius',kind:'dim',type:'rad',a:{kind:'circle',shape:1},value:7};const r=await solveFree(shapes,[c]);assert.equal(r?.conflict,false);assert.ok(Math.abs(r.shapes[1].r-7)<1e-6);assert.deepEqual(r.shapes[0],before);assert.deepEqual(sh,before);const moved=await solveFree(r.shapes,[c],{ref:{kind:'pt',shape:1,idx:0},to:[85,45]});assert.equal(moved?.conflict,false);assert.deepEqual(moved.shapes[1].c,[85,45]);assert.deepEqual(moved.shapes[0],before)
})
test('unsupported arc controls do not prevent exact native extrusion of unchanged closed arc plus ordinary dimension edits',async()=>{
 const {createRequire}=await import('node:module'),{fileURLToPath}=await import('node:url');globalThis.require=createRequire(import.meta.url);globalThis.__dirname=fileURLToPath(new URL('.',import.meta.url));register('./native-car-loader.mjs',import.meta.url);await import('../src/worker/cad.worker.ts');const w=globalThis.__wheelWorker;await w.ready();const {useApp,buildProjectPayload}=await import('../src/store.ts'),{importSTEP,measureVolume,getOC}=await import('replicad')
 const sh={...earc(),open:false},before=structuredClone(sh),area=25*(2*Math.PI/3-Math.sqrt(3)/2),c={id:'radius',kind:'dim',type:'rad',a:{kind:'circle',shape:1},value:7};useApp.setState({...useApp.getInitialState(),mode:'sketch',sketchTool:'select',sketchProfiles:[sh,{type:'circle',c:[80,40],r:4}],skCons:[c],extrudeHeight:5,sketchOp:'new'},true);await useApp.getState().resolveSk();assert.equal(useApp.getState().skConflict,false,useApp.getState().status);assert.deepEqual(useApp.getState().sketchProfiles[0],before);assert.ok(Math.abs(useApp.getState().sketchProfiles[1].r-7)<1e-6)
 const volume=async h=>{const s=await importSTEP(new Blob([await w.exportSTEP()])),check=new(getOC().BRepCheck_Analyzer)(s.wrapped,true,false);try{assert.ok(check.IsValid_2())}finally{check.delete()}const expected=(area+49*Math.PI)*h;assert.ok(Math.abs(measureVolume(s)-expected)<1e-5,`${measureVolume(s)} != ${expected}`)}
 await useApp.getState().extrudeSketch();assert.equal(useApp.getState().mode,'model',useApp.getState().status);await volume(5);assert.equal(await useApp.getState().applyFeatures(useApp.getState().features.map(f=>({...f,height:8})),'height8'),true);await volume(8);await useApp.getState().undo();await volume(5);await useApp.getState().redo();await volume(8);const payload=JSON.parse(JSON.stringify(buildProjectPayload(useApp.getState())));useApp.setState({...useApp.getInitialState()},true);await useApp.getState().applyProjectData(payload);await volume(8)
})
