import test from 'node:test'
import assert from 'node:assert/strict'
import {register,createRequire} from 'node:module'
import {fileURLToPath} from 'node:url'
globalThis.require=createRequire(import.meta.url);globalThis.__dirname=fileURLToPath(new URL('.',import.meta.url));register('./native-car-loader.mjs',import.meta.url)
await import('../src/worker/cad.worker.ts');await globalThis.__wheelWorker.ready()
const {useApp}=await import('../src/store.ts'),{ellipseArcWithSweep,ellipseArcSample}=await import('../src/sketch/ellipseArcGeometry.ts')
const arc={kind:'ellipse-arc',shape:0},edge={kind:'edge',shape:1,idx:0},fix=(id,a)=>({id,kind:'con',type:'fix',a})
function setup(cw=false){const earc=ellipseArcWithSweep({cx:20,cy:30,rx:10,ry:5,rot:30},cw?70:10,cw?-60:60),top=30+Math.sqrt(100*.25+25*.75);useApp.setState({...useApp.getInitialState(),mode:'sketch',sketchTool:'select',sketchProfiles:[{type:'poly',earc,pts:ellipseArcSample(earc),open:true},{type:'poly',pts:[[0,top],[40,top]],open:true,construction:true}],sketchShape:null,skSel:[arc,edge],skCons:[fix('C',{kind:'ellipse-point',shape:0,idx:0}),fix('V',{kind:'ellipse-point',shape:0,idx:2}),{id:'major',kind:'dim',type:'len',a:{kind:'ellipse-axis',shape:0,idx:0},value:10},{id:'horizontal',kind:'con',type:'h',a:edge}]},true)}
const snap=()=>structuredClone({shapes:useApp.getState().sketchProfiles,cons:useApp.getState().skCons,undo:useApp.getState().sketchUndo,redo:useApp.getState().sketchRedo})
const near=(x,y)=>assert.ok(Math.abs(x-y)<1e-6,`${x} != ${y}`)
function point(e,degrees){const t=degrees*Math.PI/180,r=e.rot*Math.PI/180;return[e.cx+e.rx*Math.cos(t)*Math.cos(r)-e.ry*Math.sin(t)*Math.sin(r),e.cy+e.rx*Math.cos(t)*Math.sin(r)+e.ry*Math.sin(t)*Math.cos(r)]}
function check(){const s=useApp.getState(),e=s.sketchProfiles[0].earc,c=s.skCons.find(c=>c.type==='tangent');assert.ok(c?.ellipseContact,s.status);assert.equal(c.tangentLineEnd,undefined);const expected=Math.atan2(e.ry*Math.cos(Math.PI/6),e.rx*Math.sin(Math.PI/6))*180/Math.PI;near(c.ellipseContact.angleDeg,expected);const progress=((Math.sign(e.signedSweepDeg)*(expected-e.a0))%360+360)%360;assert.ok(progress<=Math.abs(e.signedSweepDeg)+1e-6);const y=30+Math.sqrt(e.rx**2*.25+e.ry**2*.75);s.sketchProfiles[1].pts.forEach(p=>near(p[1],y));return structuredClone(c)}
for(const cw of[false,true])test(`interior tangent ${cw?'CW':'CCW'} dimension and exact history`,async()=>{setup(cw);await useApp.getState().addSkCon('tangent');const before=check();await useApp.getState().commitSkDim('major',{value:12},'major12');const after=check();assert.ok(Math.abs(before.ellipseContact.angleDeg-after.ellipseContact.angleDeg)>1);await useApp.getState().undo();assert.deepEqual(check(),before);await useApp.getState().redo();assert.deepEqual(check(),after)})
test('actual endpoint drag excluding tangent rejects without geometry metadata or history damage; valid extension and Undo work',async()=>{setup();await useApp.getState().addSkCon('tangent');check();const before=snap(),e=useApp.getState().sketchProfiles[0].earc;assert.equal(useApp.getState().skDragStart(point(e,e.a1)),true);await useApp.getState().skDragEnd(point(e,30));assert.deepEqual(snap(),before);assert.equal(useApp.getState().skDragStart(point(e,e.a1)),true);await useApp.getState().skDragEnd(point(e,80));const next=useApp.getState().sketchProfiles[0].earc;near(next.a1,80);check();await useApp.getState().undo();assert.deepEqual(useApp.getState().sketchProfiles,before.shapes);assert.deepEqual(useApp.getState().skCons,before.cons)})
for(const field of ['sketchProfiles','skSel','sketchUndo','sketchRedo','skRefGeo','sketchPlane'])test(`interior tangent discards stale ${field}`,async()=>{setup();const pending=useApp.getState().addSkCon('tangent'),s=useApp.getState();useApp.setState({[field]:field==='sketchPlane'?'XZ':field==='skRefGeo'?{pts:[[1,2]],segs:[]}:field==='skSel'?[]:[...s[field]]});const before=snap();await pending;assert.deepEqual(snap(),before)})
for(const sweep of [360,-360])test(`full turn ${sweep} stays exact across interior tangent dimension and history`,async()=>{setup();const s=useApp.getState(),earc=ellipseArcWithSweep(s.sketchProfiles[0].earc,10,sweep);useApp.setState({sketchProfiles:[{...s.sketchProfiles[0],earc,pts:ellipseArcSample(earc)},s.sketchProfiles[1]]});await useApp.getState().addSkCon('tangent');check();await useApp.getState().commitSkDim('major',{value:12},'major12');near(useApp.getState().sketchProfiles[0].earc.rx,12);assert.equal(useApp.getState().sketchProfiles[0].earc.signedSweepDeg,sweep);const after=check();await useApp.getState().undo();near(useApp.getState().sketchProfiles[0].earc.rx,10);assert.equal(useApp.getState().sketchProfiles[0].earc.signedSweepDeg,sweep);await useApp.getState().redo();assert.deepEqual(check(),after);assert.equal(useApp.getState().sketchProfiles[0].earc.signedSweepDeg,sweep)})
