import{register}from'node:module';import test from'node:test';import assert from'node:assert/strict'
register('data:text/javascript,'+encodeURIComponent(`export async function resolve(s,c,n){if(s.includes('?url'))return {url:'data:text/javascript,export default %22%22',shortCircuit:true};return n(s,c)}`))
const{solveFree,refPts,conApplicable}=await import('../src/sketch/freesolve.ts'),{ellipseArcWithSweep,ellipseArcSample,ellipseArcSweep}=await import('../src/sketch/ellipseArcGeometry.ts')
const endpoint={kind:'ellipse-arc-end',shape:0,idx:1},edge={kind:'edge',shape:1,idx:0},point=(idx)=>({kind:'ellipse-point',shape:0,idx}),fix=(id,a)=>({id,kind:'con',type:'fix',a})
function make(rx=10,ry=5,rot=30,contact=0){const earc=ellipseArcWithSweep({cx:20,cy:30,rx,ry,rot},330,80),arc={type:'poly',open:true,earc,pts:ellipseArcSample(earc)},E=refPts([arc],endpoint)[0],t=(earc.a0+ellipseArcSweep(earc))*Math.PI/180,a=rot*Math.PI/180,D=[-rx*Math.sin(t)*Math.cos(a)-ry*Math.cos(t)*Math.sin(a),-rx*Math.sin(t)*Math.sin(a)+ry*Math.cos(t)*Math.cos(a)],L=Math.hypot(...D),B=[E[0]+8*D[0]/L,E[1]+8*D[1]/L];return[arc,{type:'poly',open:true,construction:true,pts:contact?[B,E]:[E,B]}]}
const tangent=(contact=0)=>({id:'tangent-id',kind:'con',type:'tangent',a:endpoint,b:edge,tangentLineEnd:contact})
function check(shapes,contact=0){const e=shapes[0].earc,E=refPts(shapes,endpoint)[0],line=shapes[1].pts,t=(e.a0+ellipseArcSweep(e))*Math.PI/180,a=e.rot*Math.PI/180,d=[-e.rx*Math.sin(t)*Math.cos(a)-e.ry*Math.cos(t)*Math.sin(a),-e.rx*Math.sin(t)*Math.sin(a)+e.ry*Math.cos(t)*Math.cos(a)],v=[line[1][0]-line[0][0],line[1][1]-line[0][1]];assert.ok(Math.hypot(E[0]-line[contact][0],E[1]-line[contact][1])<1e-6);assert.ok(Math.abs(d[0]*v[1]-d[1]*v[0])/(Math.hypot(...d)*Math.hypot(...v))<1e-7)}
for(const[rx,ry,rot]of [[10,5,30],[5,5,30],[5,10,125]])for(const contact of [0,1])test(`actual endpoint tangent ${rx}/${ry} rot${rot} contact${contact}`,async()=>{const shapes=make(rx,ry,rot,contact),c=tangent(contact);assert.equal(conApplicable('tangent',[endpoint,edge],shapes),true);const r=await solveFree(shapes,[c]);assert.equal(r.conflict,false,JSON.stringify(r.conflictIds));assert.equal(r.dof,8);check(r.shapes,contact)})
test('radius transitions keep true contact, derivative tangent and exact line length through JSON',async()=>{let shapes=make();const cons=[fix('C',point(0)),fix('V',point(2)),{id:'R',kind:'dim',type:'len',a:{kind:'ellipse-axis',shape:0,idx:0},value:10},{id:'L',kind:'dim',type:'len',a:edge,value:8},tangent()];for(const value of [10,5,3,12]){const r=await solveFree(JSON.parse(JSON.stringify(shapes)),cons.map(c=>c.id==='R'?{...c,value}:c));assert.equal(r.conflict,false,JSON.stringify(r.conflictIds));shapes=r.shapes;check(shapes);assert.ok(Math.abs(shapes[0].earc.rx-value)<1e-6);assert.ok(Math.abs(Math.hypot(shapes[1].pts[1][0]-shapes[1].pts[0][0],shapes[1].pts[1][1]-shapes[1].pts[0][1])-8)<1e-6)}})
test('unsupported persisted tangent combinations or missing endpoint identity reject original IDs atomically',async()=>{const shapes=make();for(const c of [{...tangent(),tangentLineEnd:undefined},{...tangent(),a:{kind:'ellipse-arc',shape:0}},{...tangent(),b:{kind:'circle',shape:1}}]){const snapshot=JSON.stringify({shapes,c}),r=await solveFree(shapes,[c]);assert.equal(r.conflict,true);assert.deepEqual(r.conflictIds,['tangent-id']);assert.deepEqual(r.shapes,shapes);assert.equal(JSON.stringify({shapes,c}),snapshot)}})
test('fixed remote line cannot be silently moved to satisfy tangent',async()=>{const shapes=make();shapes[1].pts=[[100,100],[108,100]];const r=await solveFree(shapes,[fix('arc',{kind:'ellipse-arc',shape:0}),fix('line',edge),tangent()]);assert.equal(r.conflict,true);assert.deepEqual(r.shapes,shapes);assert.ok(r.conflictIds.includes('tangent-id'))})
test('endpoint drag preserves tangent contact instead of leaving the line on its old direction',async()=>{const shapes=make(),E=refPts(shapes,endpoint)[0],r=await solveFree(shapes,[tangent()],{ref:endpoint,to:[E[0]-3,E[1]+4]});assert.equal(r.conflict,false,JSON.stringify(r.conflictIds));check(r.shapes)})
test('a bulge arc edge is not accepted as a straight tangent contact line',async()=>{const shapes=make();shapes[1]={...shapes[1],verts:shapes[1].pts,bulges:[.3,0]};assert.equal(conApplicable('tangent',[endpoint,edge],shapes),false);const r=await solveFree(shapes,[tangent()]);assert.equal(r.conflict,true);assert.deepEqual(r.conflictIds,['tangent-id']);assert.deepEqual(r.shapes,shapes)})
test('creation solves a nearby non-tangent line with fixed support, choosing the persisted contact endpoint',async()=>{const shapes=make(30,20,0);shapes[0].earc=ellipseArcWithSweep({cx:40,cy:40,rx:30,ry:20,rot:0},0,45);shapes[0].pts=ellipseArcSample(shapes[0].earc);shapes[1].pts=[[60,55],[85,70]];const cs=[fix('C',point(0)),fix('V',point(2)),{id:'R',kind:'dim',type:'len',a:{kind:'ellipse-axis',shape:0,idx:0},value:30},tangent()];const r=await solveFree(shapes,cs);assert.equal(r.conflict,false,JSON.stringify(r.conflictIds));check(r.shapes)})
