import{register}from'node:module';import test from'node:test';import assert from'node:assert/strict'
register('data:text/javascript,'+encodeURIComponent(`export async function resolve(s,c,n){if(s.includes('?url'))return {url:'data:text/javascript,export default %22%22',shortCircuit:true};return n(s,c)}`))
const{solveFree,ellipseLineTangentPair,initialEllipseContact,applyRelationUpdates}=await import('../src/sketch/freesolve.ts'),{ellipseArcWithSweep,ellipseArcSample,ellipseArcPoint,ellipseArcSweep}=await import('../src/sketch/ellipseArcGeometry.ts')
const arc={kind:'ellipse-arc',shape:0},edge={kind:'edge',shape:1,idx:0},fix=(id,a)=>({id,kind:'con',type:'fix',a})
function make(sweep,rx=10,ry=5,angle=330+sweep/2){const earc=ellipseArcWithSweep({cx:20,cy:30,rx,ry,rot:30},330,sweep),E=ellipseArcPoint(earc,angle),a=Math.PI/6,t=angle*Math.PI/180,D=[-rx*Math.sin(t)*Math.cos(a)-ry*Math.cos(t)*Math.sin(a),-rx*Math.sin(t)*Math.sin(a)+ry*Math.cos(t)*Math.cos(a)],L=Math.hypot(...D);return[{type:'poly',open:true,earc,pts:ellipseArcSample(earc)},{type:'poly',open:true,pts:[-3,4].map(k=>[E[0]+k*D[0]/L,E[1]+k*D[1]/L])}]}
const tangent=(angle)=>({id:'T',kind:'con',type:'tangent',a:arc,b:edge,ellipseContact:{version:1,angleDeg:angle}})
function check(s,c){const e=s[0].earc,t=c.ellipseContact.angleDeg*Math.PI/180,a=e.rot*Math.PI/180,E=ellipseArcPoint(e,c.ellipseContact.angleDeg),D=[-e.rx*Math.sin(t)*Math.cos(a)-e.ry*Math.cos(t)*Math.sin(a),-e.rx*Math.sin(t)*Math.sin(a)+e.ry*Math.cos(t)*Math.cos(a)],[A,B]=s[1].pts,L=[B[0]-A[0],B[1]-A[1]],progress=((Math.sign(ellipseArcSweep(e))*(c.ellipseContact.angleDeg-e.a0))%360+360)%360;assert.ok(progress<=Math.abs(ellipseArcSweep(e))+1e-7);assert.ok(Math.abs((E[0]-A[0])*L[1]-(E[1]-A[1])*L[0])/Math.hypot(...L)<1e-7);assert.ok(Math.abs(D[0]*L[1]-D[1]*L[0])/(Math.hypot(...D)*Math.hypot(...L))<1e-7)}
for(const sweep of[80,-80,270,-270,360,-360])for(const[rx,ry]of[[10,5],[5,5],[5,10]])test(`signed general arc ${sweep} ${rx}/${ry} ${Math.abs(sweep)===360?9:10} DOF`,async()=>{const s=make(sweep,rx,ry),cs=[tangent(330+sweep/2)],r=await solveFree(s,cs);assert.equal(r.conflict,false,JSON.stringify(r.conflictIds));assert.equal(r.dof,Math.abs(sweep)===360?9:10);check(r.shapes,applyRelationUpdates(cs,r)[0]);if(Math.abs(sweep)===360)assert.equal(ellipseArcSweep(r.shapes[0].earc),sweep)})
for(const sweep of[80,-80,270,-270])test(`fixed complementary ${sweep} contact rejects original shape and ID`,async()=>{const angle=330+Math.sign(sweep)*(Math.abs(sweep)+(360-Math.abs(sweep))/2),s=make(sweep,10,5,angle),cs=[fix('E',arc),fix('L',edge),tangent(angle)],r=await solveFree(s,cs);assert.equal(r.conflict,true);assert.ok(r.conflictIds.includes('T'));assert.deepEqual(r.shapes,s);assert.equal(applyRelationUpdates(cs,r),cs)})
test('candidate initialization filters complement and seeds arc interior when line needs rotation',()=>{const s=make(20);s[1].pts=[[0,100],[10,100]];assert.equal(initialEllipseContact(s,ellipseLineTangentPair(s,arc,edge)).angleDeg,340);const v=make(80),c=initialEllipseContact(v,ellipseLineTangentPair(v,arc,edge));assert.ok(c);check(v,{ellipseContact:c})})
test('live axes cross equal radii and JSON maintains solved interval and contact',async()=>{let s=make(270),cs=[fix('C',{kind:'ellipse-point',shape:0,idx:0}),fix('V',{kind:'ellipse-point',shape:0,idx:2}),{id:'R',kind:'dim',type:'len',a:{kind:'ellipse-axis',shape:0,idx:0},value:10},tangent(465)];for(const value of[10,5,3,12]){cs=cs.map(c=>c.id==='R'?{...c,value}:c);const r=await solveFree(s,cs);assert.equal(r.conflict,false,JSON.stringify(r.conflictIds));s=r.shapes;cs=applyRelationUpdates(cs,r);check(s,cs.at(-1));assert.ok(Math.abs(s[0].earc.rx-value)<1e-6);({s,cs}=JSON.parse(JSON.stringify({s,cs})))}})
test('missing contact metadata rejects persisted relation atomically',async()=>{const s=make(80),r=await solveFree(s,[{...tangent(370),ellipseContact:undefined}]);assert.equal(r.conflict,true);assert.deepEqual(r.conflictIds,['T']);assert.deepEqual(r.shapes,s)})

test('free wrong-direction line rotates to interior tangent; fixed incompatible line rejects atomically',async()=>{const s=make(20);s[1].pts=[[20,40],[25,40]];const contact=initialEllipseContact(s,ellipseLineTangentPair(s,arc,edge)),cs=[fix('E',arc),{...tangent(contact.angleDeg)}],r=await solveFree(s,cs);assert.equal(r.conflict,false,JSON.stringify(r.conflictIds));check(r.shapes,applyRelationUpdates(cs,r).at(-1));const failed=await solveFree(s,[...cs,fix('L',edge)]);assert.equal(failed.conflict,true);assert.deepEqual(failed.shapes,s)})
test('endpoint drag that removes fixed tangent contact rejects; valid endpoint movement preserves relation',async()=>{const s=make(80),cs=[fix('L',edge),tangent(370)],valid=await solveFree(s,cs,{ref:{kind:'ellipse-arc-end',shape:0,idx:1},to:ellipseArcPoint(s[0].earc,425)});assert.equal(valid.conflict,false,JSON.stringify(valid.conflictIds));check(valid.shapes,applyRelationUpdates(cs,valid).at(-1));const invalid=await solveFree(s,cs,{ref:{kind:'ellipse-arc-end',shape:0,idx:1},to:ellipseArcPoint(s[0].earc,350)});assert.equal(invalid.conflict,true);assert.deepEqual(invalid.shapes,s)})
test('length-constrained orientation-free line rotates without changing driving dimension',async()=>{const s=make(20);s[1].pts=[[20,40],[25,40]];const contact=initialEllipseContact(s,ellipseLineTangentPair(s,arc,edge)),cs=[fix('E',arc),{id:'length',kind:'dim',type:'len',a:edge,value:5},tangent(contact.angleDeg)],snapshot=JSON.stringify(cs),r=await solveFree(s,cs);assert.equal(r.conflict,false,JSON.stringify(r.conflictIds));check(r.shapes,applyRelationUpdates(cs,r).at(-1));assert.ok(Math.abs(Math.hypot(r.shapes[1].pts[1][0]-r.shapes[1].pts[0][0],r.shapes[1].pts[1][1]-r.shapes[1].pts[0][1])-5)<1e-7);assert.equal(JSON.stringify(cs),snapshot)})
test('full turn live axis crossing retains exact signed sweep and rejects single-end opening',async()=>{for(const sweep of[360,-360]){let s=make(sweep,5,5),cs=[fix('C',{kind:'ellipse-point',shape:0,idx:0}),fix('V',{kind:'ellipse-point',shape:0,idx:2}),{id:'R',kind:'dim',type:'len',a:{kind:'ellipse-axis',shape:0,idx:0},value:5},tangent(330+sweep/2)];for(const value of[5,7,3,12]){cs=cs.map(c=>c.id==='R'?{...c,value}:c);const r=await solveFree(s,cs);assert.equal(r.conflict,false,JSON.stringify(r.conflictIds));s=r.shapes;cs=applyRelationUpdates(cs,r);assert.equal(ellipseArcSweep(s[0].earc),sweep);check(s,cs.at(-1))}const failed=await solveFree(s,cs,{ref:{kind:'ellipse-arc-end',shape:0,idx:1},to:ellipseArcPoint(s[0].earc,s[0].earc.a0+20)});assert.equal(failed.conflict,true);assert.deepEqual(failed.shapes,s)}})
