import{register}from'node:module';import test from'node:test';import assert from'node:assert/strict'
register('data:text/javascript,'+encodeURIComponent(`export async function resolve(s,c,n){if(s.includes('?url'))return {url:'data:text/javascript,export default %22%22',shortCircuit:true};return n(s,c)}`))
const {solveFree,ellipseLineTangentPair,initialEllipseContact,applyRelationUpdates,conApplicable}=await import('../src/sketch/freesolve.ts'),{ellipseSample}=await import('../src/sketch/ellipseGeometry.ts')
const ellipse={kind:'ellipse',shape:0},edge={kind:'edge',shape:1,idx:0},fix=(id,a)=>({id,kind:'con',type:'fix',a})
function make(rx=10,ry=5,rot=0){const ell={cx:20,cy:30,rx,ry,rot};return[{type:'poly',ell,pts:ellipseSample(ell)},{type:'poly',open:true,construction:true,pts:[[40,36],[50,36]]}]}
function tangent(s){return{id:'T',kind:'con',type:'tangent',a:ellipse,b:edge,ellipseContact:initialEllipseContact(s,ellipseLineTangentPair(s,ellipse,edge))}}
function check(s,c){const e=s[0].ell,t=c.ellipseContact.angleDeg*Math.PI/180,r=e.rot*Math.PI/180,E=[e.cx+e.rx*Math.cos(t)*Math.cos(r)-e.ry*Math.sin(t)*Math.sin(r),e.cy+e.rx*Math.cos(t)*Math.sin(r)+e.ry*Math.sin(t)*Math.cos(r)],D=[-e.rx*Math.sin(t)*Math.cos(r)-e.ry*Math.cos(t)*Math.sin(r),-e.rx*Math.sin(t)*Math.sin(r)+e.ry*Math.cos(t)*Math.cos(r)],[A,B]=s[1].pts,L=[B[0]-A[0],B[1]-A[1]];assert.ok(Math.abs((E[0]-A[0])*L[1]-(E[1]-A[1])*L[0])/Math.hypot(...L)<1e-7);assert.ok(Math.abs(D[0]*L[1]-D[1]*L[0])/(Math.hypot(...L)*Math.hypot(...D))<1e-7)}
for(const[rx,ry,rot]of [[10,5,0],[10,5,30],[5,5,125],[5,10,30]])test(`whole tangent eight DOF ${rx}/${ry}/${rot}`,async()=>{const s=make(rx,ry,rot),cs=[tangent(s)],r=await solveFree(s,cs);assert.equal(r.conflict,false,JSON.stringify(r.conflictIds));assert.equal(r.dof,8);check(r.shapes,applyRelationUpdates(cs,r)[0]);assert.equal(conApplicable('tangent',[ellipse,edge],s),true)})
test('live radius crossing equal axes with fixed center and horizontal line retains contact state',async()=>{let s=make(10,5,30),cs=[fix('C',{kind:'ellipse-point',shape:0,idx:0}),fix('V',{kind:'ellipse-point',shape:0,idx:2}),{id:'R',kind:'dim',type:'len',a:{kind:'ellipse-axis',shape:0,idx:0},value:10},{id:'H',kind:'con',type:'h',a:edge},tangent(s)];for(const v of[10,5,3,12]){cs=cs.map(c=>c.id==='R'?{...c,value:v}:c);const r=await solveFree(s,cs);assert.equal(r.conflict,false,JSON.stringify(r.conflictIds));s=r.shapes;cs=applyRelationUpdates(cs,r);check(s,cs.at(-1));assert.ok(Math.abs(s[0].ell.rx-v)<1e-6);({s,cs}=JSON.parse(JSON.stringify({s,cs})))}})
test('fixed incompatible support and line reject atomically; absent metadata rejects original ID',async()=>{const s=make(),c=tangent(s);for(const cs of[[fix('E',ellipse),fix('L',edge),c],[{...c,ellipseContact:undefined}]]){const r=await solveFree(s,cs);assert.equal(r.conflict,true);assert.deepEqual(r.shapes,s);assert.equal(applyRelationUpdates(cs,r),cs)}})
test('contact remains interior to infinite support, not pinned to finite endpoint',async()=>{const s=make(),cs=[fix('E',ellipse),{id:'H',kind:'con',type:'h',a:edge},tangent(s)],r=await solveFree(s,cs);assert.equal(r.conflict,false,JSON.stringify(r.conflictIds));check(r.shapes,applyRelationUpdates(cs,r).at(-1));assert.ok(Math.abs(r.shapes[1].pts[0][0]-20)>10)})
test('relation update roundoff preserves original identities',()=>{const s=make(),cs=[tangent(s)],r={shapes:s,dof:0,conflict:false,conflictIds:[],relationUpdates:[{id:'T',ellipseContact:{version:1,angleDeg:cs[0].ellipseContact.angleDeg+1e-10}}]};assert.equal(applyRelationUpdates(cs,r),cs)})
test('two contacts on one ellipse retain independent relation state',async()=>{const s=make();s[1].pts=[[0,35],[10,35]];s.push({type:'poly',open:true,pts:[[0,25],[10,25]]});const e2={kind:'edge',shape:2,idx:0},cs=[fix('E',ellipse),tangent(s),{id:'T2',kind:'con',type:'tangent',a:ellipse,b:e2,ellipseContact:initialEllipseContact(s,ellipseLineTangentPair(s,ellipse,e2))}],r=await solveFree(s,cs);assert.equal(r.conflict,false,JSON.stringify(r.conflictIds));const next=applyRelationUpdates(cs,r);check(r.shapes,next[1]);check([r.shapes[0],r.shapes[2]],next[2]);assert.ok(Math.abs(next[1].ellipseContact.angleDeg-next[2].ellipseContact.angleDeg)>179)})
test('rotated ellipse remote finite segment selects nearest support line branch',()=>{const s=make(20,5,45);s[1].pts=[[-1000,45],[-990,45]];const c=initialEllipseContact(s,ellipseLineTangentPair(s,ellipse,edge));const t=c.angleDeg*Math.PI/180,e=s[0].ell,y=e.cy+e.rx*Math.cos(t)*Math.SQRT1_2+e.ry*Math.sin(t)*Math.SQRT1_2;assert.ok(y>e.cy);s[1].pts.reverse();const reversed=initialEllipseContact(s,ellipseLineTangentPair(s,ellipse,edge));assert.ok(Math.abs(Math.cos(reversed.angleDeg*Math.PI/180)-Math.cos(t))<1e-9)})
