import {register} from 'node:module';import test from 'node:test';import assert from 'node:assert/strict'
register('data:text/javascript,'+encodeURIComponent(`export async function resolve(s,c,n){if(s.includes('?url'))return {url:'data:text/javascript,export default %22%22',shortCircuit:true};return n(s,c)}`))
const {solveFree,refPts,refValid}=await import('../src/sketch/freesolve.ts'),{ellipseArcSample,ellipseArcWithSweep,ellipseArcSweep}=await import('../src/sketch/ellipseArcGeometry.ts')
const make=(rx=10,ry=5,sweep=80,rot=30)=>{const earc=ellipseArcWithSweep({cx:20,cy:30,rx,ry,rot},330,sweep);return{type:'poly',open:true,earc,pts:ellipseArcSample(earc)}}
const pt=(idx=0)=>({kind:'ellipse-point',shape:0,idx}),end=(idx=0)=>({kind:'ellipse-arc-end',shape:0,idx}),axis=(idx=0)=>({kind:'ellipse-axis',shape:0,idx}),fix=(id,a)=>({id,kind:'con',type:'fix',a}),near=(a,b)=>assert.ok(Math.abs(a-b)<1e-6,`${a}!=${b}`)
async function solve(shapes,cons=[],drag){const r=await solveFree(shapes,cons,drag);assert.ok(r);assert.equal(r.conflict,false,JSON.stringify(r.conflictIds));return r}
for(const [rx,ry,sweep]of [[10,5,80],[5,5,80],[5,10,-270],[5.000001,5,270]])test(`true sevenDOF ellipse arc ${rx}/${ry} sweep${sweep}`,async()=>{const sh=make(rx,ry,sweep),r=await solve([sh]);assert.equal(r.dof,7);near(ellipseArcSweep(r.shapes[0].earc),sweep);near(r.shapes[0].earc.rx,rx);near(r.shapes[0].earc.ry,ry);for(const j of [0,1])refPts(r.shapes,end(j))[0].forEach((v,k)=>near(v,refPts([sh],end(j))[0][k]))})
test('live semiaxis changes through equalaxes keep dependent endpoint coincident and all dimensions',async()=>{let shapes=[make(),{type:'circle',c:refPts([make()],end())[0],r:1}],cons=[fix('C',pt()),fix('V',pt(2)),{id:'R',kind:'dim',type:'len',a:axis(),value:10},{id:'co',kind:'con',type:'coincident',a:end(),b:{kind:'pt',shape:1,idx:0}}];for(const radius of [10,5,3,5,12]){const r=await solve(shapes,cons.map(c=>c.id==='R'?{...c,value:radius}:c));shapes=r.shapes;near(shapes[0].earc.rx,radius);refPts(shapes,end())[0].forEach((v,k)=>near(v,shapes[1].c[k]))}})
test('endpoint radial projection across zero and distant angles retains support and moves dependent geometry',async()=>{let sh=make(10,5,80,0),shapes=[sh,{type:'circle',c:refPts([sh],end())[0],r:1}],cons=[{id:'co',kind:'con',type:'coincident',a:end(),b:{kind:'pt',shape:1,idx:0}}];for(const t of [359,1,179,271]){const to=[20+20*Math.cos(t*Math.PI/180),30+10*Math.sin(t*Math.PI/180)];const r=await solve(shapes,cons,{ref:end(),to});shapes=r.shapes;near(shapes[0].earc.rx,10);near(shapes[0].earc.ry,5);near(refPts(shapes,end())[0][0],20+10*Math.cos(t*Math.PI/180));near(refPts(shapes,end())[0][1],30+5*Math.sin(t*Math.PI/180));assert.ok(ellipseArcSweep(shapes[0].earc)>0)}})
test('whole Fix and legacy sampled refs reject atomically',async()=>{const sh=make();for(const c of [fix('whole',{kind:'ellipse-arc',shape:0}),fix('old',{kind:'pt',shape:0,idx:0})]){const r=await solveFree([sh],[c],{ref:end(),to:[5,40]});assert.equal(r.conflict,true);assert.deepEqual(r.shapes,[sh])}assert.equal(refValid([sh],{kind:'edge',shape:0,idx:0}),false)})
test('support center and axis drags preserve signed endpoint parameters',async()=>{let r=await solve([make(10,5,-270)],[],{ref:pt(),to:[35,45]});near(r.shapes[0].earc.cx,35);near(ellipseArcSweep(r.shapes[0].earc),-270);r=await solve(r.shapes,[],{ref:pt(1),to:[35,60]});near(r.shapes[0].earc.rx,15);near(r.shapes[0].earc.rot,90);near(ellipseArcSweep(r.shapes[0].earc),-270)})
test('explicit and legacy full-turn arcs retain full signed sweep without collapsing to zero',async()=>{for(const sweep of [360,-360]){const sh=make(10,5,sweep),r=await solve([sh]);near(ellipseArcSweep(r.shapes[0].earc),sweep)}const legacy=make();delete legacy.earc.version;delete legacy.earc.signedSweepDeg;legacy.earc.a1=legacy.earc.a0;legacy.pts=ellipseArcSample(legacy.earc);const r=await solve([legacy]);near(ellipseArcSweep(r.shapes[0].earc),360)})
const {ellipseArcPrimitives,decodeEllipseArc}=await import('../src/sketch/ellipseArcSolver.ts'),{solveSketch}=await import('../src/sketch/solver.ts')
test('decoder rejects antiparallel circle phase despite an endpoint lying on the ellipse',async()=>{const sh=make(),r=await solveSketch(ellipseArcPrimitives(0,sh.earc)),g=structuredClone(r.geometry),C=g.find(p=>p.id==='p0_0'),Q=g.find(p=>p.id==='ea0_Q0');Q.x=2*C.x-Q.x;Q.y=2*C.y-Q.y;assert.equal(decodeEllipseArc(0,sh.earc,g),null);assert.ok(decodeEllipseArc(0,sh.earc,r.geometry))})
test('endpoint distance constraints remain true through equal-axis transitions and JSON',async()=>{let shapes=[make()];const cs=[fix('C',pt()),fix('V',pt(2)),{id:'R',kind:'dim',type:'len',a:axis(),value:10},...[0,1].map(j=>({id:'d'+j,kind:'dim',type:'p2l',a:end(j),b:axis(),value:j+2}))];for(const value of [10,5,3,5,12]){const r=await solve(JSON.parse(JSON.stringify(shapes)),cs.map(c=>c.id==='R'?{...c,value}:c));shapes=r.shapes;assert.equal(r.dof,0);const e=shapes[0].earc,rot=e.rot*Math.PI/180;for(const j of [0,1]){const p=refPts(shapes,end(j))[0];near(Math.abs(-(p[0]-e.cx)*Math.sin(rot)+(p[1]-e.cy)*Math.cos(rot)),j+2)}}})
