import test from'node:test';import assert from'node:assert/strict';import{register,createRequire}from'node:module';import{fileURLToPath}from'node:url'
globalThis.require=createRequire(import.meta.url);globalThis.__dirname=fileURLToPath(new URL('.',import.meta.url));register('./native-car-loader.mjs',import.meta.url)
await import('../src/worker/cad.worker.ts');await globalThis.__wheelWorker.ready();const{useApp}=await import('../src/store.ts'),{ellipseArcWithSweep,ellipseArcSample}=await import('../src/sketch/ellipseArcGeometry.ts')
const end={kind:'ellipse-arc-end',shape:0,idx:1},edge={kind:'edge',shape:1,idx:0},fix=(id,a)=>({id,kind:'con',type:'fix',a})
function setup(conflict=false,reversed=false){const earc=ellipseArcWithSweep({cx:40,cy:40,rx:30,ry:20,rot:0},0,45),arc={type:'poly',earc,pts:ellipseArcSample(earc),open:true},pts=conflict?[[100,100],[120,100]]:[[60,55],[85,70]],line={type:'poly',open:true,construction:true,pts:reversed?[...pts].reverse():pts};useApp.setState({...useApp.getInitialState(),mode:'sketch',sketchTool:'select',sketchProfiles:[arc,line],sketchShape:null,skSel:[end,edge],skCons:conflict?[fix('arc',{kind:'ellipse-arc',shape:0}),fix('line',edge)]:[]},true)}
const snap=()=>structuredClone({shapes:useApp.getState().sketchProfiles,cons:useApp.getState().skCons,undo:useApp.getState().sketchUndo,redo:useApp.getState().sketchRedo})
test('store tangent persists selected nearest line endpoint once and commits one history entry',async()=>{for(const reversed of [false,true]){setup(false,reversed);await useApp.getState().addSkCon('tangent');assert.equal(useApp.getState().skCons.length,1);assert.equal(useApp.getState().skCons[0].tangentLineEnd,reversed?1:0);assert.equal(useApp.getState().sketchUndo.length,1)}})
test('conflicting tangent creation preserves original geometry/constraints/history exactly',async()=>{setup(true);const before=snap();await useApp.getState().addSkCon('tangent');assert.deepEqual(snap(),before);assert.match(useApp.getState().status,/衝突/)})
for(const field of ['sketchProfiles','skSel','sketchUndo','sketchRedo','skRefGeo'])test(`pending tangent discards stale ${field}`,async()=>{setup();const pending=useApp.getState().addSkCon('tangent');const s=useApp.getState();useApp.setState({[field]:field==='skRefGeo'?{pts:[[1,2]],segs:[]}:field==='skSel'?[]:[...s[field]]});const before=snap();await pending;assert.deepEqual(snap(),before)})
