import test from 'node:test'
import assert from 'node:assert/strict'
import {readFileSync} from 'node:fs'
import {stripTypeScriptTypes} from 'node:module'
import vm from 'node:vm'
function harness(){const src=readFileSync(new URL('../src/store.ts',import.meta.url),'utf8'),a=src.indexOf('  previewExtrudeEdit: async () => {'),b=src.indexOf('  setFeatParam:',a);let state={featDlg:{kind:'extrude-edit',editId:'e',params:{height:10}},features:[{id:'e',type:'extrude',height:5}],params:[],paramBindings:{},suppressedIds:[],editPreviewMesh:null},pending=[];const context=vm.createContext({get:()=>state,set:p=>state={...state,...p},dimensionExpression:s=>Number(s)?{value:Number(s)}:{error:'invalid'},evalExpr:()=>{},applyParamBindings:f=>f,expandFeats:f=>f,_previewFeatures:new WeakMap(),cad:{previewRound:f=>new Promise((resolve,reject)=>pending.push({resolve,reject,f}))}});const api=vm.runInContext(stripTypeScriptTypes(`let _editPreviewSeq=0;({${src.slice(a,b)}})`),context);return{api,pending,state:()=>state,set:p=>state={...state,...p}}}
const mesh={vertices:[1,2,3],triangles:[0,0,0]};
test('failed direct retry cannot retain previous extrusion preview',async()=>{const h=harness(),p=h.api.previewExtrudeEdit();h.pending[0].resolve(mesh);await p;assert.equal(h.state().editPreviewMesh,mesh);const q=h.api.previewExtrudeEdit();h.pending[1].resolve(null);await q;assert.equal(h.state().editPreviewMesh,null)});
test('cancelled dialog cannot receive late geometry',async()=>{const h=harness(),p=h.api.previewExtrudeEdit();h.set({featDlg:null});h.pending[0].resolve(mesh);assert.equal(await p,null);assert.equal(h.state().editPreviewMesh,null)});
test('invalid expression clears a previously successful preview',async()=>{const h=harness();h.set({editPreviewMesh:mesh,featDlg:{...h.state().featDlg,params:{height:0}}});assert.equal(await h.api.previewExtrudeEdit(),null);assert.equal(h.state().editPreviewMesh,null)});

test('same-dialog concurrent retries accept only newest response',async()=>{const h=harness(),a=h.api.previewExtrudeEdit(),b=h.api.previewExtrudeEdit();const newest={...mesh,tag:'new'};h.pending[1].resolve(newest);await b;h.pending[0].resolve({...mesh,tag:'old'});assert.equal(await a,null);assert.equal(h.state().editPreviewMesh,newest)});
test('switching to distance detaches old target face and next extent in preview',async()=>{const h=harness();h.set({features:[{id:'e',type:'extrude',height:5,toFace:{near:[0,0,20]},extent:'next'}],featDlg:{kind:'extrude-edit',editId:'e',params:{height:10,extent:'distance'}}});const p=h.api.previewExtrudeEdit();const f=h.pending[0].f[0];assert.equal(f.toFace,undefined);assert.equal(f.extent,undefined);h.pending[0].resolve(mesh);await p});
test('to-face preview preserves target-driven distance and direction',async()=>{const h=harness(),toFace={near:[0,0,20]};h.set({features:[{id:'e',type:'extrude',height:25,down:true,toFace}],featDlg:{kind:'extrude-edit',editId:'e',params:{height:10,extent:'toface'}}});const p=h.api.previewExtrudeEdit();const f=h.pending[0].f[0];assert.equal(f.height,25);assert.equal(f.down,true);assert.equal(f.toFace,toFace);h.pending[0].resolve(mesh);await p});
