import test from 'node:test'
import assert from 'node:assert/strict'
import {register,createRequire} from 'node:module'
import {fileURLToPath} from 'node:url'
globalThis.require=createRequire(import.meta.url);globalThis.__dirname=fileURLToPath(new URL('.',import.meta.url));register('./native-car-loader.mjs',import.meta.url)
await import('../src/worker/cad.worker.ts');const w=globalThis.__wheelWorker;await w.ready()
const {useApp,buildProjectPayload}=await import('../src/store.ts'),{hitTest,refPts}=await import('../src/sketch/freesolve.ts'),{ellipseArcWithSweep,ellipseArcSample}=await import('../src/sketch/ellipseArcGeometry.ts'),{importSTEP,measureVolume,getOC}=await import('replicad')
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-6,`${a} != ${b}`),all=()=>[...useApp.getState().sketchProfiles,...(useApp.getState().sketchShape?[useApp.getState().sketchShape]:[])]
const independentPoint=(e,t)=>{const r=e.rot*Math.PI/180;return[e.cx+e.rx*Math.cos(t)*Math.cos(r)-e.ry*Math.sin(t)*Math.sin(r),e.cy+e.rx*Math.cos(t)*Math.sin(r)+e.ry*Math.sin(t)*Math.cos(r)]}
const O=[1e6,-7e5],tol=s=>Math.max(2e-6,s*2e-6),close=(a,b,s)=>assert.ok(Math.abs(a-b)<tol(s),`${a} != ${b}`)
function seed(kind,scale,plane){const e={cx:O[0],cy:O[1],rx:10*scale,ry:5*scale,rot:30},ea=ellipseArcWithSweep(e,330,270),t=105*Math.PI/180,r=Math.PI/6,p=independentPoint(e,t),d=[-e.rx*Math.sin(t)*Math.cos(r)-e.ry*Math.cos(t)*Math.sin(r),-e.rx*Math.sin(t)*Math.sin(r)+e.ry*Math.cos(t)*Math.cos(r)],L=Math.hypot(...d);let shapes,cons
 if(kind==='rect'){shapes=[{type:'rect',a:O,b:[O[0]+20*scale,O[1]+10*scale]}];cons=[0,1,2,3].map(i=>({id:'axis'+i,kind:'con',type:i%2?'v':'h',a:{kind:'edge',shape:0,idx:i}}));cons.push({id:'fix',kind:'con',type:'fix',a:{kind:'pt',shape:0,idx:0}},{id:'w',kind:'dim',type:'hdist',a:{kind:'pt',shape:0,idx:0},b:{kind:'pt',shape:0,idx:1},name:'dWidth',value:20*scale,expr:String(20*scale),refs:{}},{id:'h',kind:'dim',type:'vdist',a:{kind:'pt',shape:0,idx:1},b:{kind:'pt',shape:0,idx:2},name:'dHeight',value:10*scale,expr:'dWidth/2',refs:{dWidth:'dimension:w'}})}else{shapes=[kind==='ellipse'?{type:'poly',ell:e,pts:Array.from({length:48},(_,i)=>independentPoint(e,i*Math.PI/24))}:{type:'poly',earc:ea,pts:ellipseArcSample(ea),open:false},{type:'poly',open:true,construction:true,pts:[-20,20].map(k=>[p[0]+k*scale*d[0]/L,p[1]+k*scale*d[1]/L])}];cons=[{id:'fix',kind:'con',type:'fix',a:{kind:'ellipse-point',shape:0,idx:0}},{id:'minor',kind:'con',type:'fix',a:{kind:'ellipse-point',shape:0,idx:2}},{id:'r',kind:'dim',type:'len',a:{kind:'ellipse-axis',shape:0,idx:0},name:'dRadius',value:10*scale,expr:String(10*scale),refs:{}}]}
 useApp.setState({...useApp.getInitialState(),mode:'sketch',sketchTool:'select',sketchProfiles:shapes,skCons:cons,skSel:kind==='rect'?[{kind:'edge',shape:0,idx:0}]:[{kind:kind==='ellipse'?'ellipse':'ellipse-arc',shape:0},{kind:'edge',shape:1,idx:0}],extrudeHeight:5*scale,sketchOp:'new',...(plane==='ARB'?{sketchPlane:'XY',sketchArb:{o:[10,20,30],xd:[0,1,0],n:[1,0,0]}}:{sketchPlane:plane})},true)
}
function verifyCurve(kind,s){assert.equal(useApp.getState().skConflict,false,useApp.getState().status);const shape=all()[0],e=shape.ell||shape.earc;close(e.cx,O[0],s);close(e.cy,O[1],s);close(e.rx,12*s,s);close(e.ry,5*s,s);close(e.rot,30,1);const con=useApp.getState().skCons.find(c=>c.type==='tangent');assert.equal(con.ellipseContact.version,1);const p=independentPoint(e,con.ellipseContact.angleDeg*Math.PI/180),line=all()[1].pts,v=[line[1][0]-line[0][0],line[1][1]-line[0][1]],L=Math.hypot(...v);close(((p[0]-line[0][0])*v[1]-(p[1]-line[0][1])*v[0])/L,0,s);const tt=con.ellipseContact.angleDeg*Math.PI/180,rr=e.rot*Math.PI/180,d=[-e.rx*Math.sin(tt)*Math.cos(rr)-e.ry*Math.cos(tt)*Math.sin(rr),-e.rx*Math.sin(tt)*Math.sin(rr)+e.ry*Math.cos(tt)*Math.cos(rr)];assert.ok(Math.abs(d[0]*v[1]-d[1]*v[0])/(L*Math.hypot(...d))<1e-5);if(kind==='earc')assert.ok(((con.ellipseContact.angleDeg-e.a0)%360+360)%360<=e.signedSweepDeg+1e-5);return structuredClone(shape)}
const verts=sh=>sh.type==='rect'?[sh.a,[sh.b[0],sh.a[1]],sh.b,[sh.a[0],sh.b[1]]]:sh.pts
function extent(sh){if(sh.type==='rect'||!sh.ell&&!sh.earc)return verts(sh);const e=sh.ell||sh.earc,r=e.rot*Math.PI/180,x=Math.atan2(-e.ry*Math.sin(r),e.rx*Math.cos(r))*180/Math.PI,y=Math.atan2(e.ry*Math.cos(r),e.rx*Math.sin(r))*180/Math.PI,ts=sh.earc?[e.a0,e.a0+e.signedSweepDeg]:[];for(const t of[x,x+180,y,y+180])if(!sh.earc||((t-e.a0)%360+360)%360<=e.signedSweepDeg+1e-8)ts.push(t);return ts.map(t=>independentPoint(e,t*Math.PI/180))}
async function native(expected,profiles,plane,s){const shape=await importSTEP(new Blob([await w.exportSTEP()])),checker=new(getOC().BRepCheck_Analyzer)(shape.wrapped,true,false);try{assert.ok(checker.IsValid_2())}finally{checker.delete()}const actual=measureVolume(shape);assert.ok(Math.abs(actual-expected)<Math.max(1e-9,expected*2e-5),`native farorigin volume ${actual} != ${expected}`);const ps=profiles.flatMap(extent),bounds=shape.boundingBox.bounds,map=plane==='YZ'?[[1,0,-1,0],[2,1,1,0]]:plane==='ARB'?[[1,0,1,20],[2,1,1,30]]:[[0,0,1,0],[1,1,-1,0]];for(const[w,l,sign,o]of map){const vals=ps.map(p=>p[l]*sign+o);close(bounds[0][w],Math.min(...vals),s);close(bounds[1][w],Math.max(...vals),s)}}
for(const [s,plane]of[[.01,'XY'],[1,'YZ'],[1000,'ARB']])for(const kind of['rect','ellipse','earc'])test(`farorigin ${kind} scale${s} ${plane} edit/native/history`,async()=>{
 seed(kind,s,plane);let profiles,area
 if(kind==='rect'){useApp.getState().startSkMove();useApp.getState().setSkMoveCopy(true);useApp.setState({skMove:{...useApp.getState().skMove,dx:80*s,dy:0,ang:30}});await useApp.getState().commitSkMove();assert.equal(all().length,2,useApp.getState().status);const dim=useApp.getState().skCons.find(c=>c.kind==='dim'&&c.a.shape===1&&c.type==='hdist');await useApp.getState().commitSkDim(dim.id,{value:28*s,expr:String(28*s)},'width');assert.equal(useApp.getState().skConflict,false,useApp.getState().status);const ps=verts(all()[1]),r=Math.PI/6;close((ps[1][0]-ps[0][0])*Math.cos(r)+(ps[1][1]-ps[0][1])*Math.sin(r),28*s,s);close(Math.hypot(ps[2][0]-ps[1][0],ps[2][1]-ps[1][1]),14*s,s);const anchor=[O[0]+90*s-10*s*Math.cos(r)+5*s*Math.sin(r),O[1]+5*s-10*s*Math.sin(r)-5*s*Math.cos(r)],u=[Math.cos(r),Math.sin(r)],v=[-Math.sin(r),Math.cos(r)];for(const[i,ww,hh]of[[0,0,0],[1,28,0],[2,28,14],[3,0,14]]){close(ps[i][0],anchor[0]+ww*s*u[0]+hh*s*v[0],s);close(ps[i][1],anchor[1]+ww*s*u[1]+hh*s*v[1],s)}close(verts(all()[0])[0][0],O[0],s);close(verts(all()[0])[0][1],O[1],s);profiles=structuredClone(all());area=(200+392)*s*s}else{await useApp.getState().addSkCon('tangent');assert.ok(useApp.getState().skCons.some(c=>c.type==='tangent'),useApp.getState().status);await useApp.getState().commitSkDim('r',{value:12*s,expr:String(12*s)},'radius');const sh=verifyCurve(kind,s);profiles=[sh];const e=sh.ell||sh.earc,t=e.signedSweepDeg*Math.PI/180;area=kind==='ellipse'?Math.PI*60*s*s:30*s*s*Math.abs(t-Math.sin(t))}
 await useApp.getState().extrudeSketch();assert.equal(useApp.getState().mode,'model',useApp.getState().status);await native(area*5*s,profiles,plane,s);assert.equal(await useApp.getState().applyFeatures(useApp.getState().features.map(f=>({...f,height:8*s})),'height8'),true);await native(area*8*s,profiles,plane,s);await useApp.getState().undo();await native(area*5*s,profiles,plane,s);await useApp.getState().redo();await native(area*8*s,profiles,plane,s);const payload=JSON.parse(JSON.stringify(buildProjectPayload(useApp.getState())));useApp.setState({...useApp.getInitialState()},true);await useApp.getState().applyProjectData(payload);await native(area*8*s,profiles,plane,s)
})
for(const [mode,h,h2,measure,d1,d2,lo,hi]of[
 ['symmetric',.03,.02,'whole',0,0,-.015,.015],
 ['symmetric',.02,.03,'half',0,0,-.02,.02],
 ['twosides',.03,.02,'whole',0,0,-.02,.03],
 ['twosides',.03,.02,'whole',1,2,-.02,.03]
])test(`small exact ${mode} ${measure} distances ${h}/${h2} draft${d1}/${d2}`,async()=>{
 const radius=.1;useApp.setState({...useApp.getInitialState(),mode:'sketch',sketchTool:'select',sketchProfiles:[{type:'circle',c:O,r:radius}],extrudeHeight:h,extrudeSide2:h2,extrudeExtent:mode,symMeasure:measure,extrudeDraft:d1,extrudeDraft2:d2,sketchOp:'new'},true)
 await useApp.getState().extrudeSketch();assert.equal(useApp.getState().mode,'model',useApp.getState().status);const sh=await importSTEP(new Blob([await w.exportSTEP()])),bounds=sh.boundingBox.bounds;close(bounds[0][2],lo,.01);close(bounds[1][2],hi,.01)
 const frustum=(height,angle)=>{const r2=radius-height*Math.tan(angle*Math.PI/180);return Math.PI*height*(radius*radius+radius*r2+r2*r2)/3},expected=d1||d2?frustum(h,d1)+frustum(h2,d2):Math.PI*radius*radius*(hi-lo),actual=measureVolume(sh);assert.ok(Math.abs(actual-expected)<expected*2e-5,`${actual} != ${expected}`);const checker=new(getOC().BRepCheck_Analyzer)(sh.wrapped,true,false);try{assert.ok(checker.IsValid_2())}finally{checker.delete()}
})
