import test from 'node:test'
import assert from 'node:assert/strict'
import {register,createRequire} from 'node:module'
import {fileURLToPath} from 'node:url'
globalThis.require=createRequire(import.meta.url);globalThis.__dirname=fileURLToPath(new URL('.',import.meta.url));register('./native-car-loader.mjs',import.meta.url)
await import('../src/worker/cad.worker.ts');await globalThis.__wheelWorker.ready()
const {useApp,buildProjectPayload}=await import('../src/store.ts')
const g=()=>useApp.getState(), json=()=>JSON.parse(JSON.stringify(buildProjectPayload(g())))
function seed(extra={}){useApp.setState({...useApp.getInitialState(),mode:'sketch',sketchProfiles:[{type:'rect',a:[-10,-8],b:[8,12]}],sketchShape:{type:'circle',c:[3,4],r:5},skCons:[{id:'r20',name:'d20',kind:'dim',type:'rad',a:{kind:'circle',shape:1},value:5}],skDimLabelOff:{r20:[7,8]},appConfirm:async()=>true,...extra},true)}
for(const plane of ['XY','XZ','YZ'])test(`save/open active ${plane} sketch preserves all geometry dimensions frame and resets previews`,async()=>{seed({sketchPlane:plane,sketchBaseZ:37});const p=json();assert.ok(p.sketchDraft);assert.equal('skScale' in p.sketchDraft,false);await g().reset();await g().applyProjectData(p);assert.deepEqual(json().sketchDraft,p.sketchDraft);assert.equal(g().mode,'sketch');assert.equal(g().sketchUndo.length,0);assert.equal(g().skMove,null)})
test('arbitrary frame and selected finished-sketch editing source survive JSON',async()=>{seed({sketchArb:{o:[5,6,7],xd:[1,0,0],n:[0,0.6,0.8]},skEditTarget:'sk9',sketchSources:{sk9:{shapes:[],cons:[],plane:'XY',baseZ:0,op:'new',height:0}}});const p=json();await g().reset();await g().applyProjectData(p);assert.deepEqual(json().sketchDraft,p.sketchDraft)})
test('snapshot reader also restores active sketch',async()=>{seed();const p=json();await g().reset();await g().applySnapshot(p);assert.deepEqual(json().sketchDraft,p.sketchDraft)})
test('opening old document removes every old sketch transient and binding',async()=>{seed({sketchStart:[9,9],polyPts:[[1,2]],pendingSketchFaceBinding:{sourceId:'old'},skEditTarget:'old',sketchPreview:[4,5]});await g().applyProjectData({app:'webcad',version:4,features:[]});assert.equal(g().mode,'model');assert.deepEqual(g().sketchProfiles,[]);assert.equal(g().sketchShape,null);assert.deepEqual(g().skCons,[]);assert.deepEqual(g().polyPts,[]);assert.equal(g().sketchStart,null);assert.equal(g().pendingSketchFaceBinding,null);assert.equal(g().skEditTarget,null)})
test('cancel open preserves sketch-only document exactly',async()=>{seed({appConfirm:async()=>false});const before=json();await g().applyProjectData({app:'webcad',version:4,features:[]});assert.deepEqual(json(),before)})
for(const [label,change] of [['geometry',p=>p.sketchDraft.sketchShape.c=[null,4]],['constraint index',p=>p.sketchDraft.skCons[0].a.shape=50],['dimension reference',p=>p.sketchDraft.skCons[0].refs={gone:'dimension:missing'}],['edit source',p=>p.sketchDraft.skEditTarget='missing'],['plane',p=>p.sketchDraft.sketchPlane='invalid'],['constraints',p=>p.sketchDraft.skCons=[null]]])test(`malformed draft ${label} refused before current document replacement`,async()=>{seed();const before=json(),bad=json();change(bad);await g().applyProjectData(bad);assert.deepEqual(json(),before);assert.match(g().status,/失效|格式|不存在/)})
test('partially placed polyline and model-ready sketch persist',async()=>{seed({polyPts:[[1,2],[3,4]],sketchStart:[3,4],sketchTool:'polyline'});const p=json();await g().reset();await g().applyProjectData(p);assert.deepEqual(g().polyPts,[[1,2],[3,4]]);assert.equal(g().sketchTool,'polyline');seed({mode:'model'});const q=json();await g().reset();await g().applyProjectData(q);assert.equal(g().mode,'model');assert.deepEqual(g().sketchShape,q.sketchDraft.sketchShape)})
test('sketch-only local autosave is restored even with no feature tree or components',async()=>{seed({sketchPlane:'YZ',sketchBaseZ:11});const p=json();await g().reset();const prior=Object.getOwnPropertyDescriptor(globalThis,'localStorage');Object.defineProperty(globalThis,'localStorage',{configurable:true,value:{getItem:()=>JSON.stringify(p),removeItem:()=>{}}});try{await g().restoreAutosave();assert.deepEqual(json().sketchDraft,p.sketchDraft)}finally{if(prior)Object.defineProperty(globalThis,'localStorage',prior);else delete globalThis.localStorage}})
