import test from 'node:test';import assert from 'node:assert/strict'
const {startGeometryPointerSession}=await import('../src/sketch/geometryPointerSession.ts')
function setup(extra={}){const host=new EventTarget(),canvas=new EventTarget(),events=[],captured=new Set();Object.assign(canvas,{ownerDocument:{defaultView:host},setPointerCapture:id=>captured.add(id),hasPointerCapture:id=>captured.has(id),releasePointerCapture:id=>{captured.delete(id);emit(canvas,'lostpointercapture',id)}});const cleanup=startGeometryPointerSession({canvas,pointerId:7,project:(x,y)=>[x*2,y*3],move:p=>events.push(['move',p]),end:p=>events.push(['end',p]),cancel:()=>events.push(['cancel']),onClose:()=>events.push(['close']),...extra});return{host,canvas,events,captured,cleanup}}
function emit(target,type,pointerId=7,x=10,y=20){const e=new Event(type);Object.assign(e,{pointerId,clientX:x,clientY:y});target.dispatchEvent(e)}
test('capture follows movement over other DOM surfaces and release outside canvas commits once',()=>{const s=setup();assert.ok(s.captured.has(7));emit(s.host,'pointermove',7,30,40);emit(s.host,'pointerup',7,1000,-40);assert.deepEqual(s.events,[['move',[60,120]],['close'],['end',[2000,-120]]]);assert.equal(s.captured.size,0);emit(s.host,'pointerup');emit(s.host,'pointermove');assert.equal(s.events.length,3)})
test('foreign pointer cannot move or release active geometry gesture',()=>{const s=setup();emit(s.host,'pointermove',8);emit(s.host,'pointerup',8);emit(s.host,'pointercancel',8);assert.deepEqual(s.events,[]);assert.ok(s.captured.has(7));s.cleanup()})
for(const type of ['pointercancel','lostpointercapture','blur'])test(`${type} cancels once and restores capture lifecycle`,()=>{const s=setup();emit(type==='lostpointercapture'?s.canvas:s.host,type);assert.deepEqual(s.events,[['close'],['cancel']]);assert.equal(s.captured.size,0);emit(s.host,'pointerup');s.cleanup();assert.equal(s.events.length,2)})
test('Escape/store/unmount cleanup is silent and invalidates subsequent native events',()=>{const s=setup();s.cleanup();s.cleanup();emit(s.host,'pointermove');emit(s.host,'pointerup');assert.deepEqual(s.events,[['close']]);assert.equal(s.captured.size,0)})
test('missing ray intersection skips preview and cancels release rather than committing stale point',()=>{const s=setup({project:()=>null});emit(s.host,'pointermove');assert.deepEqual(s.events,[]);emit(s.host,'pointerup');assert.deepEqual(s.events,[['close'],['cancel']])})
test('release detaches lost capture handler before capture is released',()=>{const s=setup();emit(s.host,'pointerup');assert.deepEqual(s.events,[['close'],['end',[20,60]]])})
test('capture failure closes session and cancels original gesture',()=>{const host=new EventTarget(),canvas=new EventTarget(),events=[];Object.assign(canvas,{ownerDocument:{defaultView:host},setPointerCapture:()=>{throw new Error('not active')},hasPointerCapture:()=>false});startGeometryPointerSession({canvas,pointerId:1,project:()=>[0,0],move:()=>{},end:()=>events.push('end'),cancel:()=>events.push('cancel'),onClose:()=>events.push('close')});assert.deepEqual(events,['close','cancel']);emit(host,'pointerup',1);assert.equal(events.length,2)})
test('late rejected final transaction cannot cancel a subsequent gesture',async()=>{let reject;const s=setup({end:()=>new Promise((_,r)=>reject=r)});emit(s.host,'pointerup');reject(new Error('old transaction'));await Promise.resolve();await Promise.resolve();assert.deepEqual(s.events,[['close']])})

test('an input blur captured by the window does not cancel the new canvas gesture',()=>{const s=setup(),input=new EventTarget(),e=new Event('blur');Object.defineProperty(e,'target',{value:input});s.host.dispatchEvent(e);assert.deepEqual(s.events,[]);assert.ok(s.captured.has(7));emit(s.host,'pointermove',7,15,25);emit(s.host,'pointerup',7,20,30);assert.deepEqual(s.events,[['move',[30,75]],['close'],['end',[40,90]]])})
