/**
 * v1.70: CREATE/MODIFY/PRINT residual ribbon labels → Traditional Chinese (HK).
 * SW CACHE → webcad-v1.70. Prefer labels — not Help encyclopedias. LAB tools stay under 實驗室.
 * Retain MESH SC pin, DRAWING/SKETCH/illegal/SELECT/導出 STL/Shell-bake/Boolean help/LAB gear/v1.69/ZH chrome.
 */
import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { tLabel } from '../src/i18n.ts'

const version = readFileSync(new URL('../src/version.ts', import.meta.url), 'utf8')
const sw = readFileSync(new URL('../public/sw.js', import.meta.url), 'utf8')
const ribbon = readFileSync(new URL('../src/ribbon.ts', import.meta.url), 'utf8')
const i18n = readFileSync(new URL('../src/i18n.ts', import.meta.url), 'utf8')
const browser = readFileSync(new URL('../src/components/BrowserTree.tsx', import.meta.url), 'utf8')
const timeline = readFileSync(new URL('../src/components/Timeline.tsx', import.meta.url), 'utf8')
const meshDrop = readFileSync(new URL('../src/io/meshDrop.ts', import.meta.url), 'utf8')
const illegal = readFileSync(new URL('../src/ui/illegalInput.ts', import.meta.url), 'utf8')
const drawing = readFileSync(new URL('../src/components/DrawingPanel.tsx', import.meta.url), 'utf8')
const featureStatus = readFileSync(new URL('../src/ui/featureStatus.ts', import.meta.url), 'utf8')
const store = readFileSync(new URL('../src/store.ts', import.meta.url), 'utf8')

test('APP_VERSION is 1.70+', () => {
  assert.match(version, /APP_VERSION = '1\.(7\d|[8-9]\d)'|APP_VERSION = '[2-9]\./)
})

test('v1.70: SW CACHE bumped to webcad-v1.70+; navigate network-first; release comment', () => {
  assert.match(sw, /const CACHE = 'webcad-v1\.(7[0-9]|[8-9]\d)'/)
  assert.doesNotMatch(sw, /const CACHE = 'webcad-v1\.69'/)
  assert.doesNotMatch(sw, /const CACHE = 'webcad-v1'/)
  assert.match(sw, /RELEASE: CACHE 必须随每次发版改名|RELEASE: CACHE 必須隨每次發版改名/)
  assert.match(sw, /mode === 'navigate'/)
  assert.match(sw, /network-first|永远攞最新|永遠攞最新/)
})

test('v1.70: ribbon CREATE/MODIFY/PRINT residual labels Traditional', () => {
  assert.match(ribbon, /id: 'facesketch', label: '面上草圖'/)
  assert.match(ribbon, /id: 'othread', label: '面加螺紋'/)
  assert.match(ribbon, /id: 'ithread', label: '內螺紋孔'/)
  assert.match(ribbon, /id: 'moveface', label: '移動面'/)
  assert.match(ribbon, /id: 'filletall', label: '全棱圓角'/)
  assert.match(ribbon, /id: 'cylpatch', label: '圓柱曲面貼花'/)
  assert.match(ribbon, /id: 'splitsketch', label: '草圖輪廓分割'/)
  assert.match(ribbon, /id: 'tube', label: '圓管'/)
  assert.match(ribbon, /id: 'rbox', label: '圓角盒'/)
  assert.match(ribbon, /id: 'dome', label: '圓頂'/)
  assert.match(ribbon, /id: 'halfcyl', label: '半圓柱'/)
  assert.match(ribbon, /id: 'xray', label: '透視'/)
  assert.match(ribbon, /id: 'autoorient', label: '自動擺正'/)
  assert.match(ribbon, /id: 'wallcheck', label: '壁厚檢查'/)
  assert.match(ribbon, /id: 'projsurf', label: '投影到圓柱面'/)
  assert.doesNotMatch(ribbon, /id: 'facesketch', label: '面上草图'/)
  assert.doesNotMatch(ribbon, /id: 'othread', label: '面加螺纹'/)
  assert.doesNotMatch(ribbon, /id: 'ithread', label: '内螺纹孔'/)
  assert.doesNotMatch(ribbon, /id: 'moveface', label: '移动面'/)
  assert.doesNotMatch(ribbon, /id: 'filletall', label: '全棱圆角'/)
  assert.doesNotMatch(ribbon, /id: 'cylpatch', label: '圆柱曲面贴花'/)
  assert.doesNotMatch(ribbon, /id: 'splitsketch', label: '草图轮廓分割'/)
  assert.doesNotMatch(ribbon, /id: 'tube', label: '圆管'/)
  assert.doesNotMatch(ribbon, /id: 'rbox', label: '圆角盒'/)
  assert.doesNotMatch(ribbon, /id: 'dome', label: '圆顶'/)
  assert.doesNotMatch(ribbon, /id: 'halfcyl', label: '半圆柱'/)
  assert.doesNotMatch(ribbon, /id: 'xray', label: '透视'/)
  assert.doesNotMatch(ribbon, /id: 'autoorient', label: '自动摆正'/)
  assert.doesNotMatch(ribbon, /id: 'wallcheck', label: '壁厚检查'/)
  assert.doesNotMatch(ribbon, /id: 'projsurf', label: '投影到圆柱面'/)
})

test('v1.70: Timeline + BrowserTree companion labels Traditional', () => {
  assert.match(timeline, /ithread: \{ icon: 'hole', label: '內螺紋孔'/)
  assert.match(timeline, /cylpatch: \{ icon: 'cylpatch', label: '曲面貼花'/)
  assert.match(timeline, /moveface: \{ icon: 'replaceface', label: '移動面'/)
  assert.match(timeline, /othread: \{ icon: 'thread', label: '面外螺紋'/)
  assert.match(browser, /ithread: \{ icon: 'hole', label: '內螺紋孔'/)
  assert.match(browser, /cylpatch: \{ icon: 'default', label: '曲面貼花'/)
  assert.match(browser, /moveface: \{ icon: 'replaceface', label: '移動面'/)
  assert.match(browser, /othread: \{ icon: 'default', label: '面外螺紋'/)
  assert.doesNotMatch(timeline, /label: '内螺纹孔'/)
  assert.doesNotMatch(timeline, /label: '移动面'/)
  assert.doesNotMatch(browser, /label: '内螺纹孔'/)
  assert.doesNotMatch(browser, /label: '面外螺纹'/)
})

test('v1.70: EN_LABEL + tLabel for TC keys; legacy SC retained', () => {
  assert.equal(tLabel('面上草圖', 'en'), 'Sketch on Face')
  assert.equal(tLabel('面加螺紋', 'en'), 'Thread')
  assert.equal(tLabel('內螺紋孔', 'en'), 'Tapped Hole')
  assert.equal(tLabel('移動面', 'en'), 'Move Face')
  assert.equal(tLabel('全棱圓角', 'en'), 'Fillet All Edges')
  assert.equal(tLabel('圓柱曲面貼花', 'en'), 'Cylindrical Emboss')
  assert.equal(tLabel('草圖輪廓分割', 'en'), 'Split by Sketch Profile')
  assert.equal(tLabel('圓管', 'en'), 'Tube')
  assert.equal(tLabel('圓角盒', 'en'), 'Rounded Box')
  assert.equal(tLabel('圓頂', 'en'), 'Dome')
  assert.equal(tLabel('半圓柱', 'en'), 'Half Cylinder')
  assert.equal(tLabel('透視', 'en'), 'Perspective')
  assert.equal(tLabel('自動擺正', 'en'), 'Auto Orient')
  assert.equal(tLabel('壁厚檢查', 'en'), 'Wall Thickness')
  assert.equal(tLabel('投影到圓柱面', 'en'), 'Project to Cylinder')
  // legacy SC retained
  assert.equal(tLabel('面上草图', 'en'), 'Sketch on Face')
  assert.equal(tLabel('面加螺纹', 'en'), 'Thread')
  assert.equal(tLabel('内螺纹孔', 'en'), 'Tapped Hole')
  assert.equal(tLabel('全棱圆角', 'en'), 'Fillet All Edges')
  assert.equal(tLabel('圆管', 'en'), 'Tube')
  assert.equal(tLabel('自动摆正', 'en'), 'Auto Orient')
  assert.match(i18n, /'面上草圖': 'Sketch on Face'/)
  assert.match(i18n, /'投影到圓柱面': 'Project to Cylinder'/)
})

test('Do not regress prior TC + MESH SC pin + LAB gear + Boolean help + construct + v1.69', () => {
  assert.match(ribbon, /id: 'insertmesh', label: '插入STL网格'/)
  assert.match(ribbon, /id: 'exportstl', label: '導出STL'/)
  assert.match(ribbon, /id: 'select', label: '選擇'/)
  assert.match(ribbon, /id: 'drawing', label: '工程圖'/)
  assert.match(ribbon, /id: 'asmdrawing', label: '裝配工程圖'/)
  assert.match(ribbon, /id: 'sk_polyline', label: '直線'/)
  assert.match(ribbon, /id: 'datumgeom', label: '構造幾何'/)
  assert.match(ribbon, /id: 'newbody', label: '新實體'/)
  assert.match(ribbon, /id: 'gear', label: '齒輪'/)
  assert.match(ribbon, /id: 'thread', label: '螺紋桿'/)
  assert.match(ribbon, /id: 'ucs', label: '用戶坐標系'/)
  assert.match(ribbon, /id: 'plane3pt', label: '過三點平面'/)
  assert.match(ribbon, /id: 'importdxf', label: '導入DXF'/)
  assert.match(ribbon, /name: '3D列印'/)
  assert.match(ribbon, /name: '構造擴展'/)
  assert.match(drawing, /裝配工程圖/)
  assert.match(illegal, /ILLEGAL_REJECT_MARKER = '尺寸已拒絕'/)
  assert.match(i18n, /CREATE: '建立'/)
  assert.match(i18n, /CONSTRUCT: '構造'/)
  assert.match(i18n, /SOLID: '實體'/)
  assert.match(store, /label: '烘焙為零件實體'/)
  assert.match(featureStatus, /已抽殼/)
  assert.match(featureStatus, /已實體布爾|時間軸可改/)
  assert.match(meshDrop, /MESH_TAB_DROP_HINT|拖到视口导入/)
  assert.match(ribbon, /'🧪實驗室': \{ id: '🧪實驗室'/)
  const labStart = ribbon.indexOf("// 🧪實驗室")
  const labEnd = ribbon.indexOf("'🧪實驗室': { id: '🧪實驗室'")
  const labBlock = ribbon.slice(labStart, labEnd)
  assert.match(labBlock, /id: 'gear', label: '齒輪'/)
  assert.match(labBlock, /name: '3D列印'/)
  assert.match(labBlock, /id: 'tube', label: '圓管'/)
  assert.match(labBlock, /id: 'autoorient', label: '自動擺正'/)
})
