/**
 * v1.72: LAB panel group names + stack label → Traditional Chinese (HK).
 * SW CACHE → webcad-v1.72. Prefer labels — not Help encyclopedias.
 * Tool labels under these panels already TC in v1.70/v1.71 — this slice is panel chrome.
 * Retain MESH SC pin + prior TC. LAB tools stay under 實驗室.
 */
import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { tLabel } from '../src/i18n.ts'

const version = readFileSync(new URL('../src/version.ts', import.meta.url), 'utf8')
const sw = readFileSync(new URL('../public/sw.js', import.meta.url), 'utf8')
const ribbon = readFileSync(new URL('../src/ribbon.ts', import.meta.url), 'utf8')
const i18n = readFileSync(new URL('../src/i18n.ts', import.meta.url), 'utf8')
const viewport = readFileSync(new URL('../src/components/Viewport.tsx', import.meta.url), 'utf8')
const browser = readFileSync(new URL('../src/components/BrowserTree.tsx', import.meta.url), 'utf8')
const timeline = readFileSync(new URL('../src/components/Timeline.tsx', import.meta.url), 'utf8')
const slice = readFileSync(new URL('../src/components/SlicePanel.tsx', import.meta.url), 'utf8')
const app = readFileSync(new URL('../src/App.tsx', import.meta.url), 'utf8')
const meshDrop = readFileSync(new URL('../src/io/meshDrop.ts', import.meta.url), 'utf8')
const illegal = readFileSync(new URL('../src/ui/illegalInput.ts', import.meta.url), 'utf8')
const drawing = readFileSync(new URL('../src/components/DrawingPanel.tsx', import.meta.url), 'utf8')
const featureStatus = readFileSync(new URL('../src/ui/featureStatus.ts', import.meta.url), 'utf8')
const store = readFileSync(new URL('../src/store.ts', import.meta.url), 'utf8')

test('APP_VERSION is 1.72+', () => {
  assert.match(version, /APP_VERSION = '1\.(7[2-9]|[8-9]\d)'|APP_VERSION = '[2-9]\./)
})

test('v1.72: SW CACHE bumped to webcad-v1.72+; navigate network-first; release comment', () => {
  assert.match(sw, /const CACHE = 'webcad-v1\.(7[2-9]|[8-9]\d)'/)
  assert.doesNotMatch(sw, /const CACHE = 'webcad-v1\.71'/)
  assert.doesNotMatch(sw, /const CACHE = 'webcad-v1'/)
  assert.match(sw, /RELEASE: CACHE 必须随每次发版改名|RELEASE: CACHE 必須隨每次發版改名/)
  assert.match(sw, /mode === 'navigate'/)
  assert.match(sw, /network-first|永远攞最新|永遠攞最新/)
})

test('v1.72: LAB panel names + stack label Traditional', () => {
  assert.match(ribbon, /name: 'CREATE 擴充'/)
  assert.match(ribbon, /name: '製造 CAM'/)
  assert.match(ribbon, /name: '裝配輔助'/)
  assert.match(ribbon, /name: '直接編輯擴展'/)
  assert.match(ribbon, /id: 'stack', label: '堆疊'/)
  assert.doesNotMatch(ribbon, /name: 'CREATE 扩充'/)
  assert.doesNotMatch(ribbon, /name: '制造 CAM'/)
  assert.doesNotMatch(ribbon, /name: '装配辅助'/)
  assert.doesNotMatch(ribbon, /name: '直接编辑扩展'/)
  assert.doesNotMatch(ribbon, /id: 'stack', label: '堆叠'/)
})

test('v1.72: Viewport assemble-menu companion Traditional', () => {
  assert.match(viewport, /label: '⊟ 垂直堆疊'/)
  assert.doesNotMatch(viewport, /label: '⊟ 垂直堆叠'/)
})

test('v1.72: EN_LABEL + tLabel for TC keys; legacy SC retained', () => {
  assert.equal(tLabel('CREATE 擴充', 'en'), 'CREATE Ext')
  assert.equal(tLabel('製造 CAM', 'en'), 'Manufacture CAM')
  assert.equal(tLabel('裝配輔助', 'en'), 'Assembly Assist')
  assert.equal(tLabel('直接編輯擴展', 'en'), 'Direct Edit Ext')
  assert.equal(tLabel('堆疊', 'en'), 'Stack')
  assert.equal(tLabel('垂直堆疊', 'en'), 'Vertical Stack')
  assert.equal(tLabel('CREATE 扩充', 'en'), 'CREATE Ext')
  assert.equal(tLabel('制造 CAM', 'en'), 'Manufacture CAM')
  assert.equal(tLabel('装配辅助', 'en'), 'Assembly Assist')
  assert.equal(tLabel('直接编辑扩展', 'en'), 'Direct Edit Ext')
  assert.equal(tLabel('堆叠', 'en'), 'Stack')
  assert.match(i18n, /'CREATE 擴充': 'CREATE Ext'/)
  assert.match(i18n, /'製造 CAM': 'Manufacture CAM'/)
  assert.match(i18n, /'直接編輯擴展': 'Direct Edit Ext'/)
  assert.match(i18n, /'堆疊': 'Stack'/)
})

test('Do not regress prior TC + MESH SC pin + Boolean leftovers + LAB under 實驗室', () => {
  assert.match(ribbon, /id: 'insertmesh', label: '插入STL网格'/)
  assert.match(ribbon, /id: 'exportstl', label: '導出STL'/)
  assert.match(ribbon, /id: 'select', label: '選擇'/)
  assert.match(ribbon, /id: 'drawing', label: '工程圖'/)
  assert.match(ribbon, /id: 'asmdrawing', label: '裝配工程圖'/)
  assert.match(ribbon, /id: 'sk_polyline', label: '直線'/)
  assert.match(ribbon, /id: 'datumgeom', label: '構造幾何'/)
  assert.match(ribbon, /id: 'planemid', label: '中間平面'/)
  assert.match(ribbon, /id: 'gear', label: '齒輪'/)
  assert.match(ribbon, /id: 'thread', label: '螺紋桿'/)
  assert.match(ribbon, /id: 'ucs', label: '用戶坐標系'/)
  assert.match(ribbon, /id: 'importdxf', label: '導入DXF'/)
  assert.match(ribbon, /id: 'explodeview', label: '爆炸視圖'/)
  assert.match(ribbon, /id: 'insertcanvas', label: '畫布'/)
  assert.match(ribbon, /id: 'insertdecal', label: '貼花'/)
  assert.match(ribbon, /id: 'facesketch', label: '面上草圖'/)
  assert.match(ribbon, /name: '3D列印'/)
  assert.match(drawing, /裝配工程圖/)
  assert.match(illegal, /ILLEGAL_REJECT_MARKER = '尺寸已拒絕'/)
  assert.match(i18n, /CREATE: '建立'/)
  assert.match(i18n, /CONSTRUCT: '構造'/)
  assert.match(store, /label: '烘焙為零件實體'/)
  assert.match(featureStatus, /已抽殼/)
  assert.match(featureStatus, /已實體布爾|時間軸可改/)
  assert.match(viewport, /manifold 網格布爾/)
  assert.match(viewport, /來源「\$\{/)
  assert.match(meshDrop, /MESH_TAB_DROP_HINT|拖到视口导入/)
  assert.match(ribbon, /'🧪實驗室': \{ id: '🧪實驗室'/)
  const labStart = ribbon.indexOf("// 🧪實驗室")
  const labEnd = ribbon.indexOf("'🧪實驗室': { id: '🧪實驗室'")
  const labBlock = ribbon.slice(labStart, labEnd)
  assert.match(labBlock, /name: 'CREATE 擴充'/)
  assert.match(labBlock, /name: '製造 CAM'/)
  assert.match(labBlock, /name: '裝配輔助'/)
  assert.match(labBlock, /name: '直接編輯擴展'/)
  assert.match(labBlock, /id: 'stack', label: '堆疊'/)
  assert.match(labBlock, /id: 'fea', label: '受力雲圖'/)
  assert.match(labBlock, /id: 'slicepreview', label: '切層預覽'/)
  assert.match(labBlock, /id: 'pyramid', label: '棱錐'/)
  assert.match(labBlock, /id: 'delface', label: '刪面治癒'/)
  assert.match(labBlock, /id: 'gear', label: '齒輪'/)
  assert.match(labBlock, /name: '構造擴展'/)
  const start = store.indexOf('componentBoolean: async')
  const end = store.indexOf('planeCutComponent: async')
  assert.ok(start >= 0 && end > start)
  const block = store.slice(start, end)
  assert.match(block, /來源體/)
  assert.match(block, /工具體/)
  assert.match(block, /組件布爾＝網格布爾（非零件時間軸）/)
})
