/**
 * v1.73: Timeline / BrowserTree FEAT feature names → Traditional Chinese (HK).
 * SW CACHE → webcad-v1.73. Prefer labels — not Help encyclopedias / tip novels.
 * Ribbon SURFACE/MODIFY already TC — this slice is tree/timeline FEAT maps.
 * Retain MESH SC pin + prior TC. LAB tools stay under 實驗室.
 */
import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { tLabel, tStatus } from '../src/i18n.ts'

const version = readFileSync(new URL('../src/version.ts', import.meta.url), 'utf8')
const sw = readFileSync(new URL('../public/sw.js', import.meta.url), 'utf8')
const ribbon = readFileSync(new URL('../src/ribbon.ts', import.meta.url), 'utf8')
const i18n = readFileSync(new URL('../src/i18n.ts', import.meta.url), 'utf8')
const browser = readFileSync(new URL('../src/components/BrowserTree.tsx', import.meta.url), 'utf8')
const timeline = readFileSync(new URL('../src/components/Timeline.tsx', import.meta.url), 'utf8')
const meshDrop = readFileSync(new URL('../src/io/meshDrop.ts', import.meta.url), 'utf8')
const illegal = readFileSync(new URL('../src/ui/illegalInput.ts', import.meta.url), 'utf8')
const drawing = readFileSync(new URL('../src/components/DrawingPanel.tsx', import.meta.url), 'utf8')
const featureStatus = readFileSync(new URL('../src/ui/featureStatus.ts', import.meta.url), 'utf8')
const store = readFileSync(new URL('../src/store.ts', import.meta.url), 'utf8')
const viewport = readFileSync(new URL('../src/components/Viewport.tsx', import.meta.url), 'utf8')

test('APP_VERSION is 1.73+', () => {
  assert.match(version, /APP_VERSION = '1\.(7[3-9]|[8-9]\d)'|APP_VERSION = '[2-9]\./)
})

test('v1.73: SW CACHE bumped to webcad-v1.73; navigate network-first; release comment', () => {
  assert.match(sw, /const CACHE = 'webcad-v1\.(7[3-9]|[8-9]\d)'/)
  assert.doesNotMatch(sw, /const CACHE = 'webcad-v1\.72'/)
  assert.doesNotMatch(sw, /const CACHE = 'webcad-v1'/)
  assert.match(sw, /RELEASE: CACHE 必须随每次发版改名|RELEASE: CACHE 必須隨每次發版改名/)
  assert.match(sw, /mode === 'navigate'/)
  assert.match(sw, /network-first|永远攞最新|永遠攞最新/)
})

test('v1.73: Timeline FEAT labels Traditional', () => {
  assert.match(timeline, /prim: \{ icon: 'box', label: '原語'/)
  assert.match(timeline, /boundarypatch: \{ icon: 'surf', label: '邊界補面'/)
  assert.match(timeline, /surfsew: \{ icon: 'shell', label: '縫合 Stitch'/)
  assert.match(timeline, /surfunstitch: \{ icon: 'shell', label: '取消縫合'/)
  assert.match(timeline, /ruled: \{ icon: 'loft', label: '規則曲面'/)
  assert.match(timeline, /untrim: \{ icon: 'shell', label: '去裁\/還原'/)
  assert.match(timeline, /mergefaces: \{ icon: 'shell', label: '合併面'/)
  assert.match(timeline, /editpoles: \{ icon: 'editpoles', label: '編輯曲面控制點'/)
  assert.match(timeline, /featpattern: \{ icon: 'pattern', label: '陣列（組）'/)
  assert.match(timeline, /extgroup: \{ icon: 'extrude', label: '拉伸組'/)
  assert.match(timeline, /scale: \{ icon: 'scale', label: '縮放'/)
  assert.match(timeline, /copybody: \{ icon: 'newbody', label: '複製實體'/)
  assert.match(timeline, /transform: \{ icon: 'move', label: '移動'/)
  assert.match(timeline, /reversesurf: \{ icon: 'shell', label: '翻轉曲面'/)
  assert.match(timeline, /thickenquilt: \{ icon: 'thicken', label: '加厚整張曲面'/)
  assert.match(timeline, /replaceface: \{ icon: 'replaceface', label: '替換面'/)
  assert.match(timeline, /stepbody: \{ icon: 'insert', label: 'STEP實體'/)
  assert.match(timeline, /sketch: \{ icon: 'sketch', label: '草圖'/)
  assert.match(timeline, /datum: \{ icon: 'mirror', label: '參考面'/)
  assert.match(timeline, /meshbody: \{ icon: 'insert', label: '網格實體'/)
  assert.doesNotMatch(timeline, /prim: \{ icon: 'box', label: '原语'/)
  assert.doesNotMatch(timeline, /copybody: \{ icon: 'newbody', label: '复制实体'/)
  assert.doesNotMatch(timeline, /transform: \{ icon: 'move', label: '移动'/)
  assert.doesNotMatch(timeline, /editpoles: \{ icon: 'editpoles', label: '编辑曲面控制点'/)
  assert.doesNotMatch(timeline, /meshbody: \{ icon: 'insert', label: '网格实体'/)
  assert.doesNotMatch(timeline, /datum: \{ icon: 'mirror', label: '参考面'/)
})

test('v1.73: BrowserTree FEAT labels + datum chrome Traditional', () => {
  assert.match(browser, /prim: \{ icon: 'box', label: '原語'/)
  assert.match(browser, /boundarypatch: \{ icon: 'loft', label: '邊界補面'/)
  assert.match(browser, /surfsew: \{ icon: 'shell', label: '縫合 Stitch'/)
  assert.match(browser, /surfunstitch: \{ icon: 'shell', label: '取消縫合'/)
  assert.match(browser, /ruled: \{ icon: 'loft', label: '規則曲面'/)
  assert.match(browser, /untrim: \{ icon: 'shell', label: '去裁\/還原'/)
  assert.match(browser, /editpoles: \{ icon: 'loft', label: '編輯曲面控制點'/)
  assert.match(browser, /copybody: \{ icon: 'newbody', label: '複製實體'/)
  assert.match(browser, /transform: \{ icon: 'move', label: '移動'/)
  assert.match(browser, /reversesurf: \{ icon: 'shell', label: '翻轉曲面'/)
  assert.match(browser, /thickenquilt: \{ icon: 'shell', label: '加厚整張曲面'/)
  assert.match(browser, /stepbody: \{ icon: 'insert', label: 'STEP實體'/)
  assert.match(browser, /sketch: \{ icon: 'sketch', label: '草圖'/)
  assert.match(browser, /meshbody: \{ icon: 'insert', label: '網格實體'/)
  assert.match(browser, /extgroup: \{ icon: 'extrude', label: '拉伸組'/)
  assert.match(browser, /tStatus\('參考面', lang\)/)
  assert.match(browser, /tStatus\('編輯參考面', lang\)/)
  assert.match(browser, /tStatus\('顯示 \/ 隱藏此參考面', lang\)/)
  assert.doesNotMatch(browser, /prim: \{ icon: 'box', label: '原语'/)
  assert.doesNotMatch(browser, /copybody: \{ icon: 'newbody', label: '复制实体'/)
  assert.doesNotMatch(browser, /transform: \{ icon: 'move', label: '移动'/)
  assert.doesNotMatch(browser, /editpoles: \{ icon: 'loft', label: '编辑曲面控制点'/)
  assert.doesNotMatch(browser, /meshbody: \{ icon: 'insert', label: '网格实体'/)
  assert.doesNotMatch(browser, /tStatus\('参考面', lang\)/)
})

test('v1.73: EN_LABEL + tLabel/tStatus for TC keys; legacy SC retained', () => {
  assert.equal(tLabel('原語', 'en'), 'Primitive')
  assert.equal(tLabel('原语', 'en'), 'Primitive')
  assert.equal(tLabel('複製實體', 'en'), 'Copy Body')
  assert.equal(tLabel('复制实体', 'en'), 'Copy Body')
  assert.equal(tLabel('移動', 'en'), 'Move')
  assert.equal(tLabel('移动', 'en'), 'Move')
  assert.equal(tLabel('網格實體', 'en'), 'Mesh Body')
  assert.equal(tLabel('网格实体', 'en'), 'Mesh Body')
  assert.equal(tLabel('STEP實體', 'en'), 'STEP Body')
  assert.equal(tLabel('參考面', 'en'), 'Reference Plane')
  assert.equal(tLabel('参考面', 'en'), 'Reference Plane')
  assert.equal(tLabel('草圖', 'en'), 'Sketch')
  assert.equal(tLabel('拉伸組', 'en'), 'Extrude Group')
  assert.equal(tLabel('陣列（組）', 'en'), 'Pattern (Group)')
  assert.equal(tLabel('編輯曲面控制點', 'en'), 'Edit Surface Poles')
  assert.equal(tLabel('翻轉曲面', 'en'), 'Reverse Normal')
  assert.equal(tStatus('參考面', 'en'), 'Reference Plane')
  assert.equal(tStatus('編輯參考面', 'en'), 'Edit Reference Plane')
  assert.match(i18n, /'原語': 'Primitive'/)
  assert.match(i18n, /'複製實體': 'Copy Body'/)
  assert.match(i18n, /'網格實體': 'Mesh Body'/)
  assert.match(i18n, /'參考面': 'Reference Plane'/)
})

test('Do not regress prior TC + MESH SC pin + Boolean leftovers + LAB under 實驗室', () => {
  assert.match(ribbon, /id: 'insertmesh', label: '插入STL网格'/)
  assert.match(ribbon, /id: 'exportstl', label: '導出STL'/)
  assert.match(ribbon, /id: 'select', label: '選擇'/)
  assert.match(ribbon, /id: 'drawing', label: '工程圖'/)
  assert.match(ribbon, /id: 'asmdrawing', label: '裝配工程圖'/)
  assert.match(ribbon, /id: 'sk_polyline', label: '直線'/)
  assert.match(ribbon, /id: 'datumgeom', label: '構造幾何'/)
  assert.match(ribbon, /id: 'planemid', label: '中間平面'/)
  assert.match(ribbon, /id: 'gear', label: '齒輪'/)
  assert.match(ribbon, /id: 'thread', label: '螺紋桿'/)
  assert.match(ribbon, /id: 'ucs', label: '用戶坐標系'/)
  assert.match(ribbon, /id: 'importdxf', label: '導入DXF'/)
  assert.match(ribbon, /id: 'explodeview', label: '爆炸視圖'/)
  assert.match(ribbon, /id: 'insertcanvas', label: '畫布'/)
  assert.match(ribbon, /id: 'insertdecal', label: '貼花'/)
  assert.match(ribbon, /id: 'facesketch', label: '面上草圖'/)
  assert.match(ribbon, /id: 'editpoles', label: '編輯曲面控制點'/)
  assert.match(ribbon, /id: 'reversesurf', label: '翻轉曲面'/)
  assert.match(ribbon, /id: 'scale', label: '縮放'/)
  assert.match(ribbon, /name: 'CREATE 擴充'/)
  assert.match(ribbon, /name: '製造 CAM'/)
  assert.match(ribbon, /name: '裝配輔助'/)
  assert.match(ribbon, /name: '直接編輯擴展'/)
  assert.match(ribbon, /name: '3D列印'/)
  assert.match(drawing, /裝配工程圖/)
  assert.match(illegal, /ILLEGAL_REJECT_MARKER = '尺寸已拒絕'/)
  assert.match(i18n, /CREATE: '建立'/)
  assert.match(i18n, /CONSTRUCT: '構造'/)
  assert.match(store, /label: '烘焙為零件實體'/)
  assert.match(featureStatus, /已抽殼/)
  assert.match(featureStatus, /已實體布爾|時間軸可改/)
  assert.match(viewport, /manifold 網格布爾/)
  assert.match(viewport, /來源「\$\{/)
  assert.match(meshDrop, /MESH_TAB_DROP_HINT|拖到视口导入/)
  assert.match(ribbon, /'🧪實驗室': \{ id: '🧪實驗室'/)
  const labStart = ribbon.indexOf("// 🧪實驗室")
  const labEnd = ribbon.indexOf("'🧪實驗室': { id: '🧪實驗室'")
  const labBlock = ribbon.slice(labStart, labEnd)
  assert.match(labBlock, /name: 'CREATE 擴充'/)
  assert.match(labBlock, /name: '製造 CAM'/)
  assert.match(labBlock, /id: 'stack', label: '堆疊'/)
  assert.match(labBlock, /id: 'fea', label: '受力雲圖'/)
  assert.match(labBlock, /id: 'slicepreview', label: '切層預覽'/)
  assert.match(labBlock, /id: 'pyramid', label: '棱錐'/)
  assert.match(labBlock, /id: 'delface', label: '刪面治癒'/)
  assert.match(labBlock, /id: 'gear', label: '齒輪'/)
  assert.match(labBlock, /name: '構造擴展'/)
  const start = store.indexOf('componentBoolean: async')
  const end = store.indexOf('planeCutComponent: async')
  assert.ok(start >= 0 && end > start)
  const block = store.slice(start, end)
  assert.match(block, /來源體/)
  assert.match(block, /工具體/)
  assert.match(block, /組件布爾＝網格布爾（非零件時間軸）/)
})
