/**
 * v1.69: Construct plane/axis/point residual ribbon/dialog/tree labels → Traditional Chinese (HK).
 * SW CACHE → webcad-v1.69. Prefer labels — not Help encyclopedias. LAB 構造擴展 stays under 實驗室.
 * Retain MESH SC pin, DRAWING/SKETCH/illegal/SELECT/導出 STL/Shell-bake/Boolean help/LAB gear/v1.68/ZH chrome.
 */
import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { tLabel, tStatus } from '../src/i18n.ts'

const version = readFileSync(new URL('../src/version.ts', import.meta.url), 'utf8')
const sw = readFileSync(new URL('../public/sw.js', import.meta.url), 'utf8')
const ribbon = readFileSync(new URL('../src/ribbon.ts', import.meta.url), 'utf8')
const i18n = readFileSync(new URL('../src/i18n.ts', import.meta.url), 'utf8')
const viewport = readFileSync(new URL('../src/components/Viewport.tsx', import.meta.url), 'utf8')
const browser = readFileSync(new URL('../src/components/BrowserTree.tsx', import.meta.url), 'utf8')
const meshDrop = readFileSync(new URL('../src/io/meshDrop.ts', import.meta.url), 'utf8')
const illegal = readFileSync(new URL('../src/ui/illegalInput.ts', import.meta.url), 'utf8')
const drawing = readFileSync(new URL('../src/components/DrawingPanel.tsx', import.meta.url), 'utf8')
const featureStatus = readFileSync(new URL('../src/ui/featureStatus.ts', import.meta.url), 'utf8')
const store = readFileSync(new URL('../src/store.ts', import.meta.url), 'utf8')

test('APP_VERSION is 1.69+', () => {
  assert.match(version, /APP_VERSION = '1\.(69|[7-9]\d)'|APP_VERSION = '[2-9]\./)
})

test('v1.69: SW CACHE bumped to webcad-v1.69+; navigate network-first; release comment', () => {
  assert.match(sw, /const CACHE = 'webcad-v1\.(69|[7-9]\d)'/)
  assert.doesNotMatch(sw, /const CACHE = 'webcad-v1\.68'/)
  assert.doesNotMatch(sw, /const CACHE = 'webcad-v1'/)
  assert.match(sw, /RELEASE: CACHE 必须随每次发版改名|RELEASE: CACHE 必須隨每次發版改名/)
  assert.match(sw, /mode === 'navigate'/)
  assert.match(sw, /network-first|永远攞最新|永遠攞最新/)
})

test('v1.69: ribbon construct plane/axis/point labels Traditional', () => {
  assert.match(ribbon, /id: 'planemid', label: '中間平面'/)
  assert.match(ribbon, /id: 'plane2edge', label: '過兩邊平面'/)
  assert.match(ribbon, /id: 'plane3pt', label: '過三點平面'/)
  assert.match(ribbon, /id: 'planepath', label: '沿路徑平面'/)
  assert.match(ribbon, /id: 'axisperpface', label: '垂直面軸'/)
  assert.match(ribbon, /id: 'axis2planes', label: '過兩平面軸'/)
  assert.match(ribbon, /id: 'axis2pt', label: '過兩點軸'/)
  assert.match(ribbon, /id: 'axisedge', label: '沿邊軸'/)
  assert.match(ribbon, /id: 'point2edges', label: '兩邊交點'/)
  assert.match(ribbon, /id: 'point3planes', label: '三平面交點'/)
  assert.match(ribbon, /id: 'pointcenter', label: '圓／球／環面中心點'/)
  assert.match(ribbon, /id: 'pointedgeplane', label: '邊與平面交點'/)
  assert.match(ribbon, /id: 'pointpath', label: '沿路徑點'/)
  assert.doesNotMatch(ribbon, /id: 'planemid', label: '中间平面'/)
  assert.doesNotMatch(ribbon, /id: 'plane2edge', label: '过两边平面'/)
  assert.doesNotMatch(ribbon, /id: 'axisperpface', label: '垂直面轴'/)
  assert.doesNotMatch(ribbon, /id: 'pointcenter', label: '圆／球／环面中心点'/)
  assert.doesNotMatch(ribbon, /id: 'pointpath', label: '沿路径点'/)
})

test('v1.69: LAB 構造擴展 planeparpt/caxis/cpoint/midcpoint/cptgrid Traditional (stay under 實驗室)', () => {
  assert.match(ribbon, /name: '構造擴展'/)
  assert.match(ribbon, /id: 'planeparpt', label: '過點平行面'/)
  assert.match(ribbon, /id: 'caxis', label: '構造軸'/)
  assert.match(ribbon, /id: 'cpoint', label: '坐標構造點'/)
  assert.match(ribbon, /id: 'midcpoint', label: '兩點中點'/)
  assert.match(ribbon, /id: 'cptgrid', label: '構造點陣列'/)
  assert.doesNotMatch(ribbon, /name: '构造扩展'/)
  assert.doesNotMatch(ribbon, /id: 'planeparpt', label: '过点平行面'/)
  assert.doesNotMatch(ribbon, /id: 'caxis', label: '方向构造轴'/)
  assert.doesNotMatch(ribbon, /id: 'cpoint', label: '坐标构造点'/)
  assert.doesNotMatch(ribbon, /id: 'midcpoint', label: '两点中点'/)
  assert.doesNotMatch(ribbon, /id: 'cptgrid', label: '构造点阵列'/)
  const labStart = ribbon.indexOf("// 🧪實驗室")
  const labEnd = ribbon.indexOf("'🧪實驗室': { id: '🧪實驗室'")
  assert.ok(labStart >= 0 && labEnd > labStart)
  const labBlock = ribbon.slice(labStart, labEnd)
  assert.match(labBlock, /name: '構造擴展'/)
  assert.match(labBlock, /id: 'cptgrid', label: '構造點陣列'/)
})

test('v1.69: BrowserTree + Viewport FD chrome Traditional', () => {
  assert.match(browser, /構造/)
  assert.match(browser, /tStatus\('構造軸', lang\)/)
  assert.match(browser, /tStatus\('構造點', lang\)/)
  assert.match(viewport, /plane: '參考平面'/)
  assert.match(viewport, /cpoint: '構造點'/)
  assert.match(viewport, /caxis: '構造軸'/)
  assert.doesNotMatch(browser, /构造 \(/)
  assert.doesNotMatch(viewport, /plane: '参考平面'/)
  assert.doesNotMatch(viewport, /cpoint: '构造点'/)
  assert.doesNotMatch(viewport, /caxis: '构造轴'/)
})

test('v1.69: EN_LABEL + tLabel / tStatus for TC keys; legacy SC retained', () => {
  assert.equal(tLabel('中間平面', 'en'), 'Midplane')
  assert.equal(tLabel('過兩邊平面', 'en'), 'Plane Through Two Edges')
  assert.equal(tLabel('過三點平面', 'en'), 'Plane Through Three Points')
  assert.equal(tLabel('沿路徑平面', 'en'), 'Plane Along Path')
  assert.equal(tLabel('垂直面軸', 'en'), 'Axis Perpendicular To Face')
  assert.equal(tLabel('過兩平面軸', 'en'), 'Axis Through Two Planes')
  assert.equal(tLabel('過兩點軸', 'en'), 'Axis Through Two Points')
  assert.equal(tLabel('沿邊軸', 'en'), 'Axis Through Edge')
  assert.equal(tLabel('兩邊交點', 'en'), 'Point Through Two Edges')
  assert.equal(tLabel('三平面交點', 'en'), 'Point Through Three Planes')
  assert.equal(tLabel('圓／球／環面中心點', 'en'), 'Point At Center Of Circle/Sphere/Torus')
  assert.equal(tLabel('邊與平面交點', 'en'), 'Point At Edge And Plane')
  assert.equal(tLabel('沿路徑點', 'en'), 'Point Along Path')
  assert.equal(tLabel('過點平行面', 'en'), 'Offset to Point')
  assert.equal(tLabel('構造軸', 'en'), 'Axis By Direction')
  assert.equal(tLabel('坐標構造點', 'en'), 'Point At Coordinates')
  assert.equal(tLabel('兩點中點', 'en'), 'Midpoint')
  assert.equal(tLabel('構造點陣列', 'en'), 'Construction Point Pattern')
  assert.equal(tLabel('構造擴展', 'en'), 'Construct Extensions')
  // legacy SC retained
  assert.equal(tLabel('中间平面', 'en'), 'Midplane')
  assert.equal(tLabel('过两边平面', 'en'), 'Plane Through Two Edges')
  assert.equal(tLabel('垂直面轴', 'en'), 'Axis Perpendicular To Face')
  assert.equal(tLabel('沿边轴', 'en'), 'Axis Through Edge')
  assert.equal(tLabel('圆／球／环面中心点', 'en'), 'Point At Center Of Circle/Sphere/Torus')
  assert.match(i18n, /'中間平面': 'Midplane'/)
  assert.match(i18n, /'構造點陣列': 'Construction Point Pattern'/)
  assert.equal(tStatus('構造軸', 'en'), 'Construction Axis')
  assert.equal(tStatus('構造點', 'en'), 'Construction Point')
  assert.equal(tStatus('參考平面', 'en'), 'Reference Plane')
})

test('v1.69: store datum method dialog labels Traditional', () => {
  assert.match(store, /id: 'parPlanePt', label: '過點平行面'/)
  assert.match(store, /id: 'twoEdges', label: '兩邊交點'/)
  assert.match(store, /id: 'twoEdges', label: '過兩邊'/)
  assert.match(store, /id: 'threePoints', label: '過三點（構造點）'/)
  assert.match(store, /id: 'midpoint', label: '兩點中點（構造點）'/)
  assert.match(store, /id: 'twoPoints', label: '過兩點（構造點）'/)
  assert.doesNotMatch(store, /id: 'parPlanePt', label: '过点平行面'/)
  assert.doesNotMatch(store, /id: 'midpoint', label: '两点中点（构造点）'/)
})

test('Do not regress prior TC + MESH TC pin + LAB gear + Boolean help + construct body + v1.68', () => {
  assert.match(ribbon, /id: 'insertmesh', label: '插入STL網格'/)
  assert.match(ribbon, /id: 'exportstl', label: '導出STL'/)
  assert.match(ribbon, /id: 'select', label: '選擇'/)
  assert.match(ribbon, /id: 'drawing', label: '工程圖'/)
  assert.match(ribbon, /id: 'asmdrawing', label: '裝配工程圖'/)
  assert.match(ribbon, /id: 'sk_polyline', label: '直線'/)
  assert.match(ribbon, /id: 'datumgeom', label: '構造幾何'/)
  assert.match(ribbon, /id: 'newbody', label: '新實體'/)
  assert.match(ribbon, /id: 'gear', label: '齒輪'/)
  assert.match(ribbon, /id: 'thread', label: '螺紋桿'/)
  assert.match(ribbon, /id: 'ucs', label: '用戶坐標系'/)
  assert.match(ribbon, /id: 'pointvertex', label: '頂點構造點'/)
  assert.match(ribbon, /id: 'importdxf', label: '導入DXF'/)
  assert.match(ribbon, /id: 'explodeview', label: '爆炸視圖'/)
  assert.match(ribbon, /name: '3D列印'/)
  assert.match(drawing, /裝配工程圖/)
  assert.match(illegal, /ILLEGAL_REJECT_MARKER = '尺寸已拒絕'/)
  assert.match(i18n, /CREATE: '建立'/)
  assert.match(i18n, /CONSTRUCT: '構造'/)
  assert.match(i18n, /SOLID: '實體'/)
  assert.match(store, /label: '烘焙為零件實體'/)
  assert.match(featureStatus + store + i18n, /已抽殼|status\.shellSuccess/)
  assert.match(featureStatus + store + i18n, /已實體布爾|時間軸可改|status\.boolean/)
  assert.match(meshDrop, /MESH_TAB_DROP_HINT|拖到视口导入/)
  assert.match(ribbon, /'🧪實驗室': \{ id: '🧪實驗室'/)
  const labStart = ribbon.indexOf("// 🧪實驗室")
  const labEnd = ribbon.indexOf("'🧪實驗室': { id: '🧪實驗室'")
  const labBlock = ribbon.slice(labStart, labEnd)
  assert.match(labBlock, /id: 'gear', label: '齒輪'/)
  assert.match(labBlock, /name: '構造擴展'/)
})
