/**
 * v1.66: LAB 齒輪／機構／傳動 ribbon labels + dialog titles → Traditional Chinese (HK).
 * Keep tools under 🧪實驗室 (do NOT move onto SOLID). Retain MESH SC pin,
 * DRAWING/SKETCH/illegal/SELECT/導出 STL/Shell-bake/ZH/construct.
 */
import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { tLabel, tStatus } from '../src/i18n.ts'

const version = readFileSync(new URL('../src/version.ts', import.meta.url), 'utf8')
const ribbon = readFileSync(new URL('../src/ribbon.ts', import.meta.url), 'utf8')
const i18n = readFileSync(new URL('../src/i18n.ts', import.meta.url), 'utf8')
const viewport = readFileSync(new URL('../src/components/Viewport.tsx', import.meta.url), 'utf8')
const timeline = readFileSync(new URL('../src/components/Timeline.tsx', import.meta.url), 'utf8')
const browser = readFileSync(new URL('../src/components/BrowserTree.tsx', import.meta.url), 'utf8')
const meshDrop = readFileSync(new URL('../src/io/meshDrop.ts', import.meta.url), 'utf8')
const store = readFileSync(new URL('../src/store.ts', import.meta.url), 'utf8')
const illegal = readFileSync(new URL('../src/ui/illegalInput.ts', import.meta.url), 'utf8')
const drawing = readFileSync(new URL('../src/components/DrawingPanel.tsx', import.meta.url), 'utf8')
const featureStatus = readFileSync(new URL('../src/ui/featureStatus.ts', import.meta.url), 'utf8')
const paramsPanel = readFileSync(new URL('../src/components/ParamsPanel.tsx', import.meta.url), 'utf8')

test('APP_VERSION is 1.66+', () => {
  assert.match(version, /APP_VERSION = '1\.(6[6-9]|[7-9]\d)'|APP_VERSION = '[2-9]\./)
})

test('v1.66: LAB 傳動／機構 ribbon labels Traditional', () => {
  assert.match(ribbon, /name: '傳動設計'/)
  assert.match(ribbon, /name: '機構'/)
  assert.match(ribbon, /id: 'gear', label: '齒輪'/)
  assert.match(ribbon, /id: 'gear', label: '正齒輪\/斜齒輪'/)
  assert.match(ribbon, /id: 'worm', label: '蝸桿'/)
  assert.match(ribbon, /id: 'crowngear', label: '冠齒輪'/)
  assert.match(ribbon, /id: 'gearbox', label: '齒輪箱'/)
  assert.match(ribbon, /id: 'rack', label: '齒條'/)
  assert.match(ribbon, /id: 'pulley', label: 'V帶輪'/)
  assert.match(ribbon, /id: 'fourbar', label: '四連桿機構'/)
  assert.match(ribbon, /id: 'slidercrank', label: '滑塊曲柄'/)
  assert.match(ribbon, /id: 'sixbar', label: '六桿機構'/)
  assert.match(ribbon, /id: 'calc', label: '工程計算'/)
  // no remaining SC labels on these ids
  assert.doesNotMatch(ribbon, /id: 'gear', label: '齿轮'/)
  assert.doesNotMatch(ribbon, /id: 'worm', label: '蜗杆'/)
  assert.doesNotMatch(ribbon, /id: 'crowngear', label: '冠齿轮'/)
  assert.doesNotMatch(ribbon, /id: 'gearbox', label: '齿轮箱'/)
  assert.doesNotMatch(ribbon, /id: 'rack', label: '齿条'/)
  assert.doesNotMatch(ribbon, /id: 'pulley', label: 'V带轮'/)
  assert.doesNotMatch(ribbon, /id: 'fourbar', label: '四连杆机构'/)
  assert.doesNotMatch(ribbon, /id: 'slidercrank', label: '滑块曲柄'/)
  assert.doesNotMatch(ribbon, /id: 'sixbar', label: '六杆机构'/)
  assert.doesNotMatch(ribbon, /name: '传动设计'/)
  assert.doesNotMatch(ribbon, /name: '机构'/)
})

test('v1.66: FD_TITLE + mechanism dialog titles Traditional', () => {
  assert.match(viewport, /gearbox: '齒輪箱向導'/)
  assert.match(viewport, /worm: '蝸桿'/)
  assert.match(viewport, /crowngear: '冠齒輪'/)
  assert.match(viewport, /gear: '齒輪'/)
  assert.match(viewport, /rack: '齒條'/)
  assert.match(viewport, /pulley: 'V帶輪'/)
  assert.match(viewport, /tStatus\('⬚ 四連桿機構（閉環）', lang\)/)
  assert.match(viewport, /tStatus\('⊙ 滑塊曲柄機構（活塞）', lang\)/)
  assert.match(viewport, /tStatus\('⬡ 六桿機構（Stephenson-III）', lang\)/)
  assert.match(viewport, /\['gearMeshCalc', '齒輪嚙合參數'\]/)
  assert.doesNotMatch(viewport, /gearbox: '齿轮箱向导'/)
  assert.doesNotMatch(viewport, /tStatus\('⬚ 四连杆机构（闭环）', lang\)/)
})

test('v1.66: Timeline + BrowserTree gear chrome Traditional', () => {
  assert.match(timeline, /gear: \{ icon: 'gear', label: '齒輪'/)
  assert.match(timeline, /worm: \{ icon: 'worm', label: '蝸桿'/)
  assert.match(timeline, /crowngear: \{ icon: 'crowngear', label: '冠齒輪'/)
  assert.match(timeline, /rack: \{ icon: 'rack', label: '齒條'/)
  assert.match(timeline, /pulley: \{ icon: 'pulley', label: 'V帶輪'/)
  assert.match(browser, /gear: \{ icon: 'default', label: '齒輪' \}/)
  assert.match(browser, /rack: \{ icon: 'default', label: '齒條' \}/)
  assert.match(browser, /pulley: \{ icon: 'default', label: 'V帶輪' \}/)
  assert.match(browser, /worm: \{ icon: 'default', label: '蝸桿' \}/)
  assert.match(browser, /crowngear: \{ icon: 'default', label: '冠齒輪' \}/)
})

test('v1.66: EN_LABEL + tLabel/tStatus for TC gear keys', () => {
  assert.equal(tLabel('齒輪', 'en'), 'Gear')
  assert.equal(tLabel('正齒輪/斜齒輪', 'en'), 'Spur / Helical Gear')
  assert.equal(tLabel('齒條', 'en'), 'Rack')
  assert.equal(tLabel('V帶輪', 'en'), 'V-Pulley')
  assert.equal(tLabel('齒輪箱', 'en'), 'Gearbox')
  assert.equal(tLabel('蝸桿', 'en'), 'Worm')
  assert.equal(tLabel('冠齒輪', 'en'), 'Crown Gear')
  assert.equal(tLabel('四連桿機構', 'en'), 'Four-Bar')
  assert.equal(tLabel('滑塊曲柄', 'en'), 'Slider-Crank')
  assert.equal(tLabel('六桿機構', 'en'), 'Six-Bar')
  assert.equal(tLabel('齒輪箱向導', 'en'), 'Gearbox Wizard')
  assert.equal(tLabel('工程計算', 'en'), 'Engineering Calc')
  // legacy SC retained
  assert.equal(tLabel('齿轮', 'en'), 'Gear')
  assert.equal(tLabel('齿条', 'en'), 'Rack')
  assert.equal(tLabel('四连杆机构', 'en'), 'Four-Bar')
  assert.equal(tStatus('⬚ 四連桿機構（閉環）', 'en'), '⬚ Four-Bar Linkage (closed loop)')
  assert.equal(tStatus('齒輪箱向導', 'en'), 'Gearbox Wizard')
  assert.equal(tStatus('蝸桿', 'en'), 'Worm')
  assert.match(i18n, /'齒輪': 'Gear'/)
  assert.match(i18n, /'四連桿機構': 'Four-Bar'/)
})

test('v1.66 BD-6501: BrowserTree / ParamsPanel export-all Traditional', () => {
  assert.match(browser, /tStatus\('導出全部零件 STL\(zip\)', lang\)/)
  assert.doesNotMatch(browser, /tStatus\('导出全部零件 STL\(zip\)', lang\)/)
  assert.match(paramsPanel, /📦 導出全部配置/)
  assert.doesNotMatch(paramsPanel, /📦 导出全部配置/)
  assert.match(paramsPanel, /📥 導入設計表/)
  assert.doesNotMatch(paramsPanel, /📥 导入设计表/)
  assert.equal(tStatus('導出全部零件 STL(zip)', 'en'), 'Export all parts STL (zip)')
  assert.equal(tStatus('导出全部零件 STL(zip)', 'en'), 'Export all parts STL (zip)')
  assert.equal(tStatus('導出全部配置', 'en'), 'Export all configurations')
  assert.equal(tStatus('导出全部配置', 'en'), 'Export all configurations')
  assert.equal(tLabel('導出全部零件 STL(zip)', 'en'), 'Export all parts STL (zip)')
  assert.equal(tLabel('導出全部配置', 'en'), 'Export all configurations')
  // ribbon MESH 導出STL pin retained
  assert.match(ribbon, /id: 'exportstl', label: '導出STL'/)
  assert.match(ribbon, /id: 'insertmesh', label: '插入STL网格'/)
})

test('LAB tools stay under 實驗室; prior TC + MESH SC retained', () => {
  // gear tools must appear inside LAB const (before WORKSPACES assignment)
  const labStart = ribbon.indexOf('const LAB: Panel[]')
  const labEnd = ribbon.indexOf("'🧪實驗室': { id: '🧪實驗室'")
  assert.ok(labStart >= 0 && labEnd > labStart)
  const lab = ribbon.slice(labStart, labEnd)
  assert.match(lab, /id: 'gear', label: '齒輪'/)
  assert.match(lab, /id: 'fourbar', label: '四連桿機構'/)
  assert.match(lab, /id: 'newbody', label: '新實體'/)
  assert.match(lab, /id: 'bodyboolean', label: '實體布爾'/)
  assert.match(lab, /id: 'offsetsolid', label: '整體偏移'/)
  // SOLID panels must NOT gain gear/mechanism (LAB starts after `const g =`)
  const solidStart = ribbon.indexOf('const SOLID:')
  const solidEnd = ribbon.indexOf('const LAB:')
  assert.ok(solidStart >= 0 && solidEnd > solidStart)
  const solid = ribbon.slice(solidStart, solidEnd)
  assert.doesNotMatch(solid, /id: 'gear'/)
  assert.doesNotMatch(solid, /id: 'fourbar'/)
  assert.doesNotMatch(solid, /id: 'gearbox'/)
  assert.doesNotMatch(solid, /id: 'worm'/)
  assert.doesNotMatch(solid, /id: 'rack'/)

  assert.match(ribbon, /id: 'insertmesh', label: '插入STL网格'/)
  assert.match(ribbon, /id: 'select', label: '選擇'/)
  assert.match(ribbon, /id: 'drawing', label: '工程圖'/)
  assert.match(ribbon, /id: 'exportstl', label: '導出STL'/)
  assert.match(ribbon, /id: 'params', label: '參數'/)
  assert.match(ribbon, /id: 'datumgeom', label: '構造幾何'/)
  assert.match(ribbon, /id: 'sk_polyline', label: '直線'/)
  assert.match(drawing, /裝配工程圖 — 三視圖/)
  assert.match(illegal, /ILLEGAL_REJECT_MARKER = '尺寸已拒絕'/)
  assert.match(i18n, /CREATE: '建立'/)
  assert.match(i18n, /SOLID: '實體'/)
  assert.match(i18n, /EXPORT: '導出'/)
  assert.match(store, /label: '烘焙為零件實體'/)
  assert.match(featureStatus, /已抽殼 壁厚/)
  assert.match(meshDrop, /MESH_TAB_DROP_HINT|拖到视口导入/)
})
