import {register}from'node:module';import test from'node:test';import assert from'node:assert/strict'
register('data:text/javascript,'+encodeURIComponent(`export async function resolve(s,c,n){if(s.includes('?url'))return {url:'data:text/javascript,export default %22%22',shortCircuit:true};return n(s,c)}`))
const {resolveConstraintAnchors:anchors}=await import('../src/sketch/constraintAnchors.ts'),{solveConstrainedPointDrag:drag}=await import('../src/sketch/constrainedDrag.ts'),{pathPts}=await import('../src/sketch/sketchOps.ts')
const p=(shape,idx=0)=>({kind:'pt',shape,idx}),center={kind:'center',shape:0,idx:0},edge={kind:'edge',shape:0,idx:0},circle=shape=>({kind:'circle',shape}),con=(id,type,a,b)=>({id,kind:'con',type,a,b}),dim=(id,type,a,value,b)=>({id,kind:'dim',type,a,value,b}),near=(a,b)=>a.forEach((v,i)=>assert.ok(Math.abs(v-b[i])<1e-5,`${a} != ${b}`))
const arc=()=>({type:'poly',open:true,verts:[[10,0],[-10,0]],bulges:[-1],pts:pathPts([[10,0],[-10,0]],[-1])}),point=(x=0,y=0)=>({type:'circle',point:true,c:[x,y],r:0})
async function checked(sh,cs,ref,to){const before=JSON.stringify([sh,cs]),r=await drag(sh,cs,ref,to);assert.equal(JSON.stringify([sh,cs]),before);assert.ok(r.ok,r.reason);return r}
test('coincident point chain anchors arc center and Equal chain propagates driving diameter',async()=>{const sh=[arc(),point(),point(),{type:'circle',c:[30,0],r:10},{type:'circle',c:[50,0],r:10}],cs=[con('a','coincident',center,p(1)),con('b','coincident',p(1),p(2)),con('fix','fix',p(2)),con('eq1','equal',edge,circle(3)),con('eq2','equal',circle(3),circle(4)),dim('dia','dia',circle(4),20)];const a=anchors(sh,cs);assert.deepEqual(a.point(center),{x:0,y:0});assert.equal(a.radius(edge),10);const r=await checked(sh,cs,p(0),[9,12]);near(r.target,[6,8]);near(r.result.shapes[0].verts[0],[6,8])})
test('unanchored coincidence and Equal cycles never become fixed evidence',()=>{const sh=[arc(),point(),{type:'circle',c:[30,0],r:10}],cs=[con('a','coincident',center,p(1)),con('b','coincident',p(1),center),con('eq1','equal',edge,circle(2)),con('eq2','equal',circle(2),edge),{...dim('driven','rad',circle(2),10),driven:true}],a=anchors(sh,cs);assert.deepEqual(a.point(center),{});assert.equal(a.radius(edge),undefined)})
test('two evaluated coordinate dimensions anchor negative-side center without mirrored target',async()=>{const a=arc();a.verts=a.verts.map(p=>[p[0]-20,p[1]+30]);a.pts=pathPts(a.verts,a.bulges);const cs=[dim('x','hdist',{kind:'origin'},20,center),dim('y','vdist',{kind:'origin'},30,center),dim('r','rad',edge,10)];const r=await checked([a],cs,p(0),[-11,42]);near(r.target,[-14,38])})
test('partial axis anchor propagates through coincidence and keeps other axis movable',async()=>{const sh=[{type:'poly',open:true,pts:[[20,20],[60,20]]},point(20,20)],cs=[con('co','coincident',p(0),p(1)),dim('y','vdist',{kind:'origin'},20,p(1)),con('h','h',edge)];const a=anchors(sh,cs);assert.deepEqual(a.point(p(0,1)),{y:20});const r=await checked(sh,cs,p(0,1),[75,35]);near(r.target,[75,20])})
test('coordinate constraint cycle without origin evidence stays unanchored',()=>{const sh=[point(0,20),point(0,30)],cs=[dim('d','vdist',p(0),10,p(1)),con('h','h',p(0),p(1))];assert.deepEqual(anchors(sh,cs).point(p(0)),{})})
test('fixed-circle radius propagates Equal while driven measurements do not override it',async()=>{const sh=[arc(),{type:'circle',c:[30,0],r:10}],cs=[con('fixCenter','fix',center),con('fixCircle','fix',circle(1)),con('equal','equal',edge,circle(1)),{...dim('measure','rad',edge,77),driven:true}];assert.equal(anchors(sh,cs).radius(edge),10);const r=await checked(sh,cs,p(0),[9,12]);near(r.target,[6,8])})
test('center coordinate dimension on one axis permits motion on the other axis',async()=>{const sh=[arc()];sh[0].verts=sh[0].verts.map(p=>[p[0]+5,p[1]]);sh[0].pts=pathPts(sh[0].verts,sh[0].bulges);const cs=[dim('x','hdist',{kind:'origin'},5,center)];const r=await checked(sh,cs,center,[9,12]);near(r.target,[5,12])})
test('reversed coordinate references preserve negative-side anchors',()=>{const sh=[point(-5,-4)],cs=[dim('x','hdist',p(0),5,{kind:'origin'}),dim('y','vdist',p(0),4,{kind:'origin'})];assert.deepEqual(anchors(sh,cs).point(p(0)),{x:-5,y:-4})})
test('contradictory evidence does not anchor upstream nodes of a coincidence chain',()=>{const sh=[point(),point(),point(1,0)],cs=[con('ab','coincident',p(0),p(1)),con('bc','coincident',p(1),p(2)),con('fa','fix',p(0)),con('fc','fix',p(2))],a=anchors(sh,cs);for(let i=0;i<3;i++)assert.equal(a.point(p(i)).x,undefined)})
test('nonexistent open closing edge is never an anchor or radius source',()=>{const sh=[{type:'poly',open:true,verts:[[0,0],[10,0]],bulges:[0,1],pts:[[0,0],[10,0]]}],invalid={kind:'edge',shape:0,idx:1},a=anchors(sh,[con('fix','fix',invalid),dim('rad','rad',invalid,5)]);assert.deepEqual(a.point(p(0)),{});assert.deepEqual(a.point(p(0,1)),{});assert.equal(a.radius(invalid),undefined)})
test('locked arc drag retains exact bulge and snapshot after successful validation',async()=>{const sh=[arc()],cs=[con('center','fix',center),con('end','fix',p(0)),dim('r','rad',edge,10)],r=await checked(sh,cs,p(0),[9,12]);assert.deepEqual(r.result.shapes,sh)})

test('invalid closing-edge constraint rejects drag rather than silently using a phantom fixed point',async()=>{const sh=[{type:'poly',open:true,pts:[[0,0],[10,0]]}],r=await drag(sh,[con('fix','fix',{kind:'edge',shape:0,idx:1})],p(0,1),[15,3]);assert.equal(r.ok,false)})
