import test from 'node:test'
import assert from 'node:assert/strict'
import {register,createRequire} from 'node:module'
import {fileURLToPath} from 'node:url'
globalThis.require=createRequire(import.meta.url);globalThis.__dirname=fileURLToPath(new URL('.',import.meta.url));register('./native-car-loader.mjs',import.meta.url)
await import('../src/worker/cad.worker.ts');await globalThis.__wheelWorker.ready()
const {useApp}=await import('../src/store.ts')
const g=()=>useApp.getState(),shapes=()=>[...g().sketchProfiles,...(g().sketchShape?[g().sketchShape]:[])],snapshot=()=>structuredClone({shapes:shapes(),cons:g().skCons,params:g().params,undo:g().sketchUndo,redo:g().sketchRedo})
function seed(extra={}){g().cancelSkScale();useApp.setState({...useApp.getInitialState(),mode:'sketch',sketchTool:'select',sketchProfiles:[{type:'circle',c:[20,30],r:10}],...extra},true);g().startSkScale()}
async function settle(){for(let i=0;i<2000&&g().skScale?.pending;i++)await new Promise(r=>setTimeout(r,1));assert.equal(g().skScale?.pending,false)}
test('interactive numeric preview derives each factor from immutable source and commits one exact Undo',async()=>{seed();const before=snapshot();await g().setSkScaleFactor(2);assert.deepEqual(snapshot(),before);assert.equal(g().skScale.preview[0].r,20);await g().setSkScaleFactor(3);assert.equal(g().skScale.preview[0].r,30);assert.deepEqual(snapshot(),before);await g().confirmSkScale();assert.equal(g().skScale,null);assert.equal(shapes()[0].r,30);assert.equal(g().sketchUndo.length,1);const result=structuredClone(shapes());await g().undo();assert.deepEqual(shapes(),before.shapes);await g().redo();assert.deepEqual(shapes(),result)})
for(const factor of [0,-1,NaN,Infinity])test(`latest invalid factor ${factor} cannot commit earlier valid preview`,async()=>{seed();const before=snapshot();await g().setSkScaleFactor(2);await g().setSkScaleFactor(factor);assert.ok(g().skScale.error);assert.equal(g().skScale.preview,null);await g().confirmSkScale();assert.deepEqual(snapshot(),before)})
test('newer rejected request owns preview even when earlier successful solve finishes later',async()=>{seed();const before=snapshot(),older=g().setSkScaleFactor(2),latest=g().setSkScaleFactor(0);await Promise.all([older,latest]);assert.ok(g().skScale.error);assert.equal(g().skScale.preview,null);await g().confirmSkScale();assert.deepEqual(snapshot(),before)})
test('cancel pending solve prevents late preview and leaves source/history exact',async()=>{seed();const before=snapshot(),p=g().setSkScaleFactor(2);g().cancelSkScale();await p;assert.equal(g().skScale,null);assert.deepEqual(snapshot(),before)})
for(const phase of ['pending','solved'])test(`source replacement during ${phase} preview prevents stale commit`,async()=>{seed();const p=g().setSkScaleFactor(2);if(phase==='solved')await p;useApp.setState({sketchProfiles:[{type:'circle',c:[90,30],r:7}]});const changed=snapshot();await p;await g().confirmSkScale();assert.deepEqual(snapshot(),changed);assert.equal(g().skScale,null)})
test('handle uses ray projection times starting factor; Esc restores pre-drag solved preview',async()=>{seed();await g().setSkScaleFactor(1.5);g().startSkScaleHandle([30,30]);g().updateSkScaleHandle([40,80]);await settle();assert.equal(g().skScale.factor,3);assert.equal(g().skScale.preview[0].r,30);g().stepBackSkScale();assert.equal(g().skScale.factor,1.5);assert.equal(g().skScale.preview[0].r,15);await g().confirmSkScale();assert.equal(shapes()[0].r,15);assert.equal(g().sketchUndo.length,1)})
test('base/handle selection is transient; crossing base rejects until explicit valid update',async()=>{seed();const before=snapshot();g().pickSkScaleBase();assert.equal(g().skScale.stage,'base');g().setSkScaleBase([0,0]);g().startSkScaleHandle([10,0]);g().updateSkScaleHandle([-10,8]);g().finishSkScaleHandle();await settle();assert.ok(g().skScale.error);await g().confirmSkScale();assert.deepEqual(snapshot(),before);await g().setSkScaleFactor(2);await g().confirmSkScale();assert.deepEqual(shapes()[0],{type:'circle',c:[40,60],r:20})})
test('stepwise Escape preserves source and exits base without history',async()=>{seed();const before=snapshot();g().startSkScaleHandle([30,30]);g().updateSkScaleHandle([40,30]);g().stepBackSkScale();await new Promise(r=>setTimeout(r,10));assert.equal(g().skScale.stage,'ready');g().stepBackSkScale();assert.equal(g().skScale.stage,'base');g().stepBackSkScale();assert.equal(g().skScale,null);assert.deepEqual(snapshot(),before)})
test('Fixed constraint rejection and factor-one no-op never add Undo',async()=>{seed({skCons:[{id:'anchor',kind:'con',type:'fix',a:{kind:'circle',shape:0}}]});const before=snapshot();await g().setSkScaleFactor(2);assert.ok(g().skScale.error);await g().confirmSkScale();assert.deepEqual(snapshot(),before);await g().setSkScaleFactor(1);await g().confirmSkScale();assert.equal(g().skScale,null);assert.deepEqual(snapshot(),before)})
test('handle start while numeric solve pending does not capture unresolved draft',async()=>{seed();const p=g().setSkScaleFactor(2);assert.equal(g().skScale.pending,true);g().startSkScaleHandle([30,30]);assert.notEqual(g().skScale.stage,'dragging');await p;assert.equal(g().skScale.preview[0].r,20)})
test('no-movement handle release retains previously solved numeric preview and commits it once',async()=>{seed();const before=snapshot();await g().setSkScaleFactor(1.5);g().startSkScaleHandle([30,30]);g().finishSkScaleHandle();assert.deepEqual(snapshot(),before);assert.equal(g().skScale.factor,1.5);assert.equal(g().skScale.preview[0].r,15);await g().confirmSkScale();assert.equal(g().skScale,null);assert.equal(shapes()[0].r,15);assert.equal(g().sketchUndo.length,1);await g().undo();assert.deepEqual(shapes(),before.shapes)})
