import test from 'node:test'
import assert from 'node:assert/strict'
import {register,createRequire} from 'node:module'
import {fileURLToPath} from 'node:url'
globalThis.require=createRequire(import.meta.url);globalThis.__dirname=fileURLToPath(new URL('.',import.meta.url));register('./native-car-loader.mjs',import.meta.url)
await import('../src/worker/cad.worker.ts');const w=globalThis.__wheelWorker;await w.ready()
const {useApp,buildProjectPayload}=await import('../src/store.ts'),{hitTest,refPts}=await import('../src/sketch/freesolve.ts'),{ellipseArcWithSweep,ellipseArcSample}=await import('../src/sketch/ellipseArcGeometry.ts'),{importSTEP,measureVolume,getOC}=await import('replicad')
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-6,`${a} != ${b}`),all=()=>[...useApp.getState().sketchProfiles,...(useApp.getState().sketchShape?[useApp.getState().sketchShape]:[])]
const independentPoint=(e,t)=>{const r=e.rot*Math.PI/180;return[e.cx+e.rx*Math.cos(t)*Math.cos(r)-e.ry*Math.sin(t)*Math.sin(r),e.cy+e.rx*Math.cos(t)*Math.sin(r)+e.ry*Math.sin(t)*Math.cos(r)]}
async function volume(expected,shape,plane){const sh=await importSTEP(new Blob([await w.exportSTEP()])),check=new(getOC().BRepCheck_Analyzer)(sh.wrapped,true,false);try{assert.ok(check.IsValid_2())}finally{check.delete()}assert.ok(Math.abs(measureVolume(sh)-expected)<Math.max(1e-5,expected*5e-8));const e=shape.ell||shape.earc;let ps=shape.type==='circle'?[[shape.c[0]-shape.r,shape.c[1]],[shape.c[0]+shape.r,shape.c[1]],[shape.c[0],shape.c[1]-shape.r],[shape.c[0],shape.c[1]+shape.r]]:shape.type==='rect'?[shape.a,[shape.b[0],shape.a[1]],shape.b,[shape.a[0],shape.b[1]]]:shape.pts;if(e){const r=e.rot*Math.PI/180,x=Math.atan2(-e.ry*Math.sin(r),e.rx*Math.cos(r))*180/Math.PI,y=Math.atan2(e.ry*Math.cos(r),e.rx*Math.sin(r))*180/Math.PI,angles=shape.earc?[e.a0,e.a0+e.signedSweepDeg]:[];for(const t of[x,x+180,y,y+180])if(!shape.earc||((Math.sign(e.signedSweepDeg)*(t-e.a0))%360+360)%360<=Math.abs(e.signedSweepDeg)+1e-9)angles.push(t);ps=angles.map(t=>independentPoint(e,t*Math.PI/180))}const bounds=sh.boundingBox.bounds,map=plane==='XZ'?[[0,0,1,0],[2,1,1,0]]:plane==='YZ'?[[1,0,-1,0],[2,1,1,0]]:plane==='ARB'?[[1,0,1,20],[2,1,1,30]]:[[0,0,1,0],[1,1,-1,0]];for(const[w,l,sign,o]of map){const v=ps.map(p=>p[l]*sign+o);assert.ok(Math.abs(bounds[0][w]-Math.min(...v))<1e-5);assert.ok(Math.abs(bounds[1][w]-Math.max(...v))<1e-5)}}
function fixture(kind){const e={cx:30,cy:30,rx:10,ry:5,rot:30},ea=ellipseArcWithSweep(e,330,-270);return kind==='circle'?{type:'circle',c:[30,30],r:10}:kind==='rect'?{type:'rect',a:[20,25],b:[40,35]}:kind==='ellipse'?{type:'poly',ell:e,pts:Array.from({length:48},(_,i)=>independentPoint(e,i*Math.PI/24))}:{type:'poly',earc:ea,pts:ellipseArcSample(ea),open:false}}
const cases=[...['circle','rect','ellipse','earc'].flatMap(kind=>['XY','XZ','YZ','ARB'].map(plane=>({kind,plane,k:2}))),...['circle','rect','ellipse','earc'].map(kind=>({kind,plane:'XY',k:.5}))]
for(const {kind,plane,k}of cases)test(`Interactive Scale ${kind} factor${k} ${plane} exact native/history/JSON`,async()=>{
 const original=fixture(kind),pivotPts=original.type==='circle'?[original.c]:original.type==='rect'?[original.a,original.b]:original.pts,pivot=[pivotPts.reduce((a,p)=>a+p[0],0)/pivotPts.length,pivotPts.reduce((a,p)=>a+p[1],0)/pivotPts.length],xf=p=>[pivot[0]+k*(p[0]-pivot[0]),pivot[1]+k*(p[1]-pivot[1])]
 useApp.setState({...useApp.getInitialState(),mode:'sketch',sketchTool:'scale',sketchProfiles:[original],extrudeHeight:5,sketchOp:'new',appPrompt:async()=>`${k},${pivot[0]},${pivot[1]}`,...(plane==='ARB'?{sketchPlane:'XY',sketchArb:{o:[10,20,30],xd:[0,1,0],n:[1,0,0]}}:{sketchPlane:plane})},true)
 useApp.getState().startSkScale();useApp.getState().setSkScaleBase(pivot);const beforePreview=structuredClone(all());await useApp.getState().setSkScaleFactor(k);assert.deepEqual(all(),beforePreview);assert.equal(useApp.getState().sketchUndo.length,0);assert.ok(useApp.getState().skScale.preview,useApp.getState().skScale.error);await useApp.getState().confirmSkScale();assert.equal(useApp.getState().skScale,null);assert.equal(all().length,1);const scaled=structuredClone(all()[0]);assert.equal(useApp.getState().skConflict,false,useApp.getState().status)
 if(kind==='circle'){near(scaled.r,10*k);assert.deepEqual(scaled.c,xf(original.c))}else if(kind==='rect'){assert.deepEqual(scaled.a,xf(original.a));assert.deepEqual(scaled.b,xf(original.b))}else{const e=scaled.ell||scaled.earc;assert.ok(e);const c=xf([30,30]);near(e.cx,c[0]);near(e.cy,c[1]);near(e.rx,10*k);near(e.ry,5*k);near(e.rot,30);if(kind==='earc'){assert.equal(e.version,2);near(e.signedSweepDeg,-270);near(e.a0,330);assert.equal(!!scaled.open,false)}for(const p of scaled.pts){const a=e.rot*Math.PI/180,x=(p[0]-e.cx)*Math.cos(a)+(p[1]-e.cy)*Math.sin(a),y=-(p[0]-e.cx)*Math.sin(a)+(p[1]-e.cy)*Math.cos(a);near((x/e.rx)**2+(y/e.ry)**2,1)}}
 assert.equal(useApp.getState().sketchUndo.length,1);await useApp.getState().undo();assert.deepEqual(all(),[original]);await useApp.getState().redo();assert.deepEqual(all(),[scaled]);const baseArea=kind==='circle'?100*Math.PI:kind==='rect'?200:kind==='ellipse'?50*Math.PI:25*(1.5*Math.PI+1),area=baseArea*k*k
 await useApp.getState().extrudeSketch();assert.equal(useApp.getState().mode,'model',useApp.getState().status);await volume(area*5,scaled,plane)
 if(plane==='XY'){const payload=JSON.parse(JSON.stringify(buildProjectPayload(useApp.getState())));useApp.setState({...useApp.getInitialState()},true);await useApp.getState().applyProjectData(payload);await volume(area*5,scaled,plane);assert.equal(await useApp.getState().applyFeatures(useApp.getState().features.map(f=>({...f,height:8})),'height8'),true);await volume(area*8,scaled,plane);await useApp.getState().undo();await volume(area*5,scaled,plane);await useApp.getState().redo();await volume(area*8,scaled,plane)}
})
test('interactive scale → native extrusion → face pocket → upstream scale rebuild preserves cut/history/JSON',async()=>{
 const g=()=>useApp.getState();useApp.setState({...useApp.getInitialState(),mode:'sketch',sketchTool:'select',sketchProfiles:[{type:'circle',c:[0,0],r:10}],extrudeHeight:5,sketchOp:'new'},true)
 async function scale(k){g().startSkScale();await g().setSkScaleFactor(k);assert.ok(g().skScale.preview,g().skScale.error);await g().confirmSkScale()}
 async function verify(r){const sh=await importSTEP(new Blob([await w.exportSTEP()])),check=new(getOC().BRepCheck_Analyzer)(sh.wrapped,true,false);try{assert.ok(check.IsValid_2());assert.ok(Math.abs(measureVolume(sh)-Math.PI*(r*r*5-4*2))<1e-5)}finally{check.delete()}}
 await scale(2);await g().extrudeSketch();const base=g().features.find(f=>f.sketchId);await g().startSketchOnFace([0,5,0],[0,0,1]);useApp.setState({sketchShape:{type:'circle',c:[0,0],r:2},sketchProfiles:[],extrudeHeight:2,extrudeExtent:'distance',extrudeFlip:false,sketchOp:'cut',faceCutThrough:false});await g().extrudeSketch();assert.equal(g().mode,'model',g().status);await verify(20);const pocket=g().features.at(-1).id
 await g().editSketchOf(base.id);await scale(1.5);await g().applySketchEdit(base.sketchId);assert.equal(g().mode,'model',g().status);assert.equal(g().features.at(-1).id,pocket);await verify(30);await g().undo();await verify(20);await g().redo();await verify(30)
 const payload=JSON.parse(JSON.stringify(buildProjectPayload(g())));useApp.setState({...useApp.getInitialState()},true);await g().applyProjectData(payload);await verify(30);assert.deepEqual(g().failedFeatureIds,[])
})
