import test from 'node:test'
import assert from 'node:assert/strict'
import {register,createRequire} from 'node:module'
import {fileURLToPath} from 'node:url'
globalThis.require=createRequire(import.meta.url);globalThis.__dirname=fileURLToPath(new URL('.',import.meta.url));register('./native-car-loader.mjs',import.meta.url)
await import('../src/worker/cad.worker.ts');await globalThis.__wheelWorker.ready()
const {useApp}=await import('../src/store.ts');const {ellipseArcWithSweep,ellipseArcSample}=await import('../src/sketch/ellipseArcGeometry.ts')
const g=()=>useApp.getState(),all=()=>[...g().sketchProfiles,...(g().sketchShape?[g().sketchShape]:[])],snapshot=()=>structuredClone({shapes:all(),cons:g().skCons,params:g().params,undo:g().sketchUndo,redo:g().sketchRedo})
function seed(text,extra={}){useApp.setState({...useApp.getInitialState(),mode:'sketch',sketchTool:'select',sketchProfiles:[{type:'circle',c:[30,0],r:5}],appPrompt:async()=>text,...extra},true)}
const run=()=>g().runCommand('sketcharray','Array')
for(const text of ['2,0','C,0','','2,20,','2,,20','2,20,1,0,99','1.5,20','NaN,20','Infinity,20','C,3,-360,0,0,9','C,3,,0,0','C,','M','M,z','M,x,9','O','O,2,9','O,0','2,20,2,0'])test(`legacy array rejects malformed/degenerate input ${JSON.stringify(text)} atomically`,async()=>{seed(text);const before=snapshot();await run();assert.deepEqual(snapshot(),before)})
test('legacy rectangular valid count/spacing appends exact original and copy',async()=>{seed('2,20');const source=structuredClone(all()[0]);await run();assert.deepEqual(all(),[source,{type:'circle',c:[50,0],r:5}]);assert.equal(g().sketchUndo.length,1)})
test('legacy negative full circle keeps signed placement and no coincident last copy',async()=>{seed('C,3,-360');await run();assert.equal(all().length,3);all().forEach((s,i)=>{assert.ok(Math.abs(s.c[0]-30*Math.cos(-i*2*Math.PI/3))<1e-7);assert.ok(Math.abs(s.c[1]-30*Math.sin(-i*2*Math.PI/3))<1e-7)})})
test('legacy multiple profiles preserve order and selected dimension identity',async()=>{seed('2,20',{sketchProfiles:[{type:'circle',c:[30,0],r:5},{type:'circle',c:[100,0],r:9}],skSel:[{kind:'circle',shape:0}],skCons:[{id:'r',kind:'dim',type:'rad',a:{kind:'circle',shape:0},value:5}]});const before=snapshot();await run();assert.deepEqual(all().slice(0,2),before.shapes);assert.equal(all().length,3);assert.deepEqual(g().skCons[0],before.cons[0])})
for(const text of ['M,x','M,y'])test(`legacy supported mirror ${text}`,async()=>{seed(text,{sketchProfiles:[{type:'circle',c:[30,20],r:5}]});await run();const circles=all().filter(s=>s.type==='circle');assert.equal(circles.length,2);assert.deepEqual(circles[0],{type:'circle',c:[30,20],r:5});assert.deepEqual(circles[1].c,text==='M,x'?[30,-20]:[-30,20])})
test('legacy supported circle offset uses explicit distance',async()=>{seed('O,2');await run();assert.equal(all().length,1);assert.equal(all()[0].r,7);assert.deepEqual(all()[0].c,[30,0])})
for(const field of ['mode','profiles','selection','params','refs'])test(`legacy prompt rejects stale ${field} changes`,async()=>{let release;seed(null,{appPrompt:()=>new Promise(r=>release=r)});const p=run();assert.equal(typeof release,'function');if(field==='mode')useApp.setState({mode:'model'});if(field==='profiles')useApp.setState({sketchProfiles:[{type:'circle',c:[99,0],r:2}]});if(field==='selection')useApp.setState({skSel:[{kind:'circle',shape:0}]});if(field==='params')useApp.setState({params:[{id:'p',name:'Width',value:8}]});if(field==='refs')useApp.setState({skRefGeo:{segs:[[[7,9],[8,9]]],pts:[[7,9]]}});const before=snapshot();release('2,20');await p;assert.deepEqual(snapshot(),before)})
test('legacy offset on multiple profiles refuses without dropping unrelated profiles',async()=>{seed('O,2',{sketchProfiles:[{type:'circle',c:[30,0],r:5}],sketchShape:{type:'circle',c:[100,0],r:9}});const before=snapshot();await run();assert.deepEqual(snapshot(),before)})
