// Public dialog/store region regression; real solver and OCCT geometry, history and persistence.
import test from 'node:test';import assert from 'node:assert/strict';import {register,createRequire} from 'node:module';import {fileURLToPath} from 'node:url';
globalThis.require=createRequire(import.meta.url);globalThis.__dirname=fileURLToPath(new URL('.',import.meta.url));register('./native-car-loader.mjs',import.meta.url);
await import('../src/worker/cad.worker.ts');const w=globalThis.__wheelWorker;await w.ready();const {useApp,buildProjectPayload}=await import('../src/store.ts');const {arcResample}=await import('../src/sketch/freesolve.ts');const {importSTEP,measureVolume,getOC}=await import('replicad');
const line=(a,b)=>({type:'poly',open:true,pts:[a,b]});const pt=(shape,idx)=>({kind:'pt',shape,idx});const join=(id,a,b)=>({id,kind:'con',type:'coincident',a,b});
for(const type of ['triangle','quarter-sector'])test(`assembled ${type} exact extrusion and edit/history/project`,async()=>{
 useApp.setState({...useApp.getInitialState()},true);
 const r=20,h=7,q=r/Math.sqrt(2),arc={a:[r,0],b:[0,r],m:[q,q]};const shapes=type==='triangle'?[line([0,0],[20,0]),line([20,0],[0,20]),line([0,20],[0,0])]:[{type:'poly',open:true,arc,pts:arcResample(arc.a,arc.b,arc.m)},line([0,r],[0,0]),line([0,0],[r,0])];
 const cons=[join('k1',pt(0,1),pt(1,0)),join('k2',pt(1,1),pt(2,0)),join('k3',pt(2,1),pt(0,0))];
 useApp.setState({mode:'sketch',sketchPlane:'XY',sketchProfiles:shapes,sketchShape:null,skCons:cons,sketchOp:'new'});await useApp.getState().resolveSk();assert.equal(useApp.getState().skConflict,false);
 useApp.getState().openExtrudeDlg();const dialog=useApp.getState();assert.equal(dialog.extrudeRegionFaces?.length,1);assert.deepEqual(dialog.extrudeRegionSel,[true]);useApp.setState({extrudeHeight:h});useApp.getState().toggleExtrudeRegion(0);await useApp.getState().extrudeSketch();assert.equal(useApp.getState().mode,'sketch');assert.equal(useApp.getState().features.length,0);useApp.getState().toggleExtrudeRegion(0);await useApp.getState().extrudeSketch();const s=useApp.getState();assert.equal(s.mode,'model',s.status);assert.ok(s.features.length>0,s.status);
 const sh=await importSTEP(new Blob([await w.exportSTEP()]));const oc=getOC(),check=new oc.BRepCheck_Analyzer(sh.wrapped,true,false);assert.ok(check.IsValid_2());check.delete();const actual=measureVolume(sh),expected=(type==='triangle'?200:Math.PI*r*r/4)*h;
 console.log(JSON.stringify({type,regionCount:dialog.extrudeRegionFaces.length,selected:dialog.extrudeRegionSel,actual,analyticExpected:expected,error:actual-expected,relativeError:Math.abs(actual-expected)/expected,exactWithin1e6:Math.abs(actual-expected)<1e-6,emittedProfiles:s.features.filter(f=>f.type==='extrude').map(f=>({kind:f.profile.kind,pts:f.profile.pts?.length})),preservedOpenSources:Object.values(s.sketchSources).map(v=>v.shapes?.map(sh=>sh.open))}));
 assert.ok(Math.abs(actual-expected)<1e-6);
 const feature=s.features.find(f=>f.type==='extrude');const id=feature.sketchId;
 const measure=async()=>measureVolume(await importSTEP(new Blob([await w.exportSTEP()])));
 await useApp.getState().undo();assert.equal(useApp.getState().features.length,0);await useApp.getState().redo();assert.ok(Math.abs(await measure()-expected)<1e-6);
 const payload=JSON.parse(JSON.stringify(buildProjectPayload(useApp.getState())));useApp.setState({...useApp.getInitialState()},true);await useApp.getState().applyProjectData(payload);assert.ok(Math.abs(await measure()-expected)<1e-6);
 await useApp.getState().editSketchOf(feature.id);assert.equal(useApp.getState().mode,'sketch');const st=useApp.getState();assert.ok([...st.sketchProfiles,...(st.sketchShape?[st.sketchShape]:[])].every(sh=>sh.open));
 const scale=sh=>{const next=structuredClone(sh);next.pts=next.pts.map(p=>p.map(v=>v*1.5));if(next.arc)for(const k of ['a','b','m'])next.arc[k]=next.arc[k].map(v=>v*1.5);return next};useApp.setState({sketchProfiles:st.sketchProfiles.map(scale),sketchShape:st.sketchShape?scale(st.sketchShape):null});await useApp.getState().resolveSk();await useApp.getState().applySketchEdit(id);assert.equal(useApp.getState().mode,'model',useApp.getState().status);assert.ok(Math.abs(await measure()-expected*2.25)<1e-6);await useApp.getState().undo();assert.ok(Math.abs(await measure()-expected)<1e-6);await useApp.getState().redo();assert.ok(Math.abs(await measure()-expected*2.25)<1e-6);
})
test('selected circular cap stays selected after radius edit and saved reopen',async()=>{
 useApp.setState({...useApp.getInitialState()},true);useApp.setState({mode:'sketch',sketchProfiles:[{type:'circle',c:[0,0],r:20},{type:'poly',open:true,pts:[[7,-40],[7,40]]}],sketchShape:null});useApp.getState().openExtrudeDlg();assert.equal(useApp.getState().extrudeRegionFaces.length,2);
 const index=useApp.getState().extrudeRegionFaces.findIndex(f=>f.outer.every(p=>p[0]>=7-1e-6));assert.ok(index>=0);useApp.getState().toggleExtrudeRegion(index);useApp.setState({extrudeHeight:7});await useApp.getState().extrudeSketch();assert.equal(useApp.getState().mode,'model',useApp.getState().status);const feat=useApp.getState().features[0],id=feat.sketchId;
 const expected=r=>(r*r*Math.acos(7/r)-7*Math.sqrt(r*r-49))*7;const measure=async()=>measureVolume(await importSTEP(new Blob([await w.exportSTEP()])));assert.ok(Math.abs(await measure()-expected(20))<1e-6);assert.equal(useApp.getState().sketchSources[id].regionSelection.length,1);
 const payload=JSON.parse(JSON.stringify(buildProjectPayload(useApp.getState())));useApp.setState({...useApp.getInitialState()},true);await useApp.getState().applyProjectData(payload);await useApp.getState().editSketchOf(feat.id);const change=sh=>sh?.type==='circle'?{...sh,r:25}:sh;useApp.setState({sketchProfiles:useApp.getState().sketchProfiles.map(change),sketchShape:change(useApp.getState().sketchShape)});await useApp.getState().applySketchEdit(id);assert.equal(useApp.getState().mode,'model',useApp.getState().status);assert.ok(Math.abs(await measure()-expected(25))<1e-6);await useApp.getState().undo();assert.ok(Math.abs(await measure()-expected(20))<1e-6);await useApp.getState().redo();assert.ok(Math.abs(await measure()-expected(25))<1e-6)
})
test('independent closed circle keeps native circle profile',async()=>{useApp.setState({...useApp.getInitialState()},true);useApp.setState({mode:'sketch',sketchShape:{type:'circle',c:[0,0],r:8}});useApp.getState().openExtrudeDlg();useApp.setState({extrudeHeight:7});await useApp.getState().extrudeSketch();assert.equal(useApp.getState().features[0].profile.kind,'circle');assert.ok(Math.abs(measureVolume(await importSTEP(new Blob([await w.exportSTEP()])))-Math.PI*64*7)<1e-6)})
test('selected independent closed circle persists through no-op edit and radius change without adding the unselected circle',async()=>{
 useApp.setState({...useApp.getInitialState()},true);useApp.setState({mode:'sketch',sketchProfiles:[{type:'circle',c:[0,0],r:10},{type:'circle',c:[40,0],r:5}],sketchShape:null});useApp.getState().openExtrudeDlg();useApp.getState().toggleExtrudeRegion(0);useApp.setState({extrudeHeight:7});await useApp.getState().extrudeSketch();const feature=useApp.getState().features[0],id=feature.sketchId;assert.equal(useApp.getState().sketchSources[id].regionSelection.length,1);
 const verify=async r=>{const fs=useApp.getState().features.filter(f=>f.type==='extrude');assert.equal(fs.length,1);assert.equal(fs[0].profile.kind,'circle');assert.equal(fs[0].profile.r,r);assert.ok(Math.abs(measureVolume(await importSTEP(new Blob([await w.exportSTEP()])))-Math.PI*r*r*7)<1e-6)};await verify(10);
 const payload=JSON.parse(JSON.stringify(buildProjectPayload(useApp.getState())));useApp.setState({...useApp.getInitialState()},true);await useApp.getState().applyProjectData(payload);await useApp.getState().editSketchOf(feature.id);await useApp.getState().applySketchEdit(id);await verify(10);
 await useApp.getState().editSketchOf(feature.id);const change=sh=>sh?.type==='circle'&&sh.c[0]===0?{...sh,r:12}:sh;useApp.setState({sketchProfiles:useApp.getState().sketchProfiles.map(change),sketchShape:change(useApp.getState().sketchShape)});await useApp.getState().applySketchEdit(id);await verify(12);await useApp.getState().undo();await verify(10);await useApp.getState().redo();await verify(12)
})
test('supported curves with unrecoverable near-tangent boundary reject atomically instead of polygon fallback',async()=>{
 useApp.setState({...useApp.getInitialState()},true);useApp.setState({mode:'sketch',sketchProfiles:[{type:'circle',c:[0,0],r:100},{type:'poly',open:true,pts:[[99.9995,-200],[99.9995,200]]}],sketchShape:null});useApp.getState().openExtrudeDlg();useApp.setState({extrudeHeight:7});const before=useApp.getState();await useApp.getState().extrudeSketch();const after=useApp.getState();assert.equal(after.mode,'sketch');assert.match(after.status,/精确圆弧/);assert.deepEqual(after.features,before.features);assert.deepEqual(after.undoStack,before.undoStack);assert.deepEqual(after.sketchProfiles,before.sketchProfiles)
})
test('same-count region reordering while dialog is open never extrudes a different region',async()=>{
 useApp.setState({...useApp.getInitialState()},true);useApp.setState({mode:'sketch',sketchProfiles:[{type:'circle',c:[0,0],r:10},{type:'circle',c:[40,0],r:5}],sketchShape:null});useApp.getState().openExtrudeDlg();useApp.getState().toggleExtrudeRegion(0);useApp.setState({extrudeHeight:7,sketchProfiles:[...useApp.getState().sketchProfiles].reverse()});await useApp.getState().extrudeSketch();assert.equal(useApp.getState().mode,'sketch');assert.equal(useApp.getState().features.length,0);assert.match(useApp.getState().status,/区域已改变/)
})
for(const curveType of ['ellipse','smooth'])test(`unsupported ${curveType} split keeps original source and explicitly reports sampled precision`,async()=>{
 useApp.setState({...useApp.getInitialState()},true);const pts=Array.from({length:96},(_,i)=>[20*Math.cos(2*Math.PI*i/96),10*Math.sin(2*Math.PI*i/96)]);const ellipse=curveType==='ellipse'?{type:'poly',pts,ell:{cx:0,cy:0,rx:20,ry:10,rot:0}}:{type:'poly',pts,smooth:true};useApp.setState({mode:'sketch',sketchProfiles:[ellipse,{type:'poly',open:true,pts:[[0,-20],[0,20]]}],sketchShape:null});useApp.getState().openExtrudeDlg();assert.match(useApp.getState().status,/采样近似/);assert.equal(useApp.getState().extrudeRegionFaces.length,2);useApp.getState().toggleExtrudeRegion(0);useApp.setState({extrudeHeight:7});await useApp.getState().extrudeSketch();assert.equal(useApp.getState().mode,'model',useApp.getState().status);assert.match(useApp.getState().status,/精度提示.*采样多边形/);const src=Object.values(useApp.getState().sketchSources)[0];assert.deepEqual(src.shapes[0],ellipse);assert.equal(src.shapes[1].open,true)
})
