import test from 'node:test';import assert from 'node:assert/strict';import {register,createRequire} from 'node:module';import {fileURLToPath} from 'node:url'
globalThis.require=createRequire(import.meta.url);globalThis.__dirname=fileURLToPath(new URL('.',import.meta.url));register('./native-car-loader.mjs',import.meta.url)
await import('../src/worker/cad.worker.ts');await globalThis.__wheelWorker.ready()
const {useApp,buildProjectPayload}=await import('../src/store.ts'),{refPts,measureDim}=await import('../src/sketch/freesolve.ts')
const g=()=>useApp.getState(),json=()=>JSON.parse(JSON.stringify(buildProjectPayload(g()))),edge=(idx,shape=0)=>({kind:'edge',shape,idx}),cfg=(nx=2)=>({kind:'rectangular',nx,ny:1,dx:50,dy:0}),near=(a,b)=>assert.ok(Math.abs(a-b)<1e-5,`${a} != ${b}`)
async function seed(fixed=false){useApp.setState({...useApp.getInitialState(),mode:'sketch',sketchProfiles:[{type:'poly',pts:[[0,0],[20,0],[20,10],[0,10]]}],skCons:[{id:'base',kind:'con',type:'fix',a:edge(0)},{id:'right',kind:'con',type:'v',a:edge(1)},{id:'left',kind:'con',type:'v',a:edge(3)},...(fixed?[{id:'top',kind:'con',type:'fix',a:edge(2)}]:[])],appConfirm:async()=>false},true);assert.equal(g().skPatternData,null)}
function check(height,count=1){assert.equal(g().sketchProfiles.length,count);for(let i=0;i<count;i++){const [a,b]=refPts(g().sketchProfiles,edge(0,i)),[c,d]=refPts(g().sketchProfiles,edge(2,i));near(Math.hypot(b[0]-a[0],b[1]-a[1]),20);near(c[1]-a[1],height);near(d[1]-a[1],height);near((b[0]-a[0])*(d[1]-c[1])-(b[1]-a[1])*(d[0]-c[0]),0);near(a[0],i*50)}}
test('parallel spacing batch drives closed profile, history, JSON and native extrusion',async()=>{await seed();const before=json(),n=g().sketchUndo.length;await g().placeSketchSpacing(edge(2),edge(0));const dim=g().skCons.find(c=>c.kind==='dim'&&c.type==='p2l'&&c.a.shape===0);assert.ok(dim,g().status);assert.ok(g().skCons.some(c=>c.kind==='con'&&c.type==='parallel'&&c.a.shape===0),'explicit parallel relation');assert.equal(g().sketchUndo.length,n+1);check(10);await g().undo();assert.deepEqual(json(),before);await g().redo();await g().commitSkDim(dim.id,{value:15,expr:undefined},'spacing edit');check(15);await g().undo();check(10);await g().redo();const saved=json();await g().reset();await g().applyProjectData(saved);check(15);useApp.setState({extrudeHeight:5,sketchOp:'new'});await g().extrudeSketch();assert.equal(g().mode,'model',g().status);const {importSTEP,measureVolume,getOC}=await import('replicad'),solid=await importSTEP(new Blob([await globalThis.__wheelWorker.exportSTEP()]));near(measureVolume(solid),20*15*5);const checkSolid=new(getOC().BRepCheck_Analyzer)(solid.wrapped,true,false);try{assert.ok(checkSolid.IsValid_2())}finally{checkSolid.delete()}})
test('fixed source spacing later edit rejects without history or side change',async()=>{await seed(true);await g().placeSketchSpacing(edge(2),edge(0));const d=g().skCons.find(c=>c.kind==='dim'&&c.type==='p2l'&&c.a.shape===0);assert.ok(d,g().status);const before=json(),n=g().sketchUndo.length;await g().commitSkDim(d.id,{value:15,expr:undefined},'blocked');assert.deepEqual(json(),before);assert.equal(g().sketchUndo.length,n)})
test('invalid parallel spacing rejects atomically',async()=>{await seed();const before=json(),n=g().sketchUndo.length;await g().placeSketchSpacing(edge(2,1),edge(0,1));assert.deepEqual(json(),before);assert.equal(g().sketchUndo.length,n)})
test('Esc cancels whole parallel+spacing pending transaction',async()=>{await seed();const before=json(),n=g().sketchUndo.length,p=g().placeSketchSpacing(edge(2),edge(0));g().escSketch();await p;assert.deepEqual(json(),before);assert.equal(g().sketchUndo.length,n)})
test('actual parallel edge dimension clicks create companion relation atomically',async()=>{await seed();useApp.setState({sketchTool:'dimension'});const n=g().sketchUndo.length;g().skClickAt([10,10]);let stop;const done=new Promise((resolve,reject)=>{const timer=setTimeout(()=>{stop?.();reject(new Error(g().status))},5000);stop=useApp.subscribe(s=>{if(s.skCons.some(c=>c.kind==='dim'&&c.type==='p2l')){clearTimeout(timer);stop();resolve()}})});g().skClickAt([10,0]);await done;assert.equal(g().sketchUndo.length,n+1);assert.ok(g().skCons.some(c=>c.kind==='con'&&c.type==='parallel'));check(10)})
test('fixed near-parallel edges reject companion relation without partial dimension',async()=>{useApp.setState({...useApp.getInitialState(),mode:'sketch',sketchProfiles:[{type:'poly',open:true,pts:[[0,0],[20,0]]},{type:'poly',open:true,pts:[[0,10],[20,10.02]]}],skCons:[{id:'a',kind:'con',type:'fix',a:edge(0,0)},{id:'b',kind:'con',type:'fix',a:edge(0,1)}],appConfirm:async()=>false},true);const before=json(),n=g().sketchUndo.length;await g().placeSketchSpacing(edge(0,0),edge(0,1));assert.deepEqual(json(),before);assert.equal(g().sketchUndo.length,n)})
