import{register}from'node:module';import test from'node:test';import assert from'node:assert/strict'
register('data:text/javascript,'+encodeURIComponent(`export async function resolve(s,c,n){if(s.includes('?url'))return {url:'data:text/javascript,export default %22%22',shortCircuit:true};return n(s,c)}`))
const{solveFree,measureDim,dimGfx}=await import('../src/sketch/freesolve.ts')
const pt=(shape)=>({kind:'pt',shape,idx:0}),fix={id:'fix',kind:'con',type:'fix',a:pt(0)},dot=(a,b)=>a[0]*b[0]+a[1]*b[1]
function fixture(angle,sign=1){const a=angle*Math.PI/180,u=[Math.cos(a),Math.sin(a)],v=[-u[1],u[0]],s=[{type:'circle',point:true,c:[17,-11],r:0},{type:'circle',point:true,c:[17+sign*7*u[0]+13*v[0],-11+sign*7*u[1]+13*v[1]],r:0}];return{s,u,v}}
for(const angle of[30,-30,125])for(const sign of[1,-1])for(const value of[3,12,0])test(`projected unrelated points ${angle} sign${sign} value${value}`,async()=>{const{s,u}=fixture(angle,sign),c={id:'dim',kind:'dim',type:'hdist',a:pt(0),b:pt(1),frameAngleDeg:angle,projectionSign:sign,value},r=await solveFree(s,[fix,c]);assert.equal(r.conflict,false,JSON.stringify(r.conflictIds));assert.equal(r.dof,1);const d=[r.shapes[1].c[0]-r.shapes[0].c[0],r.shapes[1].c[1]-r.shapes[0].c[1]];assert.ok(Math.abs(dot(d,u)-sign*value)<1e-7);assert.ok(Math.abs(measureDim(r.shapes,c)-value)<1e-7);const gfx=dimGfx(r.shapes,c),[A,B]=gfx.lines[2];assert.ok(Math.abs((B[0]-A[0])*u[1]-(B[1]-A[1])*u[0])<1e-7)})
for(const edge of[true,false])for(const type of['h','v'])test(`oriented ${type} ${edge?'edge':'point pair'} stays on frame`,async()=>{const a=30*Math.PI/180,u=type==='h'?[Math.cos(a),Math.sin(a)]:[-Math.sin(a),Math.cos(a)],s=edge?[{type:'poly',open:true,pts:[[0,0],[10*u[0],10*u[1]]]}]:[{type:'circle',point:true,c:[0,0],r:0},{type:'circle',point:true,c:[10*u[0],10*u[1]],r:0}],c={id:'orientation',kind:'con',type,frameAngleDeg:30,a:edge?{kind:'edge',shape:0,idx:0}:pt(0),...(edge?{}:{b:pt(1)})},r=await solveFree(s,[c]);assert.equal(r.conflict,false);assert.equal(r.dof,3)})
test('wrong signed branch rejects original shapes and public ID',async()=>{const{s}=fixture(30,-1),c={id:'dim',kind:'dim',type:'hdist',a:pt(0),b:pt(1),frameAngleDeg:30,projectionSign:1,value:12},r=await solveFree(s,[fix,c]);assert.equal(r.conflict,true);assert.deepEqual(r.shapes,s);assert.ok(r.conflictIds.includes('dim'))})
test('invalid frame metadata and fixed conflicts reject atomically',async()=>{const{s}=fixture(30),base={id:'dim',kind:'dim',type:'hdist',a:pt(0),b:pt(1),frameAngleDeg:30,projectionSign:1,value:12};for(const c of[{...base,frameAngleDeg:NaN},{...base,projectionSign:undefined},base]){const r=await solveFree(s,[fix,{id:'Bfix',kind:'con',type:'fix',a:pt(1)},c]);assert.equal(r.conflict,true);assert.deepEqual(r.shapes,s)}})
test('framed vertical projected distance retains horizontal local DOF and JSON',async()=>{const{s,u,v}=fixture(30),c={id:'V',kind:'dim',type:'vdist',a:pt(0),b:pt(1),frameAngleDeg:30,projectionSign:1,value:18},r=await solveFree(JSON.parse(JSON.stringify(s)),[fix,c]);assert.equal(r.conflict,false);assert.equal(r.dof,1);const d=[r.shapes[1].c[0]-17,r.shapes[1].c[1]+11];assert.ok(Math.abs(dot(d,v)-18)<1e-7);const q=await solveFree(r.shapes,[fix,c,{id:'H',kind:'dim',type:'hdist',a:pt(0),b:pt(1),frameAngleDeg:30,projectionSign:1,value:9}]);assert.equal(q.conflict,false);assert.ok(Math.abs(dot([q.shapes[1].c[0]-17,q.shapes[1].c[1]+11],u)-9)<1e-7);assert.ok(Math.abs(measureDim(r.shapes,c)-18)<1e-7)})
test('legacy horizontal dimension and driven framed readout remain compatible',async()=>{const s=[{type:'circle',point:true,c:[0,0],r:0},{type:'circle',point:true,c:[10,5],r:0}],legacy={id:'legacy',kind:'dim',type:'hdist',a:pt(0),b:pt(1),value:12},r=await solveFree(s,[fix,legacy]);assert.equal(r.conflict,false);assert.ok(Math.abs(r.shapes[1].c[0]-12)<1e-7);const readout={...legacy,id:'readout',frameAngleDeg:30,driven:true};const q=await solveFree(s,[readout]);assert.equal(q.conflict,false);assert.equal(q.dof,4);assert.ok(Math.abs(measureDim(s,readout)-(10*Math.cos(Math.PI/6)+2.5))<1e-7)})
test('rotated rectangle width and dependent height grow with fixed corner',async()=>{const angle=30,a=angle*Math.PI/180,u=[Math.cos(a),Math.sin(a)],v=[-u[1],u[0]],P=(x,y)=>[100+x*u[0]+y*v[0],40+x*u[1]+y*v[1]],s=[{type:'poly',pts:[P(0,0),P(20,0),P(20,10),P(0,10)]}],pt=i=>({kind:'pt',shape:0,idx:i}),cs=[{id:'fix',kind:'con',type:'fix',a:pt(0)},...[0,1,2,3].map(i=>({id:'orientation'+i,kind:'con',type:i%2?'v':'h',a:{kind:'edge',shape:0,idx:i},frameAngleDeg:angle})),{id:'width',kind:'dim',type:'hdist',a:pt(0),b:pt(1),frameAngleDeg:angle,projectionSign:1,value:28},{id:'height',kind:'dim',type:'vdist',a:pt(1),b:pt(2),frameAngleDeg:angle,projectionSign:1,value:14}],r=await solveFree(s,cs);assert.equal(r.conflict,false,JSON.stringify(r.conflictIds));for(const[i,p]of[P(0,0),P(28,0),P(28,14),P(0,14)].entries())assert.ok(Math.hypot(r.shapes[0].pts[i][0]-p[0],r.shapes[0].pts[i][1]-p[1])<1e-7)})
for(const scale of[.01,1,1000])test(`framed rectangle scale ${scale}: normalized dimension edit succeeds`,async()=>{const angle=125,a=angle*Math.PI/180,u=[Math.cos(a),Math.sin(a)],v=[-u[1],u[0]],Q=(x,y)=>[1000*scale+x*u[0]*scale+y*v[0]*scale,-700*scale+x*u[1]*scale+y*v[1]*scale],s=[{type:'poly',pts:[Q(0,0),Q(20,0),Q(20,10),Q(0,10)]}],pt=i=>({kind:'pt',shape:0,idx:i}),cs=[{id:'fix',kind:'con',type:'fix',a:pt(0)},...[0,1,2,3].map(i=>({id:'axis'+i,kind:'con',type:i%2?'v':'h',a:{kind:'edge',shape:0,idx:i},frameAngleDeg:angle})),{id:'width',kind:'dim',type:'hdist',a:pt(0),b:pt(1),frameAngleDeg:angle,projectionSign:1,value:28*scale},{id:'height',kind:'dim',type:'vdist',a:pt(1),b:pt(2),frameAngleDeg:angle,projectionSign:1,value:14*scale}],r=await solveFree(s,cs);assert.equal(r.conflict,false,JSON.stringify(r.conflictIds));for(const[i,p]of[Q(0,0),Q(28,0),Q(28,14),Q(0,14)].entries())assert.ok(Math.hypot(r.shapes[0].pts[i][0]-p[0],r.shapes[0].pts[i][1]-p[1])<1e-7*Math.max(1,scale))})
