import test from 'node:test';import assert from 'node:assert/strict';import {register,createRequire} from 'node:module';import {fileURLToPath} from 'node:url'
globalThis.require=createRequire(import.meta.url);globalThis.__dirname=fileURLToPath(new URL('.',import.meta.url));register('./native-car-loader.mjs',import.meta.url)
await import('../src/worker/cad.worker.ts');await globalThis.__wheelWorker.ready();const {useApp,buildProjectPayload}=await import('../src/store.ts');const {createPersistentPattern:create}=await import('../src/sketch/persistentPatterns.ts')
const g=()=>useApp.getState(),json=()=>JSON.parse(JSON.stringify(buildProjectPayload(g())));
const cfg=(nx=2,dx=20)=>({kind:'rectangular',nx,ny:1,dx,dy:0});
function seed(){useApp.setState({...useApp.getInitialState(),mode:'sketch',sketchProfiles:[{type:'circle',c:[0,0],r:5}],skCons:[{id:'radius',kind:'dim',type:'rad',a:{kind:'circle',shape:0},value:5,name:'Radius'}],appConfirm:async()=>true},true)}
const xs=()=>g().sketchProfiles.map(s=>s.c?.[0]);
async function lineSeed(){useApp.setState({...useApp.getInitialState(),mode:'sketch',sketchProfiles:[{type:'poly',pts:[[0,0],[20,5]],open:true}],skCons:[],appConfirm:async()=>true},true);await g().createSketchPattern(cfg(2,40));useApp.setState({skSel:[{kind:'edge',shape:0,idx:0}]})}
function checkHorizontal(){for(const s of g().sketchProfiles)assert.ok(Math.abs(s.pts[0][1]-s.pts[1][1])<1e-6,JSON.stringify(s));const [a,b]=g().sketchProfiles;for(let i=0;i<2;i++){assert.ok(Math.abs(b.pts[i][0]-a.pts[i][0]-40)<1e-6);assert.ok(Math.abs(b.pts[i][1]-a.pts[i][1])<1e-6)}}
test('source horizontal constraint regenerates instances and survives Undo/JSON/reconfigure',async()=>{await lineSeed();const before=json(),count=g().sketchUndo.length;await g().addSkCon('h');await g().resolveSk();checkHorizontal();assert.equal(g().sketchUndo.length,count+1);await g().undo();assert.deepEqual(json(),before);await g().redo();checkHorizontal();const saved=json();await g().reset();await g().applyProjectData(saved);await g().reconfigureSketchPattern(cfg(3,40));checkHorizontal();assert.equal(g().sketchProfiles.length,3)})
test('removing source radius also removes owned copies of that constraint',async()=>{seed();await g().createSketchPattern(cfg());const generated=g().skPatternData.patterns[0].instances.flatMap(i=>i.generatedConstraintIds),count=g().sketchUndo.length;await g().removeSkCon('radius');assert.ok(!g().skCons.some(c=>c.id==='radius'||generated.includes(c.id)));assert.equal(g().sketchUndo.length,count+1);await g().reconfigureSketchPattern(cfg(3));assert.equal(g().sketchProfiles.length,3,g().status);assert.deepEqual(g().sketchProfiles.map(s=>s.r),[5,5,5])})
test('pending constraint operation cancelled by Esc does not modify history',async()=>{await lineSeed();const before=json(),count=g().sketchUndo.length,pending=g().addSkCon('h');g().escSketch();await pending;assert.deepEqual(json(),before);assert.equal(g().sketchUndo.length,count)})
test('conflicting horizontal constraint preserves fixed source and history',async()=>{await lineSeed();useApp.setState({skCons:[{id:'fixed-line',kind:'con',type:'fix',a:{kind:'edge',shape:0,idx:0}}]});const before=json(),count=g().sketchUndo.length;await g().addSkCon('h');assert.deepEqual(json(),before);assert.equal(g().sketchUndo.length,count)})
test('source radius removal then extrusion preserves exact volume and valid B-rep',async()=>{seed();await g().createSketchPattern(cfg());await g().removeSkCon('radius');await g().reconfigureSketchPattern(cfg(3));useApp.setState({extrudeHeight:6,sketchOp:'new'});await g().extrudeSketch();const {importSTEP,measureVolume,getOC}=await import('replicad'),solid=await importSTEP(new Blob([await globalThis.__wheelWorker.exportSTEP()]));assert.ok(Math.abs(measureVolume(solid)-3*Math.PI*25*6)<.001);const check=new(getOC().BRepCheck_Analyzer)(solid.wrapped,true,false);try{assert.ok(check.IsValid_2())}finally{check.delete()}})
test('source constraint removal cannot orphan a surviving formula',async()=>{seed();useApp.setState({sketchProfiles:[...g().sketchProfiles,{type:'circle',c:[100,0],r:10}],skCons:[...g().skCons,{id:'dependent',kind:'dim',type:'rad',a:{kind:'circle',shape:1},value:10,name:'D2',expr:'Radius*2',refs:{Radius:'dimension:radius'}}],skSel:[{kind:'circle',shape:0}]});await g().createSketchPattern(cfg());const before=json(),count=g().sketchUndo.length;await g().removeSkCon('radius');assert.deepEqual(json(),before);assert.equal(g().sketchUndo.length,count)})
