import test from 'node:test';import assert from 'node:assert/strict';import {register,createRequire} from 'node:module';import {fileURLToPath} from 'node:url'
globalThis.require=createRequire(import.meta.url);globalThis.__dirname=fileURLToPath(new URL('.',import.meta.url));register('./native-car-loader.mjs',import.meta.url)
await import('../src/worker/cad.worker.ts');await globalThis.__wheelWorker.ready();const {useApp,buildProjectPayload}=await import('../src/store.ts');const {createPersistentPattern:create}=await import('../src/sketch/persistentPatterns.ts')
const g=()=>useApp.getState(),json=()=>JSON.parse(JSON.stringify(buildProjectPayload(g())));
async function seed(){const r=create({shapes:[{type:'circle',c:[10,0],r:5}],cons:[{id:'x',name:'Position',kind:'dim',type:'hdist',a:{kind:'origin'},b:{kind:'pt',shape:0,idx:0},value:10,param:'Offset',paramId:'offset'},{id:'r',name:'Radius',kind:'dim',type:'rad',a:{kind:'circle',shape:0},value:5}],entityIds:[],patterns:[]},[0],{kind:'rectangular',nx:2,ny:1,dx:20,dy:0},'p');assert.equal(r.ok,true);const d=r.document;useApp.setState({...useApp.getInitialState(),mode:'sketch',sketchProfiles:d.shapes,skCons:d.cons,skPatternData:{entityIds:d.entityIds,patterns:d.patterns},params:[{id:'offset',name:'Offset',value:10}],extrudeHeight:5,sketchOp:'new',appConfirm:async()=>true},true);await g().extrudeSketch();assert.equal(g().mode,'model',g().status)}
const xs=()=>Object.values(g().sketchSources)[0].shapes.map(s=>s.c[0]);
test('parameter table position edit regenerates instance positions and survives Undo/Redo/JSON',async()=>{await seed();await g().setParam('Offset',20);assert.deepEqual(xs(),[20,40]);const {importSTEP}=await import('replicad'),solid=await importSTEP(new Blob([await globalThis.__wheelWorker.exportSTEP()]));assert.ok(Math.abs(solid.boundingBox.bounds[0][0]-15)<.001);assert.ok(Math.abs(solid.boundingBox.bounds[1][0]-45)<.001);await g().undo();assert.deepEqual(xs(),[10,30]);await g().redo();assert.deepEqual(xs(),[20,40]);const saved=json();await g().reset();await g().applyProjectData(saved);await g().setParam('Offset',25);assert.deepEqual(xs(),[25,45])});

test('conflicting parameter update restores parameter/source/model history atomically',async()=>{await seed();const [id,src]=Object.entries(g().sketchSources)[0];useApp.setState({sketchSources:{...g().sketchSources,[id]:{...src,cons:[...src.cons,{id:'fixed-source',kind:'con',type:'fix',a:{kind:'circle',shape:0}}]}}});const before=json(),count=g().undoStack.length;await g().setParam('Offset',20);assert.deepEqual(json(),before);assert.equal(g().undoStack.length,count);assert.deepEqual(xs(),[10,30])});
