import test from 'node:test';import assert from 'node:assert/strict';import {register,createRequire} from 'node:module';import {fileURLToPath} from 'node:url'
globalThis.require=createRequire(import.meta.url);globalThis.__dirname=fileURLToPath(new URL('.',import.meta.url));register('./native-car-loader.mjs',import.meta.url)
const {evalExpr}=await import('../src/store.ts'),{createPersistentPattern:create,reconfigurePersistentPattern:reconfigure}=await import('../src/sketch/persistentPatterns.ts'),{offsetPatternSources:offset}=await import('../src/sketch/offsetPatternSources.ts'),{editPatternDimensions:edit}=await import('../src/sketch/editPatternDimensions.ts')
const cfg=(nx=2)=>({kind:'rectangular',nx,ny:1,dx:50,dy:0}),options=parameters=>({evaluate:evalExpr,parameters}),settings=(distance=2)=>({distance,parameterId:'offset-gap',parameterName:'OffsetGap'}),good=r=>{assert.ok(r.ok,r.reason);return r.document}
function source({dimension='rad',fixed=false}={}){const shapes=[{type:'circle',c:[0,0],r:10}],cons=dimension?[{id:'sourceSize',name:'SourceSize',kind:'dim',type:dimension,a:{kind:'circle',shape:0},value:dimension==='dia'?20:10}]:[];if(fixed)cons.push({id:'fix',kind:'con',type:'fix',a:{kind:'circle',shape:0}});return good(create({shapes,cons,entityIds:[],patterns:[]},[0],cfg(),'pattern'))}
function radii(doc){return doc.shapes.map(s=>s.r).sort((a,b)=>a-b)}
for(const distance of [2,-2])test(`signed circle offset ${distance} follows source radius and editable parameter`,async()=>{const before=source(),snapshot=structuredClone(before),r=await offset(before,0,settings(distance),options([])),doc=good(r);assert.deepEqual(before,snapshot);assert.equal(doc.shapes.length,4);assert.equal(doc.entityIds.length,4);assert.deepEqual(radii(doc),distance>0?[10,10,12,12]:[8,8,10,10]);assert.equal(r.newEntityIds.length,2);assert.equal(r.newShapeIndices.length,2);const changed=good(await edit(doc,[{id:'sourceSize',value:12}],options([r.distanceParameter])));assert.deepEqual(radii(changed),distance>0?[12,12,14,14]:[10,10,12,12]);const gap={...r.distanceParameter,value:distance>0?3:-3},next=good(await edit(changed,[],options([gap])));assert.deepEqual(radii(next),distance>0?[12,12,15,15]:[9,9,12,12]);const roundtrip=JSON.parse(JSON.stringify(next)),more=good(reconfigure(roundtrip,'pattern',cfg(3)));assert.equal(more.shapes.length,6);for(const id of doc.entityIds)assert.ok(more.entityIds.includes(id));assert.equal(more.cons.filter(c=>c.kind==='dim'&&c.expr?.includes('OffsetGap')).length,3)})
test('diameter source binding converts to offset radius correctly',async()=>{const r=await offset(source({dimension:'dia'}),0,settings(),options([])),doc=good(r);assert.ok(doc.cons.find(c=>c.id===r.offsetRadiusId).expr.includes('/ 2'));const edited=good(await edit(doc,[{id:'sourceSize',value:30}],options([r.distanceParameter])));assert.deepEqual(radii(edited),[15,15,17,17])})
test('undimensioned fixed source gets named radius without moving original anchors',async()=>{const before=source({dimension:null,fixed:true}),r=await offset(before,0,settings(),options([])),doc=good(r);assert.ok(doc.cons.some(c=>c.id===r.sourceRadiusId));for(const id of before.entityIds)assert.deepEqual(doc.shapes[doc.entityIds.indexOf(id)],before.shapes[before.entityIds.indexOf(id)]);assert.deepEqual(radii(doc),[10,10,12,12])})
for(const kind of ['generated','collapse','parameter collision'])test(`${kind} offset rejects without original mutation`,async()=>{const before=source(),snapshot=structuredClone(before),r=await offset(before,kind==='generated'?1:0,settings(kind==='collapse'?-10:2),options(kind==='parameter collision'?[{id:'offset-gap',name:'OffsetGap',value:1}]:[]));assert.equal(r.ok,false);assert.deepEqual(before,snapshot)})
test('two-sided offset can compose isolated candidates with separate signed parameters',async()=>{const first=await offset(source(),0,settings(2),options([])),doc=good(first),sourceIndex=doc.entityIds.indexOf(doc.patterns[0].sourceEntityIds[0]);const second=await offset(doc,sourceIndex,{distance:-2,parameterId:'inner-gap',parameterName:'InnerGap'},options([first.distanceParameter]));assert.deepEqual(radii(good(second)),[8,8,10,10,12,12]);assert.equal(second.newEntityIds.length,2)})
