import test from 'node:test';import assert from 'node:assert/strict';import {register,createRequire} from 'node:module';import {fileURLToPath} from 'node:url'
globalThis.require=createRequire(import.meta.url);globalThis.__dirname=fileURLToPath(new URL('.',import.meta.url));register('./native-car-loader.mjs',import.meta.url)
await import('../src/worker/cad.worker.ts');await globalThis.__wheelWorker.ready()
const {useApp,buildProjectPayload}=await import('../src/store.ts'),{ellipseSample}=await import('../src/sketch/ellipseGeometry.ts'),{refPts}=await import('../src/sketch/freesolve.ts')
const g=()=>useApp.getState(),json=()=>JSON.parse(JSON.stringify(buildProjectPayload(g()))),cfg=(nx=2)=>({kind:'rectangular',nx,ny:1,dx:50,dy:0}),axis=(idx,shape=0)=>({kind:'ellipse-axis',shape,idx}),dim=(idx,value,shape=0)=>({id:`axis${idx}`,name:`Axis${idx}`,kind:'dim',type:'len',a:axis(idx,shape),value}),near=(a,b)=>assert.ok(Math.abs(a-b)<1e-6,`${a} != ${b}`)
async function seed(fixed=false){const ell={cx:20,cy:30,rx:10,ry:5,rot:30};useApp.setState({...useApp.getInitialState(),mode:'sketch',sketchProfiles:[{type:'poly',ell,pts:ellipseSample(ell)}],skCons:fixed?[{id:'fixed',kind:'con',type:'fix',a:{kind:'ellipse',shape:0}}]:[],appConfirm:async()=>false},true);await g().createSketchPattern(cfg());assert.ok(g().skPatternData,g().status)}
function copies(rx,ry,count=2){assert.equal(g().sketchProfiles.length,count);const first=g().sketchProfiles[0].ell;for(const [i,s]of g().sketchProfiles.entries()){assert.ok(s.ell,'native ellipse retained');near(s.ell.rx,rx);near(s.ell.ry,ry);near(s.ell.cx-first.cx,50*i);near(s.ell.cy,first.cy);near(s.ell.rot,first.rot)}}
for(const idx of [0,1])test(`rotated local ellipse axis ${idx}: placement, edit, history, JSON, count`,async()=>{await seed();const n=g().sketchUndo.length;await g().placePatternDimension(dim(idx,idx?5:10));assert.ok(g().skCons.some(c=>c.id===`axis${idx}`),g().status);assert.equal(g().sketchUndo.length,n+1);/* One semi-axis dimension leaves the other radius free. Constrain both before requiring the unedited radius to remain exact. */await g().placePatternDimension(dim(1-idx,idx?10:5));assert.ok(g().skCons.some(c=>c.id===`axis${1-idx}`),g().status);await g().commitSkDim(`axis${idx}`,{value:idx?7:14,expr:undefined},'axis edit');copies(idx?10:14,idx?7:5);await g().undo();copies(10,5);await g().redo();const saved=json();await g().reset();await g().applyProjectData(saved);await g().reconfigureSketchPattern(cfg(3));copies(idx?10:14,idx?7:5,3)})
for(const [label,ref]of [['generated',axis(0,1)],['invalid axis',axis(2)],['invalid shape',axis(0,99)]])test(`${label} placement rejects atomically`,async()=>{await seed();const before=json(),n=g().sketchUndo.length;await g().placePatternDimension({...dim(0,10),a:ref});assert.deepEqual(json(),before);assert.equal(g().sketchUndo.length,n)})
test('fixed ellipse axis resize rejected when reference fallback cancelled',async()=>{await seed(true);const before=json(),n=g().sketchUndo.length;await g().placePatternDimension(dim(0,14));assert.deepEqual(json(),before);assert.equal(g().sketchUndo.length,n)})
test('Esc cancels pending ellipse axis placement',async()=>{await seed();const before=json(),n=g().sketchUndo.length,pending=g().placePatternDimension(dim(0,10));g().escSketch();await pending;assert.deepEqual(json(),before);assert.equal(g().sketchUndo.length,n)})
test('actual dimension click places exact local ellipse semi-axis',async()=>{await seed(true);useApp.setState({sketchTool:'dimension'});const [a,b]=refPts(g().sketchProfiles,axis(0));let stop;const done=new Promise((resolve,reject)=>{const timer=setTimeout(()=>{stop?.();reject(new Error(g().status))},5000);stop=useApp.subscribe(s=>{if(s.skCons.some(c=>c.kind==='dim')){clearTimeout(timer);stop();resolve()}})});g().skClickAt([(a[0]+b[0])/2,(a[1]+b[1])/2]);await done;const c=g().skCons.find(c=>c.kind==='dim');assert.equal(c.a.kind,'ellipse-axis');near(c.value,10);copies(10,5)})
test('both ellipse radii drive native extrusion volume',async()=>{await seed();await g().placePatternDimension(dim(0,10));await g().placePatternDimension(dim(1,5));await g().commitSkDim('axis0',{value:14,expr:undefined},'major');await g().commitSkDim('axis1',{value:7,expr:undefined},'minor');copies(14,7);useApp.setState({extrudeHeight:6,sketchOp:'new'});await g().extrudeSketch();assert.equal(g().mode,'model',g().status);const {importSTEP,measureVolume,getOC}=await import('replicad'),solid=await importSTEP(new Blob([await globalThis.__wheelWorker.exportSTEP()]));assert.ok(Math.abs(measureVolume(solid)-2*Math.PI*14*7*6)<.01);const check=new(getOC().BRepCheck_Analyzer)(solid.wrapped,true,false);try{assert.ok(check.IsValid_2())}finally{check.delete()}})
test('fixed generated ellipse blocks source radius edit without drifting copies',async()=>{await seed();await g().placePatternDimension(dim(0,10));useApp.setState({skCons:[...g().skCons,{id:'copyFix',kind:'con',type:'fix',a:{kind:'ellipse',shape:1}}]});const before=json(),n=g().sketchUndo.length;await g().commitSkDim('axis0',{value:14,expr:undefined},'blocked edit');assert.deepEqual(json(),before);assert.equal(g().sketchUndo.length,n)})
