import test from 'node:test';import assert from 'node:assert/strict';import {register,createRequire} from 'node:module';import {fileURLToPath} from 'node:url'
globalThis.require=createRequire(import.meta.url);globalThis.__dirname=fileURLToPath(new URL('.',import.meta.url));register('./native-car-loader.mjs',import.meta.url)
await import('../src/worker/cad.worker.ts');await globalThis.__wheelWorker.ready();const {useApp,buildProjectPayload}=await import('../src/store.ts')
const g=()=>useApp.getState(),json=()=>JSON.parse(JSON.stringify(buildProjectPayload(g()))),radii=()=>g().sketchProfiles.map(s=>s.r)
const vertices=[[0,0],[20,0],[20,10],[10,15],[0,10]]
async function seed(){useApp.setState({...useApp.getInitialState(),mode:'sketch',sketchProfiles:[{type:'poly',pts:structuredClone(vertices)}],skCons:[],appConfirm:async()=>true},true);await g().createSketchPattern({kind:'rectangular',nx:2,ny:1,dx:40,dy:0});useApp.setState({skSel:[{kind:'pt',shape:0,idx:3}]})}
test('source vertex deletion regenerates instance outline, one UndoRedo and JSON',async()=>{await seed();const before=json(),ids=structuredClone(g().skPatternData),count=g().sketchUndo.length;await g().skDeleteSel();assert.deepEqual(g().sketchProfiles[0].pts,[[0,0],[20,0],[20,10],[0,10]],g().status);assert.deepEqual(g().sketchProfiles[1].pts,[[40,0],[60,0],[60,10],[40,10]]);assert.deepEqual(g().skPatternData.entityIds,ids.entityIds);assert.equal(g().sketchUndo.length,count+1);await g().undo();assert.deepEqual(json(),before);await g().redo();const saved=json();await g().reset();await g().applyProjectData(saved);assert.deepEqual(g().sketchProfiles[1].pts,[[40,0],[60,0],[60,10],[40,10]])})
test('deleted vertex profile extrudes into analytically correct valid pair of solids',async()=>{await seed();await g().skDeleteSel();useApp.setState({extrudeHeight:5,sketchOp:'new'});await g().extrudeSketch();const {importSTEP,measureVolume,getOC}=await import('replicad'),sh=await importSTEP(new Blob([await globalThis.__wheelWorker.exportSTEP()]));assert.ok(Math.abs(measureVolume(sh)-2000)<.001);const check=new(getOC().BRepCheck_Analyzer)(sh.wrapped,true,false);try{assert.ok(check.IsValid_2())}finally{check.delete()}})
test('unaffected fixed point and edge constraints survive with point index remapping',async()=>{await seed();useApp.setState({skCons:[{id:'origin-fix',kind:'con',type:'fix',a:{kind:'pt',shape:0,idx:0}},{id:'tail-fix',kind:'con',type:'fix',a:{kind:'pt',shape:0,idx:4}},{id:'horizontal',kind:'con',type:'h',a:{kind:'edge',shape:0,idx:0}}]});await g().skDeleteSel();assert.equal(g().sketchProfiles[0].pts.length,4,g().status);assert.equal(g().skCons.find(c=>c.id==='tail-fix')?.a.idx,3);assert.ok(g().skCons.some(c=>c.id==='horizontal'));assert.ok(g().skCons.some(c=>c.id==='origin-fix'))})
test('generated vertex deletion is refused atomically',async()=>{await seed();useApp.setState({skSel:[{kind:'pt',shape:1,idx:3}]});const before=json(),count=g().sketchUndo.length;await g().skDeleteSel();assert.deepEqual(json(),before);assert.equal(g().sketchUndo.length,count)})
test('open source remains open and construction after endpoint deletion',async()=>{useApp.setState({...useApp.getInitialState(),mode:'sketch',sketchProfiles:[{type:'poly',pts:[[0,0],[10,0],[20,10],[30,10]],open:true,construction:true}],skCons:[]},true);await g().createSketchPattern({kind:'rectangular',nx:2,ny:1,dx:40,dy:0});useApp.setState({skSel:[{kind:'pt',shape:0,idx:0}]});await g().skDeleteSel();assert.deepEqual(g().sketchProfiles[0].pts,[[10,0],[20,10],[30,10]],g().status);for(const s of g().sketchProfiles){assert.equal(s.open,true);assert.equal(s.construction,true)}})
test('vertex deletion straightens merged edge but preserves unrelated curved segment',async()=>{const {pathPts}=await import('../src/sketch/sketchOps.ts');const bulges=[.1,0,.2,0,0];useApp.setState({...useApp.getInitialState(),mode:'sketch',sketchProfiles:[{type:'poly',verts:structuredClone(vertices),bulges,pts:pathPts(vertices,bulges)}],skCons:[]},true);await g().createSketchPattern({kind:'rectangular',nx:2,ny:1,dx:40,dy:0});useApp.setState({skSel:[{kind:'pt',shape:0,idx:3}]});await g().skDeleteSel();assert.deepEqual(g().sketchProfiles[0].verts,[[0,0],[20,0],[20,10],[0,10]],g().status);assert.deepEqual(g().sketchProfiles[0].bulges,[.1,0,0,0]);assert.deepEqual(g().sketchProfiles[1].bulges,[.1,0,0,0])})
test('vertex deletion cannot orphan formula bound to removed edge dimension',async()=>{await seed();useApp.setState({sketchProfiles:[...g().sketchProfiles,{type:'circle',c:[100,100],r:Math.sqrt(125)}],skPatternData:{...g().skPatternData,entityIds:[...g().skPatternData.entityIds,'external-circle']},skCons:[{id:'edge-length',kind:'dim',type:'len',a:{kind:'edge',shape:0,idx:2},value:Math.sqrt(125),name:'EdgeLength'},{id:'external-radius',kind:'dim',type:'rad',a:{kind:'circle',shape:2},value:Math.sqrt(125),expr:'EdgeLength',refs:{EdgeLength:'dimension:edge-length'}}]});const before=json(),count=g().sketchUndo.length;await g().skDeleteSel();assert.deepEqual(json(),before);assert.equal(g().sketchUndo.length,count)})
test('invalid vertex index leaves source and history unchanged',async()=>{await seed();useApp.setState({skSel:[{kind:'pt',shape:0,idx:99}]});const before=json(),count=g().sketchUndo.length;await g().skDeleteSel();assert.deepEqual(json(),before);assert.equal(g().sketchUndo.length,count)})
test('closed triangle minimum refuses further vertex deletion with no Undo',async()=>{useApp.setState({...useApp.getInitialState(),mode:'sketch',sketchProfiles:[{type:'poly',pts:[[0,0],[20,0],[0,20]]}],skCons:[]},true);await g().createSketchPattern({kind:'rectangular',nx:2,ny:1,dx:40,dy:0});useApp.setState({skSel:[{kind:'pt',shape:0,idx:1}]});const before=json(),count=g().sketchUndo.length;await g().skDeleteSel();assert.deepEqual(json(),before);assert.equal(g().sketchUndo.length,count)})
test('pending vertex deletion cannot overwrite changed metadata',async()=>{await seed();const pending=g().skDeleteSel();useApp.setState({skPatternData:structuredClone(g().skPatternData)});const before=json(),count=g().sketchUndo.length;await pending;assert.deepEqual(json(),before);assert.equal(g().sketchUndo.length,count)})
