import test from 'node:test';import assert from 'node:assert/strict';import {register,createRequire} from 'node:module';import {fileURLToPath} from 'node:url'
globalThis.require=createRequire(import.meta.url);globalThis.__dirname=fileURLToPath(new URL('.',import.meta.url));register('./native-car-loader.mjs',import.meta.url)
await import('../src/worker/cad.worker.ts');await globalThis.__wheelWorker.ready()
const {useApp,buildProjectPayload}=await import('../src/store.ts'),{refPts,measureDim}=await import('../src/sketch/freesolve.ts')
const g=()=>useApp.getState(),json=()=>JSON.parse(JSON.stringify(buildProjectPayload(g()))),edge=(idx,shape=0)=>({kind:'edge',shape,idx}),cfg=(nx=2)=>({kind:'rectangular',nx,ny:1,dx:50,dy:0}),near=(a,b)=>assert.ok(Math.abs(a-b)<1e-5,`${a} != ${b}`)
async function seed(fixed=false){useApp.setState({...useApp.getInitialState(),mode:'sketch',sketchProfiles:[{type:'poly',pts:[[0,0],[20,0],[20,10],[0,10]]}],skCons:[{id:'base',kind:'con',type:'fix',a:edge(0)},{id:'right',kind:'con',type:'v',a:edge(1)},{id:'left',kind:'con',type:'v',a:edge(3)},...(fixed?[{id:'top',kind:'con',type:'fix',a:edge(2)}]:[])],appConfirm:async()=>false},true);await g().createSketchPattern(cfg());assert.ok(g().skPatternData,g().status)}
function check(height,count=2){assert.equal(g().sketchProfiles.length,count);for(let i=0;i<count;i++){const [a,b]=refPts(g().sketchProfiles,edge(0,i)),[c,d]=refPts(g().sketchProfiles,edge(2,i));near(Math.hypot(b[0]-a[0],b[1]-a[1]),20);near(c[1]-a[1],height);near(d[1]-a[1],height);near((b[0]-a[0])*(d[1]-c[1])-(b[1]-a[1])*(d[0]-c[0]),0);near(a[0],i*50)}}
test('parallel spacing batch drives closed profile, copies, history, JSON and native extrusion',async()=>{await seed();const before=json(),n=g().sketchUndo.length;await g().placePatternSpacing(edge(2),edge(0));const dim=g().skCons.find(c=>c.kind==='dim'&&c.type==='p2l'&&c.a.shape===0);assert.ok(dim,g().status);assert.ok(g().skCons.some(c=>c.kind==='con'&&c.type==='parallel'&&c.a.shape===0),'explicit source parallel relation');assert.equal(g().sketchUndo.length,n+1);check(10);await g().undo();assert.deepEqual(json(),before);await g().redo();await g().commitSkDim(dim.id,{value:15,expr:undefined},'spacing edit');check(15);await g().undo();check(10);await g().redo();const saved=json();await g().reset();await g().applyProjectData(saved);await g().reconfigureSketchPattern(cfg(3));check(15,3);useApp.setState({extrudeHeight:5,sketchOp:'new'});await g().extrudeSketch();assert.equal(g().mode,'model',g().status);const {importSTEP,measureVolume,getOC}=await import('replicad'),solid=await importSTEP(new Blob([await globalThis.__wheelWorker.exportSTEP()]));near(measureVolume(solid),3*20*15*5);const checkSolid=new(getOC().BRepCheck_Analyzer)(solid.wrapped,true,false);try{assert.ok(checkSolid.IsValid_2())}finally{checkSolid.delete()}})
test('fixed source spacing later edit rejects without history or side change',async()=>{await seed(true);await g().placePatternSpacing(edge(2),edge(0));const d=g().skCons.find(c=>c.kind==='dim'&&c.type==='p2l'&&c.a.shape===0);assert.ok(d,g().status);const before=json(),n=g().sketchUndo.length;await g().commitSkDim(d.id,{value:15,expr:undefined},'blocked');assert.deepEqual(json(),before);assert.equal(g().sketchUndo.length,n)})
test('generated parallel spacing rejects atomically',async()=>{await seed();const before=json(),n=g().sketchUndo.length;await g().placePatternSpacing(edge(2,1),edge(0,1));assert.deepEqual(json(),before);assert.equal(g().sketchUndo.length,n)})
test('Esc cancels whole parallel+spacing pending transaction',async()=>{await seed();const before=json(),n=g().sketchUndo.length,p=g().placePatternSpacing(edge(2),edge(0));g().escSketch();await p;assert.deepEqual(json(),before);assert.equal(g().sketchUndo.length,n)})
test('ordinary source point-to-line distance retains original side',async()=>{await seed();const d={id:'pointGap',name:'PointGap',kind:'dim',type:'p2l',a:{kind:'pt',shape:0,idx:2},b:edge(0),value:12};await g().placePatternDimension(d);assert.ok(g().skCons.some(c=>c.id===d.id),g().status);near(measureDim(g().sketchProfiles,d),12);const [p]=refPts(g().sketchProfiles,d.a);assert.ok(p[1]>0);assert.equal(g().skCons.some(c=>c.kind==='con'&&c.type==='parallel'),false,'point distance must not invent a parallel edge relation')})
