import test from 'node:test';import assert from 'node:assert/strict';import {register,createRequire} from 'node:module';import {fileURLToPath} from 'node:url'
globalThis.require=createRequire(import.meta.url);globalThis.__dirname=fileURLToPath(new URL('.',import.meta.url));register('./native-car-loader.mjs',import.meta.url)
await import('../src/worker/cad.worker.ts');await globalThis.__wheelWorker.ready();const {useApp,buildProjectPayload}=await import('../src/store.ts')
const g=()=>useApp.getState(),json=()=>JSON.parse(JSON.stringify(buildProjectPayload(g()))),radii=()=>g().sketchProfiles.map(s=>s.r)
async function seed(){useApp.setState({...useApp.getInitialState(),mode:'sketch',sketchProfiles:[{type:'circle',c:[0,0],r:5},{type:'circle',c:[100,0],r:3}],skCons:[],skSel:[{kind:'circle',shape:0}],appConfirm:async()=>true},true);await g().createSketchPattern({kind:'rectangular',nx:2,ny:1,dx:30,dy:0});useApp.setState({skSel:[{kind:'circle',shape:0}]})}
const flags=()=>g().sketchProfiles.map(s=>!!s.construction)
test('source construction switch propagates with one UndoRedo and JSON',async()=>{await seed();const before=json(),count=g().sketchUndo.length,metadata=structuredClone(g().skPatternData);g().toggleConstruction();assert.deepEqual(flags(),[true,false,true]);assert.deepEqual(g().skPatternData,metadata);assert.equal(g().sketchUndo.length,count+1);await g().undo();assert.deepEqual(json(),before);await g().redo();const saved=json();await g().reset();await g().applyProjectData(saved);assert.deepEqual(flags(),[true,false,true])})
test('extrude ignores both source and generated construction profiles',async()=>{await seed();g().toggleConstruction();useApp.setState({extrudeHeight:5,sketchOp:'new'});await g().extrudeSketch();const {importSTEP,measureVolume,getOC}=await import('replicad'),sh=await importSTEP(new Blob([await globalThis.__wheelWorker.exportSTEP()]));assert.ok(Math.abs(measureVolume(sh)-Math.PI*9*5)<.001);const check=new(getOC().BRepCheck_Analyzer)(sh.wrapped,true,false);try{assert.ok(check.IsValid_2())}finally{check.delete()}})
test('generated-only construction switch rejects without history',async()=>{await seed();useApp.setState({skSel:[{kind:'circle',shape:2}]});const before=json(),count=g().sketchUndo.length;g().toggleConstruction();assert.deepEqual(json(),before);assert.equal(g().sketchUndo.length,count)})
test('select-all toggles each source once and regenerated copies inherit the flag',async()=>{await seed();useApp.setState({skSel:g().sketchProfiles.map((_,shape)=>({kind:'circle',shape}))});g().toggleConstruction();assert.deepEqual(flags(),[true,true,true]);useApp.setState({skSel:[{kind:'circle',shape:0}]});g().toggleConstruction();assert.deepEqual(flags(),[false,true,false]);await g().reconfigureSketchPattern({kind:'rectangular',nx:3,ny:1,dx:30,dy:0});assert.deepEqual(flags(),[false,true,false,false])})
test('reopened extrusion source can restore solid participation and rebuild all profiles',async()=>{await seed();g().toggleConstruction();useApp.setState({extrudeHeight:5,sketchOp:'new'});await g().extrudeSketch();const f=g().features.find(f=>f.sketchId);assert.ok(f);await g().editSketchOf(f.id);assert.deepEqual(flags(),[true,false,true],g().status);useApp.setState({skSel:[{kind:'circle',shape:0}]});g().toggleConstruction();await g().applySketchEdit(f.sketchId);const {importSTEP,measureVolume,getOC}=await import('replicad'),sh=await importSTEP(new Blob([await globalThis.__wheelWorker.exportSTEP()]));assert.ok(Math.abs(measureVolume(sh)-Math.PI*59*5)<.001,`${measureVolume(sh)} ${g().status}`);const check=new(getOC().BRepCheck_Analyzer)(sh.wrapped,true,false);try{assert.ok(check.IsValid_2())}finally{check.delete()}})
