import test from 'node:test';import assert from 'node:assert/strict';import {register,createRequire} from 'node:module';import {fileURLToPath} from 'node:url'
globalThis.require=createRequire(import.meta.url);globalThis.__dirname=fileURLToPath(new URL('.',import.meta.url));register('./native-car-loader.mjs',import.meta.url)
await import('../src/worker/cad.worker.ts');await globalThis.__wheelWorker.ready();const {useApp,buildProjectPayload}=await import('../src/store.ts')
const g=()=>useApp.getState(),json=()=>JSON.parse(JSON.stringify(buildProjectPayload(g()))),centers=()=>g().sketchProfiles.map(s=>s.c)
async function seed(){useApp.setState({...useApp.getInitialState(),mode:'sketch',sketchProfiles:[{type:'circle',c:[0,0],r:5}],skCons:[],appConfirm:async()=>true},true);await g().createSketchPattern({kind:'rectangular',nx:2,ny:1,dx:20,dy:0})}
function prepare(target=0){useApp.setState({skSel:[{kind:'circle',shape:target}]});g().startSkMove();useApp.setState({skMove:{...g().skMove,dx:7,dy:3}})}
test('Move source updates instances with one Undo and survives JSON',async()=>{await seed();const ids=structuredClone(g().skPatternData),before=centers(),count=g().sketchUndo.length;prepare();await g().commitSkMove();assert.deepEqual(centers(),[[7,3],[27,3]],g().status);assert.deepEqual(g().skPatternData,ids);assert.equal(g().sketchUndo.length,count+1);await g().undo();assert.deepEqual(centers(),before);await g().redo();assert.deepEqual(centers(),[[7,3],[27,3]]);const data=json();await g().reset();await g().applyProjectData(data);assert.deepEqual(centers(),[[7,3],[27,3]]);prepare();await g().commitSkMove();assert.deepEqual(centers(),[[14,6],[34,6]])})
for(const kind of ['source-fix','instance-fix','instance-selection'])test(`Move rejects ${kind} without damaging geometry or history`,async()=>{await seed();if(kind!=='instance-selection')useApp.setState({skCons:[{id:'fixed',kind:'con',type:'fix',a:{kind:'circle',shape:kind==='source-fix'?0:1}}]});prepare(kind==='instance-selection'?1:0);const before=json(),count=g().sketchUndo.length;await g().commitSkMove();assert.deepEqual(json(),before);assert.equal(g().sketchUndo.length,count)})
test('cancel pending pattern Move discards late result',async()=>{await seed();prepare();const before=json(),count=g().sketchUndo.length,pending=g().commitSkMove();g().cancelSkMove();await pending;assert.deepEqual(json(),before);assert.equal(g().sketchUndo.length,count)})
test('Move pattern then extrude produces translated valid solid',async()=>{await seed();prepare();await g().commitSkMove();useApp.setState({extrudeHeight:5,sketchOp:'new'});await g().extrudeSketch();const {importSTEP,measureVolume,getOC}=await import('replicad'),sh=await importSTEP(new Blob([await globalThis.__wheelWorker.exportSTEP()]));assert.ok(Math.abs(measureVolume(sh)-2*Math.PI*25*5)<.001);const box=sh.boundingBox.bounds;assert.ok(Math.abs(box[0][0]-2)<.001);assert.ok(Math.abs(box[1][0]-32)<.001);const check=new(getOC().BRepCheck_Analyzer)(sh.wrapped,true,false);try{assert.ok(check.IsValid_2())}finally{check.delete()}})
test('numeric prompt route moves source and preserves unrelated geometry',async()=>{await seed();useApp.setState({sketchProfiles:[...g().sketchProfiles,{type:'circle',c:[100,100],r:2}],skPatternData:{...g().skPatternData,entityIds:[...g().skPatternData.entityIds,'unrelated']},appPrompt:async()=> '7,3,0,0'});prepare();await g().skMovePrompt();assert.deepEqual(centers(),[[7,3],[27,3],[100,100]],g().status)})
test('metadata replacement invalidates pending pattern Move',async()=>{await seed();prepare();const pending=g().commitSkMove();useApp.setState({skPatternData:structuredClone(g().skPatternData)});const before=json(),count=g().sketchUndo.length;await pending;assert.deepEqual(json(),before);assert.equal(g().sketchUndo.length,count)})
test('rectangle rotation preserves pattern offset and regenerated frame constraints',async()=>{useApp.setState({...useApp.getInitialState(),mode:'sketch',sketchProfiles:[{type:'rect',a:[0,0],b:[10,6]}],skCons:[]},true);await g().createSketchPattern({kind:'rectangular',nx:2,ny:1,dx:20,dy:0});useApp.setState({skSel:[{kind:'edge',shape:0,idx:0}]});g().startSkMove();useApp.setState({skMove:{...g().skMove,ang:90}});await g().commitSkMove();assert.equal(g().sketchProfiles[0].type,'poly',g().status);const [source,copy]=g().sketchProfiles;assert.equal(source.pts.length,copy.pts.length);for(let i=0;i<source.pts.length;i++){assert.ok(Math.abs(copy.pts[i][0]-source.pts[i][0]-20)<1e-7);assert.ok(Math.abs(copy.pts[i][1]-source.pts[i][1])<1e-7)}assert.ok(g().skCons.some(c=>c.frameAngleDeg===90));assert.ok(g().skPatternData.patterns[0].instances[0].generatedConstraintIds.length>=4)})
test('solved Move preview includes instances without changing document and matches commit',async()=>{await seed();prepare();const before=json(),history=g().sketchUndo.length;await g().previewSkMove();assert.equal(g().skMovePreview.error,null);assert.deepEqual(g().skMovePreview.shapes.map(s=>s.c),[[7,3],[27,3]]);assert.deepEqual(json(),before);assert.equal(g().sketchUndo.length,history);const preview=structuredClone(g().skMovePreview.shapes);await g().commitSkMove();assert.deepEqual(g().sketchProfiles,preview);assert.equal(g().sketchUndo.length,history+1)})
test('cancel clears a completed solved preview immediately',async()=>{await seed();prepare();await g().previewSkMove();g().cancelSkMove();assert.equal(g().skMovePreview.shapes,null);assert.equal(g().skMovePreview.pending,false)})
test('latest invalid Move preview replaces previous valid result',async()=>{await seed();prepare();const first=g().previewSkMove();useApp.setState({skCons:[{id:'fixed',kind:'con',type:'fix',a:{kind:'circle',shape:1}}]});const second=g().previewSkMove();await Promise.all([first,second]);assert.equal(g().skMovePreview.shapes,null);assert.ok(g().skMovePreview.error);assert.deepEqual(centers(),[[0,0],[20,0]])})
test('ordinary Move previews selected geometry and preserves unrelated circle',async()=>{useApp.setState({...useApp.getInitialState(),mode:'sketch',sketchProfiles:[{type:'circle',c:[0,0],r:5},{type:'circle',c:[80,0],r:3}],skCons:[]},true);prepare();await g().previewSkMove();assert.deepEqual(g().skMovePreview.shapes.map(s=>s.c),[[7,3],[80,0]]);assert.deepEqual(centers(),[[0,0],[80,0]]);await g().commitSkMove();assert.deepEqual(centers(),[[7,3],[80,0]])})
test('cancel pending preview cannot publish a late ghost',async()=>{await seed();prepare();const pending=g().previewSkMove();g().cancelSkMove();await pending;assert.deepEqual(g().skMovePreview,{shapes:null,pending:false,error:null});assert.deepEqual(centers(),[[0,0],[20,0]])})
test('numeric fields preview exact values; incomplete input blocks commit then recovers',async()=>{await seed();prepare();g().setSkMoveValue('dx','12.345');g().setSkMoveValue('dy','-2');await g().previewSkMove();assert.deepEqual(g().skMovePreview.shapes.map(s=>s.c),[[12.345,-2],[32.345,-2]]);const before=json();g().setSkMoveValue('dx','-');assert.equal(g().skMovePreview.shapes,null);assert.ok(g().skMove.inputError);await g().commitSkMove();assert.deepEqual(json(),before);g().setSkMoveValue('dx','4');await g().previewSkMove();assert.equal(g().skMove.inputError,null);await g().commitSkMove();assert.deepEqual(centers(),[[4,-2],[24,-2]])})
