import test from 'node:test';import assert from 'node:assert/strict';import {register,createRequire} from 'node:module';import {fileURLToPath} from 'node:url'
globalThis.require=createRequire(import.meta.url);globalThis.__dirname=fileURLToPath(new URL('.',import.meta.url));register('./native-car-loader.mjs',import.meta.url)
await import('../src/worker/cad.worker.ts');await globalThis.__wheelWorker.ready();const {useApp,buildProjectPayload}=await import('../src/store.ts');const {createPersistentPattern:create}=await import('../src/sketch/persistentPatterns.ts')
const g=()=>useApp.getState(),json=()=>JSON.parse(JSON.stringify(buildProjectPayload(g())));
const cfg=(nx=2,dx=20)=>({kind:'rectangular',nx,ny:1,dx,dy:0});
function seed(){useApp.setState({...useApp.getInitialState(),mode:'sketch',sketchProfiles:[{type:'circle',c:[0,0],r:5}],skCons:[{id:'radius',kind:'dim',type:'rad',a:{kind:'circle',shape:0},value:5,name:'Radius'}],appConfirm:async()=>true},true)}
const xs=()=>g().sketchProfiles.map(s=>s.c?.[0]);
async function angleSeed(){useApp.setState({...useApp.getInitialState(),mode:'sketch',sketchProfiles:[{type:'poly',pts:[[0,0],[10,0],[10,10]],open:true}],skCons:[],appConfirm:async()=>true},true);await g().createSketchPattern(cfg(2,40));useApp.setState({skSel:[{kind:'edge',shape:0,idx:0},{kind:'edge',shape:0,idx:1}]})}
function angle(s){const [a,b,c]=s.pts;return ((Math.atan2(c[1]-b[1],c[0]-b[0])-Math.atan2(b[1]-a[1],b[0]-a[0]))*180/Math.PI+360)%360}
test('source angle action then edit keeps instances synchronized across Undo and JSON',async()=>{await angleSeed();const count=g().sketchUndo.length;await g().addSkAngleDim();const dim=g().skCons.find(c=>c.kind==='dim'&&c.type==='angle');assert.ok(dim,g().status);assert.equal(g().sketchUndo.length,count+1);await g().commitSkDim(dim.id,{value:60,expr:undefined},'edit');for(const s of g().sketchProfiles)assert.ok(Math.abs(angle(s)-60)<1e-5,g().status);await g().undo();for(const s of g().sketchProfiles)assert.ok(Math.abs(angle(s)-90)<1e-5);await g().redo();const saved=json();await g().reset();await g().applyProjectData(saved);await g().reconfigureSketchPattern(cfg(3,40));assert.equal(g().sketchProfiles.length,3);for(const s of g().sketchProfiles)assert.ok(Math.abs(angle(s)-60)<1e-5)})
test('angle placement preserves exact fixed noninteger angle',async()=>{useApp.setState({...useApp.getInitialState(),mode:'sketch',sketchProfiles:[{type:'poly',pts:[[0,0],[10,0],[14,3]],open:true}],skCons:[{id:'f0',kind:'con',type:'fix',a:{kind:'edge',shape:0,idx:0}},{id:'f1',kind:'con',type:'fix',a:{kind:'edge',shape:0,idx:1}}]},true);await g().createSketchPattern(cfg(2,40));const shapes=structuredClone(g().sketchProfiles);useApp.setState({skSel:[{kind:'edge',shape:0,idx:0},{kind:'edge',shape:0,idx:1}]});await g().addSkAngleDim();const d=g().skCons.find(c=>c.kind==='dim');assert.ok(d,g().status);assert.ok(Math.abs(d.value-Math.atan2(3,4)*180/Math.PI)<1e-8);assert.deepEqual(g().sketchProfiles,shapes)})
test('reflex angle placement and subsequent edit preserve directed angle',async()=>{useApp.setState({...useApp.getInitialState(),mode:'sketch',sketchProfiles:[{type:'poly',pts:[[0,0],[10,0],[10,-10]],open:true}],skCons:[]},true);await g().createSketchPattern(cfg(2,40));useApp.setState({skSel:[{kind:'edge',shape:0,idx:0},{kind:'edge',shape:0,idx:1}]});await g().addSkAngleDim();const d=g().skCons.find(c=>c.kind==='dim'&&c.type==='angle');assert.ok(d,g().status);assert.ok(Math.abs(d.value-270)<1e-8);await g().commitSkDim(d.id,{value:240,expr:undefined},'edit');for(const s of g().sketchProfiles)assert.ok(Math.abs(angle(s)-240)<1e-5,g().status);await g().undo();for(const s of g().sketchProfiles)assert.ok(Math.abs(angle(s)-270)<1e-5)})
