import test from 'node:test';import assert from 'node:assert/strict';import {register,createRequire} from 'node:module';import {fileURLToPath} from 'node:url'
globalThis.require=createRequire(import.meta.url);globalThis.__dirname=fileURLToPath(new URL('.',import.meta.url));register('./native-car-loader.mjs',import.meta.url)
await import('../src/worker/cad.worker.ts');await globalThis.__wheelWorker.ready()
const {useApp,buildProjectPayload}=await import('../src/store.ts'),{measureDim}=await import('../src/sketch/freesolve.ts')
const g=()=>useApp.getState(),json=()=>JSON.parse(JSON.stringify(buildProjectPayload(g()))),pt=(idx,shape=0)=>({kind:'pt',shape,idx}),cfg=(nx=2)=>({kind:'rectangular',nx,ny:1,dx:50,dy:0}),near=(a,b)=>assert.ok(Math.abs(a-b)<1e-5,`${a} != ${b}`),dim=(type,value,a=pt(0),b=pt(1))=>({id:type,name:type.toUpperCase(),kind:'dim',type,value,a,b})
async function seed(shape={type:'poly',open:true,pts:[[0,0],[10,6]]},cons=[],config=cfg()){useApp.setState({...useApp.getInitialState(),mode:'sketch',sketchProfiles:[shape],skCons:cons,appConfirm:async()=>false},true);await g().createSketchPattern(config);assert.ok(g().skPatternData,g().status)}
for(const type of ['dist','hdist','vdist'])test(`${type} source point pair placement/edit/history/JSON/count`,async()=>{await seed();const value=type==='dist'?Math.hypot(10,6):type==='hdist'?10:6,n=g().sketchUndo.length;await g().placePatternDimension(dim(type,value));assert.ok(g().skCons.some(c=>c.id===type),g().status);assert.equal(g().sketchUndo.length,n+1);await g().commitSkDim(type,{value:value+3,expr:undefined},'distance edit');for(let i=0;i<2;i++)near(measureDim(g().sketchProfiles,dim(type,1,pt(0,i),pt(1,i))),value+3);await g().undo();near(measureDim(g().sketchProfiles,dim(type,1)),value);await g().redo();const saved=json();await g().reset();await g().applyProjectData(saved);await g().reconfigureSketchPattern(cfg(3));for(let i=0;i<3;i++)near(measureDim(g().sketchProfiles,dim(type,1,pt(0,i),pt(1,i))),value+3)})
for(const type of ['hdist','vdist'])test(`${type} accepts zero without inventing distance`,async()=>{await seed({type:'poly',open:true,pts:type==='hdist'?[[0,0],[0,10]]:[[0,0],[10,0]]});await g().placePatternDimension(dim(type,0));assert.ok(g().skCons.some(c=>c.id===type),g().status);for(let i=0;i<2;i++)near(measureDim(g().sketchProfiles,dim(type,1,pt(0,i),pt(1,i))),0)})
test('rotated circular copies preserve local projected dimensions',async()=>{await seed(undefined,[],{kind:'circular',count:4,angle:360,cx:0,cy:0});await g().placePatternDimension(dim('hdist',10));await g().commitSkDim('hdist',{value:15,expr:undefined},'projected edit');const dims=g().skCons.filter(c=>c.kind==='dim'&&c.type==='hdist');assert.equal(dims.length,4,g().status);for(const c of dims){near(c.value,15);near(measureDim(g().sketchProfiles,c),15)}assert.ok(dims.some(c=>c.frameAngleDeg===90))})
for(const kind of ['generated','invalid','same'])test(`${kind} point pair rejects without mutation`,async()=>{await seed();const before=json(),n=g().sketchUndo.length,d=dim('dist',10);if(kind==='generated')d.b=pt(1,1);if(kind==='invalid')d.b=pt(99);if(kind==='same')d.b=pt(0);await g().placePatternDimension(d);assert.deepEqual(json(),before);assert.equal(g().sketchUndo.length,n)})
test('fixed point pair conflicting placement cancelled atomically',async()=>{await seed(undefined,[{id:'fix',kind:'con',type:'fix',a:{kind:'edge',shape:0,idx:0}}]);const before=json(),n=g().sketchUndo.length;await g().placePatternDimension(dim('dist',30));assert.deepEqual(json(),before);assert.equal(g().sketchUndo.length,n)})
test('Esc prevents late point distance placement',async()=>{await seed();const before=json(),n=g().sketchUndo.length,p=g().placePatternDimension(dim('hdist',10));g().escSketch();await p;assert.deepEqual(json(),before);assert.equal(g().sketchUndo.length,n)})
test('point projection rectangle dimensions produce exact native volume',async()=>{await seed({type:'rect',a:[0,0],b:[10,6]});await g().placePatternDimension(dim('hdist',10,pt(0),pt(2)));await g().placePatternDimension(dim('vdist',6,pt(0),pt(2)));await g().commitSkDim('hdist',{value:14,expr:undefined},'width');await g().commitSkDim('vdist',{value:8,expr:undefined},'height');for(let i=0;i<2;i++){near(measureDim(g().sketchProfiles,dim('hdist',1,pt(0,i),pt(2,i))),14);near(measureDim(g().sketchProfiles,dim('vdist',1,pt(0,i),pt(2,i))),8)}useApp.setState({extrudeHeight:5,sketchOp:'new'});await g().extrudeSketch();assert.equal(g().mode,'model',g().status);const {importSTEP,measureVolume,getOC}=await import('replicad'),solid=await importSTEP(new Blob([await globalThis.__wheelWorker.exportSTEP()]));near(measureVolume(solid),2*14*8*5);const check=new(getOC().BRepCheck_Analyzer)(solid.wrapped,true,false);try{assert.ok(check.IsValid_2())}finally{check.delete()}})
