import test from 'node:test';import assert from 'node:assert/strict';import {register,createRequire} from 'node:module';import {fileURLToPath} from 'node:url'
globalThis.require=createRequire(import.meta.url);globalThis.__dirname=fileURLToPath(new URL('.',import.meta.url));register('./native-car-loader.mjs',import.meta.url)
await import('../src/worker/cad.worker.ts');await globalThis.__wheelWorker.ready();const {useApp,buildProjectPayload}=await import('../src/store.ts')
const g=()=>useApp.getState(),json=()=>JSON.parse(JSON.stringify(buildProjectPayload(g()))),radii=()=>g().sketchProfiles.map(s=>s.r)
async function seed(){useApp.setState({...useApp.getInitialState(),mode:'sketch',sketchProfiles:[{type:'poly',open:true,pts:[[0,0],[30,0]]},{type:'poly',open:true,pts:[[0,0],[0,10],[30,10],[30,0]]}],skCons:[],appConfirm:async()=>true},true);await g().createSketchPattern({kind:'rectangular',nx:2,ny:1,dx:60,dy:0})}
const lines=()=>g().sketchProfiles.map(s=>s.verts??s.pts).filter(p=>p.length===2).sort((a,b)=>a[0][0]-b[0][0])
test('break retains both source and copy halves through UndoRedo JSON and reconfiguration',async()=>{await seed();const before=json(),count=g().sketchUndo.length;await g().skBreakAt([15,0]);assert.deepEqual(lines(),[[[0,0],[15,0]],[[15,0],[30,0]],[[60,0],[75,0]],[[75,0],[90,0]]],g().status);assert.equal(g().sketchUndo.length,count+1);await g().undo();assert.deepEqual(json(),before);await g().redo();const saved=json();await g().reset();await g().applyProjectData(saved);await g().reconfigureSketchPattern({kind:'rectangular',nx:3,ny:1,dx:60,dy:0});assert.equal(lines().length,6,g().status)})
test('broken closed regions retain native extrusion area',async()=>{await seed();await g().skBreakAt([15,0]);assert.equal(lines().length,4,g().status);useApp.setState({extrudeHeight:5,sketchOp:'new'});await g().extrudeSketch();const {importSTEP,measureVolume,getOC}=await import('replicad'),sh=await importSTEP(new Blob([await globalThis.__wheelWorker.exportSTEP()]));assert.ok(Math.abs(measureVolume(sh)-3000)<.001);const check=new(getOC().BRepCheck_Analyzer)(sh.wrapped,true,false);try{assert.ok(check.IsValid_2())}finally{check.delete()}})
test('generated-only Break does not silently detach geometry',async()=>{await seed();const before=json(),count=g().sketchUndo.length;await g().skBreakAt([75,0]);assert.deepEqual(json(),before);assert.equal(g().sketchUndo.length,count)})
test('Esc discards pending Break result',async()=>{await seed();const before=json(),count=g().sketchUndo.length,pending=g().skBreakAt([15,0]);g().escSketch();await pending;assert.deepEqual(json(),before);assert.equal(g().sketchUndo.length,count)})
test('Break preserves original fixed endpoints on source and generated copy',async()=>{await seed();useApp.setState({skCons:[{id:'left',kind:'con',type:'fix',a:{kind:'pt',shape:0,idx:0}},{id:'right',kind:'con',type:'fix',a:{kind:'pt',shape:2,idx:1}}]});await g().skBreakAt([15,0]);assert.equal(lines().length,4,g().status);const {refPts}=await import('../src/sketch/freesolve.ts');assert.deepEqual(refPts(g().sketchProfiles,g().skCons.find(c=>c.id==='left').a),[[0,0]]);assert.deepEqual(refPts(g().sketchProfiles,g().skCons.find(c=>c.id==='right').a),[[90,0]])})
test('metadata replacement invalidates pending Break',async()=>{await seed();const pending=g().skBreakAt([15,0]);useApp.setState({skPatternData:structuredClone(g().skPatternData)});const before=json(),count=g().sketchUndo.length;await pending;assert.deepEqual(json(),before);assert.equal(g().sketchUndo.length,count)})
