import test from 'node:test';import assert from 'node:assert/strict';import {register,createRequire} from 'node:module';import {fileURLToPath} from 'node:url'
globalThis.require=createRequire(import.meta.url);globalThis.__dirname=fileURLToPath(new URL('.',import.meta.url));register('./native-car-loader.mjs',import.meta.url)
await import('../src/worker/cad.worker.ts');await globalThis.__wheelWorker.ready();const {useApp,buildProjectPayload}=await import('../src/store.ts');const {createPersistentPattern:create}=await import('../src/sketch/persistentPatterns.ts')
const g=()=>useApp.getState(),json=()=>JSON.parse(JSON.stringify(buildProjectPayload(g())));
const cfg=(nx=2,dx=20)=>({kind:'rectangular',nx,ny:1,dx,dy:0});
function seed(){useApp.setState({...useApp.getInitialState(),mode:'sketch',sketchProfiles:[{type:'circle',c:[0,0],r:5}],skCons:[{id:'radius',kind:'dim',type:'rad',a:{kind:'circle',shape:0},value:5,name:'Radius'}],appConfirm:async()=>true},true)}
const xs=()=>g().sketchProfiles.map(s=>s.c?.[0]);
test('source circle-line tangent preserves radius and regenerates translated pair',async()=>{useApp.setState({...useApp.getInitialState(),mode:'sketch',sketchProfiles:[{type:'circle',c:[0,0],r:5},{type:'poly',pts:[[-10,8],[10,8]],open:true}],skCons:[{id:'radius',name:'R1',kind:'dim',type:'rad',a:{kind:'circle',shape:0},value:5},{id:'lineFix',kind:'con',type:'fix',a:{kind:'edge',shape:1,idx:0}}]},true);await g().createSketchPattern(cfg(2,40));useApp.setState({skSel:[{kind:'circle',shape:0},{kind:'edge',shape:1,idx:0}]});const count=g().sketchUndo.length;await g().addSkCon('tangent');assert.equal(g().sketchUndo.length,count+1,g().status);const circles=g().sketchProfiles.filter(s=>s.type==='circle');assert.equal(circles.length,2);for(const c of circles){assert.ok(Math.abs(c.r-5)<1e-6);assert.ok(Math.abs(Math.abs(c.c[1]-8)-5)<1e-6,g().status)}assert.ok(Math.abs(circles[1].c[0]-circles[0].c[0]-40)<1e-6);await g().undo();assert.equal(g().sketchProfiles[0].c[1],0);await g().redo();await g().reconfigureSketchPattern(cfg(3,40));assert.equal(g().sketchProfiles.filter(s=>s.type==='circle').length,3,g().status)})
test('circle-circle tangent preserves radii and translated pairs',async()=>{useApp.setState({...useApp.getInitialState(),mode:'sketch',sketchProfiles:[{type:'circle',c:[0,0],r:5},{type:'circle',c:[12,0],r:3}],skCons:[{id:'aFix',kind:'con',type:'fix',a:{kind:'circle',shape:0}},{id:'bRadius',name:'R2',kind:'dim',type:'rad',a:{kind:'circle',shape:1},value:3}]},true);await g().createSketchPattern(cfg(2,40));useApp.setState({skSel:[{kind:'circle',shape:0},{kind:'circle',shape:1}]});await g().addSkCon('tangent');const [a,b,c,d]=g().sketchProfiles;assert.ok(Math.abs(Math.hypot(b.c[0]-a.c[0],b.c[1]-a.c[1])-8)<1e-6,g().status);assert.ok(Math.abs(Math.hypot(d.c[0]-c.c[0],d.c[1]-c.c[1])-8)<1e-6);assert.deepEqual(a.c,[0,0]);assert.deepEqual(g().sketchProfiles.map(s=>s.r),[5,3,5,3]);const saved=json();await g().reset();await g().applyProjectData(saved);await g().reconfigureSketchPattern(cfg(3,40));assert.equal(g().sketchProfiles.length,6,g().status)})
test('conflicting fixed circle tangent leaves design unchanged',async()=>{useApp.setState({...useApp.getInitialState(),mode:'sketch',sketchProfiles:[{type:'circle',c:[0,0],r:5},{type:'circle',c:[12,0],r:3}],skCons:[0,1].map(shape=>({id:'fix'+shape,kind:'con',type:'fix',a:{kind:'circle',shape}}))},true);await g().createSketchPattern(cfg(2,40));useApp.setState({skSel:[{kind:'circle',shape:0},{kind:'circle',shape:1}]});const before=json(),count=g().sketchUndo.length;await g().addSkCon('tangent');assert.deepEqual(json(),before);assert.equal(g().sketchUndo.length,count)})
test('tangent to construction line then extrude preserves shifted solid volume and bounds',async()=>{useApp.setState({...useApp.getInitialState(),mode:'sketch',sketchProfiles:[{type:'circle',c:[0,0],r:5},{type:'poly',pts:[[-10,8],[10,8]],open:true,construction:true}],skCons:[{id:'r',name:'R',kind:'dim',type:'rad',a:{kind:'circle',shape:0},value:5},{id:'fix',kind:'con',type:'fix',a:{kind:'edge',shape:1,idx:0}}]},true);await g().createSketchPattern(cfg(2,40));useApp.setState({skSel:[{kind:'circle',shape:0},{kind:'edge',shape:1,idx:0}]});await g().addSkCon('tangent');const circles=g().sketchProfiles.filter(s=>s.type==='circle');assert.ok(Math.abs(circles[0].c[1]-3)<1e-6,g().status);useApp.setState({extrudeHeight:4,sketchOp:'new'});await g().extrudeSketch();const {importSTEP,measureVolume,getOC}=await import('replicad'),solid=await importSTEP(new Blob([await globalThis.__wheelWorker.exportSTEP()]));assert.ok(Math.abs(measureVolume(solid)-200*Math.PI)<.001);const bounds=solid.boundingBox.bounds;assert.ok(Math.abs(bounds[0][1]+8)<1e-5,JSON.stringify({bounds,plane:g().sketchPlane}));assert.ok(Math.abs(bounds[1][1]-2)<1e-5);const check=new(getOC().BRepCheck_Analyzer)(solid.wrapped,true,false);try{assert.ok(check.IsValid_2())}finally{check.delete()}})

test('tangent Undo and Redo restore diagnostic state with its geometry',async()=>{
 useApp.setState({...useApp.getInitialState(),mode:'sketch',sketchProfiles:[{type:'circle',c:[0,0],r:5},{type:'poly',pts:[[-10,8],[10,8]],open:true}],skCons:[{id:'r',kind:'dim',type:'rad',a:{kind:'circle',shape:0},value:5},{id:'fix',kind:'con',type:'fix',a:{kind:'edge',shape:1,idx:0}}]},true)
 await g().createSketchPattern(cfg(2,40))
 const diagnostics=()=>({dof:g().skDof,conflict:g().skConflict,ids:[...g().skConflictIds],free:[...g().skFreeShapes]})
 const before=diagnostics(),beforeGeometry=structuredClone(g().sketchProfiles)
 useApp.setState({skSel:[{kind:'circle',shape:0},{kind:'edge',shape:1,idx:0}]})
 await g().addSkCon('tangent');const after=diagnostics(),afterGeometry=structuredClone(g().sketchProfiles)
 assert.notEqual(after.dof,before.dof)
 await g().undo();assert.deepEqual(diagnostics(),before);assert.deepEqual(g().sketchProfiles,beforeGeometry)
 await g().redo();assert.deepEqual(diagnostics(),after);assert.deepEqual(g().sketchProfiles,afterGeometry)
})
