import test from 'node:test';import assert from 'node:assert/strict';import {register,createRequire} from 'node:module';import {fileURLToPath} from 'node:url'
globalThis.require=createRequire(import.meta.url);globalThis.__dirname=fileURLToPath(new URL('.',import.meta.url));register('./native-car-loader.mjs',import.meta.url)
await import('../src/worker/cad.worker.ts');await globalThis.__wheelWorker.ready()
const {useApp,buildProjectPayload}=await import('../src/store.ts'),{pathPts}=await import('../src/sketch/sketchOps.ts'),{measureDim}=await import('../src/sketch/freesolve.ts')
const g=()=>useApp.getState(),json=()=>JSON.parse(JSON.stringify(buildProjectPayload(g()))),cfg=(nx=2)=>({kind:'rectangular',nx,ny:1,dx:60,dy:0}),near=(a,b)=>assert.ok(Math.abs(a-b)<1e-5,`${a} != ${b}`),con=(a,value)=>({id:'arcLength',name:'ArcLength',kind:'dim',type:'arclen',a,value})
async function seed(shape,cons=[]){useApp.setState({...useApp.getInitialState(),mode:'sketch',sketchProfiles:[shape],skCons:cons,appConfirm:async()=>false},true);await g().createSketchPattern(cfg());assert.ok(g().skPatternData,g().status)}
function bulged(b=.5,closed=false){const verts=[[0,0],[10,0]],bulges=closed?[b,0]:[b];return {type:'poly',...(closed?{}:{open:true}),verts,bulges,pts:pathPts(verts,bulges)}}
for(const b of [.5,-.5,2,-2])test(`native bulge ${b} arc length edits preserve signed minor/major branch`,async()=>{await seed(bulged(b));const a={kind:'edge',shape:0,idx:0},length=measureDim(g().sketchProfiles,con(a,1));const n=g().sketchUndo.length;await g().placePatternDimension(con(a,length));assert.ok(g().skCons.some(c=>c.id==='arcLength'),g().status);assert.equal(g().sketchUndo.length,n+1);await g().commitSkDim('arcLength',{value:length*1.05,expr:undefined},'arc edit');for(let i=0;i<2;i++){const s=g().sketchProfiles[i];assert.ok(s.verts&&s.bulges,'analytical arc retained');assert.equal(Math.sign(s.bulges[0]),Math.sign(b));assert.equal(Math.abs(s.bulges[0])>1,Math.abs(b)>1);near(measureDim(g().sketchProfiles,con({...a,shape:i},1)),length*1.05)}await g().undo();near(measureDim(g().sketchProfiles,con(a,1)),length);await g().redo();const saved=json();await g().reset();await g().applyProjectData(saved);await g().reconfigureSketchPattern(cfg(3));for(let i=0;i<3;i++)near(measureDim(g().sketchProfiles,con({...a,shape:i},1)),length*1.05)})
test('three-point native arc rim supports length and subsequent value edit',async()=>{const arc={a:[5,0],m:[0,5],b:[-5,0]};await seed({type:'poly',open:true,arc,pts:[arc.a,arc.m,arc.b]});const a={kind:'circle',shape:0},length=5*Math.PI;await g().placePatternDimension(con(a,length));assert.ok(g().skCons.some(c=>c.id==='arcLength'),g().status);await g().commitSkDim('arcLength',{value:length*1.05,expr:undefined},'edit');for(let i=0;i<2;i++){assert.ok(g().sketchProfiles[i].arc);near(measureDim(g().sketchProfiles,con({...a,shape:i},1)),length*1.05)}})
for(const kind of ['circle','line','ellipse','generated'])test(`${kind} arc length placement rejects atomically`,async()=>{let shape=bulged(),a={kind:'edge',shape:0,idx:0};if(kind==='circle'){shape={type:'circle',c:[0,0],r:5};a={kind:'circle',shape:0}}if(kind==='line')shape={type:'poly',open:true,pts:[[0,0],[10,0]]};if(kind==='ellipse'){const {ellipseSample}=await import('../src/sketch/ellipseGeometry.ts');const ell={cx:0,cy:0,rx:10,ry:5,rot:0};shape={type:'poly',ell,pts:ellipseSample(ell)};a={kind:'ellipse-axis',shape:0,idx:0}}await seed(shape);if(kind==='generated')a.shape=1;const before=json(),n=g().sketchUndo.length;await g().placePatternDimension(con(a,12));assert.deepEqual(json(),before);assert.equal(g().sketchUndo.length,n)})
test('pending arc placement Esc is atomic',async()=>{await seed(bulged());const a={kind:'edge',shape:0,idx:0},before=json(),n=g().sketchUndo.length,p=g().placePatternDimension(con(a,measureDim(g().sketchProfiles,con(a,1))));g().escSketch();await p;assert.deepEqual(json(),before);assert.equal(g().sketchUndo.length,n)})
test('closed arc profile: radius and arc length drive independent segment area extrusion',async()=>{const verts=[[5,0],[0,5]],bulges=[Math.tan(Math.PI/8),0],a={kind:'edge',shape:0,idx:0};await seed({type:'poly',verts,bulges,pts:pathPts(verts,bulges)},[{id:'radius',name:'Radius',kind:'dim',type:'rad',a,value:5}]);await g().placePatternDimension(con(a,5*Math.PI/2));await g().commitSkDim('arcLength',{value:5*2*Math.PI/3,expr:undefined},'120 degree arc');for(let i=0;i<2;i++)near(measureDim(g().sketchProfiles,con({...a,shape:i},1)),5*2*Math.PI/3);const nativeSource=structuredClone(g().sketchProfiles);useApp.setState({extrudeHeight:6,sketchOp:'new'});await g().extrudeSketch();assert.equal(g().mode,'model',g().status);const {importSTEP,measureVolume,getOC}=await import('replicad'),solid=await importSTEP(new Blob([await globalThis.__wheelWorker.exportSTEP()])),theta=2*Math.PI/3,expected=2*6*.5*25*(theta-Math.sin(theta));assert.ok(Math.abs(measureVolume(solid)-expected)<.01,`${measureVolume(solid)} != ${expected}; source=${JSON.stringify(nativeSource)}`);const check=new(getOC().BRepCheck_Analyzer)(solid.wrapped,true,false);try{assert.ok(check.IsValid_2())}finally{check.delete()}})
test('actual arc-length dimension click uses exact analytical length',async()=>{await seed(bulged(.5));useApp.setState({sketchTool:'dimension',dimArcLen:true});const sh=g().sketchProfiles[0],a={kind:'edge',shape:0,idx:0},expected=measureDim(g().sketchProfiles,con(a,1));let stop;const done=new Promise((resolve,reject)=>{const timer=setTimeout(()=>{stop?.();reject(new Error(g().status))},5000);stop=useApp.subscribe(s=>{if(s.skCons.some(c=>c.kind==='dim')){clearTimeout(timer);stop();resolve()}})});g().skClickAt(sh.pts[Math.floor(sh.pts.length/2)]);await done;const d=g().skCons.find(c=>c.kind==='dim');assert.equal(d.type,'arclen');near(d.value,expected)})
for(const bulge of [.5,-.5,2,-2])test(`native closed two-vertex bulge ${bulge} has exact circular segment volume`,async()=>{await seed(bulged(bulge,true));useApp.setState({extrudeHeight:3,sketchOp:'new'});await g().extrudeSketch();assert.equal(g().mode,'model',g().status);const {importSTEP,measureVolume,getOC}=await import('replicad'),solid=await importSTEP(new Blob([await globalThis.__wheelWorker.exportSTEP()]));const theta=4*Math.atan(Math.abs(bulge)),radius=10*(1+bulge*bulge)/(4*Math.abs(bulge)),expected=2*3*.5*radius*radius*(theta-Math.sin(theta));assert.ok(Math.abs(measureVolume(solid)-expected)<.01,`${measureVolume(solid)} != ${expected}`);const check=new(getOC().BRepCheck_Analyzer)(solid.wrapped,true,false);try{assert.ok(check.IsValid_2())}finally{check.delete()}})
test('two straight vertices still cannot create a closed solid',async()=>{await seed(bulged(0,true));const before=structuredClone(g().sketchProfiles);useApp.setState({extrudeHeight:3,sketchOp:'new'});await g().extrudeSketch();assert.equal(g().mode,'sketch');assert.equal(g().features.length,0);assert.deepEqual(g().sketchProfiles,before)})
