import test from 'node:test';import assert from 'node:assert/strict';import {register,createRequire} from 'node:module';import {fileURLToPath} from 'node:url'
globalThis.require=createRequire(import.meta.url);globalThis.__dirname=fileURLToPath(new URL('.',import.meta.url));register('./native-car-loader.mjs',import.meta.url)
await import('../src/worker/cad.worker.ts');await globalThis.__wheelWorker.ready();const {useApp,buildProjectPayload}=await import('../src/store.ts');const {createPersistentPattern:create}=await import('../src/sketch/persistentPatterns.ts')
const g=()=>useApp.getState(),json=()=>JSON.parse(JSON.stringify(buildProjectPayload(g())));
const cfg=(nx=2,dx=20)=>({kind:'rectangular',nx,ny:1,dx,dy:0});
function seed(){useApp.setState({...useApp.getInitialState(),mode:'sketch',sketchProfiles:[{type:'circle',c:[0,0],r:5}],skCons:[{id:'radius',kind:'dim',type:'rad',a:{kind:'circle',shape:0},value:5,name:'Radius'}],appConfirm:async()=>true},true)}
const xs=()=>g().sketchProfiles.map(s=>s.c?.[0]);
test('create and reconfigure pattern use actual store history with stable surviving IDs',async()=>{seed();await g().createSketchPattern(cfg());assert.deepEqual(xs(),[0,20]);const ids=[...g().skPatternData.entityIds];assert.equal(g().sketchUndo.length,1);await g().reconfigureSketchPattern(cfg(3,25));assert.deepEqual(xs(),[0,25,50]);assert.deepEqual(g().skPatternData.entityIds.slice(0,2),ids);await g().undo();assert.deepEqual(xs(),[0,20]);await g().redo();assert.deepEqual(xs(),[0,25,50]);const payload=json();await g().reset();await g().applyProjectData(payload);await g().reconfigureSketchPattern(cfg(2,30));assert.deepEqual(xs(),[0,30])});
test('detach preserves shapes/constraints and stops propagation with reversible metadata',async()=>{seed();await g().createSketchPattern(cfg());const shapes=structuredClone(g().sketchProfiles),cons=structuredClone(g().skCons),metadata=structuredClone(g().skPatternData);g().detachSketchPattern();assert.equal(g().skPatternData,null);assert.deepEqual(g().sketchProfiles,shapes);assert.deepEqual(g().skCons,cons);await g().undo();assert.deepEqual(g().skPatternData,metadata);await g().redo();assert.equal(g().skPatternData,null);await g().commitSkDim('radius',{value:6,expr:undefined},'edit');assert.deepEqual(g().sketchProfiles.map(s=>s.r),[6,5])});
test('quantity reduction rejects external reference to removed instance atomically',async()=>{seed();await g().createSketchPattern(cfg(3));useApp.setState({sketchProfiles:[...g().sketchProfiles,{type:'poly',pts:[[40,0],[50,0]],open:true}],skPatternData:{...g().skPatternData,entityIds:[...g().skPatternData.entityIds,'free-line']},skCons:[...g().skCons,{id:'external',kind:'con',type:'coincident',a:{kind:'pt',shape:2,idx:0},b:{kind:'pt',shape:3,idx:0}}]});const before=json(),count=g().sketchUndo.length;await g().reconfigureSketchPattern(cfg(2));assert.deepEqual(json(),before);assert.equal(g().sketchUndo.length,count)});
test('source change during pattern creation discards stale candidate',async()=>{seed();const pending=g().createSketchPattern(cfg());useApp.setState({sketchProfiles:structuredClone(g().sketchProfiles)});const before=json();await pending;assert.deepEqual(json(),before);assert.equal(g().sketchUndo.length,0)});
test('selected-only creation leaves unrelated source geometry unchanged',async()=>{seed();useApp.setState({sketchProfiles:[...g().sketchProfiles,{type:'circle',c:[100,0],r:9}],skSel:[{kind:'circle',shape:1}]});await g().createSketchPattern(cfg());assert.deepEqual(xs(),[0,100,120]);assert.deepEqual(g().sketchProfiles.map(s=>s.r),[5,9,9]);assert.equal(g().skCons[0].a.shape,0)});
test('same config and repeated detach do not create redundant Undo entries',async()=>{seed();g().detachSketchPattern();assert.equal(g().sketchUndo.length,0);await g().createSketchPattern(cfg());const count=g().sketchUndo.length;await g().reconfigureSketchPattern(cfg());assert.equal(g().sketchUndo.length,count);g().detachSketchPattern();const next=g().sketchUndo.length;g().detachSketchPattern();assert.equal(g().sketchUndo.length,next)});
test('created pattern extrusion rebuilds when instance count changes through source editing',async()=>{seed();await g().createSketchPattern(cfg());useApp.setState({extrudeHeight:5,sketchOp:'new'});await g().extrudeSketch();const f=g().features.find(f=>f.sketchId);assert.ok(f);await g().editSketchOf(f.id);await g().reconfigureSketchPattern(cfg(3,25));await g().applySketchEdit(f.sketchId);assert.equal(g().mode,'model',g().status);const {importSTEP,measureVolume,getOC}=await import('replicad'),sh=await importSTEP(new Blob([await globalThis.__wheelWorker.exportSTEP()]));assert.ok(Math.abs(measureVolume(sh)-3*Math.PI*25*5)<.001);const check=new(getOC().BRepCheck_Analyzer)(sh.wrapped,true,false);try{assert.ok(check.IsValid_2())}finally{check.delete()}});
test('associative preview leaves document untouched then commits identical geometry and IDs',async()=>{seed();const before=json();await g().previewSketchPattern(cfg(3,25));assert.equal(g().skPatternPreview.error,null);assert.deepEqual(g().skPatternPreview.shapes.map(s=>s.c[0]),[0,25,50]);assert.deepEqual(json(),before);const candidate=structuredClone(g().skPatternPreview.document);await g().createSketchPattern(cfg(3,25));assert.deepEqual(g().sketchProfiles,candidate.shapes);assert.deepEqual(g().skPatternData.entityIds,candidate.entityIds);assert.equal(g().sketchUndo.length,1)})
test('reconfigure preview is cancellable without changing instances or history',async()=>{seed();await g().createSketchPattern(cfg());const before=json(),count=g().sketchUndo.length;await g().previewSketchPattern(cfg(4,30),'reconfigure');assert.deepEqual(g().skPatternPreview.shapes.map(s=>s.c[0]),[0,30,60,90]);g().cancelSketchPatternPreview();assert.equal(g().skPatternPreview.document,null);assert.deepEqual(json(),before);assert.equal(g().sketchUndo.length,count)})
test('invalid latest pattern config clears successful preview',async()=>{seed();await g().previewSketchPattern(cfg());await g().previewSketchPattern(cfg(0));assert.equal(g().skPatternPreview.shapes,null);assert.ok(g().skPatternPreview.error);assert.deepEqual(xs(),[0])})
test('associative UI session requires explicit sources and routes preview/apply',async()=>{seed();g().beginSketchPattern('create');assert.equal(g().skPatternSession,null);useApp.setState({skSel:[{kind:'circle',shape:0}]});g().beginSketchPattern('create');assert.equal(g().skPatternSession.mode,'create');g().setArrayCfg({nx:3,ny:1,dx:25,dy:0,kind:'rect',distType:'spacing'});await g().previewArray();assert.deepEqual(g().skPatternPreview.shapes.map(s=>s.c[0]),[0,25,50]);await g().applyArray();assert.deepEqual(xs(),[0,25,50]);assert.equal(g().skPatternSession,null);assert.equal(g().sketchUndo.length,1)})
test('edit session hydrates existing config and cancel preserves pattern',async()=>{seed();await g().createSketchPattern(cfg(3,25));g().setArrayCfg({nx:8,dx:90});g().beginSketchPattern('reconfigure');assert.equal(g().arrayCfg.nx,3);assert.equal(g().arrayCfg.dx,25);const before=json();g().setArrayCfg({nx:4});await g().previewArray();assert.equal(g().skPatternPreview.shapes.length,4);g().cancelSketchPattern();assert.equal(g().skPatternSession,null);assert.deepEqual(json(),before)})
test('session extent converts total span to spacing and angle preview keeps source',async()=>{seed();useApp.setState({skSel:[{kind:'circle',shape:0}]});g().beginSketchPattern('create');g().setArrayCfg({kind:'rect',nx:3,ny:1,dx:60,dy:0,distType:'extent'});await g().previewArray();assert.deepEqual(g().skPatternPreview.shapes.map(s=>s.c[0]),[0,30,60]);await g().applyArray();g().beginSketchPattern('reconfigure');g().setArrayCfg({kind:'circ'});await g().previewArray();assert.ok(g().skPatternPreview.error);assert.deepEqual(xs(),[0,30,60]);g().cancelSketchPattern();seed();useApp.setState({skSel:[{kind:'circle',shape:0}]});g().beginSketchPattern('create');g().setArrayCfg({kind:'circ',count:3,angleType:'angle',angle:180,cx:20,cy:0});await g().previewArray();const p=g().skPatternPreview.shapes;assert.equal(p.length,3);assert.ok(Math.abs(p[1].c[0]-20)<1e-6);assert.ok(Math.abs(p[1].c[1]+20)<1e-6);assert.ok(Math.abs(p[2].c[0]-40)<1e-6);await g().applyArray();assert.deepEqual(g().sketchProfiles,p)})
test('cancel pending associative preview discards result and leaves history untouched',async()=>{seed();const before=json(),pending=g().previewSketchPattern(cfg(4));g().cancelSketchPatternPreview();await pending;assert.equal(g().skPatternPreview.document,null);assert.equal(g().skPatternPreview.pending,false);assert.deepEqual(json(),before);assert.equal(g().sketchUndo.length,0)})
test('cached preview cannot overwrite an intervening source dimension edit',async()=>{seed();await g().previewSketchPattern(cfg(3));await g().commitSkDim('radius',{value:7,expr:undefined},'edit');await g().createSketchPattern(cfg(3));assert.deepEqual(g().sketchProfiles.map(s=>s.r),[7,7,7]);const saved=json();await g().reset();await g().applyProjectData(saved);g().beginSketchPattern('reconfigure');g().setArrayCfg({nx:4});await g().previewArray();assert.deepEqual(g().skPatternPreview.shapes.map(s=>s.r),[7,7,7,7]);await g().applyArray();assert.deepEqual(g().sketchProfiles.map(s=>s.r),[7,7,7,7])})
test('public preview mutation cannot corrupt cached commit geometry',async()=>{seed();await g().previewSketchPattern(cfg());g().skPatternPreview.shapes[1].r=999;await g().createSketchPattern(cfg());assert.deepEqual(g().sketchProfiles.map(s=>s.r),[5,5])})
