import test from 'node:test';import assert from 'node:assert/strict';import {register,createRequire} from 'node:module';import {fileURLToPath} from 'node:url'
globalThis.require=createRequire(import.meta.url);globalThis.__dirname=fileURLToPath(new URL('.',import.meta.url));register('./native-car-loader.mjs',import.meta.url)
await import('../src/worker/cad.worker.ts');await globalThis.__wheelWorker.ready();const {useApp,buildProjectPayload}=await import('../src/store.ts')
const g=()=>useApp.getState(),json=()=>JSON.parse(JSON.stringify(buildProjectPayload(g()))),radii=()=>g().sketchProfiles.map(s=>s.r)
async function seed(){g().cancelSkScale();useApp.setState({...useApp.getInitialState(),mode:'sketch',sketchProfiles:[{type:'circle',c:[40,40],r:5}],skCons:[],appConfirm:async()=>true},true);await g().createSketchPattern({kind:'rectangular',nx:2,ny:1,dx:40,dy:0});useApp.setState({skSel:[{kind:'circle',shape:0}]})}
test('source scale preview includes regenerated instances without mutating document; commit UndoRedo JSON',async()=>{await seed();const before=json(),count=g().sketchUndo.length;g().startSkScale();await g().setSkScaleFactor(2);assert.deepEqual(json(),before);assert.deepEqual(g().skScale.preview?.map(s=>s.r),[10,10],g().skScale.error);await g().setSkScaleFactor(3);assert.deepEqual(g().skScale.preview?.map(s=>s.r),[15,15]);await g().confirmSkScale();assert.deepEqual(radii(),[15,15]);assert.equal(g().sketchUndo.length,count+1);await g().undo();assert.deepEqual(json(),before);await g().redo();const data=json();await g().reset();await g().applyProjectData(data);assert.deepEqual(radii(),[15,15])})
test('numeric scale prompt then native extrusion has correct copy radius and volume',async()=>{await seed();useApp.setState({appPrompt:async()=> '2,40,40'});await g().skScalePrompt();assert.deepEqual(radii(),[10,10],g().status);useApp.setState({extrudeHeight:5,sketchOp:'new'});await g().extrudeSketch();const {importSTEP,measureVolume,getOC}=await import('replicad'),sh=await importSTEP(new Blob([await globalThis.__wheelWorker.exportSTEP()]));assert.ok(Math.abs(measureVolume(sh)-2*Math.PI*100*5)<.001);const check=new(getOC().BRepCheck_Analyzer)(sh.wrapped,true,false);try{assert.ok(check.IsValid_2())}finally{check.delete()}})
for(const kind of ['source-fix','instance-fix','dimension','generated'])test(`scale preserves original document for ${kind}`,async()=>{await seed();if(kind==='generated')useApp.setState({skSel:[{kind:'circle',shape:1}]});else useApp.setState({skCons:[kind==='dimension'?{id:'rad',kind:'dim',type:'rad',a:{kind:'circle',shape:0},value:5}:{id:'fixed',kind:'con',type:'fix',a:{kind:'circle',shape:kind==='source-fix'?0:1}}]});const before=json(),count=g().sketchUndo.length;g().startSkScale();await g().setSkScaleFactor(2);assert.equal(g().skScale?.preview??null,null);await g().confirmSkScale();assert.deepEqual(json(),before);assert.equal(g().sketchUndo.length,count)})
test('cancel pending pattern scale cannot restore preview or change history',async()=>{await seed();const before=json(),count=g().sketchUndo.length;g().startSkScale();const pending=g().setSkScaleFactor(2);g().cancelSkScale();await pending;assert.equal(g().skScale,null);assert.deepEqual(json(),before);assert.equal(g().sketchUndo.length,count)})
test('metadata replacement invalidates solved scale candidate',async()=>{await seed();g().startSkScale();await g().setSkScaleFactor(2);useApp.setState({skPatternData:structuredClone(g().skPatternData)});const before=json(),count=g().sketchUndo.length;await g().confirmSkScale();assert.deepEqual(json(),before);assert.equal(g().sketchUndo.length,count)})
test('handle Escape restores prior solved pattern preview and commits matching metadata',async()=>{await seed();const count=g().sketchUndo.length;g().startSkScale();await g().setSkScaleFactor(1.5);g().startSkScaleHandle([50,40]);g().updateSkScaleHandle([60,40]);for(let i=0;i<2000&&g().skScale?.pending;i++)await new Promise(r=>setTimeout(r,1));assert.equal(g().skScale.pending,false);assert.deepEqual(g().skScale.preview.map(s=>s.r),[15,15]);g().stepBackSkScale();assert.deepEqual(g().skScale.preview.map(s=>s.r),[7.5,7.5]);await g().confirmSkScale();assert.deepEqual(radii(),[7.5,7.5]);assert.equal(g().sketchUndo.length,count+1);await g().reconfigureSketchPattern({kind:'rectangular',nx:3,ny:1,dx:40,dy:0});assert.deepEqual(radii(),[7.5,7.5,7.5])})
test('external scaling pivot moves source but pattern spacing stays authoritative',async()=>{await seed();useApp.setState({appPrompt:async()=> '2,0,0'});await g().skScalePrompt();assert.deepEqual(g().sketchProfiles.map(s=>s.c),[[80,80],[120,80]],g().status);assert.deepEqual(radii(),[10,10]);assert.equal(g().skPatternData.patterns[0].config.dx,40)})
