import test from 'node:test';import assert from 'node:assert/strict';import {register,createRequire} from 'node:module';import {fileURLToPath} from 'node:url'
globalThis.require=createRequire(import.meta.url);globalThis.__dirname=fileURLToPath(new URL('.',import.meta.url));register('./native-car-loader.mjs',import.meta.url)
await import('../src/worker/cad.worker.ts');await globalThis.__wheelWorker.ready();const {useApp,buildProjectPayload}=await import('../src/store.ts');const {createPersistentPattern:create}=await import('../src/sketch/persistentPatterns.ts')
const g=()=>useApp.getState(),json=()=>JSON.parse(JSON.stringify(buildProjectPayload(g())));
function seed(){const r=create({shapes:[{type:'circle',c:[0,0],r:5}],cons:[],entityIds:[],patterns:[]},[0],{kind:'rectangular',nx:2,ny:1,dx:20,dy:0},'p');assert.equal(r.ok,true);const d=r.document;useApp.setState({...useApp.getInitialState(),mode:'sketch',sketchProfiles:d.shapes,skCons:d.cons,skPatternData:{entityIds:d.entityIds,patterns:d.patterns},appConfirm:async()=>true},true);return structuredClone(g().skPatternData)}
test('active pattern draft survives project JSON and snapshot restoration',async()=>{const metadata=seed(),payload=json();assert.deepEqual(payload.sketchDraft.skPatternData,metadata);await g().reset();await g().applyProjectData(payload);assert.deepEqual(g().skPatternData,metadata);await g().reset();await g().applySnapshot(payload);assert.deepEqual(g().skPatternData,metadata)})
test('finish and reopen standalone source preserve pattern metadata',async()=>{const metadata=seed();await g().commitStandaloneSketch();assert.equal(g().mode,'model');const pair=Object.entries(g().sketchSources)[0];assert.ok(pair);assert.deepEqual(pair[1].patternData,metadata);const payload=json();await g().reset();await g().applyProjectData(payload);await g().editSketchOf(g().features.find(f=>f.sketchId===pair[0]).id,pair[0]);assert.equal(g().mode,'sketch');assert.deepEqual(g().skPatternData,metadata)})
test('opening a legacy document clears pattern metadata',async()=>{seed();await g().applyProjectData({app:'webcad',version:4,features:[]});assert.equal(g().skPatternData,null)})
test('malformed metadata rejects project replacement',async()=>{seed();const before=json(),bad=json();bad.sketchDraft.skPatternData.entityIds=['duplicate','duplicate'];await g().applyProjectData(bad);assert.deepEqual(json(),before)})
test('sketch Undo/Redo restores geometry and metadata together',async()=>{const metadata=seed();useApp.setState({sketchUndo:[{sketchShape:null,sketchProfiles:[g().sketchProfiles[0]],polyPts:[],sketchStart:null,skCons:[],skPatternData:null}]});await g().undo();assert.equal(g().skPatternData,null);assert.equal(g().sketchProfiles.length,1);await g().redo();assert.deepEqual(g().skPatternData,metadata);assert.equal(g().sketchProfiles.length,2)})
test('invalid finished-source pattern metadata is rejected before replacing current document',async()=>{seed();await g().commitStandaloneSketch();const before=json(),bad=json();Object.values(bad.sketchSources)[0].patternData.entityIds=[];await g().applyProjectData(bad);assert.deepEqual(json(),before)})
test('extrusion source retains metadata through project reload and sketch reopen',async()=>{const metadata=seed();useApp.setState({extrudeHeight:5,sketchOp:'new'});await g().extrudeSketch();assert.equal(g().mode,'model',g().status);const f=g().features.find(f=>f.sketchId);assert.ok(f);assert.deepEqual(g().sketchSources[f.sketchId].patternData,metadata);const payload=json();await g().reset();await g().applyProjectData(payload);await g().editSketchOf(f.id);assert.deepEqual(g().skPatternData,metadata);assert.equal(g().sketchProfiles.length,2)})
