import test from 'node:test';import assert from 'node:assert/strict';import {register,createRequire} from 'node:module';import {fileURLToPath} from 'node:url'
globalThis.require=createRequire(import.meta.url);globalThis.__dirname=fileURLToPath(new URL('.',import.meta.url));register('./native-car-loader.mjs',import.meta.url)
await import('../src/worker/cad.worker.ts');await globalThis.__wheelWorker.ready();const {useApp,buildProjectPayload}=await import('../src/store.ts');const {createPersistentPattern:create}=await import('../src/sketch/persistentPatterns.ts')
const g=()=>useApp.getState(),json=()=>JSON.parse(JSON.stringify(buildProjectPayload(g())));
const cfg=(nx=2,dx=20)=>({kind:'rectangular',nx,ny:1,dx,dy:0});
function seed(){useApp.setState({...useApp.getInitialState(),mode:'sketch',sketchProfiles:[{type:'circle',c:[0,0],r:5}],skCons:[{id:'radius',kind:'dim',type:'rad',a:{kind:'circle',shape:0},value:5,name:'Radius'}],appConfirm:async()=>true},true)}
const xs=()=>g().sketchProfiles.map(s=>s.c?.[0]);
async function bareCircle(){useApp.setState({...useApp.getInitialState(),mode:'sketch',sketchProfiles:[{type:'circle',c:[0,0],r:5}],skCons:[],appConfirm:async()=>true},true);await g().createSketchPattern(cfg())}
test('place source diameter then edit propagates and survives history/JSON',async()=>{await bareCircle();const count=g().sketchUndo.length;await g().placePatternDimension({id:'diameter',name:'D1',kind:'dim',type:'dia',a:{kind:'circle',shape:0},value:10});assert.ok(g().skCons.some(c=>c.id==='diameter'));assert.equal(g().sketchUndo.length,count+1);await g().commitSkDim('diameter',{value:14,expr:undefined},'edit');assert.deepEqual(g().sketchProfiles.map(s=>s.r),[7,7]);await g().undo();assert.deepEqual(g().sketchProfiles.map(s=>s.r),[5,5]);await g().redo();const saved=json();await g().reset();await g().applyProjectData(saved);await g().reconfigureSketchPattern(cfg(3));assert.deepEqual(g().sketchProfiles.map(s=>s.r),[7,7,7])})
test('generated dimension placement refuses without history or geometry change',async()=>{await bareCircle();const before=json(),count=g().sketchUndo.length;await g().placePatternDimension({id:'copyrad',name:'D1',kind:'dim',type:'rad',a:{kind:'circle',shape:1},value:5});assert.deepEqual(json(),before);assert.equal(g().sketchUndo.length,count)})
test('source line length dimension resizes each instance consistently',async()=>{useApp.setState({...useApp.getInitialState(),mode:'sketch',sketchProfiles:[{type:'poly',pts:[[0,0],[10,0]],open:true}],skCons:[]},true);await g().createSketchPattern(cfg(2,40));await g().placePatternDimension({id:'length',name:'D1',kind:'dim',type:'len',a:{kind:'edge',shape:0,idx:0},value:10});await g().commitSkDim('length',{value:15,expr:undefined},'edit');for(const s of g().sketchProfiles)assert.ok(Math.abs(Math.hypot(s.pts[1][0]-s.pts[0][0],s.pts[1][1]-s.pts[0][1])-15)<1e-6);const [a,b]=g().sketchProfiles;for(let i=0;i<2;i++)assert.ok(Math.abs(b.pts[i][0]-a.pts[i][0]-40)<1e-6)})
for(const accept of [false,true])test(`fixed source conflicting dimension reference fallback accept=${accept}`,async()=>{await bareCircle();let prompts=0;useApp.setState({skCons:[{id:'fix',kind:'con',type:'fix',a:{kind:'circle',shape:0}}],appConfirm:async()=>{prompts++;return accept}});const before=json(),count=g().sketchUndo.length;await g().placePatternDimension({id:'newrad',name:'D1',kind:'dim',type:'rad',a:{kind:'circle',shape:0},value:8});assert.equal(prompts,1,g().status);assert.deepEqual(g().sketchProfiles.map(s=>s.r),[5,5]);if(accept){assert.equal(g().skCons.find(c=>c.id==='newrad').driven,true);assert.equal(g().sketchUndo.length,count+1)}else{assert.deepEqual(json(),before);assert.equal(g().sketchUndo.length,count)}})
test('Esc while placing dimension cannot commit late result',async()=>{await bareCircle();const before=json(),count=g().sketchUndo.length,pending=g().placePatternDimension({id:'newrad',name:'D1',kind:'dim',type:'rad',a:{kind:'circle',shape:0},value:5});g().escSketch();await pending;assert.deepEqual(json(),before);assert.equal(g().sketchUndo.length,count)})
test('new diameter then resize and extrusion produce exact valid solid',async()=>{await bareCircle();await g().placePatternDimension({id:'diameter',name:'D1',kind:'dim',type:'dia',a:{kind:'circle',shape:0},value:10});await g().commitSkDim('diameter',{value:14,expr:undefined},'edit');useApp.setState({extrudeHeight:6,sketchOp:'new'});await g().extrudeSketch();const {importSTEP,measureVolume,getOC}=await import('replicad'),solid=await importSTEP(new Blob([await globalThis.__wheelWorker.exportSTEP()]));assert.ok(Math.abs(measureVolume(solid)-2*Math.PI*49*6)<.001);const check=new(getOC().BRepCheck_Analyzer)(solid.wrapped,true,false);try{assert.ok(check.IsValid_2())}finally{check.delete()}})
test('actual dimension click keeps unrounded fixed circle size',async()=>{useApp.setState({...useApp.getInitialState(),mode:'sketch',sketchProfiles:[{type:'circle',c:[0,0],r:5.123}],skCons:[{id:'fixed',kind:'con',type:'fix',a:{kind:'circle',shape:0}}]},true);await g().createSketchPattern(cfg());useApp.setState({sketchTool:'dimension'});let unsubscribe;const completed=new Promise((resolve,reject)=>{const timer=setTimeout(()=>{unsubscribe?.();reject(new Error(g().status))},3000);unsubscribe=useApp.subscribe(s=>{if(s.skCons.some(c=>c.kind==='dim')){clearTimeout(timer);unsubscribe();resolve()}})});g().skClickAt([5.123,0]);await completed;const d=g().skCons.find(c=>c.kind==='dim');assert.equal(d.type,'dia');assert.ok(Math.abs(d.value-10.246)<1e-8);assert.deepEqual(g().sketchProfiles.map(s=>s.r),[5.123,5.123])})
test('bulged arc radius placement and edit preserve instance radius and spacing',async()=>{const {pathPts,bulgeRadius}=await import('../src/sketch/sketchOps.ts');const verts=[[5,0],[-5,0]],bulges=[1];useApp.setState({...useApp.getInitialState(),mode:'sketch',sketchProfiles:[{type:'poly',open:true,verts,bulges,pts:pathPts(verts,bulges)}],skCons:[]},true);await g().createSketchPattern(cfg(2,40));await g().placePatternDimension({id:'arcR',name:'R1',kind:'dim',type:'rad',a:{kind:'edge',shape:0,idx:0},value:5});assert.ok(g().skCons.some(c=>c.id==='arcR'),g().status);await g().commitSkDim('arcR',{value:7,expr:undefined},'edit');for(const s of g().sketchProfiles)assert.ok(Math.abs(bulgeRadius(s.verts[0],s.verts[1],s.bulges[0])-7)<1e-6,g().status);const [a,b]=g().sketchProfiles;for(let i=0;i<2;i++){assert.ok(Math.abs(b.verts[i][0]-a.verts[i][0]-40)<1e-6);assert.ok(Math.abs(b.verts[i][1]-a.verts[i][1])<1e-6)}})
