import assert from "node:assert/strict";
import fs from "node:fs";
import { test } from "node:test";

// This is a source-level contract for capabilities.  It deliberately avoids
// translated UI copy and line-wrapping so an i18n or formatter change cannot
// conceal a functional regression.
const lab = fs
  .readFileSync(new URL("../src/components/PhysicsLab.tsx", import.meta.url), "utf8")
  .replace(/\s+/g, " ");
const store = fs.readFileSync(new URL("../src/store.ts", import.meta.url), "utf8");
const ribbon = fs.readFileSync(new URL("../src/ribbon.ts", import.meta.url), "utf8");

test("Physics Lab keeps the WebCAD solid-to-rigid-body and measurement contracts", () => {
  for (const capability of [
    /@dimforge\/rapier3d-compat/,
    /ENVIRONMENT_PRESETS/,
    /EnvironmentPreset = "earth" \| "moon" \| "mars" \| "zero-g" \| "custom"/,
    /physics-environment-preset/,
    /w\.gravity = \{ x: 0, y: -settings\.gravity, z: 0 \}/,
    /while \( accumulator\.current >= 1 \/ 120 && stepsThisFrame < frameStepBudget/,
    /ColliderDesc\.convexHull/,
    /CadBodyMode = "dynamic" \| "fixed"/,
    /RigidBodyDesc\.fixed\(\)/,
    /activeCadBodyMode: cadBodyMode/,
    /cadShape\.positions/,
    /body\?\.parked\?\.length/,
    /const parkedShapes = useMemo<ParkedShape\[\]>/,
    /parkedCadBodies: parkedShapes\.map/,
    /CAD 固定實體：\$\{shape\.name\}/,
    /activeCadBody:/,
    /collider: ["']convex-hull["']/,
    /componentShapes/,
    /componentBodies/,
    /componentJoints/,
    /JointData\.revolute/,
    /JointData\.prismatic/,
    /JointData\.spherical/,
    /JointData\.fixed/,
    /JointData\.generic/,
    /RAPIER\.JointAxesMask\.LinY \| RAPIER\.JointAxesMask\.LinZ/,
    /type: "screw"/,
    /type: "pinslot"/,
    /pitchPerRad/,
    /constraint\.angleRad \+= relAngular \* dt/,
    /slide - constraint\.pitchPerRad \* constraint\.angleRad/,
    /parentPinAxis/,
    /childPinAxis/,
    /customConstraints\.current\.forEach/,
    /applyTorqueImpulse/,
    /MATERIALS/,
    /densityKgM3/,
    /windSpeedMps/,
    /dragCoefficient/,
    /relativeSpeed = Math\.hypot\(rx, rz\)/,
    /roomWidth/,
    /roomDepth/,
    /roomHeight/,
    /webcad\.physics-lab\.scenario\/v1/,
    /webcad\.physics-lab-report\/v1/,
    /collisionEvents: collisions/,
    /activeCadTraceM: cadTrace/,
    /finalStateM:/,
    /onCadState/,
    /onCadTrace/,
    /ActiveEvents\.COLLISION_EVENTS/,
    /ActiveEvents\.CONTACT_FORCE_EVENTS/,
    /setContactForceEventThreshold\(0\.05\)/,
    /drainCollisionEvents/,
    /drainContactForceEvents/,
    /totalForceMagnitude\(\)/,
    /forceN\?: number/,
    /cadFlightEnabled/,
    /physics-cad-flight-enabled/,
    /physics-cad-thrust-n/,
    /cadLiftCoefficient/,
    /cadDragCoefficient/,
    /cadReferenceAreaM2/,
    /activeCadFlightTelemetry/,
    /activeCadPeakFlightLoad/,
    /activeCadPeakImpactLoad/,
    /physics-cad-impact-readings/,
    /physics-transfer-impact-load-to-fea/,
    /physics-transfer-impact-load-auto-cantilever/,
    /onCadImpact/,
    /maxForceDirection\(\)/,
    /maxForceMagnitude\(\)/,
    /cadColliderHandle/,
    /source: "rapier-max-contact"/,
    /physics-transfer-flight-load-to-fea/,
    /physics-transfer-flight-load-auto-cantilever/,
    /transferPeakFlightLoadToFea/,
    /transferPeakFlightLoadWithAutoSupport/,
    /autoFeaCantilever/,
    /physics-run-peak-fea/,
    /physics-peak-fea-verdict/,
    /linkedStaticPeakLoadFea/,
    /static-equivalent-peak-load-linear-elastic-fea/,
    /runPeakLoadFea/,
    /physics-cad-altitude-hold-enabled/,
    /physics-cad-target-altitude/,
    /cadAutopilotEnabled/,
    /cadTargetAltitudeM/,
    /commandedThrustN/,
    /physics-cad-waypoint-enabled/,
    /physics-cad-waypoint-x/,
    /physics-cad-waypoint-z/,
    /physics-cad-waypoint-add/,
    /physics-cad-waypoint-replay/,
    /physics-cad-waypoint-loop/,
    /cadWaypointRoute/,
    /waypointRouteIndex/,
    /waypointCompleted/,
    /cadWaypointEnabled/,
    /waypointDistanceM/,
    /CadTelemetrySample/,
    /onCadTelemetrySample/,
    /activeCadTelemetryTrace/,
    /physics-cad-telemetry-trace/,
    /physics-cad-obstacle-avoidance-enabled/,
    /physics-obstacle-count/,
    /cadObstacleAvoidanceEnabled/,
    /nearestObstacleDistanceM/,
    /procedural-fixed-cubes-only/,
    /physics-cad-raycast-avoidance-enabled/,
    /cadRaycastAvoidanceEnabled/,
    /raycastAvoidanceEnabled/,
    /nearestColliderDistanceM/,
    /castRayAndGetNormal/,
    /roomColliderHandles/,
    /all-collision-enabled-bodies-except-active-and-room/,
    /physics-cad-dynamic-replan-enabled/,
    /cadDynamicReplanEnabled/,
    /ReplanDecision/,
    /waypointDetour/,
    /three-ray-clearer-side-temporary-detour/,
    /activeCadReplanDecisions/,
    /physics-cad-train-navigation-policy/,
    /trainNavigationPolicy/,
    /cadNavigationPolicy/,
    /deterministic-evolutionary-search-on-2d-surrogate/,
    /rapier-ground-vehicle-xz-waypoint-and-avoidance-controller/,
    /supportedModes: \["ground-vehicle", "flight"\]/,
    /rapier-3d-flight-waypoint-and-avoidance-controller/,
    /physics-cad-transient-enabled/,
    /physics-cad-transient-material/,
    /stepTransientMaterial/,
    /cad-local-signed-kelvin-voigt-bilinear-elastoplastic-cumulative-damage-reduced-order/,
    /equivalent-transient-response-not-full-nonlinear-fea/,
    /activeCadTransientMaterialState/,
    /physics-cad-fracture-enabled/,
    /physics-cad-fracture-threshold/,
    /reduced-order-damage-threshold/,
    /bounding-box-four-rigid-fragment-reduced-order/,
    /activeCadFractureEvents/,
    /fractureBodies/,
    /physics-fast-forward-enabled/,
    /physics-fast-forward-steps/,
    /physics-stop-at-seconds/,
    /physics-simulation-time/,
    /fastForwardStepsPerFrame/,
    /onSimulationTargetReached/,
    /onWorldReady/,
    /disabled=\{!worldReady\}/,
    /建立物理世界…/,
    /physicsTimestepHz: 120/,
    /lastCadTelemetrySampleAt/,
    /elapsed\.current - lastCadTelemetrySampleAt\.current >= 0\.1/,
    /applyCadFlightController/,
    /c\.resetForces\(true\)/,
    /c\.resetTorques\(true\)/,
    /stepGroundVehicleController/,
    /applyCadGroundVehicleController/,
    /physics-cad-ground-enabled/,
    /physics-cad-ground-target-speed/,
    /physics-cad-ground-drive-force/,
    /physics-cad-ground-brake-force/,
    /physics-cad-ground-steering/,
    /physics-cad-ground-steering-torque/,
    /physics-cad-ground-readings/,
    /activeCadGroundVehicle/,
    /activeCadGroundTelemetry/,
    /physics-rosbridge-url/,
    /physics-rosbridge-connect/,
    /physics-rosbridge-disconnect/,
    /physics-rosbridge-status/,
    /parseRosTwist/,
    /rosPublishSimulationState/,
    /geometry_msgs\/msg\/Twist/,
    /\/webcad\/simulation_state/,
    /physics-cad-train-rl-navigation/,
    /physics-cad-rl-navigation-enabled/,
    /trainTabularNavigationPolicy/,
    /chooseRlAction/,
    /tabular-q-learning/,
    /rapier-ground-vehicle-runtime-steering-and-speed/,
    /physics-apply-wind-tunnel-calibration/,
    /webcad-lbm-wind-tunnel/,
    /windTunnelCalibration/,
    /tyreForceRequiresGroundContact: true/,
    /cadCollider\.setFriction\(0\)/,
    /cadCollider\.setFrictionCombineRule\(RAPIER\.CoefficientCombineRule\.Min\)/,
    /simTime <= 0/,
    /feaFixed/,
    /feaLoad/,
    /setFeaOpt/,
    /feaCustomDir/,
    /const cadForce: Vec3 = \[wx, -wz, wy\]/,
    /relative airflow/,
    /liftDirection/,
    /dynamicPressure/,
  ]) {
    assert.match(lab, capability);
  }
});

test("ground vehicle avoids double-counting Rapier floor friction", () => {
  assert.match(lab, /cadCollider\.setFriction\(0\)/);
  assert.match(
    lab,
    /cadCollider\.setFrictionCombineRule\(RAPIER\.CoefficientCombineRule\.Min\)/,
  );
});

test("Physics Lab remains reachable through store and ribbon command", () => {
  assert.match(store, /physicsLabOpen: boolean/);
  assert.match(store, /case 'physicslab'/);
  assert.match(ribbon, /id: 'physicslab'/);
});
