import test from 'node:test'
import assert from 'node:assert/strict'
import {register,createRequire} from 'node:module'
import {fileURLToPath} from 'node:url'
globalThis.require=createRequire(import.meta.url);globalThis.__dirname=fileURLToPath(new URL('.',import.meta.url));register('./native-car-loader.mjs',import.meta.url)
await import('../src/worker/cad.worker.ts');const w=globalThis.__wheelWorker;await w.ready()
const {useApp,buildProjectPayload}=await import('../src/store.ts'),{hitTest,refPts}=await import('../src/sketch/freesolve.ts'),{ellipseArcWithSweep,ellipseArcSample}=await import('../src/sketch/ellipseArcGeometry.ts'),{importSTEP,measureVolume,getOC}=await import('replicad')
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-6,`${a} != ${b}`),all=()=>[...useApp.getState().sketchProfiles,...(useApp.getState().sketchShape?[useApp.getState().sketchShape]:[])]
const independentPoint=(e,t)=>{const r=e.rot*Math.PI/180;return[e.cx+e.rx*Math.cos(t)*Math.cos(r)-e.ry*Math.sin(t)*Math.sin(r),e.cy+e.rx*Math.cos(t)*Math.sin(r)+e.ry*Math.sin(t)*Math.cos(r)]}
function seed(){const a=Math.PI/6;useApp.setState({...useApp.getInitialState(),mode:'sketch',sketchTool:'select',sketchProfiles:[{type:'poly',open:true,pts:[[20,30],[20+5*Math.cos(a)-4*Math.sin(a),30+5*Math.sin(a)+4*Math.cos(a)]]}],skCons:[{id:'fixed',kind:'con',type:'fix',a:{kind:'pt',shape:0,idx:0}},{id:'x',kind:'dim',type:'hdist',frameAngleDeg:30,projectionSign:1,a:{kind:'pt',shape:0,idx:0},b:{kind:'pt',shape:0,idx:1},value:5,expr:'5',name:'dX',refs:{}},{id:'y',kind:'dim',type:'vdist',frameAngleDeg:30,projectionSign:1,a:{kind:'pt',shape:0,idx:0},b:{kind:'pt',shape:0,idx:1},value:4,expr:'4',name:'dY',refs:{}}]},true)}
const projection=()=>{const [p,q]=all()[0].pts,a=Math.PI/6;return[(q[0]-p[0])*Math.cos(a)+(q[1]-p[1])*Math.sin(a),-(q[0]-p[0])*Math.sin(a)+(q[1]-p[1])*Math.cos(a)]}
test('zero projected formula edit stays nondegenerate and survives UndoRedo',async()=>{seed();await useApp.getState().commitSkDim('x',{value:0,expr:'0'},'zero');near(projection()[0],0);near(projection()[1],4);assert.equal(useApp.getState().skCons.find(c=>c.id==='x').value,0);assert.equal(useApp.getState().sketchUndo.length,1);await useApp.getState().undo();near(projection()[0],5);await useApp.getState().redo();near(projection()[0],0)})
test('editSkDim accepts zero projected distance through actual numeric entry path',async()=>{seed();useApp.getState().editSkDim('x',0);for(let i=0;i<100&&useApp.getState().sketchUndo.length===0;i++)await new Promise(r=>setTimeout(r,1));near(projection()[0],0);near(projection()[1],4);assert.equal(useApp.getState().sketchUndo.length,1)})
test('negative projected distance and zero positive length remain atomic rejections',async()=>{seed();const before=structuredClone({shapes:all(),cons:useApp.getState().skCons,undo:useApp.getState().sketchUndo});await useApp.getState().commitSkDim('x',{value:-1,expr:'-1'},'negative');assert.deepEqual({shapes:all(),cons:useApp.getState().skCons,undo:useApp.getState().sketchUndo},before);useApp.setState({sketchProfiles:[{type:'circle',c:[20,30],r:10}],skCons:[{id:'r',kind:'dim',type:'rad',a:{kind:'circle',shape:0},value:10,expr:'10'}]});await useApp.getState().commitSkDim('r',{value:0,expr:'0'},'zeroRadius');near(all()[0].r,10);assert.equal(useApp.getState().sketchUndo.length,0)})
test('zero vertical projected parameter preserves nonzero horizontal span and parameter identity',async()=>{seed();useApp.setState({params:[{id:'zero-param',name:'Zero',value:0}]});await useApp.getState().commitSkDim('y',{value:0,expr:'Zero',refs:{Zero:'zero-param'}},'verticalZero');near(projection()[0],5);near(projection()[1],0);const dim=useApp.getState().skCons.find(c=>c.id==='y');assert.equal(dim.value,0);assert.equal(dim.expr,'Zero');assert.deepEqual(dim.refs,{Zero:'zero-param'});assert.equal(useApp.getState().sketchUndo.length,1)})
