import test from'node:test';import assert from'node:assert/strict'
import{factorFromScalePointer,defaultScaleHandle}from'../src/sketch/scaleInteraction.ts'
const p=(x,y)=>({x,y})
test('axis handle projects lateral pointer movement without adding rotation',()=>{const r=factorFromScalePointer(p(0,0),p(10,0),p(20,7));assert.deepEqual(r,{ok:true,factor:2,handle:p(20,0)})})
test('oblique handle keeps the original ray and positive scale',()=>{const r=factorFromScalePointer(p(10,20),p(13,24),p(12,31));assert.equal(r.ok,true);assert.ok(Math.abs(r.factor-2)<1e-12);assert.deepEqual(r.handle,p(16,28))})
test('far-origin intent avoids squaring world coordinates',()=>{const r=factorFromScalePointer(p(1e6,-7e5),p(1e6+10,-7e5),p(1e6+5,-7e5+8));assert.equal(r.ok,true);assert.equal(r.factor,.5);assert.deepEqual(r.handle,p(1e6+5,-7e5))})
for(const current of[p(0,0),p(-1,5),p(0,10)])test(`zero or reverse ray rejects ${JSON.stringify(current)}`,()=>{assert.deepEqual(factorFromScalePointer(p(0,0),p(10,0),current),{ok:false,reason:'non-positive-factor'})})
test('degenerate initial handle and non-finite input reject explicitly',()=>{assert.deepEqual(factorFromScalePointer(p(0,0),p(0,0),p(10,0)),{ok:false,reason:'zero-handle-radius'});assert.deepEqual(factorFromScalePointer(p(0,0),p(1e-9,0),p(10,0)),{ok:false,reason:'zero-handle-radius'});for(const bad of[NaN,Infinity,-Infinity])assert.equal(factorFromScalePointer(p(0,0),p(10,0),p(bad,0)).ok,false)})
test('factor stays continuous through positive compression with no clamping',()=>{for(const factor of[.00001,.1,.5,1,2,10]){const r=factorFromScalePointer(p(3,4),p(13,4),p(3+10*factor,14));assert.equal(r.ok,true);assert.ok(Math.abs(r.factor-factor)<1e-12)}})
test('default handle lies beyond all selected bounds and supports collapsed selections',()=>{const h=defaultScaleHandle(p(10,20),{min:p(0,0),max:p(30,40)},2);assert.ok(h);assert.equal(h.y,20);assert.ok(h.x>10+Math.hypot(20,20));assert.deepEqual(defaultScaleHandle(p(10,20),{min:p(10,20),max:p(10,20)},5),p(15.75,20))})
test('default handle invalid bounds, overflow and invalid minimum never leak NaN',()=>{assert.equal(defaultScaleHandle(p(0,0),{min:p(2,0),max:p(1,0)}),null);assert.equal(defaultScaleHandle(p(0,0),{min:p(0,0),max:p(Infinity,1)}),null);assert.equal(defaultScaleHandle(p(0,0),{min:p(0,0),max:p(1,1)},0),null);assert.equal(defaultScaleHandle(p(Number.MAX_VALUE,0),{min:p(-Number.MAX_VALUE,0),max:p(Number.MAX_VALUE,0)}),null)})
