import test from 'node:test'
import assert from 'node:assert/strict'
import {readFileSync} from 'node:fs'
import {stripTypeScriptTypes} from 'node:module'
import vm from 'node:vm'
function harness(){const src=readFileSync(new URL('../src/store.ts',import.meta.url),'utf8'),a=src.indexOf('  refreshSectionCap: async () => {'),b=src.indexOf('  overhang: null,',a);let state={section:{on:true,capped:true,axis:'X',offset:10,flip:false},features:[{id:'body'}],params:[],paramBindings:{},suppressedIds:[],bodyMesh:{},sectionMesh:{old:true}},pending=[];const registry=new WeakMap();const context=vm.createContext({get:()=>state,set:p=>state={...state,...p},_previewFeatures:registry,applyParamBindings:f=>f.map(x=>({...x,bound:true})),expandFeats:f=>f,cad:{splitBuild:(...args)=>new Promise((resolve,reject)=>pending.push({args,resolve,reject}))}});const api=vm.runInContext(stripTypeScriptTypes(`let _sectionCapSeq=0;({${src.slice(a,b)}})`),context);return{api,pending,registry,state:()=>state,set:p=>state={...state,...p}}}
const half=tag=>({vertices:[1,2,3],triangles:[0,0,0],tag});
test('cap uses exact registered preview feature snapshot, including evaluated parameters',async()=>{for(const kind of ['shell','round','edit']){const h=harness(),preview={},features=[{id:'evaluated-preview',height:7}];h.registry.set(preview,features);h.set(kind==='shell'?{shellMode:true,shellPreviewMesh:preview}:kind==='round'?{edgeRoundPick:'fillet',roundPreviewMesh:preview}:{editPreviewMesh:preview});const p=h.api.refreshSectionCap();assert.equal(h.pending[0].args[0],features);h.pending[0].resolve({a:half(kind),b:half('other')});await p;assert.equal(h.state().sectionMesh.tag,kind)}});
test('new plane request clears old cap and rejects late results',async()=>{const h=harness(),old=h.api.refreshSectionCap();assert.equal(h.state().sectionMesh,null);h.set({section:{...h.state().section,offset:12}});const latest=h.api.refreshSectionCap();h.pending[1].resolve({a:half('latest'),b:half('b')});await latest;h.pending[0].resolve({a:half('old'),b:half('b')});await old;assert.equal(h.state().sectionMesh.tag,'latest')});
test('cancel restores bound committed source and empty half stays empty',async()=>{const h=harness(),preview={};h.registry.set(preview,[{id:'shell'}]);h.set({shellMode:true,shellPreviewMesh:preview});const p=h.api.refreshSectionCap();h.set({shellMode:false,shellPreviewMesh:null});const q=h.api.refreshSectionCap();assert.equal(h.pending[1].args[0][0].bound,true);const empty={vertices:[],triangles:[]};h.pending[1].resolve({a:empty,b:half('solid')});await q;h.pending[0].resolve({a:half('obsolete-shell'),b:half('b')});await p;assert.equal(h.state().sectionCapStatus,'empty');assert.equal(h.state().sectionMesh,empty)});
test('failed calculation cannot retain old cap and disabling section ignores outstanding work',async()=>{const h=harness(),p=h.api.refreshSectionCap();h.pending[0].resolve(null);await p;assert.equal(h.state().sectionCapStatus,'unavailable');assert.equal(h.state().sectionMesh,null);const q=h.api.refreshSectionCap();h.set({section:{...h.state().section,on:false}});await h.api.refreshSectionCap();h.pending[1].resolve({a:half('late'),b:half('b')});await q;assert.equal(h.state().sectionMesh,null);assert.equal(h.state().sectionCapStatus,'idle')});
