import test from 'node:test'
import assert from 'node:assert/strict'
import {register,createRequire} from 'node:module'
import {fileURLToPath} from 'node:url'
globalThis.require=createRequire(import.meta.url);globalThis.__dirname=fileURLToPath(new URL('.',import.meta.url));register('./native-car-loader.mjs',import.meta.url)
await import('../src/worker/cad.worker.ts');const w=globalThis.__wheelWorker;await w.ready()
const {useApp,buildProjectPayload}=await import('../src/store.ts'),{hitTest,refPts}=await import('../src/sketch/freesolve.ts'),{ellipseArcWithSweep,ellipseArcSample}=await import('../src/sketch/ellipseArcGeometry.ts'),{importSTEP,measureVolume,getOC}=await import('replicad')
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-6,`${a} != ${b}`),all=()=>[...useApp.getState().sketchProfiles,...(useApp.getState().sketchShape?[useApp.getState().sketchShape]:[])]
const independentPoint=(e,t)=>{const r=e.rot*Math.PI/180;return[e.cx+e.rx*Math.cos(t)*Math.cos(r)-e.ry*Math.sin(t)*Math.sin(r),e.cy+e.rx*Math.cos(t)*Math.sin(r)+e.ry*Math.sin(t)*Math.cos(r)]}
const area=sh=>{if(sh.type==='circle')return Math.PI*sh.r**2;if(sh.ell)return Math.PI*sh.ell.rx*sh.ell.ry;const e=sh.earc,t=e.signedSweepDeg*Math.PI/180;return e.rx*e.ry*Math.abs(t-Math.sin(t))/2}
// Real store/kernel Move regression; seeded geometry, actual command paths.
const xf=p=>{const a=Math.PI/6;return[30+(p[0]-30)*Math.cos(a)-(p[1]-30)*Math.sin(a)+70,30+(p[0]-30)*Math.sin(a)+(p[1]-30)*Math.cos(a)]}
function fixture(kind){const e={cx:30,cy:30,rx:10,ry:5,rot:30};return kind==='ellipse'?{type:'poly',ell:e,pts:Array.from({length:48},(_,i)=>independentPoint(e,i*Math.PI/24))}:kind==='earc'?{type:'poly',earc:ellipseArcWithSweep(e,330,270),pts:ellipseArcSample(ellipseArcWithSweep(e,330,270)),open:false}:{type:'rect',a:[20,25],b:[40,35]}}
async function move(path,angle=30){useApp.setState({skSel:[{kind:'edge',shape:0,idx:0}]});useApp.getState().startSkMove();const mv=useApp.getState().skMove;if(path==='numeric'){useApp.setState({appPrompt:async()=> `70,0,${angle},0`});await useApp.getState().skMovePrompt()}else{useApp.getState().skMoveHandleDown('x',[mv.cx,mv.cy]);useApp.getState().skMoveHandleMove([mv.cx+70,mv.cy]);useApp.getState().skMoveHandleUp();useApp.getState().skMoveHandleDown('rot',[mv.cx+80,mv.cy]);useApp.getState().skMoveHandleMove([mv.cx+70+10*Math.cos(angle*Math.PI/180),mv.cy+10*Math.sin(angle*Math.PI/180)]);useApp.getState().skMoveHandleUp();await useApp.getState().commitSkMove()}return mv}
async function volume(expected,shape,plane){const sh=await importSTEP(new Blob([await w.exportSTEP()])),check=new(getOC().BRepCheck_Analyzer)(sh.wrapped,true,false);try{assert.ok(check.IsValid_2())}finally{check.delete()}assert.ok(Math.abs(measureVolume(sh)-expected)<Math.max(1e-5,expected*5e-8));const e=shape.ell||shape.earc;let ps=shape.type==='rect'?[shape.a,[shape.b[0],shape.a[1]],shape.b,[shape.a[0],shape.b[1]]]:shape.pts;if(e){const r=e.rot*Math.PI/180,x=Math.atan2(-e.ry*Math.sin(r),e.rx*Math.cos(r))*180/Math.PI,y=Math.atan2(e.ry*Math.cos(r),e.rx*Math.sin(r))*180/Math.PI,angles=shape.earc?[e.a0,e.a0+e.signedSweepDeg]:[];for(const t of[x,x+180,y,y+180])if(!shape.earc||((t-e.a0)%360+360)%360<=e.signedSweepDeg+1e-9)angles.push(t);ps=angles.map(t=>independentPoint(e,t*Math.PI/180))}const bounds=sh.boundingBox.bounds,map=plane==='XZ'?[[0,0,1,0],[2,1,1,0]]:plane==='YZ'?[[1,0,-1,0],[2,1,1,0]]:plane==='ARB'?[[1,0,1,20],[2,1,1,30]]:[[0,0,1,0],[1,1,-1,0]];for(const[w,l,sign,o]of map){const v=ps.map(p=>p[l]*sign+o);assert.ok(Math.abs(bounds[0][w]-Math.min(...v))<1e-5);assert.ok(Math.abs(bounds[1][w]-Math.max(...v))<1e-5)}}
for(const kind of['ellipse','earc','rect'])for(const path of['gizmo','numeric'])for(const plane of['XY','XZ','YZ','ARB'])test(`${path} noncopy ${kind} Move ${plane} analytic native/history`,async()=>{
 const original=fixture(kind);useApp.setState({...useApp.getInitialState(),mode:'sketch',sketchTool:'select',sketchProfiles:[original],extrudeHeight:5,sketchOp:'new',...(plane==='ARB'?{sketchPlane:'XY',sketchArb:{o:[10,20,30],xd:[0,1,0],n:[1,0,0]}}:{sketchPlane:plane})},true)
 const angle=30,pivot=await move(path,angle);assert.equal(all().length,1);const moved=all()[0];if(kind==='ellipse'){assert.ok(moved.ell);near(moved.ell.cx,100);near(moved.ell.cy,30);near(moved.ell.rot,60);near(moved.ell.rx,10);near(moved.ell.ry,5)}if(kind==='earc'){assert.ok(moved.earc);near(moved.earc.signedSweepDeg,270);assert.equal(moved.earc.version,2);assert.equal(moved.open,false);const r=Math.PI/6;near(moved.earc.cx,pivot.cx+(30-pivot.cx)*Math.cos(r)-(30-pivot.cy)*Math.sin(r)+70);near(moved.earc.cy,pivot.cy+(30-pivot.cx)*Math.sin(r)+(30-pivot.cy)*Math.cos(r));near(moved.earc.rot,60)}
 const originalPts=kind==='rect'?[original.a,[original.b[0],original.a[1]],original.b,[original.a[0],original.b[1]]]:original.pts,r=angle*Math.PI/180,movedPts=moved.type==='rect'?[moved.a,[moved.b[0],moved.a[1]],moved.b,[moved.a[0],moved.b[1]]]:moved.pts;if(kind==='ellipse'){const e=moved.ell,a=e.rot*Math.PI/180;for(const p of movedPts){const x=(p[0]-e.cx)*Math.cos(a)+(p[1]-e.cy)*Math.sin(a),y=-(p[0]-e.cx)*Math.sin(a)+(p[1]-e.cy)*Math.cos(a);near((x/e.rx)**2+(y/e.ry)**2,1)}}else for(let i=0;i<originalPts.length;i++){const p=originalPts[i],q=[pivot.cx+(p[0]-pivot.cx)*Math.cos(r)-(p[1]-pivot.cy)*Math.sin(r)+70,pivot.cy+(p[0]-pivot.cx)*Math.sin(r)+(p[1]-pivot.cy)*Math.cos(r)];near(movedPts[i][0],q[0]);near(movedPts[i][1],q[1])}
 assert.equal(useApp.getState().sketchUndo.length,1);await useApp.getState().undo();assert.deepEqual(all(),[original]);await useApp.getState().redo();assert.deepEqual(all(),[moved]);const a=kind==='rect'?200:area(original);await useApp.getState().extrudeSketch();await volume(a*5,moved,plane)
 if(plane==='XY'){const payload=JSON.parse(JSON.stringify(buildProjectPayload(useApp.getState())));useApp.setState({...useApp.getInitialState()},true);await useApp.getState().applyProjectData(payload);await volume(a*5,moved,plane);assert.equal(await useApp.getState().applyFeatures(useApp.getState().features.map(f=>({...f,height:8})),'height8'),true);await volume(a*8,moved,plane)}
})
for(const path of['gizmo','numeric'])test(`${path} fixed whole circle Move preserves original anchor and both histories`,async()=>{
 useApp.setState({...useApp.getInitialState(),mode:'sketch',sketchTool:'select',sketchProfiles:[{type:'circle',c:[5,7],r:10}],skCons:[{id:'fixed',kind:'con',type:'fix',a:{kind:'circle',shape:0}}],skSel:[{kind:'circle',shape:0}],sketchRedo:[{sketchProfiles:[],skCons:[]}]},true)
 useApp.getState().startSkMove();const snapshot=()=>structuredClone({shapes:all(),cons:useApp.getState().skCons,undo:useApp.getState().sketchUndo,redo:useApp.getState().sketchRedo}),before=snapshot()
 if(path==='numeric'){useApp.setState({appPrompt:async()=> '20,10,0,0'});await useApp.getState().skMovePrompt()}else{const mv=useApp.getState().skMove;useApp.getState().skMoveHandleDown('x',[mv.cx,mv.cy]);useApp.getState().skMoveHandleMove([mv.cx+20,mv.cy]);useApp.getState().skMoveHandleUp();useApp.getState().skMoveHandleDown('y',[mv.cx+20,mv.cy]);useApp.getState().skMoveHandleMove([mv.cx+20,mv.cy+10]);useApp.getState().skMoveHandleUp();await useApp.getState().commitSkMove()}
 assert.deepEqual(snapshot(),before,'Move must not recreate a Fix anchor from the transformed candidate')
})
for(const path of['gizmo','numeric'])test(`${path} construction rectangle Move retains exclusion from native extrusion`,async()=>{
 useApp.setState({...useApp.getInitialState(),mode:'sketch',sketchTool:'select',sketchProfiles:[{...fixture('rect'),construction:true},{type:'circle',c:[200,30],r:5}],extrudeHeight:5,sketchOp:'new'},true)
 await move(path,30);assert.equal(all().length,2);assert.equal(all()[0].construction,true);assert.deepEqual(all()[1],{type:'circle',c:[200,30],r:5});await useApp.getState().extrudeSketch();const sh=await importSTEP(new Blob([await w.exportSTEP()]));near(measureVolume(sh),125*Math.PI)
})
for(const path of['gizmo','numeric'])test(`${path} explicit H/V rectangle rotation rejects instead of redefining its horizontal/vertical frame`,async()=>{
 useApp.setState({...useApp.getInitialState(),mode:'sketch',sketchTool:'select',sketchProfiles:[fixture('rect')],skCons:[0,1,2,3].map(i=>({id:'axis'+i,kind:'con',type:i%2?'v':'h',a:{kind:'edge',shape:0,idx:i}}))},true)
 const snapshot=()=>structuredClone({shapes:all(),cons:useApp.getState().skCons,undo:useApp.getState().sketchUndo,redo:useApp.getState().sketchRedo}),before=snapshot();await move(path,30);assert.deepEqual(snapshot(),before)
})
