import test from 'node:test'
import assert from 'node:assert/strict'
import {register,createRequire} from 'node:module'
import {fileURLToPath} from 'node:url'
globalThis.require=createRequire(import.meta.url);globalThis.__dirname=fileURLToPath(new URL('.',import.meta.url));register('./native-car-loader.mjs',import.meta.url)
await import('../src/worker/cad.worker.ts');await globalThis.__wheelWorker.ready()
const {useApp}=await import('../src/store.ts'),{pathPts,bulgeRadius}=await import('../src/sketch/sketchOps.ts')
const geometry=()=>structuredClone({profiles:useApp.getState().sketchProfiles,shape:useApp.getState().sketchShape,cons:useApp.getState().skCons})
async function setup(){const verts=[[60,40],[20,40]],bulges=[1],shape={type:'poly',open:true,verts,bulges,pts:pathPts(verts,bulges)},profiles=[{type:'circle',c:[0,60],r:20,construction:true}],cons=[{id:'cx',kind:'dim',type:'hdist',a:{kind:'origin'},b:{kind:'center',shape:1,idx:0},value:40},{id:'cy',kind:'dim',type:'vdist',a:{kind:'origin'},b:{kind:'center',shape:1,idx:0},value:40},{id:'master-radius',kind:'dim',type:'rad',a:{kind:'circle',shape:0},value:20},{id:'equal-radius',kind:'con',type:'equal',a:{kind:'edge',shape:1,idx:0},b:{kind:'circle',shape:0}}];useApp.setState({...useApp.getInitialState(),mode:'sketch',sketchTool:'select',navTool:'select',sketchPlane:'XY',sketchShape:shape,sketchProfiles:profiles,skCons:cons},true);await useApp.getState().resolveSk()}
test('repeated valid solves retain exact circle and Equal-arc geometry snapshots',async()=>{await setup();const initial=geometry();for(let i=0;i<8;i++){await useApp.getState().resolveSk();assert.deepEqual(geometry(),initial)}assert.equal(useApp.getState().sketchUndo.length,0)})
test('constrained arc drag Undo and Redo restore exact snapshots repeatedly',async()=>{await setup();const before=geometry();useApp.getState().skDragStart([60,40]);assert.ok(useApp.getState().skDrag);await useApp.getState().skDragEnd([70,30]);assert.equal(useApp.getState().sketchUndo.length,1);const after=geometry();assert.notDeepEqual(after,before);for(let i=0;i<5;i++){await useApp.getState().undo();assert.deepEqual(geometry(),before);await useApp.getState().redo();assert.deepEqual(geometry(),after)}})
test('normalizing roundoff never suppresses actual driving radius changes',async()=>{await setup();useApp.setState({skCons:useApp.getState().skCons.map(c=>c.id==='master-radius'?{...c,value:25}:c)});await useApp.getState().resolveSk();assert.equal(useApp.getState().skConflict,false);assert.ok(Math.abs(useApp.getState().sketchProfiles[0].r-25)<1e-6);const a=useApp.getState().sketchShape;assert.ok(Math.abs(bulgeRadius(a.verts[0],a.verts[1],a.bulges[0])-25)<1e-6);assert.equal(useApp.getState().skCons.find(c=>c.id==='master-radius').driven,undefined)})
