import test from 'node:test'
import assert from 'node:assert/strict'
import {register,createRequire} from 'node:module'
import {fileURLToPath} from 'node:url'
globalThis.require=createRequire(import.meta.url);globalThis.__dirname=fileURLToPath(new URL('.',import.meta.url));register('./native-car-loader.mjs',import.meta.url)
await import('../src/worker/cad.worker.ts');const w=globalThis.__wheelWorker;await w.ready()
const {useApp,buildProjectPayload}=await import('../src/store.ts'),{catmullRomClosed}=await import('../src/sketch/sketchOps.ts'),{sampleBSpline}=await import('../src/cad/bspline2d.ts'),{importSTEP,measureVolume,getOC}=await import('replicad')
// Independent cubic polynomial line-integral oracle: three-point Gauss integrates degree <=5 exactly.
function area(ctrl,bspline){const basis=bspline?[[1/6,-.5,.5,-1/6],[2/3,0,-1,.5],[1/6,.5,.5,-.5],[0,0,0,1/6]]:[[0,-.5,1,-.5],[1,0,-2.5,1.5],[0,.5,2,-1.5],[0,0,-.5,.5]];let sum=0;for(let i=0;i<ctrl.length;i++){const ps=Array.from({length:4},(_,j)=>ctrl[(i+j+(bspline?0:-1)+ctrl.length)%ctrl.length]);for(const[t,weight]of [[.5-Math.sqrt(3/5)/2,5/18],[.5,4/9],[.5+Math.sqrt(3/5)/2,5/18]]){let x=0,y=0,dx=0,dy=0;for(let j=0;j<4;j++){const[a,b,c,d]=basis[j],v=a+b*t+c*t*t+d*t*t*t,dv=b+2*c*t+3*d*t*t;x+=ps[j][0]*v;y+=ps[j][1]*v;dx+=ps[j][0]*dv;dy+=ps[j][1]*dv}sum+=weight*(x*dy-y*dx)}}return Math.abs(sum/2)}
const ctrlFor=x=>[[40,20],[x,20],[60,40],[40,40]]
function seed(bspline){const ctrl=ctrlFor(60);useApp.setState({...useApp.getInitialState(),mode:'sketch',sketchTool:'mirror',sketchProfiles:[{type:'poly',smooth:true,...(bspline?{bspline:true}:{}),ctrl,pts:bspline?sampleBSpline(ctrl,{closed:true,samples:64}):catmullRomClosed(ctrl)},{type:'poly',open:true,construction:true,pts:[[100,0],[100,60]]}],skCons:[...[0,2,3].map(idx=>({id:`fix${idx}`,kind:'con',type:'fix',a:{kind:'pt',shape:0,idx}})),{id:'ctrlX',name:'dCtrlX',kind:'dim',type:'hdist',a:{kind:'origin'},b:{kind:'pt',shape:0,idx:1},value:60,expr:'60',refs:{}},{id:'ctrlY',kind:'dim',type:'vdist',a:{kind:'origin'},b:{kind:'pt',shape:0,idx:1},value:20},{id:'axis',kind:'con',type:'fix',a:{kind:'edge',shape:1,idx:0}}],mirrorPick:{shapes:[0],stage:'line',p1:null},extrudeHeight:5,sketchOp:'new'},true)}
function verify(x,bspline){const s=useApp.getState(),a=[...s.sketchProfiles,...(s.sketchShape?[s.sketchShape]:[])],curves=a.filter(v=>v.smooth);assert.equal(curves.length,2);assert.equal(s.skConflict,false,s.status);for(const sh of curves){assert.equal(!!sh.bspline,bspline);assert.equal(!!sh.open,false)}ctrlFor(x).forEach((p,i)=>{assert.ok(Math.hypot(curves[0].ctrl[i][0]-p[0],curves[0].ctrl[i][1]-p[1])<1e-6);assert.ok(Math.hypot(curves[1].ctrl[i][0]-(200-p[0]),curves[1].ctrl[i][1]-p[1])<1e-6)});assert.equal(curves[0].pts.length,curves[1].pts.length);curves[0].pts.forEach((p,i)=>assert.ok(Math.hypot(curves[1].pts[i][0]-(200-p[0]),curves[1].pts[i][1]-p[1])<1e-6))}
async function volume(expected){const sh=await importSTEP(new Blob([await w.exportSTEP()])),checker=new(getOC().BRepCheck_Analyzer)(sh.wrapped,true,false);try{assert.ok(checker.IsValid_2())}finally{checker.delete()}const actual=measureVolume(sh),error=Math.abs(actual-expected)/expected;console.log('SPLINE ORACLE',JSON.stringify({actual,expected,error}));assert.ok(Number.isFinite(actual)&&error<1e-8,`${actual} differs from source cubic ${expected} by ${error}`)}
for(const bspline of [false,true])test(`closed ${bspline?'B-spline':'Catmull-Rom'} associative mirror native ctrl edit/history/JSON/STEP with independent integral`,async()=>{
 seed(bspline);const original=structuredClone(useApp.getState().skCons);await useApp.getState().skMirrorAt([100,30]);verify(60,bspline);for(const c of original)assert.deepEqual(useApp.getState().skCons.find(d=>d.id===c.id),c);await useApp.getState().extrudeSketch();assert.equal(useApp.getState().mode,'model',useApp.getState().status);await volume(2*area(ctrlFor(60),bspline)*5)
 let feat=useApp.getState().features.find(f=>f.sketchId);await useApp.getState().editSketchOf(feat.id);useApp.setState({skCons:useApp.getState().skCons.map(c=>c.id==='ctrlX'?{...c,value:65,expr:'65'}:c)});await useApp.getState().resolveSk();verify(65,bspline);await useApp.getState().applySketchEdit(feat.sketchId);await volume(2*area(ctrlFor(65),bspline)*5)
 assert.equal(await useApp.getState().applyFeatures(useApp.getState().features.map(f=>({...f,height:8})),'height8'),true);await volume(2*area(ctrlFor(65),bspline)*8);await useApp.getState().undo();await volume(2*area(ctrlFor(65),bspline)*5);await useApp.getState().redo();await volume(2*area(ctrlFor(65),bspline)*8)
 const payload=JSON.parse(JSON.stringify(buildProjectPayload(useApp.getState())));useApp.setState({...useApp.getInitialState()},true);await useApp.getState().applyProjectData(payload);await volume(2*area(ctrlFor(65),bspline)*8);feat=useApp.getState().features.find(f=>f.sketchId);await useApp.getState().editSketchOf(feat.id);verify(65,bspline);await useApp.getState().applySketchEdit(feat.sketchId);await volume(2*area(ctrlFor(65),bspline)*8)
})
for(const bspline of [false,true])for(const plane of ['XZ','YZ','ARB'])test(`${bspline?'B-spline':'Catmull-Rom'} cubic mirror transforms to ${plane} without changing area`,async()=>{
 seed(bspline);useApp.setState(plane==='ARB'?{sketchPlane:'XY',sketchArb:{o:[10,20,30],xd:[0,1,0],n:[1,0,0]}}:{sketchPlane:plane});await useApp.getState().skMirrorAt([100,30]);verify(60,bspline);await useApp.getState().extrudeSketch();assert.equal(useApp.getState().mode,'model',useApp.getState().status);await volume(2*area(ctrlFor(60),bspline)*5);const shape=await importSTEP(new Blob([await w.exportSTEP()])),bounds=shape.boundingBox.bounds,axis=plane==='XZ'?1:0;assert.ok(Math.abs(bounds[1][axis]-bounds[0][axis]-5)<1e-5,`${plane} normal depth must be5`)
})
