import test from 'node:test'
import assert from 'node:assert/strict'
import {register,createRequire} from 'node:module'
import {fileURLToPath} from 'node:url'
globalThis.require=createRequire(import.meta.url);globalThis.__dirname=fileURLToPath(new URL('.',import.meta.url));register('./native-car-loader.mjs',import.meta.url)
await import('../src/worker/cad.worker.ts');const w=globalThis.__wheelWorker;await w.ready()
const {useApp,buildProjectPayload}=await import('../src/store.ts'),{hitTest,refPts}=await import('../src/sketch/freesolve.ts'),{importSTEP,measureVolume,getOC}=await import('replicad')
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-6,`${a} != ${b}`)
const shapes=()=>[...useApp.getState().sketchProfiles,...(useApp.getState().sketchShape?[useApp.getState().sketchShape]:[])]
function setup(){const ell={cx:20,cy:30,rx:10,ry:5,rot:0},pts=Array.from({length:48},(_,i)=>[20+10*Math.cos(i*2*Math.PI/48),30+5*Math.sin(i*2*Math.PI/48)]);useApp.setState({...useApp.getInitialState(),mode:'sketch',sketchTool:'select',sketchProfiles:[{type:'poly',ell,pts}],extrudeHeight:5,sketchOp:'new'},true)}
function pick(p){const ref=hitTest(shapes(),p,.1);assert.ok(ref,`missing true ellipse handle at ${p}`);const q=refPts(shapes(),ref)[0];near(q[0],p[0]);near(q[1],p[1]);return ref}
function verify(rx){const sh=shapes()[0],e=sh.ell;near(e.cx,20);near(e.cy,30);near(e.rx,rx);near(e.ry,5);near(e.rot,0);assert.ok(sh.pts.length>=16);for(const p of sh.pts){assert.ok(p.every(Number.isFinite));near(((p[0]-20)/rx)**2+((p[1]-30)/5)**2,1)}assert.equal(useApp.getState().skConflict,false,useApp.getState().status)}
async function volume(rx,h,count=1){const sh=await importSTEP(new Blob([await w.exportSTEP()])),check=new(getOC().BRepCheck_Analyzer)(sh.wrapped,true,false);try{assert.ok(check.IsValid_2())}finally{check.delete()}const expected=count*Math.PI*rx*5*h,actual=measureVolume(sh);assert.ok(Math.abs(actual-expected)<1e-5,`${actual} != ${expected}`)}
test('ellipse principal endpoint drag and distance dimension preserve analytic metadata and native rebuild/history/JSON STEP',async()=>{
 setup();const center=pick([20,30]),minor=pick([20,35]);useApp.setState({skCons:[{id:'center',kind:'con',type:'fix',a:center},{id:'minor',kind:'con',type:'fix',a:minor}]});assert.equal(useApp.getState().skDragStart([30,30]),true);await useApp.getState().skDragEnd([35,30]);verify(15);assert.equal(useApp.getState().sketchUndo.length,1);await useApp.getState().undo();verify(10);await useApp.getState().redo();verify(15)
 const major=pick([35,30]),dimension={id:'major',name:'dPrincipalRadius',kind:'dim',type:'dist',a:center,b:major,value:15,expr:'15',refs:{}};useApp.setState({skCons:[...useApp.getState().skCons,dimension]});await useApp.getState().resolveSk();verify(15);await useApp.getState().extrudeSketch();assert.equal(useApp.getState().mode,'model',useApp.getState().status);await volume(15,5)
 assert.equal(await useApp.getState().applyFeatures(useApp.getState().features.map(f=>({...f,height:8})),'height8'),true);await volume(15,8);await useApp.getState().undo();await volume(15,5);await useApp.getState().redo();await volume(15,8)
 const payload=JSON.parse(JSON.stringify(buildProjectPayload(useApp.getState())));useApp.setState({...useApp.getInitialState()},true);await useApp.getState().applyProjectData(payload);await volume(15,8);const feat=useApp.getState().features.find(f=>f.sketchId);await useApp.getState().editSketchOf(feat.id);verify(15);assert.deepEqual(useApp.getState().skCons.find(c=>c.id==='major'),dimension);useApp.setState({skCons:useApp.getState().skCons.map(c=>c.id==='major'?{...c,value:18,expr:'18'}:c)});await useApp.getState().resolveSk();verify(18);await useApp.getState().applySketchEdit(feat.sketchId);await volume(18,8);await useApp.getState().undo();await volume(15,8);await useApp.getState().redo();await volume(18,8)
})
test('Esc cancels ellipse endpoint preview and pending release without sample or metadata drift',async()=>{
 setup();const before=structuredClone(shapes());assert.equal(useApp.getState().skDragStart([30,30]),true);const pending=useApp.getState().skDragEnd([35,30]);assert.equal(useApp.getState().escSketch(),true);await pending;assert.deepEqual(shapes(),before);assert.equal(useApp.getState().sketchUndo.length,0);assert.equal(useApp.getState().mode,'sketch')
})
test('rotated ellipse mirror preserves analytic locus through major radius edits and native history/JSON/STEP',async()=>{
 const rot=Math.PI/6,ell={cx:20,cy:30,rx:10,ry:5,rot:30},pts=Array.from({length:48},(_,i)=>{const t=i*2*Math.PI/48;return[20+10*Math.cos(t)*Math.cos(rot)-5*Math.sin(t)*Math.sin(rot),30+10*Math.cos(t)*Math.sin(rot)+5*Math.sin(t)*Math.cos(rot)]})
 const center={kind:'ellipse-point',shape:0,idx:0},minor={kind:'ellipse-point',shape:0,idx:2},major={kind:'ellipse-point',shape:0,idx:1}
 useApp.setState({...useApp.getInitialState(),mode:'sketch',sketchTool:'mirror',sketchProfiles:[{type:'poly',ell,pts},{type:'poly',construction:true,open:true,pts:[[70,0],[70,70]]}],skCons:[{id:'center',kind:'con',type:'fix',a:center},{id:'minor',kind:'con',type:'fix',a:minor},{id:'axis',kind:'con',type:'fix',a:{kind:'edge',shape:1,idx:0}},{id:'radius',kind:'dim',type:'dist',a:center,b:major,value:10,expr:'10',name:'dMajor',refs:{}}],mirrorPick:{shapes:[0],stage:'line',p1:null},extrudeHeight:5,sketchOp:'new'},true)
 const check=rx=>{const es=shapes().filter(s=>s.ell);assert.equal(es.length,2);near(es[0].ell.cx,20);near(es[1].ell.cx,120);for(const s of es){near(s.ell.cy,30);near(s.ell.rx,rx);near(s.ell.ry,5)}near(es[0].ell.rot,30);near(es[1].ell.rot,150);for(const p of es[0].pts){const dx=140-p[0]-120,dy=p[1]-30,a=150*Math.PI/180,x=dx*Math.cos(a)+dy*Math.sin(a),y=-dx*Math.sin(a)+dy*Math.cos(a);near((x/rx)**2+(y/5)**2,1)}assert.equal(useApp.getState().skConflict,false,useApp.getState().status)}
 await useApp.getState().skMirrorAt([70,30]);check(10);await useApp.getState().extrudeSketch();assert.equal(useApp.getState().mode,'model',useApp.getState().status);await volume(10,5,2)
 let feat=useApp.getState().features.find(f=>f.sketchId);await useApp.getState().editSketchOf(feat.id);check(10);useApp.setState({skCons:useApp.getState().skCons.map(c=>c.id==='radius'?{...c,value:12,expr:'12'}:c)});await useApp.getState().resolveSk();check(12);await useApp.getState().applySketchEdit(feat.sketchId);await volume(12,5,2);await useApp.getState().undo();await volume(10,5,2);await useApp.getState().redo();await volume(12,5,2)
 const payload=JSON.parse(JSON.stringify(buildProjectPayload(useApp.getState())));useApp.setState({...useApp.getInitialState()},true);await useApp.getState().applyProjectData(payload);await volume(12,5,2);feat=useApp.getState().features.find(f=>f.sketchId);await useApp.getState().editSketchOf(feat.id);check(12);await useApp.getState().applySketchEdit(feat.sketchId);await volume(12,5,2)
})
