import test from 'node:test';import assert from 'node:assert/strict';import {register,createRequire} from 'node:module';import {fileURLToPath} from 'node:url'
globalThis.require=createRequire(import.meta.url);globalThis.__dirname=fileURLToPath(new URL('.',import.meta.url));register('./native-car-loader.mjs',import.meta.url)
await import('../src/worker/cad.worker.ts');await globalThis.__wheelWorker.ready();const {useApp}=await import('../src/store.ts');const {pathPts}=await import('../src/sketch/sketchOps.ts')
const circle=(x=0)=>({type:'circle',c:[x,0],r:10}),radius=(shape)=>({id:'r1',name:'d1',kind:'dim',type:'rad',a:{kind:'circle',shape},value:10})
function setup(profiles=[],shape=circle(),cons=[radius(profiles.length)]){useApp.setState({...useApp.getInitialState(),mode:'sketch',sketchTool:'select',sketchProfiles:structuredClone(profiles),sketchShape:structuredClone(shape),skCons:structuredClone(cons)},true)}
const all=()=>[...useApp.getState().sketchProfiles,...(useApp.getState().sketchShape?[useApp.getState().sketchShape]:[])]
async function copy(targets,dx=30){useApp.setState({skMove:{cx:0,cy:0,dx,dy:0,ang:0,copy:true,targets,drag:null}});await useApp.getState().commitSkMove();await useApp.getState().resolveSk()}
async function changeR(){useApp.setState({skCons:useApp.getState().skCons.map(c=>c.id==='r1'?{...c,value:12}:c)});await useApp.getState().resolveSk()}
test('copy active circle keeps original radius identity; new copy remains independent',async()=>{setup();await copy([0]);assert.deepEqual(all().map(s=>s.c),[[0,0],[30,0]]);assert.deepEqual(useApp.getState().skCons.filter(c=>c.id==='r1'),[radius(0)]);assert.ok(useApp.getState().skCons.some(c=>c.id!=='r1'&&c.a.shape===1));await changeR();assert.equal(all()[0].r,12);assert.equal(all()[1].r,10)})
test('copy unrelated profile does not change active circle source index',async()=>{setup([circle(-30)],circle());await copy([0]);assert.deepEqual(all().map(s=>s.c),[[-30,0],[0,0],[0,0]]);await changeR();assert.equal(all()[1].r,12);assert.equal(all()[0].r,10);assert.equal(all()[2].r,10)})
test('copy banks original active shape and UndoRedo restores exact source references',async()=>{setup();const original=structuredClone({profiles:useApp.getState().sketchProfiles,shape:useApp.getState().sketchShape,cons:useApp.getState().skCons});await copy([0]);const copied=structuredClone(all()),copiedCons=structuredClone(useApp.getState().skCons);assert.equal(useApp.getState().sketchUndo.length,1);await useApp.getState().undo();assert.deepEqual({profiles:useApp.getState().sketchProfiles,shape:useApp.getState().sketchShape,cons:useApp.getState().skCons},original);await useApp.getState().redo();assert.deepEqual(all(),copied);assert.deepEqual(useApp.getState().skCons,copiedCons)})
test('prompt multiple copies preserve original order and dimension IDs',async()=>{setup();useApp.setState({appPrompt:async()=> '30, 0, 0, 3'});await useApp.getState().skMovePrompt();await useApp.getState().resolveSk();assert.deepEqual(all().map(s=>s.c),[[0,0],[30,0],[60,0],[90,0]]);assert.deepEqual(useApp.getState().skCons.filter(c=>c.id==='r1'),[radius(0)]);assert.ok(useApp.getState().skCons.some(c=>c.id!=='r1'&&c.a.shape===1));await changeR();assert.deepEqual(all().map(s=>s.r),[12,10,10,10])})
test('center references and dimension formula binding keep their original shape after copy',async()=>{const verts=[[10,0],[-10,0]],bulges=[-1],arc={type:'poly',open:true,verts,bulges,pts:pathPts(verts,bulges)},cons=[{id:'center',kind:'con',type:'fix',a:{kind:'center',shape:1,idx:0}},{id:'rad',name:'dArc',kind:'dim',type:'rad',a:{kind:'edge',shape:1,idx:0},value:10,expr:'R',refs:{R:'R'}}];setup([circle(-30)],arc,cons);useApp.setState({params:[{id:'R',name:'R',value:10}],skDimLabelOff:{rad:[11,13]}});await copy([0,1]);assert.deepEqual(useApp.getState().skCons.slice(0,cons.length),cons);assert.equal(useApp.getState().skCons.length,4);assert.equal(all().length,4);assert.equal(all()[1].type,'poly');assert.deepEqual(useApp.getState().skDimLabelOff.rad,[11,13]);const copiedRad=useApp.getState().skCons.find(c=>c.kind==='dim'&&c.a.shape===3);assert.deepEqual(useApp.getState().skDimLabelOff[copiedRad.id],[11,13]);assert.equal(all()[3].type,'poly')})

test('prompt rejects changed sketch while awaiting input without applying stale targets',async()=>{setup();let answer;useApp.setState({appPrompt:()=>new Promise(r=>answer=r)});const pending=useApp.getState().skMovePrompt();useApp.setState({sketchShape:circle(80)});const before=structuredClone(all());answer('30, 0, 0, 2');await pending;assert.deepEqual(all(),before);assert.equal(useApp.getState().sketchUndo.length,0)})
for(const input of ['', '10', '10,20,Infinity', '10,20,0,NaN'])test(`invalid move/copy prompt is atomic: ${JSON.stringify(input)}`,async()=>{setup();const before=structuredClone(all());useApp.setState({appPrompt:async()=>input});await useApp.getState().skMovePrompt();assert.deepEqual(all(),before);assert.equal(useApp.getState().sketchUndo.length,0)})
