import test from 'node:test'
import assert from 'node:assert/strict'
import {register,createRequire} from 'node:module'
import {fileURLToPath} from 'node:url'
globalThis.require=createRequire(import.meta.url);globalThis.__dirname=fileURLToPath(new URL('.',import.meta.url));register('./native-car-loader.mjs',import.meta.url)
await import('../src/worker/cad.worker.ts');const w=globalThis.__wheelWorker;await w.ready()
const {useApp,buildProjectPayload}=await import('../src/store.ts'),{hitTest,refPts}=await import('../src/sketch/freesolve.ts'),{ellipseArcWithSweep,ellipseArcSample}=await import('../src/sketch/ellipseArcGeometry.ts'),{importSTEP,measureVolume,getOC,drawCircle}=await import('replicad')
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-6,`${a} != ${b}`),all=()=>[...useApp.getState().sketchProfiles,...(useApp.getState().sketchShape?[useApp.getState().sketchShape]:[])]
const independentPoint=(e,t)=>{const r=e.rot*Math.PI/180;return[e.cx+e.rx*Math.cos(t)*Math.cos(r)-e.ry*Math.sin(t)*Math.sin(r),e.cy+e.rx*Math.cos(t)*Math.sin(r)+e.ry*Math.sin(t)*Math.cos(r)]}
const g=()=>useApp.getState()
async function vol(expected){const sh=await importSTEP(new Blob([await w.exportSTEP()])),check=new(getOC().BRepCheck_Analyzer)(sh.wrapped,true,false);try{assert.ok(check.IsValid_2());assert.ok(Math.abs(measureVolume(sh)-expected)<Math.max(1e-5,expected*1e-7),`${measureVolume(sh)} != ${expected}`)}finally{check.delete()}}
for(const kind of ['circle','ellipse','earc'])for(const plane of ['XY','XZ','YZ','ARB'])test(`circular array ${kind} ${plane} keeps exact geometry through native extrusion/history/JSON`,async()=>{
 const e={cx:30,cy:0,rx:5,ry:3,rot:25},ea=ellipseArcWithSweep(e,330,-270),shape=kind==='circle'?{type:'circle',c:[30,0],r:5}:kind==='ellipse'?{type:'poly',ell:e,pts:Array.from({length:48},(_,i)=>independentPoint(e,i*Math.PI/24))}:{type:'poly',earc:ea,pts:ellipseArcSample(ea),open:false},area=kind==='circle'?25*Math.PI:kind==='ellipse'?15*Math.PI:7.5*(1.5*Math.PI+1)
 useApp.setState({...useApp.getInitialState(),mode:'sketch',sketchTool:'array',sketchProfiles:[shape],extrudeHeight:5,sketchOp:'new',...(plane==='ARB'?{sketchPlane:'XY',sketchArb:{o:[10,20,30],xd:[0,1,0],n:[1,0,0]}}:{sketchPlane:plane})},true)
 g().setArrayCfg({kind:'circ',count:3,angle:-360,angleType:'full',cx:0,cy:0});
 await g().previewArray();assert.equal(g().arrayPreview.error,null);const ghosts=structuredClone(g().arrayPreview.shapes);assert.equal(ghosts?.length,2);assert.deepEqual(all(),[shape]);assert.equal(g().sketchUndo.length,0);
 await g().applyArray();assert.deepEqual(all().slice(1),ghosts);assert.equal(all().length,3);assert.deepEqual(all()[0],shape);for(let i=0;i<3;i++){const s=all()[i],a=-i*2*Math.PI/3,c=s.c||[s.ell?.cx??s.earc.cx,s.ell?.cy??s.earc.cy];near(c[0],30*Math.cos(a));near(c[1],30*Math.sin(a));if(kind!=='circle'){const m=s.ell||s.earc;assert.ok(m);near(m.rx,5);near(m.ry,3);near(Math.cos(m.rot*Math.PI/180),Math.cos(25*Math.PI/180+a));if(kind==='earc')assert.equal(m.signedSweepDeg,-270)}}
 const result=structuredClone(all());assert.equal(g().sketchUndo.length,1);await g().undo();assert.deepEqual(all(),[shape]);await g().redo();assert.deepEqual(all(),result);await g().extrudeSketch();assert.equal(g().mode,'model',g().status);await vol(3*area*5)
 if(plane==='XY'){const payload=JSON.parse(JSON.stringify(buildProjectPayload(g())));useApp.setState({...useApp.getInitialState()},true);await g().applyProjectData(payload);await vol(3*area*5);assert.equal(await g().applyFeatures(g().features.map(f=>({...f,height:8})),'height8'),true);await vol(3*area*8);await g().undo();await vol(3*area*5);await g().redo();await vol(3*area*8)}
})
for(const count of [2,3])for(const pocketX of Array.from({length:count},(_,i)=>i*20))test(`dimensioned ${count}-array extrusion → pocket at x${pocketX} → upstream source radius edit preserves independent copies`,async()=>{
 async function verify(v){await vol(v);const solid=await importSTEP(new Blob([await w.exportSTEP()]));for(let i=0;i<count;i++){const probe=drawCircle(1).translate(i*20,0).sketchOnPlane('XY',3.5).extrude(1),overlap=solid.intersect(probe);near(measureVolume(overlap),i*20===pocketX?0:Math.PI)}}
 const original={type:'circle',c:[0,0],r:5},dim={id:'radius',kind:'dim',type:'rad',a:{kind:'circle',shape:0},value:5,expr:'5',name:'dRadius'};useApp.setState({...useApp.getInitialState(),mode:'sketch',sketchTool:'array',sketchProfiles:[original],skCons:[dim],extrudeHeight:5,sketchOp:'new'},true);await g().sketchArrayRect(count,20,1,0);assert.equal(all().length,count);await g().extrudeSketch();assert.equal(g().mode,'model',g().status);const base=g().features.find(f=>f.sketchId);await vol(count*125*Math.PI)
 await g().startSketchOnFace([pocketX,5,0],[0,0,1]);assert.deepEqual(g().skCons,[]);assert.deepEqual(g().sketchUndo,[]);assert.deepEqual(g().sketchRedo,[]);useApp.setState({sketchProfiles:[],sketchShape:{type:'circle',c:[pocketX,0],r:2},extrudeHeight:2,extrudeExtent:'distance',extrudeFlip:false,faceCutThrough:false,sketchOp:'cut'});await g().extrudeSketch();assert.equal(g().mode,'model',g().status);await verify((count*125-8)*Math.PI);const cut=g().features.at(-1).id
 await g().editSketchOf(base.id);useApp.setState({skCons:g().skCons.map(c=>c.id==='radius'?{...c,value:6,expr:'6'}:c)});await g().resolveSk();near(all()[0].r,6);near(all()[1].r,5);if(count===3)near(all()[2].r,5);await g().applySketchEdit(base.sketchId);assert.equal(g().mode,'model',g().status+JSON.stringify(g().featureErrors));assert.deepEqual(g().failedFeatureIds,[],JSON.stringify(g().featureErrors));assert.equal(g().features.at(-1).id,cut);await verify((count*125+47)*Math.PI);await g().undo();assert.deepEqual(g().failedFeatureIds,[],g().status);await verify((count*125-8)*Math.PI);await g().redo();await verify((count*125+47)*Math.PI);const payload=JSON.parse(JSON.stringify(buildProjectPayload(g())));useApp.setState({...useApp.getInitialState()},true);await g().applyProjectData(payload);await verify((count*125+47)*Math.PI)
})
