import test from 'node:test'
import assert from 'node:assert/strict'
import {register,createRequire} from 'node:module'
import {fileURLToPath} from 'node:url'
globalThis.require=createRequire(import.meta.url);globalThis.__dirname=fileURLToPath(new URL('.',import.meta.url));register('./native-car-loader.mjs',import.meta.url)
await import('../src/worker/cad.worker.ts');await globalThis.__wheelWorker.ready()
const {useApp}=await import('../src/store.ts');const {ellipseArcWithSweep,ellipseArcSample}=await import('../src/sketch/ellipseArcGeometry.ts')
const g=()=>useApp.getState(),all=()=>[...g().sketchProfiles,...(g().sketchShape?[g().sketchShape]:[])],snap=()=>structuredClone({shapes:all(),cons:g().skCons,params:g().params,undo:g().sketchUndo,redo:g().sketchRedo})
function seed(extra={}){useApp.setState({...useApp.getInitialState(),mode:'sketch',sketchTool:'array',sketchProfiles:[{type:'circle',c:[0,0],r:5},{type:'circle',c:[100,0],r:9}],skSel:[{kind:'circle',shape:0}],skCons:[{id:'sourceRadius',kind:'dim',type:'rad',a:{kind:'circle',shape:0},value:5,name:'dRadius'}],...extra},true)}
test('selected rectangular array preserves original ordering and dimension binding; copies dimension independently',async()=>{seed();const old=snap();await g().sketchArrayRect(2,20,1,0);assert.deepEqual(all().slice(0,2),old.shapes);assert.deepEqual(g().skCons[0],old.cons[0]);assert.deepEqual(all()[2],{type:'circle',c:[20,0],r:5});const copied=g().skCons.find(c=>c.id!=='sourceRadius'&&c.kind==='dim');assert.ok(copied);assert.equal(copied.a.shape,2);assert.notEqual(copied.name,'dRadius');useApp.setState({skCons:g().skCons.map(c=>c.id==='sourceRadius'?{...c,value:6,expr:'6'}:c)});await g().resolveSk();assert.equal(all()[0].r,6);assert.equal(all()[1].r,9);assert.equal(all()[2].r,5)})
test('negative full circular array keeps direction and exact analytic arc metadata',async()=>{const e=ellipseArcWithSweep({cx:30,cy:0,rx:5,ry:3,rot:25},330,-270),sh={type:'poly',earc:e,pts:ellipseArcSample(e),open:false};seed({sketchProfiles:[sh],skCons:[],skSel:[]});await g().sketchArrayCirc(4,-360,0,0);assert.deepEqual(all()[0],sh);assert.equal(all().length,4);all().forEach((s,i)=>{assert.ok(s.earc);const a=-i*Math.PI/2;assert.ok(Math.abs(s.earc.cx-30*Math.cos(a))<1e-7);assert.ok(Math.abs(s.earc.cy-30*Math.sin(a))<1e-7);assert.equal(s.earc.signedSweepDeg,-270);assert.ok(Math.abs(Math.cos(s.earc.rot*Math.PI/180)-Math.cos((25-i*90)*Math.PI/180))<1e-7)})})
for(const count of [NaN,Infinity,1.5,0])for(const route of ['rect','circ'])test(`${route} rejects invalid count ${count} atomically`,async()=>{seed();const before=snap();await(route==='rect'?g().sketchArrayRect(count,20,1,0):g().sketchArrayCirc(count,360,-50,0));assert.deepEqual(snap(),before)})
test('array preserves original Fixed anchor and copies fixed shape at requested new location',async()=>{seed({skCons:[{id:'anchor',kind:'con',type:'fix',a:{kind:'circle',shape:0}}]});const before=snap();await g().sketchArrayRect(2,20,1,0);assert.deepEqual(all().slice(0,2),before.shapes);assert.equal(all()[2].c[0],20);assert.equal(g().skCons.length,2);const result=structuredClone(all());await g().undo();assert.deepEqual(all(),before.shapes);await g().redo();assert.deepEqual(all(),result)})
test('pending array rejects source replacement without undo or stale copies',async()=>{seed();const p=g().sketchArrayRect(4,20,1,0);useApp.setState({sketchProfiles:[{type:'circle',c:[99,20],r:2}]});const current=snap();await p;assert.deepEqual(snap(),current)})
test('failed applyArray with existing profiles retains array tool and exact history',async()=>{seed();g().setArrayCfg({nx:NaN});const before=snap();await g().applyArray();assert.deepEqual(snap(),before);assert.equal(g().sketchTool,'array')})
test('array config edit during solve invalidates requested candidates',async()=>{seed();const before=snap(),p=g().applyArray();g().setArrayCfg({dx:35});await p;assert.deepEqual(snap(),before);assert.equal(g().arrayPending,false)})
test('negative rectangular total extent distributes exact spacing',async()=>{seed();g().setArrayCfg({kind:'rect',nx:3,ny:1,dx:-40,dy:0,distType:'extent'});await g().applyArray();assert.deepEqual(all().map(s=>s.c),[[0,0],[100,0],[-20,0],[-40,0]])})
test('array total output limit rejects rather than truncating',async()=>{seed();const before=snap();await g().sketchArrayRect(1001,20,1,0);assert.deepEqual(snap(),before)})
