import type {SketchPrimitive,Constraint,SketchGeometry} from '@salusoft89/planegcs'
import {ellipseArcPoint,ellipseArcSweep,type EllipseArcGeometry} from './ellipseArcGeometry'
import {ellipseArcPointId} from './ellipseArcSolver'
type Pt=[number,number]
export function ellipseArcTangentPrimitives(i:number,e:EllipseArcGeometry,end:0|1,lineId:string,linePoints:[string,string],contact:0|1,key:string):(SketchPrimitive|Constraint)[]{
 const id=(s:string)=>`${key}:${s}`,inner=(s:string)=>`ea${i}_${s}`,C:Pt=[e.cx,e.cy],t=(e.a0+(end?ellipseArcSweep(e):0))*Math.PI/180,a=e.rot*Math.PI/180,ux=Math.cos(a),uy=Math.sin(a),P:Pt=[C[0]+e.rx*(Math.cos(t)*ux-Math.sin(t)*uy),C[1]+e.rx*(Math.cos(t)*uy+Math.sin(t)*ux)],Q:Pt=[C[0]+e.ry*(Math.cos(t)*ux-Math.sin(t)*uy),C[1]+e.ry*(Math.cos(t)*uy+Math.sin(t)*ux)],R:Pt=[C[0]-P[1]+C[1],C[1]+P[0]-C[0]],S:Pt=[C[0]-Q[1]+C[1],C[1]+Q[0]-C[0]],D:Pt=[C[0]-e.rx*Math.sin(t)*ux-e.ry*Math.cos(t)*uy,C[1]-e.rx*Math.sin(t)*uy+e.ry*Math.cos(t)*ux]
 const point=(k:string,p:Pt)=>({id:id(k),type:'point',x:p[0],y:p[1],fixed:false} as SketchPrimitive),line=(k:string,p1:string,p2:string)=>({id:id(k),type:'line',p1_id:p1,p2_id:p2} as SketchPrimitive),diff=(k:string,p1:string,p2:string,vector:string,prop:'x'|'y')=>({id:id(k),type:'difference',param1:{o_id:p1,prop},param2:{o_id:p2,prop},difference:{o_id:vector,prop}} as Constraint)
 return [point('R',R),point('S',S),line('CR',`p${i}_0`,id('R')),line('CS',`p${i}_0`,id('S')),{id:id('onR'),type:'point_on_circle',p_id:id('R'),c_id:inner('rx')} as Constraint,{id:id('onS'),type:'point_on_circle',p_id:id('S'),c_id:inner('ry')} as Constraint,{id:id('perpR'),type:'perpendicular_ll',l1_id:inner('CP'+end),l2_id:id('CR')} as Constraint,{id:id('perpS'),type:'perpendicular_ll',l1_id:inner('CQ'+end),l2_id:id('CS')} as Constraint,point('T',[R[0]-e.ry*uy,R[1]+e.ry*ux]),point('W',[S[0]+e.rx*ux,S[1]+e.rx*uy]),point('D',D),line('RT',id('R'),id('T')),line('SW',id('S'),id('W')),line('CD',`p${i}_0`,id('D')),{id:id('projR'),type:'point_on_line_pl',p_id:id('D'),l_id:id('RT')} as Constraint,{id:id('projS'),type:'point_on_line_pl',p_id:id('D'),l_id:id('SW')} as Constraint,...(['x','y'] as const).flatMap(prop=>[diff('T'+prop,id('R'),id('T'),inner('DV'),prop),diff('W'+prop,id('S'),id('W'),inner('DU'),prop)]),{id:id('contact'),type:'p2p_coincident',p1_id:linePoints[contact],p2_id:ellipseArcPointId(i,end)} as Constraint,{id:id('direction'),type:'parallel',l1_id:lineId,l2_id:id('CD')} as Constraint]
}
export function validateEllipseArcTangent(i:number,e:EllipseArcGeometry,end:0|1,linePoints:[string,string],contact:0|1,key:string,geometry:SketchGeometry[]):boolean{
 const m=new Map(geometry.map(p=>[String(p.id),p])),get=(id:string):Pt|null=>{const p=m.get(id);return p?.type==='point'&&Number.isFinite(p.x)&&Number.isFinite(p.y)?[p.x,p.y]:null},C:Pt=[e.cx,e.cy],R=get(key+':R'),S=get(key+':S'),P=get(`ea${i}_P${end}`),Q=get(`ea${i}_Q${end}`),a=get(linePoints[0]),b=get(linePoints[1]);if(!R||!S||!P||!Q||!a||!b)return false
 const cross=(p:Pt,q:Pt,r:number)=>((p[0]-C[0])*(q[1]-C[1])-(p[1]-C[1])*(q[0]-C[0]))/(r*r)
 if(Math.abs(cross(P,R,e.rx)-1)>1e-7||Math.abs(cross(Q,S,e.ry)-1)>1e-7)return false
 const E=ellipseArcPoint(e,e.a0+(end?ellipseArcSweep(e):0)),p=contact===0?a:b;if(Math.hypot(p[0]-E[0],p[1]-E[1])>1e-7)return false
 const t=(e.a0+(end?ellipseArcSweep(e):0))*Math.PI/180,rot=e.rot*Math.PI/180,dx=-e.rx*Math.sin(t)*Math.cos(rot)-e.ry*Math.cos(t)*Math.sin(rot),dy=-e.rx*Math.sin(t)*Math.sin(rot)+e.ry*Math.cos(t)*Math.cos(rot),lx=b[0]-a[0],ly=b[1]-a[1],len=Math.hypot(lx,ly);return len>1e-8&&Math.abs(dx*ly-dy*lx)/(Math.hypot(dx,dy)*len)<1e-7
}
